### ISSUE TITLE
CF Objectstore

### ISSUE THREAD

**Issue by dcarissi** [cloudfoundry/cf-release#1006]
Hi,
I'm looking for the steps to create my own key/cert files to use with CF's Objectstore.  I've googled but didn't find any.  Also, I've been told that there are additional settings in the manifest yml file in the CC section for webdav_config: section that are also needed.  So, can someone explain the steps needed to create my own ca/cert/key files for the objectstore and the setup steps to add those to the manifest yml file??
Thanks

**Comment by Amit-PivotalLabs** [comment]
I searched "generate root ca self signed certificate" and followed this page: https://datacenteroverlords.com/2012/03/01/creating-your-own-ssl-certificate-authority/.  They key steps for me were:

```
$ openssl genrsa -out rootCA.key 2048
$ openssl req -x509 -new -nodes -key rootCA.key -sha256 -days 1024 -out rootCA.pem
$ openssl genrsa -out device.key 2048
$ openssl req -new -key device.key -out device.csr
$ openssl x509 -req -in device.csr -CA rootCA.pem -CAkey rootCA.key -CAcreateserial -out device.crt -days 500 -sha256
```

In your manifest, you typically have [3 global blobstore TLS properties](https://github.com/cloudfoundry/cf-release/blob/12f0c2e0718503bffed08d1bbd822d644433675a/spec/fixtures/vsphere/cf-manifest.yml#L907-L909) that you can get from the contents of some of the above generated files:

* `BLOBSTORE_CA_CERT` comes from `rootCA.pem`
* `BLOBSTORE_PRIVATE_KEY` comes from `device.key`
* `BLOBSTORE_TLS_CERT` comes from `device.crt`

There are some [Cloud Foundry docs](http://docs.cloudfoundry.org/deploying/common/cc-blobstore-config.html#webdav) here on blobstore configuration, but they're a bit hard to find and perhaps a bit incomplete.  I'll let the CAPI team know.

/cc @SocalNick @utako

**Comment by SocalNick** [comment]
@dcarissi we plan on adding a script to cf-release to help generate the certs for the blobstore: https://www.pivotaltracker.com/story/show/124966951
