### ISSUE TITLE
Failed creating missing vms due to the limit for specified instance type

### ISSUE THREAD

**Issue by billsg** [cloudfoundry/cf-release#1007]
The error happened during "Create and Deploy CF Release" from https://github.com/cloudfoundry/cf-release/tree/master/example_manifests

The minimal-aws.yml is trying to create more than five c3.large instances in AWS. However the default max number of the same type instances is 5 in AWS.

<img width="567" alt="screen shot 2016-07-11 at 2 50 49 pm" src="https://cloud.githubusercontent.com/assets/20392588/16722156/6104b0d4-4777-11e6-9dca-aa81452a5450.png">

![capture](https://cloud.githubusercontent.com/assets/20392588/16722062/b84d05cc-4776-11e6-8587-ba4e5dd7a2bf.JPG)

**Comment by Amit-PivotalLabs** [comment]
That's interesting.  According to [this doc](http://aws.amazon.com/ec2/faqs/#How_many_instances_can_I_run_in_Amazon_EC2) the limit is 20, but might be lower for new accounts.  Is your account very new?  Can you confirm you are working with default limits and not some post hoc limits that have been applied to your account?

**Comment by billsg** [comment]
I have requested to AWS to upgrade the limit to 20. The limitation issue should have been solved for now. Btw, is it possible to deploy all instances in one bosh lite VM in EC2? We cannot afford 1000+ dollars monthly for 20 instances in EC2.

**Comment by Amit-PivotalLabs** [comment]
Yes.  [Docs](http://docs.cloudfoundry.org/deploying/boshlite/create_a_manifest.html#create-stub).  [CI](https://runtime.ci.cf-app.com/pipelines/cf-release/jobs/bosh-lite-provision-cf-deploy/builds/83).

**Comment by Amit-PivotalLabs** [comment]
Assuming those links work for you @billsg.  Closing.  Let me know if you have more questions.
