### ISSUE TITLE
Error 400007: 'consul_z1/0 (b0ba6708-5f03-4c8e-9157-df64e4a34113)' is not running after update. Review logs for failed jobs: consul_agent

### ISSUE THREAD

**Issue by cpraveen412** [cloudfoundry/cf-release#1008]
Hello,
I got the following error in Cloud foundry deployment.

Started updating job consul_z1
  Started updating job consul_z1 > consul_z1/0 (b0ba6708-5f03-4c8e-9157-df64e4a34113) (canary). Failed: 'consul_z1/0 (b0ba6708-5f03-4c8e-9157-df64e4a34113)' is not running after update. Review logs for failed jobs: consul_agent (00:10:47)

Error 400007: 'consul_z1/0 (b0ba6708-5f03-4c8e-9157-df64e4a34113)' is not running after update. Review logs for failed jobs: consul_agent

and my log says:

2016/07/11 14:37:21 [ERR] agent.client: Failed to decode response header: EOF
2016/07/11 14:37:21 [ERR] agent.client: Failed to decode response header: EOF
error during start: rpc error: failed to get conn: x509: certificate signed by unknown authority

what does it mean by unknown authority?

This is what i did to generate certificates for consul server

[admin@localhost certstrap]$ ./build
[admin@localhost certstrap]$ ./bin/certstrap init --common-name "CertAuth"
Enter passphrase (empty for no passphrase): 

Enter same passphrase again: 

Created out/CertAuth.key
Created out/CertAuth.crt
Created out/CertAuth.crl
[admin@localhost certstrap]$ ./bin/certstrap request-cert --common-name server.dc1.cf.internal
Enter passphrase (empty for no passphrase): 

Enter same passphrase again: 

Created out/server.dc1.cf.internal.key
Created out/server.dc1.cf.internal.csr
[admin@localhost certstrap]$ ./bin/certstrap request-cert
Must provide Common Name or SAN
[admin@localhost certstrap]$ ./bin/certstrap sign server.dc1.cf.internal --CA CertAuth
Created out/server.dc1.cf.internal.crt from out/server.dc1.cf.internal.csr signed by out/CertAuth.key

this is my VM Status

[admin@localhost certstrap]$ bosh vms --dns
RSA 1024 bit CA certificates are loaded due to old openssl compatibility
Acting as user 'admin' on 'my-bosh'
Deployment 'vsphere-test'

Director task 83

Task 83 done

+---------------------------------------------------------------------------+---------+-----+-----------+---------------+---------------+
| VM                                                                        | State   | AZ  | VM Type   | IPs           | DNS A records |
+---------------------------------------------------------------------------+---------+-----+-----------+---------------+---------------+
| api_worker_z1/0 (ff33af09-29c2-4063-88bd-82f712aab3d0)                    | running | n/a | small_z1  | 192.168.5.108 | n/a           |
| api_worker_z2/0 (bfbb8c98-4032-4544-9af0-5fa3fda5d4bf)                    | running | n/a | small_z2  | 192.168.5.109 | n/a           |
| api_z1/0 (b7ed7d61-7b66-4316-8505-c423730fa5b9)                           | running | n/a | large_z1  | 192.168.5.105 | n/a           |
| api_z2/0 (4d7f7fd3-b708-4858-9cd6-d7e7ac5ae3f0)                           | running | n/a | large_z2  | 192.168.5.106 | n/a           |
| blobstore_z1/0 (d33570f2-b6ed-4f8c-afc3-46cfa4bb1f37)                     | running | n/a | medium_z1 | 192.168.5.102 | n/a           |
| clock_global/0 (51c9147e-ebfb-46a4-beae-f68741a87506)                     | running | n/a | medium_z1 | 192.168.5.107 | n/a           |
| consul_z1/0 (b0ba6708-5f03-4c8e-9157-df64e4a34113)                        | failing | n/a | small_z1  | 192.168.5.247 | n/a           |
| consul_z1/1 (a917ffa5-0487-419d-bd53-c31f45d30106)                        | running | n/a | small_z1  | 192.168.5.248 | n/a           |
| consul_z2/0 (6857b4c4-c620-432f-9e52-5e6f8a95b8b6)                        | running | n/a | small_z2  | 192.168.5.170 | n/a           |
| doppler_z1/0 (23a605d0-9721-45f4-8dd5-a84b1a70546d)                       | running | n/a | medium_z1 | 192.168.5.114 | n/a           |
| doppler_z2/0 (cdfa4942-8b8d-48f2-bb21-271e197ef8fd)                       | running | n/a | medium_z2 | 192.168.5.115 | n/a           |
| etcd_z1/0 (7687d983-551e-4159-aff0-265bc8ddc940)                          | running | n/a | medium_z1 | 192.168.5.244 | n/a           |
| etcd_z1/1 (975c7687-323e-45f4-b604-a6bc25ff525a)                          | running | n/a | medium_z1 | 192.168.5.245 | n/a           |
| etcd_z2/0 (f56ca00f-48b7-462d-8232-3e5633fbad91)                          | running | n/a | medium_z2 | 192.168.5.173 | n/a           |
| ha_proxy_z1/0 (2d0a06d4-3b6b-4cc3-88e8-78637fdadbc7)                      | running | n/a | router_z1 | 192.168.5.233 | n/a           |
| hm9000_z1/0 (dda98ce7-d8eb-4d03-82fe-ebfc5136d69b)                        | running | n/a | medium_z1 | 192.168.5.110 | n/a           |
| hm9000_z2/0 (0d1a1f7e-f95c-4be1-a06b-5247fbfccaf6)                        | running | n/a | medium_z2 | 192.168.5.111 | n/a           |
| loggregator_trafficcontroller_z1/0 (4b9b3ec4-3975-4ff7-869f-2839a4cea140) | running | n/a | small_z1  | 192.168.5.116 | n/a           |
| loggregator_trafficcontroller_z2/0 (52200f26-5671-4794-91fd-3e35828b3bb2) | running | n/a | small_z2  | 192.168.5.117 | n/a           |
| nats_z1/0 (e45e3538-fd1a-4c2b-8956-0390666b40e2)                          | running | n/a | medium_z1 | 192.168.5.231 | n/a           |
| nats_z2/0 (2697a96a-1d9b-449e-8716-112afe9417c1)                          | running | n/a | medium_z2 | 192.168.5.172 | n/a           |
| postgres_z1/0 (251ff048-f086-440c-bc29-b9ab8a4ac020)                      | running | n/a | medium_z1 | 192.168.5.242 | n/a           |
| router_z1/0 (b0ce401b-804f-47c2-b099-1e92c375fbaa)                        | running | n/a | router_z1 | 192.168.5.235 | n/a           |
| router_z2/0 (1e6928d4-fd1f-4ff3-b89e-d3280f0c2d20)                        | running | n/a | router_z2 | 192.168.5.171 | n/a           |
| runner_z1/0 (b712b666-f607-44d1-905c-730cd0732dd6)                        | running | n/a | runner_z1 | 192.168.5.112 | n/a           |
| runner_z2/0 (2d876e5a-0264-4721-8af5-584116a93eef)                        | running | n/a | runner_z2 | 192.168.5.113 | n/a           |
| stats_z1/0 (b39dad79-8743-4a1b-86da-5da39c8e0d43)                         | running | n/a | small_z1  | 192.168.5.101 | n/a           |
| uaa_z1/0 (c01311d3-42f7-432f-84d0-109ce0c15605)                           | running | n/a | medium_z1 | 192.168.5.103 | n/a           |
| uaa_z2/0 (7f7787d1-0e15-4079-93aa-2052d50d88a2)                           | running | n/a | medium_z2 | 192.168.5.104 | n/a           |
+---------------------------------------------------------------------------+---------+-----+-----------+---------------+---------------+

**Comment by cpraveen412** [comment]
Is it possible to deploy without certificates or with self-signed certificates?

**Comment by cpraveen412** [comment]
Could anyone please reply on this?

**Comment by cpraveen412** [comment]
I figured out how to get proper signed certificates and consul_z1 job was updated successfully. 
But i have another question. How to create SSL certificates for HA_Proxy?

**Comment by cpraveen412** [comment]
I Figured that out too.....

**Comment by Alex-Mussell** [comment]
Could you please provide your solution?

**Comment by cpraveen412** [comment]
hello @Alex-Mussell,
please take a look at thread #1010
