### ISSUE TITLE
Unable to Login

### ISSUE THREAD

**Issue by cpraveen412** [cloudfoundry/cf-release#1010]
Could anyone help!!

when I did curl, it suggested me to skip certificates. so i did this (skipped certificates)

[admin@localhost cf-release]$ curl -k https://api.cloud.xxxxxxxx.com/info
{"name":"","build":"","support":"http://support.cloudfoundry.com","version":0,"description":"","authorization_endpoint":"http://login.cloud.xxxxxxx.com","token_endpoint":"https://uaa.cloud.xxxxxxx.com","allow_debug":true}

But when i tried to login through cf login, i got error.

[admin@localhost cf-release]$ cf login --skip-ssl-validation
API endpoint: https://api.cloud.xxxxxxx.com

Email> admin

Password> 
Authenticating...
Server error, status code: 400, error code: , message: 

I need Help in figuring out this..

**Comment by dsabeti** [comment]
Hey @cpraveen412. We're happy to help. For starters, can you post the output of the following command: `CF_TRACE=true cf login --skip-ssl-validation` -- ***please remember to remove any sensitive data, such as passwords***. This will help us to diagnose which component is having problems, and we'll ask you for logs from that component.

**Comment by cpraveen412** [comment]
Thank You for your response @dsabeti.
As it took too long to get response, i started deploying again. but at this time, i'm getting the below error

Started updating job uaa_z1 > uaa_z1/0 (c25ac8a3-db19-41e1-b2de-4a732f1e61be) (canary). Failed: Action Failed get_task: Task 0805ab4f-8e19-4a07-63f6-05f0ebbc933e result: 1 of 1 post-start scripts failed. Failed Jobs: uaa. (00:13:49)

Error 450001: Action Failed get_task: Task 0805ab4f-8e19-4a07-63f6-05f0ebbc933e result: 1 of 1 post-start scripts failed. Failed Jobs: uaa.

Could you help me on this?

I'm using cf-239 with bosh stemcell 3262.4

tls:
      cert: server.crt
      private_key: server.key
      ca_cert: server-ca.crt
  consul:
     ca_cert: server-ca.crt
    server_cert: server.crt
    server_key: server.key
    agent_cert: agent.crt
    agent_key: agent.key

**Comment by dsabeti** [comment]
@cpraveen412 

Ok, so this confirms our theory that UAA is having a problem. Could you show us your UAA logs, **again, making sure to remove sensitive data**? You can download them by running `bosh logs uaa_z1 0`.

**Comment by cpraveen412** [comment]
hi @dsabeti,
Here are the logs.
[uaa_logs.tar.gz](https://github.com/cloudfoundry/cf-release/files/384456/uaa_logs.tar.gz)

**Comment by APShirley** [comment]
Hi @cpraveen412,

We have taken a look at your logs and manifest and noticed a few things that look suspect and may be causing the issue.  
1. Variable whitespace in your jwt keys section. We can't tell if this is because of how you deleted your keys, or indicates the actual indentation used in your unaltered manifest:
```
    jwt:
      signing_key: |+
        -----BEGIN RSA PRIVATE KEY-----
   <-whitespace here
        -----END RSA PRIVATE KEY-----
      verification_key: |+
        -----BEGIN PUBLIC KEY-----
       <-whitespace here
        -----END PUBLIC KEY-----
```
2. Using a chomp indicator `+` on the jwt keys section. This isn't necessary, and we're not sure what impact it might have on how the keys end up being read:
```
    jwt:
      signing_key: |+
      verification_key: |+
```
The reason we suspect these things is an error that we found in the logs indicating that the signing key properties could not be created.

```
Caused by: org.yaml.snakeyaml.error.YAMLException: Cannot create property=jwt for JavaBean=org.cloudfoundry.identity.uaa.impl.config.UaaConfiguration@35de958; Cannot create property=token for JavaBean=org.cloudfoundry.identity.uaa.impl.config.UaaConfiguration$Jwt@7d8f6bbe; Cannot create property=revocable for JavaBean=org.cloudfoundry.identity.uaa.impl.config.UaaConfiguration$Jwt$Token@32047987; Unable to find property 'revocable' on class: org.cloudfoundry.identity.uaa.impl.config.UaaConfiguration$Jwt$Token
        at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.constructJavaBean2ndStep(Constructor.java:299)
        at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.construct(Constructor.java:189)
        at org.yaml.snakeyaml.constructor.Constructor$ConstructYamlObject.construct(Constructor.java:331)
        ... 40 more
Caused by: org.yaml.snakeyaml.error.YAMLException: Cannot create property=token for JavaBean=org.cloudfoundry.identity.uaa.impl.config.UaaConfiguration$Jwt@7d8f6bbe; Cannot create property=revocable for JavaBean=org.cloudfoundry.identity.uaa.impl.config.UaaConfiguration$Jwt$Token@32047987; Unable to find property 'revocable' on class: org.cloudfoundry.identity.uaa.impl.config.UaaConfiguration$Jwt$Token
        at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.constructJavaBean2ndStep(Constructor.java:299)
        at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.construct(Constructor.java:189)
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:182)
        at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.constructJavaBean2ndStep(Constructor.java:296)
        ... 42 more
Caused by: org.yaml.snakeyaml.error.YAMLException: Cannot create property=revocable for JavaBean=org.cloudfoundry.identity.uaa.impl.config.UaaConfiguration$Jwt$Token@32047987; Unable to find property 'revocable' on class: org.cloudfoundry.identity.uaa.impl.config.UaaConfiguration$Jwt$Token
        at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.constructJavaBean2ndStep(Constructor.java:299)
        at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.construct(Constructor.java:189)
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:182)
        at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.constructJavaBean2ndStep(Constructor.java:296)
        ... 45 more
Caused by: org.yaml.snakeyaml.error.YAMLException: Unable to find property 'revocable' on class: org.cloudfoundry.identity.uaa.impl.config.UaaConfiguration$Jwt$Token
        at org.yaml.snakeyaml.introspector.PropertyUtils.getProperty(PropertyUtils.java:132)
        at org.yaml.snakeyaml.introspector.PropertyUtils.getProperty(PropertyUtils.java:121)
        at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.getProperty(Constructor.java:308)
        at org.cloudfoundry.identity.uaa.impl.config.CustomPropertyConstructor$CustomPropertyConstructMapping.getProperty(CustomPropertyConstructor.java:71)
        at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.constructJavaBean2ndStep(Constructor.java:240)
        ... 48 more
```

Let us know if this changes the behavior at all.

Thanks
Al && @JesseTAlford

**Comment by fhanik** [comment]
As Al and @JesseTAlford indicate, base64 encoding is invalid


InvalidBase64CharacterException: Bad Base64 input character decimal 45 in array position 5

**Comment by staylor14** [comment]
@cpraveen412 I've reviewed your logs, and it's pretty clear that the problem is in the post-start script.  We added a step in the deployment that waits for UAA to actually complete startup before signaling a successful deployment to Bosh.  The way it works is that it attempts to hit our health check endpoint running on port 8989.

What's strange is that the UAA log looks like it came up just fine.  So, the mystery is why we can't hit the healthcheck endpoint.  There's only one UAA process, so if it's logging, it should also be able to be reached via healthcheck.

It appears that between your initial issue report and our initial response to you, something has changed such that UAA no longer comes up.  Can you provide some insight into what you did between "deploys but returns 400" and "Bosh deployment fails"?

**Comment by cpraveen412** [comment]
i deleted the certs while i was uploading here. 
Please take a look at my full manifest with certs.
i edited manifest(converted cf2 network to cf1 network) after it was generated.

[cf-deployment.yml.tar.gz](https://github.com/cloudfoundry/cf-release/files/386819/cf-deployment.yml.tar.gz)

**Comment by cpraveen412** [comment]
Hi @dsabeti, 
i got a reply to mail which i didn't see here. 
My initial post was regarding login. At that time, my environment was CF-238 with bosh stemcell 3242.4. To reach that point, i made lot of changes to cf-deployment.yml(editing certs) based on some previous posts in here. I even posted those issues (#1008 & #1009) for help. 
So I wanted to completely reinstall CF with all the changes I made. At the time of redeployment, I found the new version of CF(239). So I deployed CF using latest release and surprisingly I got UAA Error!!.
I hope this explains that question.

**Comment by cpraveen412** [comment]
Hi @dsabeti, @APShirley , @JesseTAlford 
I passed through that error by updating my JWT certs which are generated by using below commands.
I request you to update the docs with these commands so that everyone will know how to generate them.

ha_proxy:  Run "openssl genrsa -out cf.key 1024"
           Run "openssl req -new -key cf.key -out cf.csr"
             For the Common Name, you must enter "*." followed by your System Domain
           Run "openssl x509 -req -in cf.csr -signkey cf.key -out cf.crt"
          Run "cat cf.crt && cat cf.key" and replace REPLACE_WITH_SSL_CERT_AND_KEY with this value.

JWT:  Run "openssl genrsa -out privkey.pem 2048"
      Run "openssl rsa -pubout -in privkey.pem -out pubkey.pem"
Blobstore certs: (use consul certs server-ca.crt,server.key & server.crt)
Consul certs: Use the script in cf-release/scripts/generate-consil-certs. open this script and update it with your domain name(instead of consulCA)
hm9000: use the script in the same location as consul certs

**Comment by cpraveen412** [comment]
Hi @dsabeti, @APShirley , @JesseTAlford
But i'm back to my original Issue now.

[admin@localhost cf]$ ./cf login

API endpoint> api.cloud.xxxxxx.com
FAILED
Invalid SSL Cert for api.cloud.xxxxxx.com
TIP: Use 'cf login --skip-ssl-validation' to continue with an insecure API endpoint
[admin@localhost cf]$ cf login --skip-ssl-validation
bash: cf: command not found...
Similar command is: 'fc'
[admin@localhost cf]$ ./cf login --skip-ssl-validation

API endpoint> api.cloud.xxxxxx.com

Email> admin

Password> 
Authenticating...
Server error, status code: 400, error code: , message: 

[admin@localhost cf]$ CF_TRACE=true ./cf login --skip-ssl-validation
API endpoint: https://api.cloud.xxxxxx.com

REQUEST: [2016-07-29T14:28:15-04:00]
GET /v2/info HTTP/1.1
Host: api.cloud.xxxxxx.com
Accept: application/json
Connection: close
Content-Type: application/json
User-Agent: go-cli 6.21.0+dff2cf8 / linux



RESPONSE: [2016-07-29T14:28:15-04:00]
HTTP/1.1 200 OK
Connection: close
Content-Length: 549
Content-Type: application/json;charset=utf-8
Date: Fri, 29 Jul 2016 18:28:15 GMT
Server: nginx
X-Content-Type-Options: nosniff
X-Vcap-Request-Id: 43628393-e4dc-4415-60dd-d181571b44aa
X-Vcap-Request-Id: 43628393-e4dc-4415-60dd-d181571b44aa::60c49129-eee1-4809-a000-5d398b1e6ea3

{"name":"","build":"","support":"http://support.cloudfoundry.com","version":0,"description":"","authorization_endpoint":"http://login.cloud.xxxxxx.com","token_endpoint":"https://uaa.cloud.xxxxxx.com","min_cli_version":null,"min_recommended_cli_version":null,"api_version":"2.58.0","app_ssh_endpoint":"ssh.cloud.xxxxxx.com:2222","app_ssh_host_key_fingerprint":null,"app_ssh_oauth_client":"ssh-proxy","logging_endpoint":"wss://loggregator.cloud.xxxxxx.com:443","doppler_logging_endpoint":"wss://doppler.cloud.xxxxxx.com:4443"}

REQUEST: [2016-07-29T14:28:15-04:00]
GET /login HTTP/1.1
Host: login.cloud.xxxxxx.com
Accept: application/json
Connection: close
Content-Type: application/json
User-Agent: go-cli 6.21.0+dff2cf8 / linux



REQUEST: [2016-07-29T14:28:15-04:00]
GET /login HTTP/0.0
Host: login.cloud.xxxxxx.com
Accept: application/json
Connection: close
Referer: http://login.cloud.xxxxxx.com/login
User-Agent: go-cli 6.21.0+dff2cf8 / linux



RESPONSE: [2016-07-29T14:28:16-04:00]
HTTP/1.1 200 OK
Connection: close
Content-Length: 467
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Cache-Control: no-store
Content-Language: en-US
Content-Type: application/json;charset=UTF-8
Date: Fri, 29 Jul 2016 18:28:16 GMT
Expires: 0
Pragma: no-cache
Server: Apache-Coyote/1.1
Strict-Transport-Security: max-age=31536000 ; includeSubDomains
X-Content-Type-Options: nosniff
X-Frame-Options: DENY
X-Vcap-Request-Id: f340c716-510e-4baf-42c4-ab57eb38024e
X-Xss-Protection: 1; mode=block

{"app":{"version":"3.4.1"},"links":{"uaa":"https://uaa.cloud.xxxxxx.com","passwd":"https://login.cloud.xxxxxx.com/forgot_password","login":"https://login.cloud.xxxxxx.com","register":"https://login.cloud.xxxxxx.com/create_account"},"zone_name":"uaa","entityID":"login.cloud.xxxxxx.com","commit_id":"ddae2a1","idpDefinitions":{},"prompts":{"username":["text","Email"],"password":["password","Password"]},"timestamp":"2016-06-20T16:18:23+0000"}

Email> admin

Password> 
Authenticating...

REQUEST: [2016-07-29T14:28:33-04:00]
POST /oauth/token HTTP/1.1
Host: login.cloud.xxxxxx.com
Accept: application/json
Authorization: [PRIVATE DATA HIDDEN]
Connection: close
Content-Type: application/x-www-form-urlencoded
User-Agent: go-cli 6.21.0+dff2cf8 / linux

grant_type=password&password=[PRIVATE DATA HIDDEN]&scope=&username=admin

RESPONSE: [2016-07-29T14:28:33-04:00]
HTTP/1.1 400 Bad Request
Connection: close
Content-Length: 1086
Content-Language: en
Content-Type: text/html;charset=utf-8
Date: Fri, 29 Jul 2016 18:28:33 GMT
Server: Apache-Coyote/1.1
X-Vcap-Request-Id: 8f8fb18f-0bc4-449c-5bc3-7f4bc4aa71ee

<html><head><title>Apache Tomcat/7.0.61 - Error report</title><style></style> </head><body><h1>HTTP Status 400 - {&quot;error&quot;: &quot;request must be over https&quot;}</h1><HR size="1" noshade="noshade"><p><b>type</b> Status report</p><p><b>message</b> <u>{&quot;error&quot;: &quot;request must be over https&quot;}</u></p><p><b>description</b> <u>The request sent by the client was syntactically incorrect.</u></p><HR size="1" noshade="noshade"><h3>Apache Tomcat/7.0.61</h3></body></html>
Server error, status code: 400, error code: , message:

**Comment by Infra-Red** [comment]
@cpraveen412 Could you please check the value of property `uaa.require_https`, by default this value set to `true`and it can be a problem in case of self-signed certs, here the reference for bosh-lite stub example:
https://github.com/cloudfoundry/cf-release/blob/develop/templates/cf-infrastructure-bosh-lite.yml#L471

**Comment by cpraveen412** [comment]
that worked.
thanks @Infra-Red
