### ISSUE TITLE
boshhmforwarder doesn't appear to be in cf version 239?

### ISSUE THREAD

**Issue by dave-read** [cloudfoundry/cf-release#1015]
[Release notes](http://bosh.io/releases/github.com/cloudfoundry/cf-release?version=239#loggregator) for cf build 239 note inclusion of the boshhmforwarder.

I do see the boshhmforwarder job in version 58 of  [loggregator](http://bosh.io/releases/github.com/cloudfoundry/loggregator) but not in cf build 239.

Should boshhmforwarder  be in cf build 239?

Thanks

**Comment by Amit-PivotalLabs** [comment]
ping @Jim-Campbell @wfernandes

**Comment by wfernandes** [comment]
@Amit-PivotalLabs 

It's in the [Loggregator src](https://github.com/cloudfoundry/loggregator/tree/90a1f5f813d2a65bc05e9d494400efe720179734/src/boshhmforwarder)

And it's part of the [loggregator jobs](https://github.com/cloudfoundry/loggregator/tree/90a1f5f813d2a65bc05e9d494400efe720179734/jobs/boshhmforwarder) and [packages](https://github.com/cloudfoundry/loggregator/tree/90a1f5f813d2a65bc05e9d494400efe720179734/packages/boshhmforwarder)

Were we supposed to add it somewhere else?

**Comment by dave-read** [comment]
Yes it's in the loggregator jobs and packages.  However the announcement/details of the feature is in cf-release: http://bosh.io/releases/github.com/cloudfoundry/cf-release?version=239#loggregator

I could be wrong, but I assumed that the cf-release would be updated to include a version of loggregator that included the feature.

**Comment by wfernandes** [comment]
@dave-read I'm not sure I understand.
 
CF Release 239 [e53f998d](https://github.com/cloudfoundry/cf-release/tree/e53f998d767b5a09a43c87435fb655a6411f76db/src) does include a loggregator [90a1f5f](https://github.com/cloudfoundry/loggregator/tree/90a1f5f813d2a65bc05e9d494400efe720179734/jobs) that includes boshhmforwarder.

Now, CF Release doesn't provide a [job](https://github.com/cloudfoundry/cf-release/tree/e53f998d767b5a09a43c87435fb655a6411f76db/jobs) to expose the boshhmforwarder directly.


So if you'd want to make use of it, you can upload the [latest loggregator release](http://bosh.io/releases/github.com/cloudfoundry/loggregator?all=1) and pull the job in from the `loggregator` release.
[Here](https://github.com/cloudfoundry/loggregator/tree/b0d1f0beb4acd8fbfaf3b0f4a4b9ca9861f92e91/src/boshhmforwarder#setup-with-loggregator-as-a-separate-release) are some basic instructions of adding the `boshhmforwarder` to your manifest.

Hope this helps.

**Comment by Amit-PivotalLabs** [comment]
I think the question is, if cf-release doesn't expose the job directly, why is it in the cf-release release notes?

**Comment by Jim-Campbell** [comment]
OK, then if we've added the component to Loggregator, and it is straight forward to install via the readme, we should just announce on cf-dev and pull mention from release notes?

**Comment by Jim-Campbell** [comment]
Then we'll put a PR on cf-release for 240

**Comment by Amit-PivotalLabs** [comment]
Unless you plan to have it deployed and tested in the integration pipelines for CF release, it prob doesn't make sense to expose it in cf-release.  I would start with announcing it on cf-dev for folks to know they can use it.

**Comment by Jim-Campbell** [comment]
OK, remove from release notes?

**Comment by Amit-PivotalLabs** [comment]
Yeah, I think that makes the most sense.

**Comment by dave-read** [comment]
@wfernandes yes, pulling the latest loggregator release as you described works.  

@Amit-PivotalLabs thanks, you described the question more clearly than I did.

The suggestion to announce it for those that are interested make sense to me.

**Comment by wfernandes** [comment]
Closing this issue. The release notes have been updated.
