### ISSUE TITLE
Support for SSL certs for multiple domains in HA_proxy

### ISSUE THREAD

**Issue by GuruprakashS** [cloudfoundry/cf-release#1022]
Hi Team,

How do we go about supporting ssl certs for multiple domains in HA_proxy job coming along with CF release. Looks like we could not configure the required properties for multiple ssl config in the manifest file. Could someone help here?

Thanks,
Guru.

**Comment by Amit-PivotalLabs** [comment]
Hi @GuruprakashS 

There's a few different things to consider here, so it depends on your use case.  You might want to check out this previous discussion: https://lists.cloudfoundry.org/archives/list/cf-dev@lists.cloudfoundry.org/thread/WS3F4JPY4KHH26WMC4KLA3SKG556LU43/

If you could share more details about your use case, that might help, e.g. why do you have multiple domains, do you intend to have a frequently changing/increasing set of domains, why are you using the built-in HA Proxy, etc?

/cc @shalako @crhino

**Comment by GuruprakashS** [comment]
Hello @Amit-PivotalLabs , Thank you for your response.

We are deploying a CF on vSphere to support our CI, QE and DEV environments and hence we decided we have seperate orgs and then create a private domain corresponding to each of these Environments.
For SSL (which will terminate at HA_proxy) we need to have separate certs configured on Ha_proxy Job and hence this github issue.

The discussion you shared has useful information. We would try SAN certificates first and see if that satisfies our requirements.

Also i read in the discussion thread about terminating the  SSL using go router and not using HA_proxy at all. Could you please share any documentation around it and also the release version of CF which has that feature. It Would be helpful

Thanks,
Guru.

**Comment by GuruprakashS** [comment]
Thanks Shannon for the information. It's useful.
Yes our clients does support SNI.

Thanks,
Guru.
