### ISSUE TITLE
Invalid Ruby Version Set

### ISSUE THREAD

**Issue by apeschel** [cloudfoundry/cf-release#1025]
.ruby-version has an invalid ruby version set. This results in an error when at least `rbenv` is used as a Ruby version manager.

```
[master] 1187> rbenv versions
rbenv: version `2.3' is not installed (set by /Users/apeschel/projects/cf-release/.ruby-version)
  system
  2.3.1

[master] 1186> rbenv install -l | grep '^ *2.3'
  2.3.0-dev
  2.3.0-preview1
  2.3.0-preview2
  2.3.0
  2.3.1
```

**Comment by apeschel** [comment]
Relevant `rbenv` documentation on this behavior: https://github.com/rbenv/rbenv/wiki

**Comment by Amit-PivotalLabs** [comment]
@apeschel Just going to delete this file.  There's no reason for it to be strict about the ruby version you use.

**Comment by apeschel** [comment]
@Amit-PivotalLabs I appreciate it, thanks!
