### ISSUE TITLE
api_worker_z1/0' is not running after update - Blobstore is not available

### ISSUE THREAD

**Issue by valenbb** [cloudfoundry/cf-release#1028]
Getting the following for a fresh cf deployment on Openstack:

  Started updating job api_z1 > api_z1/0 (6bb0914f-8e3e-46fa-bad0-70085d6f02d2) (canary). Failed: 'api_z1/0 (6bb0914f-8e3e-46fa-bad0-70085d6f02d2)' is not running after update. Review logs for failed jobs: cloud_controller_ng, cloud_controller_worker_local_1, cloud_controller_worker_local_2, nginx_cc, cloud_controller_worker_1 (00:11:01)

Error 400007: 'api_z1/0 (6bb0914f-8e3e-46fa-bad0-70085d6f02d2)' is not running after update. Review logs for failed jobs: cloud_controller_ng, cloud_controller_worker_local_1, cloud_controller_worker_local_2, nginx_cc, cloud_controller_worker_1 

Specs:
- One single openstack all-in-one server (controller, neutron, glance, nova, identity, horizon)
- Ubuntu 14.04 bosh-init server (bosh-init cli version version 0.0.96-a26a88a-2016-07-19T23:13:15Z)
- bosh cli version BOSH 1.3262.4.0
- stemcell used is Ubuntu Trusty Openstack KVM 3262.5
- cf-release v239
- bosh v257.3
- Openstack CPI v25

Deployment file: https://s3.amazonaws.com/andysw/cf-deployment.yml

I have enabled one instance for blobstore and nfs jobs, respectively.

blobstore_z1 updated successfully with monit summary:
Process 'consul_agent'              running
Process 'metron_agent'              running
Process 'blobstore_nginx'           running
Process 'blobstore_url_signer'      running
Process 'route_registrar'           running
System 'system_localhost'           running

nfs_z1 also updated successfully with monit summary:
Process 'consul_agent'              running
Process 'rpc_nfsd'                  running
Process 'rpc_mountd'                running
Process 'metron_agent'              running
Process 'blobstore_nginx'           running
Process 'blobstore_url_signer'      running
Process 'route_registrar'           running
System 'system_localhost'           running

Logged into api_z1/0 instance via bosh ssh and looked over cloud_controller_ng logs. "Blobstore is not available" is being reported by cloud_controller_ng_ctl and cloud_controller_worker_ctl logs. 

api_z1/0 job log: https://s3.amazonaws.com/andysw/api_z1.0.2016-08-08-02-26-23.tgz

I have tried setting 0 instances for blobstore, or 0 for nfs or no blobstore and nfs, but the error still occurs.

Not sure where else to be looking.

Thanks in advance for all replies!

**Comment by valenbb** [comment]
Per Amit's suggestion in #985: 
"If you have a section in your stub that looks like this: https://github.com/cloudfoundry/cf-release/blob/3290ed8d88cc453a013b77941d3960abe27b2317/spec/fixtures/openstack/cf-stub.yml#L155-L187, you can try removing it and see if that helps."

I did this and the issue is resolved.
Uncommented cloud_controller_ng and cloud_controller_worker from the templates section of the api_z1 job since they were both reporting "Blobstore is not available".

If someone can verify for sure that there are no side effects, I will close this isssue.

**Comment by Infra-Red** [comment]
@valenbb The issue that yours manifest does not include `consul_agent` for api_z1 job. Just add to stub in api_z1 templates:
```
- name: consul_agent
  release: cf
```
@Amit-PivotalLabs This is a mistake in a Cloud Foundry deployment docs and this is must be fixed, stub for Openstack does not include `consul_agent` in `api_z1` job.
http://docs.cloudfoundry.org/deploying/openstack/cf-stub.html

**Comment by valenbb** [comment]
@Infra-Red You are correct, in that, my stub file does not include consul_agent for api_z1 job.

**Comment by tomsherrod** [comment]
I verified today, that if the stub has the section removed re: https://github.com/cloudfoundry/cf-release/issues/985 , the api_z1 job succeeds. Deployed apps with no issues.

**Comment by Amit-PivotalLabs** [comment]
Sounds like @tomsherrod verified, closing.

**Comment by valenbb** [comment]
I also verified that it also works if the consul_agent for api_z1 job is included. There needs to be verification if consul_agent template is needed for api_z1 job.

**Comment by tomsherrod** [comment]
@valenbb yes, before getting Amit's suggestion and reviewing later vsphere/aws stubs, we made the stub work by adding the consul_agent template. I believe the stub modified to be without the api_z1 section is the better way, to pick up any addition template mods.

**Comment by discrete** [comment]
I had the same issue with @valenbb and adding colsul_agent solved the problem
