### ISSUE TITLE
cf-release 239 - running ./scripts/update fails with Failed to recurse into submodule path 'src/consul-release'

### ISSUE THREAD

**Issue by ra1100** [cloudfoundry/cf-release#1030]
Recurrence or similar issue to cf-release 231 issue #916 https://github.com/cloudfoundry/cf-release/issues/916

Issue:  Incorrect URL in .gitmodules for consul-release module in check-a-dns

Fix: edit and replace URL git:// with https:// - in .gitmodules, file:
./src/consul-release/src/acceptance-tests/vendor/github.com/cloudfoundry-incubator/check-a-record/.gitmodules

Submodule path 'src/consul-release/src/acceptance-tests/vendor/github.com/cloudfoundry-incubator/check-a-record': checked out '35484353ff36236f2a46ea0f722066e659690269'
Cloning into 'vendor/github.com/miekg/dns'...
fatal: unable to connect to github.com:
github.com[0: 192.30.253.112]: errno=Connection timed out

Clone of 'git://github.com/miekg/dns' into submodule path 'vendor/github.com/miekg/dns' failed

**Comment by Infra-Red** [comment]
Hi @ra1100 !
This submodule was already removed from consul-release, please refer to the following commit in https://github.com/cloudfoundry-incubator/consul-release/commit/0d967bff361a190a652e0d9a85ee0c9503df2cba#diff-8903239df476d7401cf9e76af0252622L73.

If you are trying to create dev bosh release, i would recommend you to sync with develop branch from `cf-release` and run `./scripts/update` again.

**Comment by ra1100** [comment]
Thanks @Infra-Red , good advice.

However the issue is breaking things for people (maybe first time users) trying to run a bosh-lite install + cloud foundry deploy [instructions](https://github.com/cloudfoundry/bosh-lite/blob/master/README.md#install-bosh-lite)

pulls from master when fetching submodules with ./scripts/update or provision_cf,  so looks like this needs a fix in the packaging removed / promoted to master from develop in order for the cf deploy to bosh-lite to work per the instructions

**Comment by christianang** [comment]
Hi @ra1100,

This is now fixed in v240, which was pushed a few hours ago. Please try again with the latest release and let us know if you continue to see this issue.

Thanks,
Christian and @kkallday

**Comment by Amit-PivotalLabs** [comment]
Gonna assume @christianang's comment fixes your problem.  Feel free to ask here if you still need help.  Closing.
