### ISSUE TITLE
Error Generating Manifest:  Unresolved Nodes

### ISSUE THREAD

**Issue by aremily** [cloudfoundry/cf-release#1036]
I'm attempting to perform a local deployment of Cloud Foundry on Ubuntu 16.04.1 LTS that I will use as a sandbox in an effort to familiarize myself with CF.  I am following the instructions for "Create a Deployment Manifest for Cloud Foundry on BOSH-Lite" located here:

http://docs.cloudfoundry.org/deploying/boshlite/create_a_manifest.html.

I have successfully completed the preparatory steps "Setup a BOSH-Lite Vagrant VM" using Virtualbox as a provider located here:

https://github.com/cloudfoundry/bosh-lite/blob/master/README.md#install-bosh-lite 

I omitted all optional steps for "Create a Deployment Manifest for Cloud Foundry on BOSH-Lite" because I am using Virtualbox.  I am using the bosh-lite and cf-release repositories current as of today.  When I run the following script (Step 5) to create a deployment manifest:

`
alex@ubuntu:~/workspace/cf-release$ sudo ./scripts/generate-bosh-lite-dev-manifest`

I get the below error.  I hope that this is a simple configuration problem and that someone with more CF experience can easily point me in the right direction.

```
2016/08/14 11:23:36 error generating manifest: unresolved nodes:
	(( .properties.nats.machines ))	in /home/alex/workspace/cf-release/templates/cf.yml	properties.etcd_metrics_server.nats.machines
	(( .properties.uaa.port ))	in /home/alex/workspace/cf-release/templates/cf.yml	meta.uaa_routes.[0].port
	(( .properties.uaa.port ))	in /home/alex/workspace/cf-release/templates/cf.yml	jobs.[11].properties.route_registrar.routes.[0].port
	(( .properties.uaa.port ))	in /home/alex/workspace/cf-release/templates/cf.yml	jobs.[12].properties.route_registrar.routes.[0].port
```

**Comment by Amit-PivotalLabs** [comment]
Hi @aremily 

I wasn't able to reproduce this issue.  Can you share the output of the following commands from your `cf-release` directory?

```
$ git log -1 --oneline
c432b73 Manifest generation scripts support TLS etcd cluster [#122070663]

$ git status
On branch develop
Your branch is up-to-date with 'origin/develop'.
nothing to commit, working tree clean

$ spiff -v
spiff version 1.0.7

$ bosh -v
BOSH 1.3262.4.0

$ ./scripts/generate-bosh-lite-dev-manifest
Deployment set to '/Users/agupta/workspace/cf-release/bosh-lite/deployments/cf.yml'
```

**Comment by aremily** [comment]
alex@ubuntu:~/workspace/cf-release$ git log -1 --oneline
1b88d9e Final release 240
alex@ubuntu:~/workspace/cf-release$ git status
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working directory clean
alex@ubuntu:~/workspace/cf-release$ spiff -v
spiff version 1.0.0
alex@ubuntu:~/workspace/cf-release$ bosh -v
BOSH 1.3262.4.0
alex@ubuntu:~/workspace/cf-release$ ./scripts//generate-bosh-lite-dev-manifest 
./scripts//generate-bosh-lite-dev-manifest: line 37: ./scripts/../bosh-lite/deployments/cf.yml: Permission denied
alex@ubuntu:~/workspace/cf-release$ sudo ./scripts//generate-bosh-lite-dev-manifest 
[sudo] password for alex: 
Deployment set to '/home/alex/workspace/cf-release/bosh-lite/deployments/cf.yml'
alex@ubuntu:~/workspace/cf-release$

**Comment by Amit-PivotalLabs** [comment]
That looks like it worked, since it says:

```
Deployment set to '/home/alex/workspace/cf-release/bosh-lite/deployments/cf.yml'
```

That's the message it outputs when it's successful.  You're not seeing the unresolved nodes errors anymore.

**Comment by aremily** [comment]
I wish all my problems were that easy to solve.  Thanks!

**Comment by gidxl03** [comment]
Just got the same error, turned out it was due to using an old version of spiff (1.0.0)
