### ISSUE TITLE
'dea_next' pre-packaging failed

### ISSUE THREAD

**Issue by aremily** [cloudfoundry/cf-release#1039]
This is a follow on from Error Generating Manifest: Unresolved Nodes [#1036](https://github.com/cloudfoundry/cf-release/issues/1036#issuecomment-240417186).  Once I successfully generated the manifest file, I proceeded with the instructions here: 

http://docs.cloudfoundry.org/deploying/common/deploy.html

When I performed the "Build the Cloud Foundry Release" step by executing 
`bosh create release` I received what appears to be a Ruby related build error.  I'm not sure if it's relevant, but I notice that the cf release build builds Ruby 2.1.8, and I am running Ruby 2.3.1 per the earlier instructions.  Should I target a different build?

Thanks again.

Pertinent log output, beginning with specifying the release name (Cleaned up the formatting as best I could):

Please enter development release name: |cf| cf-2405M  
.
.
.
Building rootfs_cflinuxfs2...
  Using final version '0289ab40e052400035836445cf9841deefd04767'

Building etcd-dns-checker...
  Using final version '9676918944de93dd773b706cc7ecc68073492372'

Building ruby-2.1.8...
  Using final version '0a758a4dc3408937b64f89aaa39f8ee25cce5454'

Building php-buildpack...
  Using final version '6803736622b95ae7c804ef91316436b9d9a17069'

Building python-buildpack...
  Using final version '3aa7326b3cc0a8732c829a09fd3a617b303e8474'

Building nginx_webdav...
  Using final version 'ee1d48cbce7f78f1395b12837a500c11e5066fa7'

Building nsync...
  Using final version 'c327241cb74eb4b53d616b7020771947f4749881'

Building binary-buildpack...
  Using final version 'fa170a1f3c2aa97658e1158eb1ff2651b3190d13'

Building common...
  Using final version '953ccbc1b39fc972d2b4903beb16af7daf78cc85'

Building consul...
  Using final version '786f3d52dcbb785f523f3b39b172b9b7e2a9c148'

Building cc_uploader...
  Using final version '127877d71992ee16053d4f1996c811c19e9b6622'

Building nats-common...
  Using final version '1f712a21c0b1cbb3b547eccc79eb159aaee48b99'

Building haproxy...
  Using final version 'f5d89b125a66892628a8cd61d23be7f9b0d31171'

Building stager...
  Using final version '2bd4e3a6b76ca980be2d33e25676bd6c895429ef'

Building capi_utils...
  Using final version 'f0746a954b2d4ab7bf905b8bc742584801e21357'

Building collector...
  Using final version '9f8dfbcbcfffb124820327ad2ad4fee35e51d236'

Building loggregator_trafficcontroller...
  Using final version '2fc7911b9d9aad4106649c4f4d2e585b0dbc9b4e'

Building cli...
  Using final version '817758b7e99b9cece5a45f7c6ef2920b52014ac0'

Building dea_next...
  No artifact found for dea_next
  Generating...
  Pre-packaging...
set -e -x
cd /tmp/d20160817-21763-d84lff/d20160817-21763-1halpou/dea_next
BUNDLE_WITHOUT=development:test
bundle package --all --no-install --path ./vendor/cache
Fetching gem metadata from https://rubygems.org/
Fetching version metadata from https://rubygems.org/
Fetching https://github.com/cloudfoundry/warden.git
Fetching https://github.com/intridea/grape.git
Fetching https://github.com/cloudfoundry/loggregator_emitter.git
Fetching https://github.com/nats-io/ruby-nats.git
Using json 1.8.3
Using minitest 5.8.4
Using httpclient 2.7.1
Using json_pure 1.8.3
Using bundler 1.12.5
Using warden-protocol 0.1.5 from https://github.com/cloudfoundry/warden.git (at master@b72b8c5)
Using loggregator_emitter 5.0.1 from https://github.com/cloudfoundry/loggregator_emitter.git (at master@7863578)
Using warden-client 0.1.0 from https://github.com/cloudfoundry/warden.git (at master@b72b8c5)
Using nats 0.6.0 from https://github.com/nats-io/ruby-nats.git (at master@d0556a0)
Using em-warden-client 0.1.2 from https://github.com/cloudfoundry/warden.git (at master@b72b8c5)
Using grape 0.16.3 from https://github.com/intridea/grape.git (at master@c2778cf)
Updating files in vendor/cache
* rake-11.1.2.gem
* i18n-0.7.0.gem
* json-1.8.3.gem
Could not find minitest-5.8.4.gem for installation

'dea_next' pre-packaging failed
alex@ubuntu:~/workspace/cf-release$ ruby -v
ruby 2.3.1p112 (2016-04-26) [x86_64-linux-gnu]

**Comment by Amit-PivotalLabs** [comment]
As an alternative to building from source (if you're not hacking on the internals of Cloud Foundry itself, no need to build from source), you may want to just deploy the latest stable build:

```
bosh upload release https://bosh.io/d/github.com/cloudfoundry/cf-release
```

**Comment by aremily** [comment]
I'll give that a shot.  Thanks.

**Comment by kevinzurek** [comment]
I am still receiving this same issue as @aremily when building from source per instructions (http://docs.cloudfoundry.org/deploying/common/deploy.html). minitest 5.8.4 is in my list of local gems.
