### ISSUE TITLE
What is the difference between staging-security-group, running-security-group & security-group ?

### ISSUE THREAD

**Issue by Niranjana-5588** [cloudfoundry/cf-release#1053]
The command `cf bind-security-group SECURITY-GROUP ORG SPACE` binds security group to ORG and SPACE. Already security-group bind with ORG and SPACE then what is the use of `bind-staging-security-group` and `bind-running-security-group.`

It make sense that different security groups for app staging and running, what is use of `bind-security-group` when running security group applied to app.

Commands
```
cf bind-staging-security-group SECURITY-GROUP
cf bind-running-security-group SECURITY-GROUP
```
not mentioned ORG and SPACE. With what it is binding ORG or SPACE or container ?

**Comment by Amit-PivotalLabs** [comment]
I believe `bind-staging-security-group` applies the security group to *all* staging containers, and similar for the `-running-` variety.  The `bind-security-group` applies to a specific space as you can see in the command usage from the CLI, and I believe only applies to running containers.  Docs: https://docs.pivotal.io/pivotalcf/1-7/adminguide/app-sec-groups.html#binding-groups

/cc @SocalNick @dkoper

**Comment by SocalNick** [comment]
@Amit-PivotalLabs that is correct, this is also documented in OSS docs: http://docs.cloudfoundry.org/adminguide/app-sec-groups.html#binding-groups

**Comment by Niranjana-5588** [comment]
Thank you Amit, Thats simple and clear reply. 
@Amit-PivotalLabs  & @SocalNick If ORG has 5 SPACES and applied security group using `bind-staging-security-group` or `bind-running-security-group`. Is this security group will applied to all 5 SPACES ?

Because these commands applies to containers not to SPACES. Is my understanding correct ?

**Comment by Amit-PivotalLabs** [comment]
I believe `bind-staging-security-group` and `bind-running-security-group` would apply to not only your 5 spaces in your org, but in fact all spaces in all orgs.  I believe you need to be an admin to do this.  I don't understand your last statement: "Because these commands applies to containers."

**Comment by SocalNick** [comment]
@Niranjana-5588 all security groups end up applying to containers (personally, I would think about them applying to apps and staging tasks as containers are an implementation detail), it's just a matter of which containers. 

cf bind-staging-security-group SECURITY-GROUP Applies to all staging tasks for the entire Cloud Foundry deployment. 

cf bind-running-security-group SECURITY-GROUP Applies to all applications for the entire Cloud Foundry deployment. 

cf bind-security-group SECURITY-GROUP ORG SPACE Applies to all applications in a space.

**Comment by Niranjana-5588** [comment]
Got it and closing this issue. Thank you all.
