### ISSUE TITLE
cloud controller failed after update

### ISSUE THREAD

**Issue by chrisrana** [cloudfoundry/cf-release#1054]
I am  using bosh-257.9.tgz, bosh-openstack-cpi-release-27.tgz and cf-233 on Openstack Liberty.

I am using 3262.2 stemcell.

Cloud controller is failing to update

Process 'etcd'                      running
Process 'etcd_metrics_server'       running
Process 'nats'                      running
Process 'nats_stream_forwarder'     not monitored
Process 'collector'                 Execution failed
Process 'postgres'                  running
Process 'uaa'                       Connection failed
Process 'cloud_controller_clock'    running
Process 'consul_agent'              Execution failed
Process 'cloud_controller_ng'       Execution failed
Process 'cloud_controller_worker_local_1' initializing
Process 'cloud_controller_worker_local_2' initializing
Process 'nginx_cc'                  initializing
Process 'cloud_controller_migration' running
Process 'statsd-injector'           running
Process 'blobstore_nginx'           running
Process 'route_registrar'           Execution failed
Process 'metron_agent'              running
System 'system_localhost'           running

I found two host  entry against cloud controller, one starts with index other one starts with some ID.
95a07d80-3fb8-40db-8a13-3c295755b066.cloud-controller.ccc-bosh-net.cf-installer-team-test.microbosh

**postgres db records table in Director**

  7 | 232.0.20.10.in-addr.arpa                                                                            | PTR  | 0.consul.ccc-bosh-net.cf-installer-team-test.microbosh
  8 | 48d2b0a4-8533-4b7d-a3c5-b11ab463e910.consul.ccc-bosh-net.cf-installer-team-test.microbosh           | A    | 10.20.0.232
  9 | 232.0.20.10.in-addr.arpa                                                                            | PTR  | 48d2b0a4-8533-4b7d-a3c5-b11ab463e910.consul.ccc-bosh-net.cf-installer-team-test.mi
crobosh
 10 | 0.cloud-controller.ccc-bosh-net.cf-installer-team-test.microbosh                                    | A    | 10.20.0.231
 11 | 231.0.20.10.in-addr.arpa                                                                            | PTR  | 0.cloud-controller.ccc-bosh-net.cf-installer-team-test.microbosh
 12 | 95a07d80-3fb8-40db-8a13-3c295755b066.cloud-controller.ccc-bosh-net.cf-installer-team-test.microbosh | A    | 10.20.0.231
 13 | 231.0.20.10.in-addr.arpa                                                                            | PTR  | 95a07d80-3fb8-40db-8a13-3c295755b066.cloud-controller.ccc-bosh-net.cf-installer-te
am-test.microbosh

**cloud_controller_clock_ctl.err.log**

[2016-09-14 10:32:13+0000] PG::ConnectionBad: could not translate host name 0.cloud-controller.ccc-bosh-net.cf-installer-team-test.microbosh to address: Name or service not known
[2016-09-14 10:32:13+0000] Tasks: TOP => clock:start
[2016-09-14 10:32:13+0000] (See full trace by running task with --trace)
[2016-09-14 10:35:08+0000] ------------ STARTING cloud_controller_clock_ctl at Wed Sep 14 10:35:08 UTC 2016 --------------
[2016-09-14 10:35:11+0000] rake aborted!
[2016-09-14 10:35:11+0000] Sequel::Migrator::NotCurrentError: migrator is not current
[2016-09-14 10:35:11+0000] Tasks: TOP => clock:start
[2016-09-14 10:35:11+0000] (See full trace by running task with --trace)
[2016-09-14 10:39:17+0000] ------------ STARTING cloud_controller_clock_ctl at Wed Sep 14 10:39:17 UTC 2016 --------------

When I try to ping 0.cloud-controller.ccc-bosh-net.cf-installer-team-test.microbosh   inside the cloud controller VM, it is failing to ping.
Please help me on this

**Comment by jaresty** [comment]
Hi @chrisrana -- can you please submit a copy of your deployment manifest?  Please redact any secrets before you submit it.  It will help us try to understand your issue better.  

*FWIW: It may be relevant that version 233 of CF is several months old; we are on v243 now.*

**Comment by chrisrana** [comment]
The issue was because of dns ip.I should have added bosh director ip as dns ip.Please close this case
