### ISSUE TITLE
Application instance's CPU display is not correct

### ISSUE THREAD

**Issue by ybshen** [cloudfoundry/cf-release#1063]
CF release is V237.The runtime is dea_next.When i create a tomcat app,I found that the app instance's cpu display 2008.94%.How can i do ?
Thanks.

**Comment by jleavers** [comment]
I believe this was resolved in v239:

https://github.com/cloudfoundry/cf-release/releases/tag/v239

"Fix order of magnitude in CPU consumption reported by cf app"

**Comment by dsabeti** [comment]
@ybshen I'm going to close this issue since the bug has been resolved in more recent releases of cf. Please open a new issue if upgrading hasn't solved this for you.
