### ISSUE TITLE
Unable to Create a Compiled Release of CF 244 Due to Windows Packaging Issue

### ISSUE THREAD

**Issue by davewalter** [cloudfoundry/cf-release#1068]
When trying to create a compiled release of v244 of CF we encountered an error for a windows package inside of loggregator. While BOSH is intelligent enough to skip the compilation of unused packages in a source deployment, it does not have the ability to skip incompatible packages when creating a compiled release for later deployments.

The fix has already been submitted as a PR to loggregator (https://github.com/cloudfoundry/loggregator/pull/156). What we are proposing/asking is if the team maintaining cf-release could validate the ability to create a compiled release prior to cutting final releases. 

Does this seem reasonable?

**Comment by dsabeti** [comment]
@davewalter Thanks for pointing this out. It seems like a reasonable request, but I'm only the acting PM while @Amit-PivotalLabs is on vacation. I'll discuss it with him next week when he gets back.

**Comment by davewalter** [comment]
Thanks for the update.

**Comment by youngm** [comment]
Any update on this issue?

**Comment by dsabeti** [comment]
@davewalter I've been thinking about this some more. The Release Integration team would definitely be the responsible team if we decided to do this. However, we're gearing up to deprecate cf-release in favor of [cf-deployment](https://github.com/cloudfoundry/cf-deployment). In such a world, there will be no cf-release, only the component sub-releases, such as capi-release, routing-release, diego-release, etc. So, each release team (e.g., loggregator, capi, diego, routing, etc.) would be responsible for validating that their releases can be compiled prior to cutting final releases.

I'm going to reach out the PM's of those teams to see if this seems like something they could prioritize soon.

**Comment by dsabeti** [comment]
Hey @davewalter. I took 6 months, but we finally got around to acting on this. The RelInt team is working to ship compiled releases with [cf-deployment](https://github.com/cloudfoundry/cf-deployment).

You can follow our first release marker [here](https://www.pivotaltracker.com/story/show/141059981), and future ones [here](https://www.pivotaltracker.com/story/show/141059933) and [here](https://www.pivotaltracker.com/story/show/141059931).
