### ISSUE TITLE
Cannot bosh deploy due to director VM paused

### ISSUE THREAD

**Issue by kenfting** [cloudfoundry/cf-release#1069]
Hi, dear all,
When I use bosh deploy to deploy the uploaded Cloud Foundry release, it prints:
System call error while talking to director: No route to host - connect(2) for "130.127.*.*" port 25555 (130.127.*.*:25555)

Also I run "watch df -h" from director VM, until the director vm was paused. At last moment, it told me that:
Filesystem      Size  Used Avail Use% Mounted on
udev            7.9G  4.0K  7.9G   1% /dev
tmpfs           1.6G  392K  1.6G   1% /run
/dev/vda1       2.8G  1.6G  1.1G  60% /
none            4.0K     0  4.0K   0% /sys/fs/cgroup
none            5.0M     0  5.0M   0% /run/lock
none            7.9G     0  7.9G   0% /run/shm
none            100M     0  100M   0% /run/user
/dev/vda3       140G  5.4G  127G   5% /var/vcap/data
tmpfs           1.0M   44K  980K   5% /var/vcap/data/sys/run
/dev/vdb1        40G  361M   37G   1% /var/vcap/store

I tried to soft reboot director vm, and I got:
Error: Failed to perform requested operation on instance "vm-6459b9b8-d11e-4ac9-91e8-9dec3397c5a3", the instance has an error status: Please try again later [Error: [Errno 28] No space left on device].

Maybe the deployment run out the space of director vm, is it /dev/vda1? so what should I do to enlarge  the space? Thanks!

**Comment by dsabeti** [comment]
@kenfting There are lot of things that could be going wrong here. Let's try to rule some things out. Can you ssh on to your bosh director? If you can do that, can you use `du` to find the file(s) in `/` (the mount point for `/dev/vda1`) that are using up all your disk?

Also, just to get this out of the way, what IaaS are you running this on? Please also upload your bosh-init manifest and your cf manifest **but make sure to remove any passwords or private keys**.

**Comment by kenfting** [comment]
@dsabeti  Thanks so much for your reply. I use Openstack to deploy cf. Because the director is paused, and can not be connected by ssh. I will re-deploy the director again. my cf manifest is here, please help me check it. Thanks again.
https://github.com/kenfting/my-bosh/blob/master/cf-stub.yml
So could I configure a bigger size for /dev/vda1?

**Comment by dsabeti** [comment]
@kenfting I don't think the disk size for that mount point is configurable. Most likely, something else is going wrong and so the bosh director is spewing logs to `/var/log` and filling up the disk. Let me know what you find when you re-deploy your director and ssh onto it.

**Comment by kenfting** [comment]
@dsabeti  Thanks. I re-deploy the director and ssh onto it, use  "du -h / | sort -hr | head",
2.0G	        /
1.1G   	/var
991M	/var/vcap
562M	/var/vcap/data
541M	/usr
436M	/var/vcap/data/packages
390M	/var/vcap/micro_bosh/data/cache
390M	/var/vcap/micro_bosh/data
390M	/var/vcap/micro_bosh
351M	/lib

Is there something wrong here or my cf-stub.yml wrong? Thanks again.

**Comment by dsabeti** [comment]
@kenfting I'm not sure what's going wrong here. Since this is really a question about BOSH (as opposed to cf-release), would you mind closing this issue and starting a thread with the BOSH team? You can email cf-bosh@lists.cloudfoundry.org, ask for help in the #bosh channel on the [CF Slack](https://slack.cloudfoundry.org/), or even open a github issue on [the bosh repo](https://github.com/cloudfoundry/bosh).

**Comment by kenfting** [comment]
@dsabeti Thanks all the same for your help.
