### ISSUE TITLE
Unable to connect to CF login, getting i/o timeout error

### ISSUE THREAD

**Issue by vchattamoni** [cloudfoundry/cf-release#1070]
Hello,

I have installed CF 239 on bare metal from https://docs.cloudfoundry.org/deploying/vsphere/

cli version
cf version 6.22.1+6b7af9c-2016-09-24

Getting Error during cf curl operation is
Error performing request: Get https://api.xxx.com/v2/info: dial tcp 12.xx.xxx.102:443: i/o timeout
TIP: If you are behind a firewall and require an HTTP proxy, verify the https_proxy environment variable is correctly set. Else, check your network connection.

Can anyone suggest ASAP.

**Comment by dsabeti** [comment]
I addressed this issue in https://github.com/cloudfoundry/cli/issues/969. I'm going to close it.
