### ISSUE TITLE
error generating manifest: unresolved nodes in v244

### ISSUE THREAD

**Issue by neilhwatson** [cloudfoundry/cf-release#1072]
```
 /root/cf-release/scripts/generate_deployment_manifest vsphere /root/cf-manifest.yml > /root/cf-deployment.yml
2016/10/05 13:42:02 error generating manifest: unresolved nodes:
        (( merge ))     in /root/cf-release/templates/cf.yml    properties.uaa.clients.cc-service-dashboards.secret     (properties.uaa.clients.cc-service-dashboards.secret)
```

This manifest worked with v242.

[cf-manifest.txt](https://github.com/cloudfoundry/cf-release/files/511818/cf-manifest.txt)

**Comment by dsabeti** [comment]
Hey @neilhwatson. You need to generate a random secret and add/merge the following in your stub:
```yaml
properties:
  uaa:
    clients:
      cc-service-dashboards:
        secret: YOUR_SECRET
```

It's been an optional field for a pretty long time (it was introduced roughly two years ago), but was made mandatory in v244. Apologies -- it's typically something that gets recorded in release notes for exactly this reason -- for deployers not to be surprised by new required fields. I'm going to add it in now. Thanks!
