### ISSUE TITLE
Error dialing trafficcontroller server: websocket: bad handshake.

### ISSUE THREAD

**Issue by acho-bacho** [cloudfoundry/cf-release#1075]
When issuing command "cf logs <app_name>" I get and error 

> FAILED
> Error dialing trafficcontroller server: websocket: bad handshake.
> Please ask your Cloud Foundry Operator to check the platform configuration (trafficcontroller is wss://doppler.bosh-lite.com:443).

The issue came after latest update of cf-release repository

CLI version: 6.22.1+6b7af9c-2016-09-24
cf-release at 3fe0372061cf04c65fd0b3c69de8633977b0a1d8

**Comment by acho-bacho** [comment]
cf logs <app_name> --recent
gives me 

> FAILED
> unknown issue when making HTTP request to Loggregator

**Comment by jaresty** [comment]
Hi @acho-bacho,

Can you please upload your manifest (or let us know how to rebuild it -- e.g. did you just run cf-`release/scripts/generate-bosh-lite-dev-manifest`, for example?), redacting all passwords and sensitive information?  This will help us debug your issue.

Thanks,

jaresty && @ChunyiLyu

**Comment by acho-bacho** [comment]
@jaresty I provision the CF using the "./bin/provision_cf" command from within bosh-lite directory

**Comment by dsabeti** [comment]
Hi @acho-bacho. We have a few questions:

1. Did you perform an upgrade on this cf deployment? By that I mean, did you have an earlier version of cf-release deployed before deploying v245? If so, which version? Also, assuming you upgraded your deployment, did you use `provision_cf` both times that you deployed? If you didn't use `provision_cf` for both deploys, did you re-generate the manifest when you re-deployed?

2.  Could you show the output of `cf curl /v2/info`?

There was a change to [loggregator that changed the logging endpoint](https://github.com/cloudfoundry/cf-release/releases/tag/v244#loggregator), and I'm wondering if that's what's causing this problem. @wfernandes @nelsam, do y'all have any thoughts on this?

Lastly, @acho-bacho, if you don't care about the history of this deployment (considering that its bosh-lite) and would be ok tearing it down, you might want to consider running `vagrant destroy; vagrant up; bin/provision_cf`. We just re-deployed from scratch and don't have any problems with the logging endpoint.

**Comment by acho-bacho** [comment]
@dsabeti 
Yes, I performed an upgrade of the cf deployment. But I am not sure what version it was before, but I initially installed the environment not more than two weeks before that. For all updates I use `provision_cf`.
Here's the output of  `cf curl /v2/info`

> {
>    "name": "",
>    "build": "",
>    "support": "http://support.cloudfoundry.com",
>    "version": 0,
>    "description": "",
>    "authorization_endpoint": "https://login.bosh-lite.com",
>    "token_endpoint": "https://uaa.bosh-lite.com",
>    "min_cli_version": null,
>    "min_recommended_cli_version": null,
>    "api_version": "2.63.0",
>    "app_ssh_endpoint": "ssh.bosh-lite.com:2222",
>    "app_ssh_host_key_fingerprint": "a6:d1:08:0b:b0:cb:9b:5f:c4:ba:44:2a:97:26:19:8a",
>    "app_ssh_oauth_client": "ssh-proxy",
>    "logging_endpoint": "wss://loggregator.bosh-lite.com:443",
>    "doppler_logging_endpoint": "wss://doppler.bosh-lite.com:4443"
> }

My environment has the following versions now:
CF cf/245+dev.1 
CLI cf version 6.21.1+6fd3c9f-2016-08-10
Vagrant box cloudfoundry/bosh-lite (virtualbox, 9000.131.0)
BOSH 1.3262.4.0


cf logs and cf logs --recent still give me:

> 
> $ cf logs <app>
> FAILED
> Error dialing traffic controller server: websocket: bad handshake.
> Please ask your Cloud Foundry Operator to check the platform configuration (traffic controller is wss://doppler.bosh-lite.com:443).
> $ cf logs <app> --recent
> Connected, dumping recent logs for app dashboard in org bosch / space demo as admin...
> 
> FAILED
> unknown issue when making HTTP request to Loggregator
>

**Comment by APShirley** [comment]
Hey @acho-bacho, here's what we suspect is going on:

Your loggregator traffic controller may have, for whatever reason, failed to register its route with with the router post-upgrade. To help confirm, could you set CF_TRACE=true and re-run the logging commands?

If this is the case, we'd expect to see the websocket response come back 404.

There's an older [blog post](http://www.starkandwayne.com/blog/fixing-loggregator-problems-one-problem-at-a-time/) about this issue; we've not seen it in a while, but it looks like it may well be what you're experiencing. The fix described there (login to your loggregator_trafficcontroller and restart its jobs) might help. More simply (and destructively) you could `bosh recreate` the loggregator_trafficcontroller job.

**Comment by acho-bacho** [comment]
@APShirley 
I get 

> RESPONSE: [2016-10-17T13:23:06+03:00]
> HTTP/1.1 200 OK
> Connection: close
> Content-Length: 8872
> Content-Type: application/json;charset=utf-8

for both` cf logs` and `cf logs --recent`

**Comment by acho-bacho** [comment]
Let me know if you need more feedback from my side. I do confirm that this issue is reproducible as our whole team is hitting the issue.

**Comment by ChunyiLyu** [comment]
@cloudfoundry/cf-loggregator, any chance we can get your eyes on this? The release integration team isn't sure how to take this any further.

**Comment by iplay88keys** [comment]
@acho-bacho We deployed to a new bosh lite and couldn't see the issue, either.  It seems like one of the loggregator jobs (most likely traffic controller or doppler) is in a bad state after the upgrade.

1. Can you show us the output of `bosh vms --vitals`?
2. Could you look on the `loggregator_trafficcontroller` VM in `/var/vcap/sys/log/loggregator_trafficcontroller/loggregator_trafficcontroller.stdout.log` and on the `doppler` VM in `/var/vcap/sys/log/doppler/doppler.stdout.log` for any logs that might be related to your request?  It might be worth tailing those logs while you try `cf logs --recent` to see if either of those logs show any errors while your request is being made.

**Comment by acho-bacho** [comment]
@iplay88keys 
`bosh vms --vitals` gives me
[vitals.txt](https://github.com/cloudfoundry/cf-release/files/544682/vitals.txt)

and here are the doppler and logregator files


[loggregator_trafficcontroller.stdout.log.txt](https://github.com/cloudfoundry/cf-release/files/544725/loggregator_trafficcontroller.stdout.log.txt)
[doppler.stdout.log.txt](https://github.com/cloudfoundry/cf-release/files/544724/doppler.stdout.log.txt)

**Comment by iplay88keys** [comment]
@acho-bacho It seems like DNS resolution for `api.bosh-lite.com` is failing on the trafficcontroller.

    lookup api.bosh-lite.com on 10.0.2.3:53: dial udp 10.0.2.3:53: i/o timeout

I'm not sure what would cause this but if traffic controller can not resolve the cloud controller the 500 is the desired behavior. @dsabeti Any ideas on why DNS would be failing?

I would just `vagrant destroy -f && vagrant up && bin/provision_cf` since it's just a bosh-lite (if you haven't tried that already). 

Not sure if someone from cf-release is interested in the failed upgrade behavior.

**Comment by acho-bacho** [comment]
@iplay88keys I alredy did `vagrant destroy -f && vagrant up && bin/provision_cf`
Some other ideas on how to solve the issue will be highly appreciated.

**Comment by dsabeti** [comment]
Ok @acho-bacho, let's try to troubleshoot your networking situation. It appears that your machine cannot reach either of the DNS servers listed in bosh-lite's `/etc/resolv.conf`. Is there anything unusual about the network you're running from? For example, are you inside a VPN?

Let's also get some data. Please ssh onto the vagrant host (you can use `vagrant ssh` for this) and provide the output of the following commands:
1. `cat /etc/resolv.conf`
2. `nslookup api.bosh-lite.com 8.8.8.8` (the second parameter tells `nslookup` to use a specific IP address for DNS lookup)
3. `nslookup api.bosh-lite.com 10.0.2.3`
4. `ping 8.8.8.8`
5. `ping 10.0.2.3`

**Comment by acho-bacho** [comment]
@dsabeti , yes, I am running my environment in a VM which is in a VPN. 

1. `cat /etc/resolv.conf`
> vagrant@bosh-lite:~$ cat /etc/resolv.conf
> # Dynamic resolv.conf(5) file for glibc resolver(3) generated by resolvconf(8)
> #     DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN
> nameserver 8.8.8.8
> nameserver 10.0.2.3

2. `nslookup api.bosh-lite.com 8.8.8.8`
> vagrant@bosh-lite:~$ nslookup api.bosh-lite.com 8.8.8.8
> ;; connection timed out; no servers could be reached

3. `nslookup api.bosh-lite.com 10.0.2.3`
vagrant@bosh-lite:~$ nslookup api.bosh-lite.com 10.0.2.3
> Server:         10.0.2.3
> Address:        10.0.2.3#53
> 
> Non-authoritative answer:
> Name:   api.bosh-lite.com
> Address: 10.244.0.34

4. `ping 8.8.8.8`
> vagrant@bosh-lite:~$ ping 8.8.8.8
> PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.
> 64 bytes from 8.8.8.8: icmp_seq=1 ttl=63 time=40.5 ms
> 64 bytes from 8.8.8.8: icmp_seq=2 ttl=63 time=40.3 ms
> ....and so on

5. `ping 10.0.2.3`
> vagrant@bosh-lite:~$ ping 10.0.2.3
> PING 10.0.2.3 (10.0.2.3) 56(84) bytes of data.
> 64 bytes from 10.0.2.3: icmp_seq=1 ttl=64 time=0.298 ms
> 64 bytes from 10.0.2.3: icmp_seq=2 ttl=64 time=0.332 ms
> ...and so on

**Comment by jasonkeene** [comment]
UDP:53 to 8.8.8.8 is likely blocked on your network. I'd remove the block. If that is not an option you can probably remove 8.8.8.8 from the list of DNS servers. 10.0.2.3 seems to be resolving. If all else fails, you can hard code the IPs for bosh-lite.com in your `/etc/hosts`.

**Comment by acho-bacho** [comment]
@jasonkeene thanks. Can you guide to me to the right way of removing 8.8.8.8 from the list of DNS servers? Can I just remove the symbolic link for `/etc/resolv.conf` and manually create the file with just 10.0.2.3 in it?

**Comment by ChunyiLyu** [comment]
@acho-bacho, the host hardcoding won't work in this case, and is unnecessary. The bosh-lite CPI picks up the vagrant VM's `/etc/resolve.conf` when configuring deployed agents/containers, but doesn't know or care about its `etc/hosts`.

You will, however, need to recreate the deployment containers in order to get them to pickup any changes. You can do this by running your normal `bosh` deploy command, but with the `--recreate` flag added.

If this resolves your issue, you may wish to make the change that ends up in your `/etcd/resolv.conf` in your Vagrantfile, so that it doesn't have to be done manually on the guest VM every time.

**Comment by acho-bacho** [comment]
@ChunyiLyu I did  bosh `deploy --recreate` but the problem still exists. 
Looking forward to more ideas.

**Comment by jaresty** [comment]
@acho-bacho Can you please run:
```
bosh download manifest cf-warden bosh-lite.yml
```
And upload the resulting bosh-lite manifest?  That way we can see exactly what you are running and try deploying it ourselves.  Thanks!

**Comment by jaresty** [comment]
Also, please upload the `Vagrantfile` you are using from the bosh-lite repo.

**Comment by acho-bacho** [comment]
@jaresty 
[Vagrantfile.txt](https://github.com/cloudfoundry/cf-release/files/584258/Vagrantfile.txt)

**Comment by staylor14** [comment]
Hi @acho-bacho,

I see that you've customized your virtualbox vm to disable natdnshostresolver1 and natdnsproxy1.  Can you try removing those customizations, and doing another destroy / up / provision cycle again?

**Comment by acho-bacho** [comment]
@staylor14 , those settings were added at a later point after the this issue was created so they are not the cause of the problem. Anyways, I removed them and re-provisioned but the problem persists.

**Comment by affandi19** [comment]
How do you fix this issue in windows? I having the same problem in windows locally when trying:
cf logs <app-name> and cf logs <app-name> --recent

**Comment by emperorente** [comment]
grpc: Server.Serve failed to complete security handshake from "192.168.16.22:52460": EOF

seems bad handshake with loggregator

**Comment by dsabeti** [comment]
@affandi19, please provide the following information:
- The output of `CF_TRACE=true cf logs --recent`
- The out put `cf curl /v2/info`
- Any information about your deployment (which IaaS, what version of cf-release and diego-release, etc.)

**Comment by affandi19** [comment]
@dsabeti I was able to resolve the issue. It seems i had multiple installations of Cloud Foundry all over the place in my local LOL. It was picking up an older version of cf. I uninstalled all of them, reinstalled the latest version, and it started working for me. Thanks for your replies.

**Comment by apoydence** [comment]
The 400 seems to indicate something else is wrong. 

- What IaaS is this installed on?
- What CLI version are you using?
- What version of the nozzle plugin are you using?
- What version of CF is this?
- Do the logs on traffic controller indicate anything?

**Comment by ashwithahn** [comment]
@apoydence 
1) We have Installed this on AWS
2) cf version` `cf version 6.36.1+e3799ad7e.2018-04-04``
3) Nozzle version ` FirehosePlugin   0.13.0`
4) Logs on Loggregator Traffic controller is as below
```
2018/07/25 03:16:17.463152 Startup: Setting up the loggregator traffic controller
2018/07/25 03:16:17.464459 health bound to: 127.0.0.1:14825
2018/07/25 03:16:17.464519 Metrics endpoint is listening on 127.0.0.1:14825
2018/07/25 03:16:17.465494 Event from finder: {GRPCDopplers:[10.0.16.16:8082 10.0.32.4:8082]}
2018/07/25 03:16:17.465527 adding doppler 10.0.32.4:8082
2018/07/25 03:16:17.465727 adding doppler 10.0.16.16:8082
2018/07/25 03:16:17.469336 ws bound to: 0.0.0.0:8081
2018/07/25 03:16:17.472072 pprof bound to: 127.0.0.1:46519
2018/07/25 03:42:15.072331 Connecting to 2 dopplers
2018/07/25 03:42:15.072367 websocket handler: Not a websocket handshake: websocket: not a websocket handshake: 'upgrade' token not found in 'Connection' header
2018/07/25 03:42:15.072497 Unable to connect to doppler (10.0.16.16:8082): rpc error: code = Canceled desc = context canceled
2018/07/25 03:42:15.072562 Disconnecting from stream (10.0.32.4:8082) (doppler.disconnect=false) (ctx.disconnect=1)
2018/07/25 03:42:15.072677 error receiving from doppler via gRPC context canceled
2018/07/25 03:42:15.073733 Disconnecting from stream (10.0.16.16:8082) (doppler.disconnect=false) (ctx.disconnect=1)
2018/07/25 03:42:21.768469 Connecting to 2 dopplers
2018/07/25 03:42:21.768502 websocket handler: Not a websocket handshake: websocket: not a websocket handshake: 'upgrade' token not found in 'Connection' header
2018/07/25 03:42:21.768570 Disconnecting from stream (10.0.16.16:8082) (doppler.disconnect=false) (ctx.disconnect=1)
2018/07/25 03:42:21.768592 Disconnecting from stream (10.0.32.4:8082) (doppler.disconnect=false) (ctx.disconnect=1)
```

**Comment by apoydence** [comment]
Based on those logs, it doesn't appear that the request is being proxied (either by the `gorouter` or your load balancer) correctly. 

This can be further proved if you try using a [sample loggregator client](https://github.com/cloudfoundry/noaa/tree/master/samples/firehose) on the traffic controller box directly. If it works there, then it safe to assume its one of the jumps in front of loggregator.
