### ISSUE TITLE
bosh deploy fails on haproxy using cf.yml template and dynamic networks

### ISSUE THREAD

**Issue by valeriap** [cloudfoundry/cf-release#1078]
Deploying cf with the provided cf.yml template and dynamic networks fails on updating haproxy job: 

```
Error 400007: 'ha_proxy_z1/0 (485e53e7-5dcc-4745-8c90-ef67cb04328d)' is not running after update. Review logs for failed jobs: haproxy_config, haproxy
```

This because ha_proxy_z1 job preceeds the router_z1 and router_z2 jobs.
Routers hostname are not yet registered when haproxy is updated and haproxy fails to start if backend server names don’t resolve:

```
2016-10-19 14:58:12+0000] [ALERT] 292/145812 (4150) : parsing [/var/vcap/jobs/haproxy/config/haproxy.conf:51] : 'server node0' : invalid address: '0.router-z1.cf1.xxx.microbosh' in '0.router-z1.cf1.xxx.microbosh:80'
```

Is it possible to move the ha_proxy_z1 job after routers in the template?

**Comment by dsabeti** [comment]
@valeriap We've made a change to the stubs to change the deployment order, and it's currently on the `release-candidate` branch. We'll close this issue out.
