### ISSUE TITLE
Cannot configure `artifacts_directory` from the manifest for smoke tests

### ISSUE THREAD

**Issue by henrytk** [cloudfoundry/cf-release#1089]
## Expected behaviour

When setting `properties.smoke_tests.artifacts_directory` in the manifest it is expected to be [templated into the smoke tests configuration file](https://github.com/cloudfoundry/cf-release/blob/v245/jobs/smoke-tests/templates/config.json.erb#L20-L37), with some logic which only adds it if it has been set.

## Actual behaviour

It does not.

## Impact

Implementors who want to configure an artifacts directory either have to use their own template or create workarounds, such as manipulating the configuration file after it has been templated.

## Suggested solution

Add logic to the template which checks if it has been set in the properties and add it if it has. I would not expect it to [hard code the value as is done for the acceptance tests](https://github.com/cloudfoundry/cf-release/blob/v245/jobs/acceptance-tests/templates/config.json.erb#L24) for the following reasons:

* this forces it to be on by default
* smoke tests can be run with much higher frequency, therefore generating a lot of output.

**Comment by dsabeti** [comment]
Hi @henrytk. You're correct that `artifacts_directory` is a field in the configuration as defined by the smoke test source code, but you may notice that it has never been part of [the errand's configuration definition](https://github.com/cloudfoundry/cf-release/blob/master/jobs/smoke-tests/spec#L15-L56). In general, an internal component (in this case, smoke-tests) consuming a certain field does not necessitate the ability to configure that field via the bosh manifests -- in fact, in some cases we purposefully do this to simplify the (already bloated) bosh manifests.

Having said that, it seems like a totally reasonable thing to add to the interface of smoke-tests errand. Would you be willing to submit a PR?

**Comment by dsabeti** [comment]
Hi @henrytk. I'm going to close this issue since we've prioritized your PR: https://github.com/cloudfoundry/cf-release/pull/1090
