### ISSUE TITLE
Connecting to endpoint https://api.bosh-lite.com/v2/info fails i/o timeout

### ISSUE THREAD

**Issue by khick77** [cloudfoundry/cf-release#1095]
using cf version  6.22.2+a95e24c-2016-10-27

When attempting to run cf api, I get the connection failure message:
```
vagrant@vagrant-ubuntu-trusty-64:~/bosh-lite$ cf api --skip-ssl-validation http
s://api.bosh-lite.com
Setting api endpoint to https://api.bosh-lite.com...

REQUEST: [2016-11-04T20:35:46Z]
GET /v2/info HTTP/1.1
Host: api.bosh-lite.com
Accept: application/json
Connection: close
Content-Type: application/json
User-Agent: go-cli 6.22.2+a95e24c / linux


FAILED
Error performing request: Get https://api.bosh-lite.com/v2/info: dial tcp 10.244
.0.34:443: i/o timeout
TIP: If you are behind a firewall and require an HTTP proxy, verify the https_pr
oxy environment variable is correctly set. Else, check your network connection.
```

I have run ./bin/add_route, with an output of:

```
vagrant@vagrant-ubuntu-trusty-64:~/bosh-lite$ ./bin/add-route
+ old_ips=10.244.0.0/19
+ ips=10.244.0.0/16
+ gw=192.168.50.4
+ echo 'Adding the following route entry to your local route table to enable dir
ect container access: 10.244.0.0/16 via 192.168.50.4. Your sudo password may be
required.'
++ uname
+ '[' Linux = Darwin ']'
++ uname
+ '[' Linux = Linux ']'
+ type route
+ sudo route del -net 10.244.0.0/19 gw 192.168.50.4
SIOCDELRT: No such process
+ sudo route add -net 10.244.0.0/16 gw 192.168.50.4
SIOCADDRT: File exists
```

For reference, my  /etc/resolve.conf looks like:
```
# Dynamic resolv.conf(5) file for glibc resolver(3) generated by resolvconf(8)
#     DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN
nameserver 10.0.2.3
nameserver 10.60.10.12
nameserver 10.60.10.11
search rpega.com
```

I've seen this topic repeatedly on the forums, but I haven't seen a clear solution.  Any thoughts or next steps I can take to troubleshoot?

**Comment by dsabeti** [comment]
Hi @khick77, let's see what we can figure out.

DNS resolution doesn't seem to be the problem, because when you try to target the url, the output shows the correct IP:
```
Error performing request: Get https://api.bosh-lite.com/v2/info: dial tcp 10.244
.0.34:443: i/o timeout
```

It seems like `bin/add_route` is failing:
```
SIOCDELRT: No such process

...

SIOCADDRT: File exists
```

I'm not very familiar with either of those errors, but a quick search reveals that there's possibly something unusual about your local networking or routing configuration. Could you post the output of both `ifconfig` and `route -n`?

**Comment by dsabeti** [comment]
@khick77, do you still need help with this? I'm going to close this issue on Monday otherwise.

**Comment by peluu** [comment]
i am also facing the same issue
`vagrant@bosh-lite:~$ cf login -a https://api.bosh-lite.com --skip-ssl-validation -u admin -p admin
API endpoint: https://api.bosh-lite.com
FAILED
Error performing request: Get https://api.bosh-lite.com/v2/info: dial tcp 10.244.0.34:443: i/o timeout
TIP: If you are behind a firewall and require an HTTP proxy, verify the https_proxy environment variable is correctly set. Else, check your network connection.`

but i was not able to run ./bin/add_route . it is showing error :
`vagrant@bosh-lite:~$ ./bin/add-route
-bash: ./bin/add-route: No such file or directory
vagrant@bosh-lite:~$ /bin/add-route
-bash: /bin/add-route: /bin/bash^M: bad interpreter: No such file or directory`
but it exists in bin
`vagrant@bosh-lite:/$ cd bin
vagrant@bosh-lite:/bin$ ls
add-route   `

for reference output of ifconfig:
`vagrant@bosh-lite:~$ ifconfig
eth0      Link encap:Ethernet  HWaddr 08:00:27:86:99:68
          inet addr:10.0.2.15  Bcast:10.0.2.255  Mask:255.255.255.0
          inet6 addr: fe80::a00:27ff:fe86:9968/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:1173 errors:0 dropped:0 overruns:0 frame:0
          TX packets:772 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:108082 (108.0 KB)  TX bytes:96810 (96.8 KB)

eth1      Link encap:Ethernet  HWaddr 08:00:27:94:de:a2
          inet addr:192.168.50.4  Bcast:192.168.50.255  Mask:255.255.255.0
          inet6 addr: fe80::a00:27ff:fe94:dea2/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:16 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:0 (0.0 B)  TX bytes:1296 (1.2 KB)

lo        Link encap:Local Loopback
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:79999 errors:0 dropped:0 overruns:0 frame:0
          TX packets:79999 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1
          RX bytes:10943669 (10.9 MB)  TX bytes:10943669 (10.9 MB)

lo:1      Link encap:Local Loopback
          inet addr:10.254.50.4  Mask:255.255.255.0
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
`

output of route -n:
`vagrant@bosh-lite:~$ route -n
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         10.0.2.2        0.0.0.0         UG    0      0        0 eth0
10.0.2.0        0.0.0.0         255.255.255.0   U     0      0        0 eth0
192.168.50.0    0.0.0.0         255.255.255.0   U     0      0        0 eth1`

Any thoughts for troubleshooting?

**Comment by killer-imaniac** [comment]
I am also facing the same issue @peluu .
