### ISSUE TITLE
Deploying CF behind the AWS load balancer

### ISSUE THREAD

**Issue by StanleyShen** [cloudfoundry/cf-release#1098]
Hello, all

Is there a document to show how to deploy the CF behind the AWS load balancer.

I tried to deploy the CF beside an AWS load balancer, and I met some problems.

Before, I deploy all instances in VPC and I created one NAT VM to these private subnet for communication and they work well.

Right now I changed to use AWS load balancer.

I found these subnets cannot talk to load balancer, it seems it because these private subnets cannot talk to external VMs, so I changed them to use the public internal gateway.

And then the load balancer shows it's working, I tried to push a simple application, and it doesn't work.
1. when creating org/space, it's failed to assign roles.
2. when pushing APP, it's keeping running at uploading APP.

I once asked in slack, it seems these VMs cannot talk to each other.
So for now, I tried to assigh public IP to these VMs, and it works, but I think it's not the best way.

I am some new to AWS VPC network, need more specific instructions on it.
What's the correct way to deploy CF behind AWS load balancer.

Thanks in advance for help.

**Comment by dsabeti** [comment]
Hi @StanleyShen. Deploying CF behind an AWS load balancer (called ELBs) is definitely possible. There are a few docs that will help you out:
- [Official CF docs](http://docs.cloudfoundry.org/deploying/aws/index.html). These will use the bosh AWS bootstrap plugin to set up everything in your VPC
- [BOSH docs for AWS](http://bosh.io/docs/setup-aws.html).
- You could also take a look at [bbl](https://github.com/cloudfoundry/bosh-bootloader). This is a tool that sets up all the necessary resources in your AWS account with just a few commands. Take a look at the `up` and `create-lbs` commands (the second command creates an ELB for you). IMPORTANT: the tool is designed to be used with v2 bosh manifests, so you won't be able to use the normal manifest generation scripts in cf-release. Instead, you'd have to use [cf-deployment](https://github.com/cloudfoundry/cf-deployment), which is our (still experimental) way of deploying CF.

If you still need help after looking through those docs/tools. Feel free to come back to this github issue and post detailed information about the following:
- Your ELBs and their configuration
- Your VPC and Subnets
- Your security groups
- Your routing tables
- The IP addresses of the gorouter

Thanks,
David

**Comment by djvdorp** [comment]
Heya @dsabeti -- not to say that what you wrote above is wrong, but I happen to have worked with [bbl](https://github.com/cloudfoundry/bosh-bootloader) quite intensively in the past, and the last time I used it, they embedded a BOSH [version 257+](https://github.com/cloudfoundry/bosh/releases/tag/stable-3262) that is compatible with BOSH v2 and v1 manifests (see story [enable user to use v1 and v2 manifests on the same director](https://www.pivotaltracker.com/story/show/117938521)) and this was also described in my issue [Workflow description to get started with CloudFoundry on AWS](https://github.com/cloudfoundry/bosh-bootloader/issues/40), that might be helpful for @StanleyShen.

**Comment by dsabeti** [comment]
@djvdorp Yeah, I was being a bit glib. I was focusing on the fact that `bbl` generates a cloud-config based on the output of cloudformation, so it was clearly built with v2 manifests in mind. But you're correct that a v1 manifest could also be deployed (so long as the various `cloud_properties` sections had the correct IaaS information). It's still the case that the _easiest_ way to use `bbl` is to deploy with cf-deployment.

@StanleyShen, how did it go for you? Do you still need help getting the AWS load balancers set up?

**Comment by StanleyShen** [comment]
Recently I am not working on it, I will check more on pages you all mentioned.
Close it for now, if I have more questions regarding it, I will back to the thread.

Thanks all for information.
