### ISSUE TITLE
generate-manifest results in empty manifest?

### ISSUE THREAD

**Issue by jadekler** [cloudfoundry/cf-release#1099]
```
 2016-11-12 17:28:33 ☆  |2.3.0| DEN_Recently_Imaged in ~/workspace/cf-release
±  |master ?:1 ✗| → ./scripts/generate_deployment_manifest openstack ~/workspace/git-cloudfoundry-on-openstack-talk/private/cf/cf-manifest.yml > cf-deployment.yml

 2016-11-12 17:28:42 ☆  |2.3.0| DEN_Recently_Imaged in ~/workspace/cf-release
±  |master ?:1 ✗| → cat cf-deployment.yml
{}
```

Anyone know what the deal is?

**Comment by dsabeti** [comment]
Hi @jadekler, I think this is the same problem as in these github issues for spiff:
- https://github.com/cloudfoundry-incubator/spiff/issues/81
- https://github.com/cloudfoundry-incubator/spiff/issues/79

If so, could you close this github issue and we'll continue the discussion there?

Thanks,
David

**Comment by jadekler** [comment]
@dsabeti This seems to be a `spiff` issue more than a `cf-release` issue - would you prefer me to move discussion there? Otherwise I'll be happy to do as you asked!

**Comment by dsabeti** [comment]
@jadekler. Great. I'll close this issue, and we'll continue discussing in https://github.com/cloudfoundry-incubator/spiff/issues/81
