### ISSUE TITLE
Potential issue with DNS resolution from application containers

### ISSUE THREAD

**Issue by yatzek** [cloudfoundry/cf-release#1101]
Application containers have a consul dns server entry 127.0.0.1 in /etc/resolv.conf. This server is not accessible from a container. Testing resolution with dig results in queries taking over a second - first name server on the list times out:
```
vcap@9609ac9c-9ae7-4160-6d46-f6ed496f6e47: cat /etc/resolv.conf 
nameserver 127.0.0.1
nameserver 10.10.0.2
nameserver 10.10.0.7
nameserver 10.10.0.6
vcap@9609ac9c-9ae7-4160-6d46-f6ed496f6e47: time dig www.google.co.uk

; <<>> DiG 9.9.5-3ubuntu0.9-Ubuntu <<>> www.google.co.uk
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 22127
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;www.google.co.uk.		IN	A

;; ANSWER SECTION:
www.google.co.uk.	25	IN	A	74.125.22.94

;; Query time: 3 msec
;; SERVER: 10.10.0.2#53(10.10.0.2)
;; WHEN: Mon Nov 14 12:36:58 UTC 2016
;; MSG SIZE  rcvd: 61


real	0m1.039s
user	0m0.004s
sys	0m0.004s
vcap@9609ac9c-9ae7-4160-6d46-f6ed496f6e47: time dig @127.0.0.1 www.google.co.uk

; <<>> DiG 9.9.5-3ubuntu0.9-Ubuntu <<>> @127.0.0.1 www.google.co.uk
; (1 server found)
;; global options: +cmd
;; connection timed out; no servers could be reached

real	0m15.018s
user	0m0.008s
sys	0m0.004s
vcap@9609ac9c-9ae7-4160-6d46-f6ed496f6e47: time dig @10.10.0.2 www.google.co.uk

; <<>> DiG 9.9.5-3ubuntu0.9-Ubuntu <<>> @10.10.0.2 www.google.co.uk
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 53240
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;www.google.co.uk.		IN	A

;; ANSWER SECTION:
www.google.co.uk.	60	IN	A	172.217.1.67

;; Query time: 1 msec
;; SERVER: 10.10.0.2#53(10.10.0.2)
;; WHEN: Mon Nov 14 12:37:38 UTC 2016
;; MSG SIZE  rcvd: 61


real	0m0.010s
user	0m0.008s
sys	0m0.000s
```

Resolving names with IPSocket.getaddress in ruby works fine:

```
vcap@9609ac9c-9ae7-4160-6d46-f6ed496f6e47: cat socket.rb 
require 'socket'
host = 'www.google.co.uk'
puts IPSocket.getaddress host

vcap@9609ac9c-9ae7-4160-6d46-f6ed496f6e47: time ruby socket.rb 
172.217.1.67

real	0m0.072s
user	0m0.052s
sys	0m0.004s
```

However, Resolv.getaddress takes 5 seconds:

```
vcap@9609ac9c-9ae7-4160-6d46-f6ed496f6e47: cat resolv.rb 
require 'resolv'
host = 'www.google.co.uk'
puts Resolv.getaddress host
vcap@9609ac9c-9ae7-4160-6d46-f6ed496f6e47: time ruby resolv.rb 
172.217.1.67

real	0m5.118s
user	0m0.088s
sys	0m0.012s
```

**Comment by dsabeti** [comment]
@yatzek Thanks for bringing this to our attention. This is an interesting artifact of colocating consul and garden.

@julz, is this behavior that you would expect? Is there a way we can prevent `127.0.0.1` from being brought into containers resolv.conf? I imagine this would be a nice optimization for apps, so that any outbound requests would be faster. FWIW, I actually verified that this is the case -- I used `cf ssh` to jump onto a container and started curling external urls and found that DNS resolution was slowing requests down.

**Comment by evanfarrar** [comment]
This is an interesting issue, thanks for raising it. I don't know of a straightforward solution to the issue.

Omitting that entry seems ideal. Garden has a feature to specify what gets written into the resolv.conf, but still keeping that in sync with what DNS bosh has been configured to start VMs with could be a problem I think.

**Comment by CAFxX** [comment]
We (Rakuten) have run into the same issue and we know that other providers that have not migrated to diego yet ran into it as well.

**Comment by cppforlife** [comment]
one of the solutions is to set dns servers explicitly on the garden job, instead of inheriting dns entries from the host.

http://bosh.io/jobs/garden?source=github.com/cloudfoundry/garden-runc-release&version=1.0.4#p=garden.dns_servers

**Comment by CAFxX** [comment]
@cppforlife yes that's what we're going to do from 239+ (right now we patch resolv.conf in the container). It would likely help if these kind of things were mentioned in the release notes.

**Comment by ematpl** [comment]
Talked with @julz about this on the CF Slack (circa https://cloudfoundry.slack.com/archives/garden/p1481912094003416), and we're pretty sure it would make sense for garden-runc to remove `127.0.0.1` from the host `/etc/resolv.conf` when it's copied into the container. I don't see a story for it yet in the Garden tracker, but Julz said he'd probably want to check with the community on cf-dev to see if this would break anyone (although we can't think how, unless some users are intentionally running Consul or another DNS service as a sidecar process in their CF app containers).

**Comment by dsabeti** [comment]
I see the story for this here: https://www.pivotaltracker.com/story/show/136300381

Does that look right, @julz?

**Comment by dsabeti** [comment]
@yatzek. The story for this has been accepted and will be available in the next release of garden-runc-release. I'm going to go ahead and close this since the feature has been implemented.
