### ISSUE TITLE
sshfs fuse issue

### ISSUE THREAD

**Issue by nick255** [cloudfoundry/cf-release#1106]
I noticed when trying to mount a remote filesystem over sshfs or s3fs, fuse throws a permission error
`fusermount: failed to open /etc/fuse.conf: Permission denied`

I believe this is caused by the vcap user not being in the fuse group and /etc/fuse.conf only being readable by the owner or group.

Anybody else run into this?
Thanks.

**Comment by jaresty** [comment]
Hey @nick255, we're trying to figure out what to do with the tracker story for this issue, and saw that you closed this. Did you figure out what was going on?

**Comment by nick255** [comment]
@jaresty sorry, I maybe wrong but I was under the impression that fuse support might have been dropped from cf so figured that it wasnt worth looking into.

**Comment by dsabeti** [comment]
@nick255 fuse support hasn't been dropped, it's just that it's disabled by default. Please answer the following questions to help us troubleshoot:
1. Which backend -- DEA or Diego -- are you using?
2. If you're using Diego, what is the value of `diego_privileged_containers` (https://github.com/cloudfoundry/diego-release/blob/918c2c9f443b3f8137c0bc3723252b3e08ef3122/manifest-generation/diego.yml#L638)?

**Comment by nick255** [comment]
Its Diego on pivotal webservices.

**Comment by dsabeti** [comment]
I see, you're not deploying this CF yourself. I'd contact (Pivotal Web Services support)[http://run.pivotal.io/support-services-offering/] for help, but I suspect that, because it's a public offering of CF, they probably do not support use of privileged containers, which is what enables or disable fuse mount use.
