### ISSUE TITLE
Commit 29c9e3f missing 'RSA END PRIVATE KEY' line

### ISSUE THREAD

**Issue by andrew-edgar** [cloudfoundry/cf-release#1111]
The line 

-----END RSA PRIVATE KEY-----

is required to complete the private key field in the cf-infrastructure-bosh-lite.yml or else UAA will fail reading the KEY and will not start.

Not sure how this was ever tested as UAA does not even run if you deploy with the commit done 5 days ago.

Please see my comment on the commit.

**Comment by dsabeti** [comment]
Hi @andrew-edgar, thanks for pointing this out. It looks like this issue is resolved as of af2b904b631bc8e05f8980d4c22234fdf119f53f.
