### ISSUE TITLE
Scale problem

### ISSUE THREAD

**Issue by BongChan** [cloudfoundry/cf-release#1119]
I use multiple application instances. If i use the scale API to reduce instances, i will instantly get 503 bad gateways.
I think the router sends the request to the deleted instance. I am using cf 238 version, please check.

gorouter_ctl.log:[2016-12-07 09:41:53+0000]
```
 {timestamp:1481103713.871946812,source:vcap.gorouter,message:vcap.gorouter.proxy.request-handler.status,log_level:1,data:{Host:spring-music-bong.paas.skcc.com,Path:/,RemoteAddr:172.16.1.17:49593,X-Forwarded-For:[10.250.46.237],X-Forwarded-Proto:[http],body:502 Bad Gateway: Registered endpoint failed to handle the request.,route-endpoint:{ApplicationId:9bdd97d7-6207-42ad-969e-250a47b21d69,Addr:172.16.13.30:60280,Tags:{component:route-emitter},RouteServiceUrl:},session:4.1069772}}
```

**Comment by dsabeti** [comment]
Hi @BongChan, I've got a few question to start debugging.

1. Which backend are you using for this app: DEA or Diego?
1. How long after scaling down does this problem persist? If you wait for 2-3 minutes, does traffic still get routed to the removed instance?
1. If you make many requests -- for example, if you make one request for each instance you had before scaling down -- what percentage of the tests fail?
1. Please upload your deployment manifest **with sensitive data such as passwords and private keys redacted.**

Thanks!

**Comment by BongChan** [comment]
Hi @dsabeti  Thanks for quick reply.

1. Which backend are you using for this app: DEA or Diego?
    1. I am using diego 
2. How long after scaling down does this problem persist? If you wait for 2-3 minutes, does traffic still get routed to the removed instance?
    1. This problem occurs very momentarily.
3. If you make many requests -- for example, if you make one request for each instance you had before scaling down -- what percentage of the tests fail?
    1. I did this performance test and found it.
    2. I sent a request of about 10 TPS to the application with the JMeter.
4. Please upload your deployment manifest with sensitive data such as passwords and private keys redacted.
    1. Unfortunately I am using private paas, so you can not connect. The same is true for testing with spring music.

Below is a scenario where an error occurs.

1.  application push
2. cf scale -i 3
3. send a lot of request with jmeter(about 10TPS)
4. cf scale -i 1
5. Some requests result in a 502 error

router logs
/var/vcap/sys/log/gorouter/gorouter_ctl.err.log
[2016-12-06 14:24:24+0000] 2016/12/06 14:24:24 http: proxy error: read tcp 172.16.1.16:64547->172.16.13.31:60084: read: connection reset by peer
/var/vcap/sys/log/gorouter/gorouter_ctl.log
{Host:ams2.skcc.com,Path:/resources/images/main/process_bg_03.gif,RemoteAddr:172.16.13.33:49713,X-Forwarded-For:[10.178.48.87],X-Forwarded-Proto:[https],body:502 Bad Gateway: Registered endpoint failed to handle the request.,route-endpoint:

**Comment by shashwathi** [comment]
Hi @BongChan :  

Thank you for reporting the issue. We noticed this last week on our CI as well and this is the corresponding tracker story for fixing this bug https://www.pivotaltracker.com/story/show/135303477

This was a bug about how gorouter subscribes messages from NATS (source for routing info). Nats does not guarantee order of messages received from 2 subscribers. Gorouter has 1 subscriber for registering and other for un-registering router and order for messages get messed up when there is more traffic from unregistration. We have solved this problem by merging into 1 subscription. 

I am not sure which version of CF will have this fix but we will try our best to get this in ASAP. 

Regards
Shash

**Comment by dsabeti** [comment]
Hi @BongChan. Since the routing team has already worked on a fix that will go out in the next release, I'm going to close this issue. Feel free to re-open it if you have any other questions or concerns, or if you see that the problem persists after upgrading to the next version of cf-release when it's released.
