### ISSUE TITLE
duplicated and missing organisations when querying /v2/organizations

### ISSUE THREAD

**Issue by paolostivanin** [cloudfoundry/cf-release#1121]
* Command  
1. `cf orgs | sed '1,3d' | sort | wc -l`
2. `cf orgs | sed '1,3d' | sort -u | wc -l`

* What occurred, incl. error and/or stack trace
The first command gives back 129 org names, the second 94 and in both cases some orgs are missing.
```
CF_TRACE=true cf orgs| grep '^GET'
GET /v2/organizations?order-by=name HTTP/1.1
GET /v2/organizations?order-by=name HTTP/1.1
GET /v2/organizations?order-direction=asc&page=2&results-per-page=50 HTTP/1.1
GET /v2/organizations?order-direction=asc&page=3&results-per-page=50 HTTP/1.1
```

* CLI Version  
`6.22.2+a95e24c-2016-10-27`

* CC API Endpoint Version  
API endpoint: https://endpoint (API version: 2.65.0)

* Platform & Shell Details  
We are running Ubuntu 14.04 on our dev landscape and stemcell 3312 in our prod system

* Any other relevant information  
The problem is **not** related to cf cli because I was able to reproduce it with a self-developed python script using the requests module.
Taking out the parameters `order-by=name` and `order-direction=asc` from my script solved the problem though.

**Comment by dsabeti** [comment]
@SocalNick @utako This looks like it's likely a CAPI issue. Would you mind helping @paolostivanin to debug his problem?

**Comment by SocalNick** [comment]
@paolostivanin this looks like a CLI issue, the second and third page request are missing the `order-by=name` query parameter.

**Comment by paolostivanin** [comment]
@SocalNick but I do have the issue with a self developed Python script (I am using requests, I am not calling cf cli)...

**Comment by SocalNick** [comment]
@paolostivanin we can't help you with your Python script, but if the CLI is using two different orders across pages, it's not an accurate listing of all orgs.

**Comment by fraenkel** [comment]
@SocalNick Normally those links are in the response. Do the next links in the response contain the name query?

**Comment by SocalNick** [comment]
@fraenkel good call:
```
cf curl "/v2/organizations?order-by=name&results-per-page=1"
{
   "total_results": 6,
   "total_pages": 6,
   "prev_url": null,
   "next_url": "/v2/organizations?order-direction=asc&page=2&results-per-page=1",
   "resources": [
```

**Comment by SocalNick** [comment]
@dsabeti I moved the story to our tracker

**Comment by dsabeti** [comment]
Great, thanks.
