### ISSUE TITLE
cf-release/example_manifests/minimal-aws.yml not compatible with  Diego 1.2.0

### ISSUE THREAD

**Issue by larsarea9** [cloudfoundry/cf-release#1125]
The example minimal manifest fails to deploy due to Diego 1.2.0 release claiming: 

(https://github.com/cloudfoundry/diego-release/releases)
IMPORTANT: It is now a deployment error not to configure a relational data store for the BBS API server. Both MySQL and Postgres are supported SQL dialects. Please see documentation on Diego data stores for information about selecting a relational store and, for existing deployments, migrating data from etcd if so desired.

Error message:
Error filling in template 'bbs_as_vcap.erb' (line 128: diego.bbs.sql.db_username,diego.bbs.sql.db_password,diego.bbs.sql.db_host,diego.bbs.sql.db_port,diego.bbs.sql.db_schema are required fields)

**Comment by biolounge** [comment]
Same issue here: 

_Error 100: Unable to render instance groups for deployment. Errors are:
   - Unable to render jobs for instance group 'diego_brain_z1'. Errors are:
     - Unable to render templates for job 'bbs'. Errors are:
       - Error filling in template 'bbs_as_vcap.erb' (line 128: diego.bbs.sql.db_username,diego.bbs.sql.db_password,diego.bbs.sql.db_host,diego.bbs.sql.db_port,diego.bbs.sql.db_schema are required fields)_

**Comment by dsabeti** [comment]
@larsarea9 Thanks for the heads up. We have the story to fix this prioritized and will hopefully get to it soon.

**Comment by biolounge** [comment]
Is this issue is resolved?

**Comment by dsabeti** [comment]
Hi @biolounge Thanks for following up. Yes, this issue is resolved. I was under the impression when I accepted this story in Pivotal tracker, our automation would lose out the issue. I'll close this issue now.
