### ISSUE TITLE
Hardcoded port in HM9k code 

### ISSUE THREAD

**Issue by ronakbanka** [cloudfoundry/cf-release#1128]
Hello ,

While upgrading to cf-release v235 , during testing phase we found out a hardcoded port in HM9k code and dea_next job templates. 

`Port number 5335`, HM listens on this port for heartbeats from DEA.

This port was mentioned nowhere in release notes and is still sitting there in v249 code which can break things on ACL level in secure networks. 

It was introduced in v235 itself , while enabling heartbeat over https from DEA -> HM9k.
- [Pivotal tracker](https://www.pivotaltracker.com/n/projects/900612/stories/112077807)
- [Code commit in hm9k](https://github.com/cloudfoundry/hm9000/blame/0abac94301342b6f1563ea11d8c87929f5c4da2a/config/config.go#L133)
- [Fixed config in DEA job templates](https://github.com/cloudfoundry/dea-hm-workspace/blob/1b8733d40e24c88efedbf0f679f1a97d8ddb9453/jobs/dea_next/templates/dea.yml.erb#L100)

It would be really helpful , if there is more visibility on such things , either in release notes or pivotal tracker itself.

**Comment by SocalNick** [comment]
I believe this was added to move HM9k / DEA to use https instead of nats. @fraenkel can confirm.

**Comment by fraenkel** [comment]
Normally we don't document things that cannot be changed via manifest. It is a hardcoded value.

**Comment by JesseTAlford** [comment]
The port usage of a job is of general interest when figuring out deployment topologies. Ideally, even non-configurable port-usage of a bosh job would be documented _somewhere._ That said, I'm pretty sure we don't have a standard system in place for this, and the ability to find said documentation would be as important as its existence.

Release notes and pivotal tracker are not especially discoverable homes for information that is relevant for every version after 235.

**Comment by ronakbanka** [comment]
@fraenkel Even if something can't be changed from manifests and is a platform breaking change , would be a good idea to mention on individual component changes , which are already there on bosh.io release notes.

It would be good if not on release notes,  but can have a additional source of some type,  where port details for each component can be checked. 

Like @JesseTAlford mentioned , it would be helpful when figuring out deployment topologies , specially for security reasons where keeping track of ACL's are important

**Comment by dsabeti** [comment]
Hey @ronakbanka and @fraenkel. I'm wondering what we could do to resolve this.

I think there's a good point that port usage is important to deployers. There's also not a great a place to document this kind of change.

@fraenkel, would it make sense to allow this port to be configurable, even if the job spec continues to use `5335` as a default?  If @ronakbanka submitted a PR, would you be willing to merge it in? This way, it's a little more discoverable as part of the release. It also allows operators to use a different port if they so choose.

**Comment by fraenkel** [comment]
Submit the PR.

**Comment by dsabeti** [comment]
I'm going to close the issue due to inactivity. @ronakbanka, feel free to re-open if there's anything else regarding this that you'd like to discuss.
