### ISSUE TITLE
Problems bosh deploy

### ISSUE THREAD

**Issue by Hans9010** [cloudfoundry/cf-release#1129]
Hi,

I am trying to set up a bosh lite on a centos 7. To say it in advance: I am a newbe to CF.

Everything seems to work well. VBox with vagrant is running, stemcell is uploaded,...  But I get an error when I do "bosh deploy":
```
Deploying
---------
Are you sure you want to deploy? (type 'yes' to continue): yes

Director task 76
Deprecation: Ignoring cloud config. Manifest contains 'networks' section.

  Started preparing deployment > Preparing deployment. Done (00:00:02)

  Started preparing package compilation > Finding packages to compile. Done (00:00:01)

  Started updating job consul_z1 > consul_z1/0 (ab77aaf1-8e8b-49d8-a673-e6e78ad87e45) (canary). Failed: 'consul_z1/0 (ab77aaf1-8e8b-49d8-a673-e6e78ad87e45)' is not running after update. (00:03:08)

Error 400007: 'consul_z1/0 (ab77aaf1-8e8b-49d8-a673-e6e78ad87e45)' is not running after update.

Task 76 error

For a more detailed error report, run: bosh task 76 --debug
```

The inscance "consul" isn't coming up (bosh -ps):
```
+----------------------------------------------------------------------------+---------+-----+-----------+--------------+
| Instance                                                                   | State   | AZ  | VM Type   | IPs          |
+----------------------------------------------------------------------------+---------+-----+-----------+--------------+
| api_z1/0 (97e19cbd-3db3-4085-9b71-48da2f7b2027)*                           | running | n/a | large_z1  | 10.244.0.138 |
+----------------------------------------------------------------------------+---------+-----+-----------+--------------+
| blobstore_z1/0 (2279c0c1-06ce-4b2c-b47a-e22bcf82b1bd)*                     | running | n/a | medium_z1 | 10.244.0.130 |
+----------------------------------------------------------------------------+---------+-----+-----------+--------------+
| consul_z1/0 (ab77aaf1-8e8b-49d8-a673-e6e78ad87e45)*                        | failing | n/a | small_z1  | 10.244.0.54  |
+----------------------------------------------------------------------------+---------+-----+-----------+--------------+
| doppler_z1/0 (6d918399-ec2c-4e9a-a9d2-8a3440809d71)*                       | running | n/a | medium_z1 | 10.244.0.146 |
+----------------------------------------------------------------------------+---------+-----+-----------+--------------+
| etcd_z1/0 (c731d76f-45e5-48fb-90fc-3b7c96310e0d)*                          | running | n/a | large_z1  | 10.244.0.42  |
+----------------------------------------------------------------------------+---------+-----+-----------+--------------+
| ha_proxy_z1/0 (f014be96-5ef6-4b26-80c7-70622ba71221)*                      | running | n/a | router_z1 | 10.244.0.34  |
+----------------------------------------------------------------------------+---------+-----+-----------+--------------+
| hm9000_z1/0 (62eed083-67c7-4557-a80f-c8429a612b2d)*                        | running | n/a | medium_z1 | 10.244.0.142 |
+----------------------------------------------------------------------------+---------+-----+-----------+--------------+
| loggregator_trafficcontroller_z1/0 (2de6ad2d-2e75-4e34-9dbb-cc13a6f21356)* | running | n/a | small_z1  | 10.244.0.150 |
+----------------------------------------------------------------------------+---------+-----+-----------+--------------+
| nats_z1/0 (67def115-65b7-4ae3-bbe4-1d0285141f60)*                          | running | n/a | medium_z1 | 10.244.0.6   |
+----------------------------------------------------------------------------+---------+-----+-----------+--------------+
| postgres_z1/0 (34e98bda-b384-46d1-bde1-130fe94aae55)*                      | running | n/a | medium_z1 |              |
+----------------------------------------------------------------------------+---------+-----+-----------+--------------+
| router_z1/0 (78de6b15-9bf5-4dae-ab76-6d4457d011ad)*                        | running | n/a | router_z1 | 10.244.0.22  |
+----------------------------------------------------------------------------+---------+-----+-----------+--------------+
| runner_z1/0 (4efe276a-d03c-44a2-ac47-516edaf46301)*                        | running | n/a | runner_z1 | 10.244.0.26  |
+----------------------------------------------------------------------------+---------+-----+-----------+--------------+
| uaa_z1/0 (bed905b2-e509-4132-86d5-ce1faa5b9990)*                           | running | n/a | medium_z1 | 10.244.0.134 |
+----------------------------------------------------------------------------+---------+-----+-----------+--------------+
```

I can login with bosh ssh to the consul instance, but can't find a "speakable" error message. The output of the task greped to ERR-Messages gives the following:

```
 bosh task 76 --debug | grep ERR
RSA 1024 bit CA certificates are loaded due to old openssl compatibility
Acting as user 'admin' on 'Bosh Lite Director'
E, [2016-12-19 18:47:43 #23596] [canary_update(consul_z1/0 (ab77aaf1-8e8b-49d8-a673-e6e78ad87e45))] ERROR -- DirectorJobRunner: Error updating canary instance: #<Bosh::Director::AgentJobNotRunning: 'consul_z1/0 (ab77aaf1-8e8b-49d8-a673-e6e78ad87e45)' is not running after update.>
E, [2016-12-19 18:47:43 #23596] [] ERROR -- DirectorJobRunner: Worker thread raised exception: 'consul_z1/0 (ab77aaf1-8e8b-49d8-a673-e6e78ad87e45)' is not running after update. - /var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-1.3262.3.0/lib/bosh/director/instance_updater/state_applier.rb:48:in `post_start'
E, [2016-12-19 18:47:43 #23596] [task:76] ERROR -- DirectorJobRunner: 'consul_z1/0 (ab77aaf1-8e8b-49d8-a673-e6e78ad87e45)' is not running after update.
```

Since I tried now several times with fresh installations, I do not have any clue, where to find out more about this issue. Can anyone help me?

Thanks & Best regards

   Hans

**Comment by JesseTAlford** [comment]
Hello @Hans9010! Would you mind jumping back on the failed job and poking around in /var/vcap/sys/log/consul_agent/ to see if there are interesting log entries there? We might be able to get something to go on that way.

**Comment by Hans9010** [comment]
Hi Jesse, sorry for the delay. 

Here is what I found on the consul vm:
bosh_lvjkugyl3@e656203d-5c01-436a-ae0b-97ed39abc915:/var/vcap/sys/log/consul_agent$ cat agent_ctl.err.log 
[2016-12-21 21:03:50+0000] + main stop
[2016-12-21 21:03:50+0000] + mkdir -p /var/vcap/sys/run/consul_agent
[2016-12-21 21:03:50+0000] + case ${1} in
[2016-12-21 21:03:50+0000] + stop_confab
[2016-12-21 21:03:50+0000] + /var/vcap/packages/confab/bin/confab stop --config-file /var/vcap/jobs/consul_agent/confab.json
[2016-12-21 21:03:50+0000] ++ tee -a /var/vcap/sys/log/consul_agent/consul_agent.stdout.log
[2016-12-21 21:03:50+0000] ++ logger -p user.info -t vcap.consul-agent
[2016-12-21 21:03:50+0000] ++ logger -p user.error -t vcap.consul-agent
[2016-12-21 21:03:50+0000] ++ tee -a /var/vcap/sys/log/consul_agent/consul_agent.stderr.log
bosh_lvjkugyl3@e656203d-5c01-436a-ae0b-97ed39abc915:/var/vcap/sys/log/consul_agent$ cat agent_ctl.log 
bosh_lvjkugyl3@e656203d-5c01-436a-ae0b-97ed39abc915:/var/vcap/sys/log/consul_agent$ cat consul_agent.stderr.log 
error during stop: dial tcp [::1]:8400: getsockopt: connection refused
bosh_lvjkugyl3@e656203d-5c01-436a-ae0b-97ed39abc915:/var/vcap/sys/log/consul_agent$ cat consul_agent.stdout.log 
{"timestamp":"1482354230.956595182","source":"confab","message":"confab.controller.stop-agent.leave","log_level":1,"data":{}}
{"timestamp":"1482354230.956788063","source":"confab","message":"confab.agent-client.leave.nil-rpc-client","log_level":2,"data":{"error":"consul rpc client is nil"}}
{"timestamp":"1482354230.956982374","source":"confab","message":"confab.controller.stop-agent.leave.failed","log_level":2,"data":{"error":"consul rpc client is nil"}}
{"timestamp":"1482354230.957132578","source":"confab","message":"confab.controller.stop-agent.stop","log_level":1,"data":{}}
{"timestamp":"1482354230.957149506","source":"confab","message":"confab.agent-runner.stop.get-process","log_level":1,"data":{}}
{"timestamp":"1482354230.957233191","source":"confab","message":"confab.agent-runner.stop.get-process.failed","log_level":2,"data":{"error":"open /var/vcap/sys/run/consul_agent/consul_agent.pid: no such file or directory"}}
{"timestamp":"1482354230.957260609","source":"confab","message":"confab.controller.stop-agent.stop.failed","log_level":2,"data":{"error":"open /var/vcap/sys/run/consul_agent/consul_agent.pid: no such file or directory"}}
{"timestamp":"1482354230.957275391","source":"confab","message":"confab.controller.stop-agent.wait","log_level":1,"data":{}}
{"timestamp":"1482354230.957293034","source":"confab","message":"confab.agent-runner.wait.get-process","log_level":1,"data":{}}
{"timestamp":"1482354230.957324505","source":"confab","message":"confab.agent-runner.wait.get-process.failed","log_level":2,"data":{"error":"open /var/vcap/sys/run/consul_agent/consul_agent.pid: no such file or directory"}}
{"timestamp":"1482354230.957346916","source":"confab","message":"confab.controller.stop-agent.wait.failed","log_level":2,"data":{"error":"open /var/vcap/sys/run/consul_agent/consul_agent.pid: no such file or directory"}}
{"timestamp":"1482354230.957378864","source":"confab","message":"confab.controller.stop-agent.cleanup","log_level":1,"data":{}}
{"timestamp":"1482354230.957414389","source":"confab","message":"confab.agent-runner.cleanup.remove","log_level":1,"data":{"pidfile":"/var/vcap/sys/run/consul_agent/consul_agent.pid"}}
{"timestamp":"1482354230.957456112","source":"confab","message":"confab.agent-runner.cleanup.remove.failed","log_level":2,"data":{"error":"remove /var/vcap/sys/run/consul_agent/consul_agent.pid: no such file or directory","pidfile":"/var/vcap/sys/run/consul_agent/consul_agent.pid"}}
{"timestamp":"1482354230.957477093","source":"confab","message":"confab.controller.stop-agent.cleanup.failed","log_level":2,"data":{"error":"remove /var/vcap/sys/run/consul_agent/consul_agent.pid: no such file or directory"}}
{"timestamp":"1482354230.957498312","source":"confab","message":"confab.controller.stop-agent.success","log_level":1,"data":{}}
bosh_lvjkugyl3@e656203d-5c01-436a-ae0b-97ed39abc915:/var/vcap/sys/log/consul_agent$ cat drain.log 
+ /var/vcap/jobs/consul_agent/bin/agent_ctl stop
++ basename /var/vcap/jobs/consul_agent/bin/agent_ctl
+ SCRIPT_NAME=agent_ctl
+ RUN_DIR=/var/vcap/sys/run/consul_agent
+ LOG_DIR=/var/vcap/sys/log/consul_agent
+ JOB_DIR=/var/vcap/jobs/consul_agent
+ CONFAB_PACKAGE=/var/vcap/packages/confab
+ exec
+ exec
++ tee -a /dev/fd/63
++ tee -a /dev/fd/63
+++ date '+%Y-%m-%d %H:%M:%S%z'
+++ date '+%Y-%m-%d %H:%M:%S%z'
+++ logger -p user.info -t vcap.agent_ctl.stdout
+++ logger -p user.error -t vcap.agent_ctl.stderr
++ sed -e 's/^/[2016-12-21 21:03:50+0000] /'
++ sed -e 's/^/[2016-12-21 21:03:50+0000] /'
+ echo 0
+ exit 0
bosh_lvjkugyl3@e656203d-5c01-436a-ae0b-97ed39abc915:/var/vcap/sys/log/consul_agent$ 

Does that help?

Best regards


   Hans

**Comment by evanfarrar** [comment]
Hmm this looks interesting:
```
{"timestamp":"1482354230.956982374","source":"confab","message":"confab.controller.stop-agent.leave.failed","log_level":2,"data":{"error":"consul rpc client is nil"}}
```

Not sure why rpc client is nil, this looks like an error that was not expected to be encountered. It is possible this is a bug in consul-release, but I will create a story in our backlog to try to replicate your issue to know for sure.

One thing might help me though, could you share the contents of ```/var/vcap/data/jobs/consul_agent/*/confab.json``` AFTER DELETING CERTS AND KEYS? For example mine looks like:
```
{"node":{"name":"consul","index":0,"external_ip":"10.0.31.194"},"consul":{"agent":{"mode":"server","servers":{"lan":["10.0.31.194","10.0.47.190","10.0.47.194"],"wan":[]},"log_level":"info","datacenter":"dc1","services":{},"protocol_version":2,"dns_config":{"allow_stale":true,"max_stale":"30s","recursor_timeout":"5s"},"domain":"cf.internal"},"ca_cert":"DELETED","server_cert":"DELETED","server_key":"DELETED","agent_cert":"DELETED","agent_key":"DELETED","encrypt_keys":["DELETED"]}}
```

**Comment by Hans9010** [comment]
How can I delete the cert key? Is there a comand to do that?

**Comment by evanfarrar** [comment]
Unfortunately no, I just made the edit by hand. Alternatively, delete everything after the word "ca_cert", and just paste that, that should be enough for me.

**Comment by Hans9010** [comment]
Hi,

here you are:
{"node":{"name":"consul_z1","index":0,"external_ip":"10.244.0.54"},"consul":{"agent":{"mode":"server","servers":{"lan":["10.244.0.54"],"wan":[]},"log_level":"info","datacenter":"dc1","services":{},"protocol_version":2,"dns_config":{"allow_stale":true,"max_stale":"30s","recursor_timeout":"5s"},"domain":"cf.internal"},"ca_cert":...

By the way: I scripted the installation. So I can exactly give you anything what I have done during the installation on a fresh centos 7:
###################################################
# Bash Log Information
################################################### 
set -v

###################################################
# Repo erweitern
################################################### 

echo "-----------------------------------------"
echo "Start Installation of additional Packages"
echo "-----------------------------------------"
date "+%d.%m.%Y %H:%M:%S"

# Repo für Virtual Box hinzufügen
cd /etc/yum.repos.d
#wget http://download.virtualbox.org/virtualbox/rpm/rhel/virtualbox.repo
cp /root/virtualbox.repo .

###################################################
# yum Aktionen
################################################### 

yum -y install epel-release
yum -y install dkms libyaml-devel
yum -y install go

# Installieren von Paketen (sollte bereits in Haupt Kickstart File geschehen sein
# Ist für "Standalone" Installation
yum -y install gcc make patch  qt libgomp
yum -y install kernel-headers kernel-devel fontforge binutils glibc-headers glibc-devel

# Upgrade System
yum -y update

# Aktuelle Kernel Sourcen installieren
yum -y install kernel-devel-`uname -r`

echo "---------------------------------------"
echo "End Installation of additional Packages"
echo "---------------------------------------"
date "+%d.%m.%Y %H:%M:%S"

###################################################
# VBox 
################################################### 

echo "---------------------------------------"
echo "Installation of VBox"
echo "---------------------------------------"
date "+%d.%m.%Y %H:%M:%S"

mkdir "/cf/VirtualBox VMs"
ln -s "/cf/VirtualBox VMs" "/root/VirtualBox VMs"
yum install -y VirtualBox-5.0*
/usr/lib/virtualbox/vboxdrv.sh setup KERN_DIR=/usr/src/kernels/`uname -r` 
usermod -a -G vboxusers root
  
###################################################
# Vagrant 
################################################### 

echo "---------------------------------------"
echo "Installation of vagrant"
echo "---------------------------------------"
date "+%d.%m.%Y %H:%M:%S"

cd /usr/src
mkdir vagrant
cd vagrant
#wget https://releases.hashicorp.com/vagrant/1.8.1/vagrant_1.8.1_x86_64.rpm
cp /root/vagrant_1.8.1_x86_64.rpm .
yum -y install vagrant_1.8.1_x86_64.rpm
vagrant plugin install vagrant-hostsupdater

###################################################
# Bosh Light 
# https://mariash.github.io/learn-bosh/#deploy
################################################### 

echo "---------------------------------------"
echo "Installation of Bosh & Repo"
echo "---------------------------------------"
date "+%d.%m.%Y %H:%M:%S"

# Bosh Light Client installieren
cd /cf
gem install bosh_cli --no-ri --no-rdoc

# Bosh Light Repository herunterladen
cd /cf
#git clone https://github.com/cloudfoundry/bosh-lite
tar -xvf /root/bosh-lite.tar 
cd bosh-lite

echo "---------------------------------------"
echo "Bosh Director Startup"
echo "---------------------------------------"
date "+%d.%m.%Y %H:%M:%S"

# Start Bosh Directory via Vagrant
vagrant up --provider=virtualbox
bosh

echo "Wait for vargant VM comming up"
response=$(vagrant status default | awk '/default/{print $2}')
while [ "$response" != "running" ]; do 
	response=$(vagrant status default | awk '/default/{print $2}') ; 
	echo -n '.'; 
done

echo "Try to target bosh"
count=0
returncode=`bosh target 192.168.50.4 lite <<EOF
admin
admin
EOF`
while [ "$returncode" != "Target set to 'Bosh Lite Director'" ]; do
        let count=count+1
echo $count
        if [ $count == 10 ] ; then
                echo "$count retrys. Giving up...."
                echo "Command: bosh target 192.168.50.4 lite"
                echo "Returncode: $returncode"
                exit
        fi
        returncode=`bosh target 192.168.50.4 lite <<EOF
admin
admin
EOF`
done
echo $returncode

bin/add-route

###################################################
# Cloud Foundry 
###################################################

echo "---------------------------------------"
echo "Download Tools for Cloud Foundry"
echo "---------------------------------------"
date "+%d.%m.%Y %H:%M:%S"

# gem Tool installieren
gem install bundler

# spiff installieren
cd /usr/local/bin
#wget https://github.com/cloudfoundry-incubator/spiff/releases/download/v1.0.7/spiff_linux_amd64 -O spiff
cp /root/spiff .
chmod a+x spiff



echo "---------------------------------------"
echo "Download & Cloud Foundry Manifest"
echo "---------------------------------------"
date "+%d.%m.%Y %H:%M:%S"

# Clone CF Repo
cd /cf
#git clone https://github.com/cloudfoundry/cf-release.git
tar -xvf /root/cf-release.tar

# CF Release
cd /cf/cf-release
./scripts/update

# Generating Manifest File
cd /cf/cf-release
./scripts/generate-bosh-lite-dev-manifest

echo "---------------------------------------"
echo "Download & Installation Stemcell"
echo "---------------------------------------"
date "+%d.%m.%Y %H:%M:%S"

# Stemcell download 
cd /cf/bosh-lite/
#wget https://d26ekeud912fhb.cloudfront.net/bosh-stemcell/warden/bosh-stemcell-389-warden-boshlite-ubuntu-trusty-go_agent.tgz
cp /root/bosh-stemcell-389-warden-boshlite-ubuntu-trusty-go_agent.tgz .

# Streamcell upload
cd /cf/bosh-lite/
bosh upload stemcell /cf/bosh-lite/bosh-stemcell-389-warden-boshlite-ubuntu-trusty-go_agent.tgz

echo "---------------------------------------"
echo "Build Cloud Foundry Release"
echo "---------------------------------------"
date "+%d.%m.%Y %H:%M:%S"

cd /cf/cf-release
bosh create release --force <<EOF

EOF

bosh upload releaseb

bosh deploy<<EOF
yes
EOF


.

**Comment by Hans9010** [comment]
the headings are commends in the origional script... sorry for the german language :-)

**Comment by jaresty** [comment]
@evanfarrar Did you find anything more out about this issue during your consul investigation?  We just picked this story up again and noticed that there was some further information since your last response.

**Comment by Hans9010** [comment]
Hi @all,

from my site I still have that problem. Perhaps it has to do with the stemcell version? 

Best regards

   Thomas

**Comment by Hans9010** [comment]
Hi @all,

my collegue Thomas was right. It seems to be a problem with the semcell version. I did the following:

> bosh download public stemcell  bosh-stemcell-389-warden-boshlite-centos-go_agent.tgz
> bosh upload stemcell /cf/bosh-lite/bosh-stemcell-389-warden-boshlite-centos-go_agent.tgz
> bosh create release --force
> bosh upload release
> bosh deploy

bosh vms shows now
+---------------------------------------------------------------------------+---------+-----+-----------+--------------+
| VM                                                                        | State   | AZ  | VM Type   | IPs          |
+---------------------------------------------------------------------------+---------+-----+-----------+--------------+
| api_z1/0 (4f26fda9-4274-47ec-ad62-4a8471b8ef7a)                           | running | n/a | large_z1  | 10.244.0.138 |
| blobstore_z1/0 (046a9075-02e7-4d3d-8897-e000be647ee1)                     | running | n/a | medium_z1 | 10.244.0.130 |
| consul_z1/0 (da98d278-e70c-4f86-b5e6-05cb4f57d1df)                        | running | n/a | small_z1  | 10.244.0.54  |
| doppler_z1/0 (f9821ce5-1d62-4d1b-b873-c5c5d0a5461f)                       | running | n/a | medium_z1 | 10.244.0.146 |
| etcd_z1/0 (15840fe5-9333-41ea-afb0-f534ae2eebf6)                          | running | n/a | large_z1  | 10.244.0.42  |
| ha_proxy_z1/0 (591ffabb-be18-4543-af8f-8d71dc7cffb0)                      | running | n/a | router_z1 | 10.244.0.34  |
| hm9000_z1/0 (1f404d4d-9823-47d9-a753-df5bdf6db65c)                        | running | n/a | medium_z1 | 10.244.0.142 |
| loggregator_trafficcontroller_z1/0 (aeda75dd-b351-41aa-93e1-cdba3657bc33) | running | n/a | small_z1  | 10.244.0.150 |
| nats_z1/0 (31248983-3e73-48cd-970f-d269411361bc)                          | running | n/a | medium_z1 | 10.244.0.6   |
| postgres_z1/0 (143add56-a6bd-471b-ba9a-cfcb98a1fbfe)                      | running | n/a | medium_z1 | 10.244.0.30  |
| router_z1/0 (5fb52b26-aefd-42eb-8845-f0669285b04b)                        | running | n/a | router_z1 | 10.244.0.22  |
| runner_z1/0 (d7caa4e8-920c-4f0d-a2ad-ff36675bd8d5)                        | running | n/a | runner_z1 | 10.244.0.26  |
| uaa_z1/0 (eaab8324-2566-44fd-b4f2-eb89c0feb9a6)                           | running | n/a | medium_z1 | 10.244.0.134 |
+---------------------------------------------------------------------------+---------+-----+-----------+--------------+

Thanks for your help & best regards

    Hans
