### ISSUE TITLE
Error 100: Unable to render instance groups for deployment. Errors are:   - Unable to render jobs for instance group 'doppler_z1'

### ISSUE THREAD

**Issue by harshalk91** [cloudfoundry/cf-release#1138]
Facing issue while "bosh deploy".

Error 100: Unable to render instance groups for deployment. Errors are:
   - Unable to render jobs for instance group 'doppler_z1'. Errors are:
     - Unable to render templates for job 'doppler'. Errors are:
       - Error filling in template 'doppler.crt.erb' (line 1: Can't find property '["loggregator.tls.doppler.cert"]')
       - Error filling in template 'doppler.key.erb' (line 1: Can't find property '["loggregator.tls.doppler.key"]')
   - Unable to render jobs for instance group 'loggregator_trafficcontroller_z1'. Errors are:
     - Unable to render templates for job 'loggregator_trafficcontroller'. Errors are:
       - Error filling in template 'trafficcontroller.crt.erb' (line 1: Can't find property '["loggregator.tls.trafficcontroller.cert"]')
       - Error filling in template 'trafficcontroller.key.erb' (line 1: Can't find property '["loggregator.tls.trafficcontroller.key"]')

![bosh_release](https://cloud.githubusercontent.com/assets/11748852/21938425/4c86d75c-d9e1-11e6-822b-24e4f92ebf40.JPG)

**Comment by dsabeti** [comment]
Hi @harshalk91.

It looks like your manifest is missing some required properties: `loggregator.tls.trafficcontroller.cert`, `loggregator.tls.trafficcontroller.key`, `loggregator.tls.doppler.cert`, and `loggregator.tls.doppler.key`.

If you're using the manifest generation scripts in cf-release, you'll need to add these values into your spiff stub. They'll fill in [this section of the manifest template](https://github.com/cloudfoundry/cf-release/blob/master/templates/cf.yml#L691-L696).

You can find docs for how to generate loggregator certs [here](https://github.com/cloudfoundry/loggregator#generating-tls-certificates).

**Comment by harshalk91** [comment]
Hi @dsabeti 
Exellent!!! That solved my issue. I am newbie to Cloud Foundry. After this when i run bosh deploy, i stuck with this issue.

Bosh::Clouds::CloudError' with message 'OpenStack API service not found error: Expected([201])

Failed compiling packages > ruby-2.3/ca5b2d16eac54f907ab6c1f454d9c81560f311a2: CPI error 'Bosh::Clouds::CloudError' with message 'OpenStack API service not found error: Expected([201]) <=> Actual(404 Not Found)
excon.error.response
:body => "{"NeutronError": {"message": "The resource could not be found.", "type": "HTTPNotFound", "detail": ""}}"
:cookies => [
]
:headers => {
"Content-Length" => "103"
"Content-Type" => "application/json; charset=UTF-8"
"Date" => "Fri, 13 Jan 2017 19:47:31 GMT"
"X-Openstack-Request-Id" => "req-74cee047-9a6b-4db9-a7ec-96fe16861618"
}
:host => "**************"
:local_address => "192.168.1.14"
:local_port => 42626
:path => "/v2.0/ports"
:port => 9696
:reason_phrase => "Not Found"
:remote_ip => "10.104.68.18"
:status => 404
:status_line => "HTTP/1.1 404 Not Found\r\n"

**Comment by dsabeti** [comment]
@harshalk91 Happy to help. The error you're seeing now has to do with Openstack and Bosh rather than Cloud Foundry. You can ask for help in the [Openstack CPI repo](https://github.com/cloudfoundry-incubator/bosh-openstack-cpi-release). They'll probably be able to help out. You can also ask in the [Slack channel](https://cloudfoundry.slack.com/messages/openstack/) on the Cloud Foundry slack for help debugging.

**Comment by harshalk91** [comment]
@dsabeti I think so. Will Post this issue there. 
Appreciate your prompt response.

**Comment by dsabeti** [comment]
No problem @harshalk91. I'll close out this issue in the meantime, but feel free to open a new issue if you need more help.
