### ISSUE TITLE
CF v251 on vSphere 6.0 can't 'cf login' returns server error 502

### ISSUE THREAD

**Issue by comxtohr** [cloudfoundry/cf-release#1142]
Hello, I deployed CF v251 on vSphere 6.0 followed docs here:  http://docs.cloudfoundry.org/deploying/vsphere/index.html

when I tried to run `cf login` it returns 502 server error with no error message

here is full response of `cf login -v`

```
Email> admin

Password>
Authenticating...

REQUEST: [2017-01-20T20:42:17-05:00]
POST /oauth/token HTTP/1.1
Host: login.cf.footoo.org
Accept: application/json
Authorization: [PRIVATE DATA HIDDEN]
Connection: close
Content-Type: application/x-www-form-urlencoded
User-Agent: go-cli 6.23.1+a70deb3.2017-01-13 / linux

grant_type=password&password=[PRIVATE DATA HIDDEN]&scope=&username=admin

RESPONSE: [2017-01-20T20:42:17-05:00]
HTTP/1.1 200 OK
Connection: close
Content-Length: 1548
Cache-Control: no-store
Content-Type: application/json;charset=UTF-8
Date: Sat, 21 Jan 2017 01:42:17 GMT
Pragma: no-cache
Server: Apache-Coyote/1.1
Strict-Transport-Security: max-age=31536000 ; includeSubDomains
X-Content-Type-Options: nosniff
X-Frame-Options: DENY
X-Vcap-Request-Id: b7ec97b7-6746-4d00-5596-70cc3c2f04dd
X-Xss-Protection: 1; mode=block

{"access_token":"[PRIVATE DATA HIDDEN]","token_type":"[PRIVATE DATA HIDDEN]","refresh_token":"[PRIVATE DATA HIDDEN]","expires_in":599,"scope":"openid scim.read cloud_controller.admin uaa.user cloud_controller.read password.write cloud_controller.write doppler.firehose scim.write","jti":"dda75ac05cc743f28141dd8cb74f8db3"}
OK

REQUEST: [2017-01-20T20:42:17-05:00]
GET /v2/organizations?order-by=name HTTP/1.1
Host: api.cf.footoo.org
Accept: application/json
Authorization: [PRIVATE DATA HIDDEN]
Connection: close
Content-Type: application/json
User-Agent: go-cli 6.23.1+a70deb3.2017-01-13 / linux

RESPONSE: [2017-01-20T20:42:17-05:00]
HTTP/1.1 502 Bad Gateway
Connection: close
Date: Sat, 21 Jan 2017 01:42:17 GMT
Server: nginx
X-Vcap-Request-Id: 8cc2b6c8-cbf9-48c6-440c-cac68f29d9a4
X-Vcap-Request-Id: 8cc2b6c8-cbf9-48c6-440c-cac68f29d9a4::750d8df5-531c-4adb-af7a-be975a855a10
Content-Length: 0

API endpoint:   https://api.cf.footoo.org (API version: 2.69.0)
User:           admin
No org or space targeted, use 'cf target -o ORG -s SPACE'
FAILED
Error finding available orgs
Server error, status code: 502, error code: 0, message:
```

I also  sshed to the vm of cloud cntroller and checked the log, and I found this in log:

```
{"timestamp":1484924151.500687,"message":"Failed communicating with UAA: The UAA was unavailable","log_level":"error","source":"cc.security_context_setter","data":{},"thread_id":47436376931340,"fiber_id":47436376219800,"process_id":7966,"file":"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/middleware/security_context_setter.rb","lineno":22,"method":"rescue in call"}
```

The log shows that cloud controller could not communicate with uaa. 

I checked source code of cloud controller, it shows cloud controller communicates uaa via an internal url.

The internal url of uaa  is configured in `/var/vcap/jobs/cloud_controller_ng/config/cloud_controller_ng.yml` on cloud controller vm

However when I curl internal url of uaa on cloud controller vm, no error raised. Here is result: 

```
$ curl uaa.service.cf.internal:8443 -v
* Rebuilt URL to: uaa.service.cf.internal:8443/
* Hostname was NOT found in DNS cache
*   Trying 172.16.20.103...
* Connected to uaa.service.cf.internal (172.16.20.103) port 8443 (#0)
> GET / HTTP/1.1
> User-Agent: curl/7.35.0
> Host: uaa.service.cf.internal:8443
> Accept: */*
>
* Empty reply from server
* Connection #0 to host uaa.service.cf.internal left intact
```

Please help me out on this problem, thanks a lot!

**Comment by dsabeti** [comment]
@comxtohr Let's get a little more data. Could you provide the following information?
1. Output of `bosh instances`. Specifically, I'm interested in the state of the UAA.
2. Result of `curl https://uaa.service.cf.internal:8443/login -v -k` when run from the CC vm. The output should be HTML (instead of the `Empty reply...` response)
3. UAA logs

**Comment by comxtohr** [comment]
@dsabeti thanks for responsing! I've fixed this bug. I found that there is an error in my stub.yml (networks section). When I correct it the bug just disappeared.

**Comment by nota-ja** [comment]
@comxtohr Would you let me know how did you fix your error?
I have the same trouble right now.

**Comment by comxtohr** [comment]
@nota-ja Double check your stub.yml. I found an indent error in my stub.yml. After I fix it the bug just disappeared.

**Comment by nota-ja** [comment]
Thank you, @comxtohr !
I'll check indents in my YAML file.

**Comment by Senthilannaswamy** [comment]
HI comxtohr,

I'm also facing the same issues while deploying in AWS and stub.yml looks correct as compared to one mentioned in the document.
> https://docs.cloudfoundry.org/deploying/aws/cf-stub.html#editing.

Please let me know which other part needs to be corrected (other than network section)

@dsabeti 
1. VM are up and running, even UAA server
2.  Results `curl https://uaa.service.cf.internal:8443/login -v -k`, is a html page, which has similar content of, when I access through browser `https://uaa.sys.offshore.mydomain.com`
3. UAA log:

> {"timestamp":1492487307.0338788,"message":"Statsd: cc.requests.outstanding:1|c","log_level":"debug","source":"statsd.client","data":{},"thread_id":47366862966400,"fiber_id":47366870115240,"process_id":8590,"file":"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/statsd-ruby-1.2.1/lib/statsd.rb","lineno":254,"method":"send_to_socket"}
{"timestamp":1492487307.0387304,"message":"fetch-verification-keys-retry","log_level":"debug","source":"cc.uaa_verification_keys","data":{"request_guid":"bab06f37-beee-4b7c-6611-7f7189f752d0::02ab3cd5-5d8f-47d3-a00b-6c04ac3a1a78","error":"","remaining_retries":3},"thread_id":47366862966400,"fiber_id":47366870115240,"process_id":8590,"file":"/var/vcap/data/packages/cloud_controller_ng/562841da857b858ce025bac17c36e151a07e8d40/cloud_controller_ng/lib/cloud_controller/uaa/uaa_verification_keys.rb","lineno":52,"method":"rescue in fetch_from_uaa"}
{"timestamp":1492487307.0392003,"message":"fetch-verification-keys-retry","log_level":"debug","source":"cc.uaa_verification_keys","data":{"request_guid":"bab06f37-beee-4b7c-6611-7f7189f752d0::02ab3cd5-5d8f-47d3-a00b-6c04ac3a1a78","error":"","remaining_retries":2},"thread_id":47366862966400,"fiber_id":47366870115240,"process_id":8590,"file":"/var/vcap/data/packages/cloud_controller_ng/562841da857b858ce025bac17c36e151a07e8d40/cloud_controller_ng/lib/cloud_controller/uaa/uaa_verification_keys.rb","lineno":52,"method":"rescue in fetch_from_uaa"}
{"timestamp":1492487307.0396554,"message":"fetch-verification-keys-retry","log_level":"debug","source":"cc.uaa_verification_keys","data":{"request_guid":"bab06f37-beee-4b7c-6611-7f7189f752d0::02ab3cd5-5d8f-47d3-a00b-6c04ac3a1a78","error":"","remaining_retries":1},"thread_id":47366862966400,"fiber_id":47366870115240,"process_id":8590,"file":"/var/vcap/data/packages/cloud_controller_ng/562841da857b858ce025bac17c36e151a07e8d40/cloud_controller_ng/lib/cloud_controller/uaa/uaa_verification_keys.rb","lineno":52,"method":"rescue in fetch_from_uaa"}
{"timestamp":1492487307.0398061,"message":"Connection to 10.11.17.2 closed by remote host.el":"error","source":"cc.uaa_verification_keys","data":{"request_guid":"bab06fConnection to 10.11.17.2 closed.02ab3cd5-5d8f-47d3-a00b-6c04ac3a1a78"},"thread_id":47366862966400,"fiber_id":47366870115240,"process_id":8590,"file":"/var/vcap/data/pac[centos@ip-10-11-0-83 deployment]$ 57b858ce025bac17c36e151a07e8d40/cloud_controller_ng/lib/cloud_controller/uaa/uaa_verification_keys.rb","lineno":22,"method":"update_keys"}
{"timestamp":1492487307.0400007,"message":"Failed communicating with UAA: The UAA was unavailable","log_level":"error","source":"cc.security_context_setter","data":{"request_guid":"bab06f37-beee-4b7c-6611-7f7189f752d0::02ab3cd5-5d8f-47d3-a00b-6c04ac3a1a78"},"thread_id":47366862966400,"fiber_id":47366870115240,"process_id":8590,"file":"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/middleware/security_context_setter.rb","lineno":22,"method":"rescue in call"}
{"timestamp":1492487307.0402062,"message":"Statsd: cc.requests.outstanding:-1|c\ncc.requests.completed:1|c\ncc.http_status.5XX:1|c","log_level":"debug","source":"statsd.client","data":{},"thread_id":47366862966400,"fiber_id":47366870115240,"process_id":8590,"file":"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/statsd-ruby-1.2.1/lib/statsd.rb","lineno":254,"method":"send_to_socket"}

Do let me know your thoughts.
Thanks
Senthil
[cf-stub - Copy.txt](https://github.com/cloudfoundry/cf-release/files/927658/cf-stub.-.Copy.txt)

**Comment by dsabeti** [comment]
@Senthilannaswamy, if you ssh onto the api_z1 vm, can you curl `uaa.service.cf.internal/token_keys`? What does that command return? What's the exit code?

**Comment by Senthilannaswamy** [comment]
Hi dsabeti,
When I did a curl `https://uaa.service.cf.internal:8443/token_keys`, from api_z1 (IP: 10.11.17.2), I go the following response and the public matches with `jwt.verification_key`. 
Response:
> {
keys: [
	{
		kty: "RSA",
		e: "AQAB",
		use: "sig",
		kid: "legacy-token-key",
		alg: "RS256",
		value: "-----BEGIN PUBLIC KEY-----
		MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA2Ex12neXRwA6UHDDtOL8
		Y8rPE956u/gSiDeaVAF9qln3/giPADfho8oNs+p0febviDiiBhHeXfkiAKRD0kse
		Ec/eZp+CVHLNfo+lmu3G3GNTLvTKeG91HYLLixJHWIukPArOK35SL9CKNWoVIsRS
		/1WVRDK7o67LYqLyWFjslBKH11Li4tmRtGX6sBaF/wPGmN/J6LAGgNKDx8lXn2mw
		IKUFPbX85p3PUTWU9D5vxEyHEmYsARyQBZemYEcRvsWhqCJLvJvDuMPBgJz3Lajr
		UfiZJ1zSRAFTpBzny18qWyxoCDRBXYo5lAnr+8ntkAnsz3XYTc3GTLde5E58CHel
		3QIDAQAB
		-----END PUBLIC KEY-----",
		n: "ANhMddp3l0cAOlBww7Ti_GPKzxPeerv4Eog3mlQBfapZ9_4IjwA34aPKDbPqdH3m74g4ogYR3l35IgCkQ9JLHhHP3mafglRyzX6PpZrtxtxjUy70ynhvdR2Cy4sSR1iLpDwKzit-Ui_QijVqFSLEUv9VlUQyu6Ouy2Ki8lhY7JQSh9dS4uLZkbRl-rAWhf8DxpjfyeiwBoDSg8fJV59psCClBT21_Oadz1E1lPQ-b8RMhxJmLAEckAWXpmBHEb7FoagiS7ybw7jDwYCc9y2o61H4mSdc0kQBU6Qc58tfKlssaAg0QV2KOZQJ6_vJ7ZAJ7M912E3Nxky3XuROfAh3pd0="
	}
 ]
}

**Comment by dsabeti** [comment]
What happens if you don't provide the `--insecure` flag to your curl command?

**Comment by Senthilannaswamy** [comment]
Hi David ,
I get following response
> api_z1/c9118ab5-a9e3-4af3-9af2-438da730a134:~$ curl https://uaa.service.cf.internal:8443/login
curl: (60) SSL certificate problem: unable to get local issuer certificate

**Comment by dsabeti** [comment]
Ok, what's that's telling me is that the TLS certificates for your UAA are not configured correctly. Take a look at [this document](https://github.com/cloudfoundry/cf-release/blob/master/on-tls-certificates.md) for guidance regarding the TLS certificates in cf-release.

**Comment by Senthilannaswamy** [comment]
Thanks David for the support. Now I'm able to push the apps as well.

Btw, In the last section of the document 
>[Last, generate the certs for statsd-injector](https://github.com/cloudfoundry/cf-release/blob/master/on-tls-certificates.md#last-generate-the-certs-for-statsd-injector)

I had used `statsd_injector` instead of `doppler`.

**Comment by dsabeti** [comment]
Hey, good catch! I'll update the doc now.
