### ISSUE TITLE
Re-Opening Issue 1087

### ISSUE THREAD

**Issue by cpraveen412** [cloudfoundry/cf-release#1147]
Hello Team!!
I already opened a tkt ( #1087 ) long back but did not get a chance to continue my work. But i started working on it again.

I'm trying to deploy multi zoned CF on vSphere. I've been trying but got failed.
I'm trying to achieve the following:

![image](https://cloud.githubusercontent.com/assets/19999722/22521423/ea63d620-e885-11e6-8d9a-255063fc9669.png)

1) As shown in the picture, I have a datacenter called CF-Datacenter with two clusters named CF-Cluster & CF-Cluster1.
2) Each cluster has a server with IPs 192.168.6.3 & 192.168.5.5 respectively.
3) In CF-Cluster the network is VM Network(Standard Switch) and CF-Cluster1 has VM Network1(Standard Switch) as the network.
4) I'm trying to make each cluster as a zone. two zones (z1 & z2). For this, I created bosh.yml in the following way.

https://gist.github.com/cpraveen412/d2e1577182af12f41ac27dca4bbfcd4f

5) After deploying bosh, I generated cf-deployment using the regular stub from CF docs and scripts expecting that it will deploy to both the clusters.
 But it was not as expected. Please suggest me changes in vSphere level and bosh/CF level

Thank You

**Comment by dsabeti** [comment]
We've decided to reopen #1087 instead. I'll close this to keep the conversation in a single thread.
