### ISSUE TITLE
issue with - uaac client add

### ISSUE THREAD

**Issue by betht1220** [cloudfoundry/cf-release#1151]
I've used the above command to register oauth2 client for my application.
When my app runs, and access through browser say http://localhost:8080, I was redirect to
cf login endpoint and asked to login as I expected.
However, the "authorization approval" did not come up.

I have cf v247

I've tried to look for a while, but found nothing wrong in my setup

Thanks

**Comment by dsabeti** [comment]
Hey @betht1220. This sounds like an issue pretty specific to the UAA (our OAuth2 provider). Maybe @sreetummidi and @plfx from the Identity team can help you to debug. Otherwise, you might have better luck opening an issue on the [UAA repo](https://github.com/cloudfoundry/uaa).

**Comment by plfx** [comment]
Yes, please open an issue at UAA. When you do so, include a detailed description of what occurred, and what you expected to occur.

**Comment by betht1220** [comment]
Thanks, I have open this issue with uaa
