### ISSUE TITLE
minimal-aws deploy doesn't provide instructions for all needed values

### ISSUE THREAD

**Issue by pglombardo** [cloudfoundry/cf-release#1155]
Just went through the [minimal aws deploy steps](https://github.com/cloudfoundry/cf-release/blob/master/example_manifests/README.md) but there were still values that needed to be replaced in the deployment manifest but which the documentation didn't cover.  After going through the doc, these values are still in the `minimal-aws.yml` deployment manifest.

* `REPLACE_WITH_PASSWORD` (not mentioned but straight forward & handled)
* `REPLACE_WITH_TPS_CC_CA_CERT`
* `REPLACE_WITH_TPS_CC_CLIENT_CERT`
* `REPLACE_WITH_TPS_CC_CLIENT_KEY`
* `REPLACE_WITH_UAA_CA_CERT`
* `REPLACE_WITH_UAA_SSL_KEY`
* `REPLACE_WITH_UAA_SSL_CERT`

Likely this is a simple fix for experienced users but definitely not for first timers deploying to AWS.

Before noticing the above were overlooked, I deployed to AWS and the deploy ultimately failed (and burned a lot of time).

It would be great if we could update that README with expanded instructions covering the above.

cc: @jaresty re: https://github.com/cloudfoundry/cf-release/commit/5bd3e0b35cf6e438c0a74dc524a0a6c16d252b45

**Comment by dsabeti** [comment]
Hey @pglombardo. Thanks for this feedback. What are you using the manifest for? Just to get started with setting up a CF, or for a "real" environment that you intend to maintain?

I'm asking because the minimal-aws manifest is merely an example and isn't meant to be secure in any meaningful way. You might notice that other private keys are hard-coded. My preferred solution to this issue is to hard-code the keypairs you referenced -- and potentially the passwords as well.

Would that fit your use case? Our do you need instructions for how to generate hose keypairs yourself?

**Comment by pglombardo** [comment]
Yes - just testing/learning what a real deployment (non BOSH-lite) looks like.  This manifest was helpful and even states its only for educational purposes at the top which is great.

Hard coded values would be fine.

**Comment by dsabeti** [comment]
Great. Also, I'd consider taking a look at [cf-deployment](https://github.com/cloudfoundry/cf-deployment). It's our new manifest generation tool for CF that's still in beta. You'll learn a lot about the newer BOSH features.

**Comment by dsabeti** [comment]
@pglombardo I've hard-coded the certs in the minimal manifest now.

Deployers still need to replace the following:
- `REPLACE_WITH_PASSWORD`
- `REPLACE_WITH_BOSH_STEMCELL_VERSION`
- Deployment-specific information
  - `REPLACE_WITH_SYSTEM_DOMAIN`
  - `REPLACE_WITH_DIRECTOR_ID`
  - `REPLACE_WITH_SSL_CERT_AND_KEY` (has directions in the README)
- IaaS-specific information
  - `REPLACE_WITH_ELASTIC_IP`
  - `REPLACE_WITH_AZ`
  - `REPLACE_WITH_BOSH_SECURITY_GROUP`
  - `REPLACE_WITH_PUBLIC_SECURITY_GROUP`
  - `REPLACE_WITH_PUBLIC_SUBNET_ID`
  - `REPLACE_WITH_PRIVATE_SUBNET_ID`

Let me know if this doesn't address your concerns. Assuming everything is ok, I'll close out this issue.

**Comment by pglombardo** [comment]
Thanks for following up and fixing @dsabeti!
