### ISSUE TITLE
AWS manifest template should use current gen instance types

### ISSUE THREAD

**Issue by thausler786** [cloudfoundry/cf-release#1158]
AWS recently added a new AZ to us-east-1 which does not support the `m3`instance types:

```
CPI 'create_vm' method responded with error: CmdError{"type":"Unknown","message":"Your requested instance type (m3.xlarge) is not supported in your requested Availability Zone (us-east-1b). Please retry your request by not specifying an Availability Zone or choosing us-east-1d, us-east-1a, us-east-1c, us-east-1e.","ok_to_retry":false}
```

This lack of support is not super surprising as m3 has been replaced with m4 types for some time, as well as c3 being replaced with c4. Could y'all bump to the m4 and c4 instances to get around this error?

**Comment by dsabeti** [comment]
@thausler786. Is this an immediate problem for you? Overall, this seems like a reasonable request, but I'm thinking about addressing this in [cf-deployment](https://github.com/cloudfoundry/cf-deployment) instead. There are also a few other reasons not to do this just yet.

**Comment by dsabeti** [comment]
Hey @thausler786. After think about this for a while, I think I'd prefer to let this get solved as part of cf-deployment instead. For what it's worth, you can always override the vm type in your spiff stub.
