### ISSUE TITLE
minimal-aws example manifest hardcodes JWT signing key and other sensitive values

### ISSUE THREAD

**Issue by cantino** [cloudfoundry/cf-release#1160]
Anyone using this manifest, even for experimentation, will have a CF installation that will accept bearer tokens from any other similar installation, or from anyone who spoofs their JWT tokens with this shared private key. Those values in the example manifest should be replaced with placeholders such as `REPLACE_WITH_UAA_JWT_SIGNING_PRIVATE_KEY`, `REPLACE_WITH_UAA_JWT_VERIFICATION_PUBLIC_KEY`, etc.

Additionally, there are a bunch of other sensitive hardcoded default values in this manifest.

**Comment by dsabeti** [comment]
Hey @cantino. Thanks for bringing this up, but we're aware. There's actually a warning in [the README](https://github.com/cloudfoundry/cf-release/tree/master/example_manifests#introduction) that the manifest doesn't give you a secure deployment. The idea behind this minimal manifest is that it gives users a bosh deployment manifest that they can deploy pretty much immediately -- if anything, I've thought about hard-coding _all_ of the credentials in that file.

One of the things we're looking forward to in the [cf-deployment](https://github.com/cloudfoundry/cf-deployment) world is not to have to support such a manifest -- the BOSH CLI (and soon CredHub) will manage credential generation and management, so users can deploy pretty easily.

Anyway, let me know if that addresses your concerns. I could always make the warning in the README bigger.

**Comment by squeedee** [comment]
Perhaps the disclaimer could be in the manifest comment header, along with a recommendation not to remove the discalimer?

That way, a person does not need to have read the readme, and the next person to see the copy of the manifest continues to see it.

**Comment by dsabeti** [comment]
@squeedee Sounds like a good idea. I'll update it.

**Comment by dsabeti** [comment]
@squeedee @cantino: https://github.com/cloudfoundry/cf-release/commit/6b0202a2125d68fa62809d5956a739f7f57b4916

**Comment by cantino** [comment]
I think that's a good improvement, thanks @dsabeti.
