### ISSUE TITLE
StagingFailed error for pushing .net application windows stack

### ISSUE THREAD

**Issue by cfmagnum** [cloudfoundry/cf-release#1161]
CloudFoundary version-250
diego/1.4.1
windows windows2012R2
Cloud- aws 
windows cell size-r3.xlarge

Hi i am trying to push a .net application on windows stack.But after starting the applicationn its giving staging failed error.
I am pushing app from repo  https://github.com/cloudfoundry/wats

Using Buildpack is  https://github.com/ryandotsmith/null-buildpack

Command for pushing app are as followed.

**cf push windows-test-app-1 -s windows2012R2 -b https://github.com/ryandotsmith/null-buildpack.git -m 1G --no-start**
**cf start windows-test-app-1**
I am attaching output of  CF_TRACE 
[cf_trace=true.txt](https://github.com/cloudfoundry/diego-release/files/823559/cf_trace.true.txt)
.

on checking logs with command 
**cf logs windows-test-app-1 --recent**
![screen shot 03-07-17 at 12 09 pm](https://cloud.githubusercontent.com/assets/13657881/23644759/ed2694f6-032e-11e7-9116-163858a9b35b.PNG)

Can you please assist us with the problem?
Thanks in Advance

**Comment by dsabeti** [comment]
Hey @cfmagnum. 

I don't know much about the "null buildpack", but it seems like it's designed for `cf push`ing a binary. From what I can tell, you're not pre-compiled this app so I don't think this buildpack will work. The buildpack for pushing windows apps is  `https://github.com/cloudfoundry-incubator/hwc-buildpack/releases/download/v2.1.0/hwc_buildpack-cached-v2.1.0.zip`

You can find more information for how to push the app by reading [this README](https://github.com/cloudfoundry/wats/tree/936a2c5fec7ccf2d545d8708b3ba611fcb59493e/assets/nora) and the scripts inside the assets directory.

Let me know if that helps.

**Comment by dsabeti** [comment]
Hey @cfmagnum, any update on this? If you have what you need, I'd like to close out the issue.

**Comment by dsabeti** [comment]
I'm going to close this issue. Feel free to re-open it if you need help.
