### ISSUE TITLE
Error while deploying Cloud Fountry 253 on vsphere- Timed out

### ISSUE THREAD

**Issue by renatodelgaudio** [cloudfoundry/cf-release#1162]
While following the [official steps](https://docs.cloudfoundry.org/deploying/vsphere/index.html) to deploy Cloud Fountry on vsphere, I am getting the following error during the deploy step.

# Deploy Command
$ BOSH DEPLOY
```
Are you sure you want to deploy? (type 'yes' to continue): yes

Director task 36
Deprecation: Ignoring cloud config. Manifest contains 'networks' section.

  Started preparing deployment > Preparing deployment. Done (00:00:01)

  Started preparing package compilation > Finding packages to compile. Done (00:00:01)

  Started compiling packages
  Started compiling packages > cli/34a960bea4f871cf1de2c61258b0ffbfb7c58f20
  Started compiling packages > haproxy/ad6e9e08a6d7a0f8951322f9a2ce394105df7fcf
  Started compiling packages > rootfs_cflinuxfs2/4854a81309bca40031403d9ff1a0da6d12701764
  Started compiling packages > nginx/1c08b1a776875d2efb3e2262c09f10bed06f9d86
  Started compiling packages > ruby-2.3/ca5b2d16eac54f907ab6c1f454d9c81560f311a2
  Started compiling packages > libpq/7e51aa75bcabc47002eccc38be269de63fc6df7d
   Failed compiling packages > cli/34a960bea4f871cf1de2c61258b0ffbfb7c58f20: Timed out pinging to c244b51e-cf00-403c-80ba-19bb2d8c0984 after 600 s0:10:34)
   Failed compiling packages > haproxy/ad6e9e08a6d7a0f8951322f9a2ce394105df7fcf: Timed out pinging to 29b74528-f277-44d4-aacc-6ee4f87c786a after 6s (00:10:47)
   Failed compiling packages > rootfs_cflinuxfs2/4854a81309bca40031403d9ff1a0da6d12701764: Timed out pinging to e67831e4-85b9-44f3-b7ec-d502460bff600 seconds (00:10:47)
   Failed compiling packages > nginx/1c08b1a776875d2efb3e2262c09f10bed06f9d86: Timed out pinging to ef871202-0114-4f8e-b8ee-efd6e7a94c7d after 600(00:10:49)
   Failed compiling packages > ruby-2.3/ca5b2d16eac54f907ab6c1f454d9c81560f311a2: Timed out pinging to 541347c9-fbf6-40cf-b35b-d56b43e4e1c9 after ds (00:10:49)
   Failed compiling packages > libpq/7e51aa75bcabc47002eccc38be269de63fc6df7d: Timed out pinging to aa5776f9-16d4-424a-bb49-12b051dcf062 after 600(00:10:49)

Error 450002: Timed out pinging to c244b51e-cf00-403c-80ba-19bb2d8c0984 after 600 seconds
```

## Remarks
During the deploy command is running, I can see 6 VM getting created on my ESXI and the IP get correctly assigned according to my deployment manifest (e.g. 10.0.0.141, 10.0.0.142 etc).
I guess that the issue is due to the fact that the deployment process is not able to reach those VM (probably DNS resolution) but I am not sure where should I look at.
Is the Director using an internal DNS to resolve the newly created VM?
The configured network uses an external DNS (10.0.0.2) that of course is not aware of the new VM created by bosh deploy command.
Should I configure something in my DNS ? How/What?

I see the same issue also when both networks have no external DNS and no external DHCP.
Probably I've not understood very well which are the network/topology requirements.

# Deployment Manifest Stub
The deployment manifest stub as follows:

```
meta:
  environment: DEV

director_uuid: 611b18c6-f487-4e08-b584-741697553054

networks:
  - name: cf1
    subnets:
    - range: 10.0.0.0/24
      gateway: 10.0.0.1
      reserved:
      - 10.0.0.2 - 10.0.0.130
      - 10.0.0.200 - 10.0.0.210
      dns:
      - 10.0.0.2
      - 10.0.0.1
      static:
      - 10.0.0.230 - 10.0.0.254
      cloud_properties:
        name: VM Network

  - name: cf2
    subnets:
     - range: 10.0.1.0/24
       gateway: 10.0.1.1
       reserved:
        - 10.0.1.2 - 10.0.1.100
       dns:
       - 10.0.0.2
       - 10.0.0.1
       static:
       - 10.0.1.200 - 10.0.1.254
       cloud_properties:
         name: cf2


properties:
  system_domain: cf.intranet.renatodelgaudio.com
  system_domain_organization: HOME
  app_domains:
    - cf.intranet.renatodelgaudio.com

  ssl:
    skip_cert_verify: true
```

The release uploaded on Director is the latest as shown below (it was not build locally, as described in the steps, but using the remote URL: bosh upload release https://github.com/cloudfoundry/cf-release/blob/master/releases/cf-253.yml):

```
$ bosh releases
RSA 1024 bit CA certificates are loaded due to old openssl compatibility
Acting as user 'admin' on 'my-bosh'

+------+----------+-------------+
| Name | Versions | Commit Hash |
+------+----------+-------------+
| cf   | 253      | 82fb38a8+   |
+------+----------+-------------+
(+) Uncommitted changes

Releases total: 1
```

# Documentation Note
Referring to the [manifest stub](https://docs.cloudfoundry.org/deploying/common/vsphere-vcloud-cf-stub.html#stub), the template is missing the required property saml.**serviceProviderCertificate**.

**Comment by dsabeti** [comment]
Hi @renatodelgaudio.

Bosh doesn't use DNS to find those VMs. It actually manages their IP addresses and addresses them directly. So what's actually going wrong is that the BOSH director can't find these VMS, _even by their IP addresses._ This suggests that something much bigger is going wrong.

You could always perform the following experiment to try to debug what the BOSH director can't find these VMs:
1. Start the deploy
2. While the deploy is happening, run `bosh vms`. Hopefully, you should see a bunch of [compilation VMs](http://bosh.io/docs/deployment-manifest.html#compilation), including their IP addresses.
3. `ssh` onto the bosh director. From there, can you ping the compilation VMs? Can you ssh onto them? You may have to use some more advanced networking tools to figure out why traffic isn't being routed to those VMs.

A few other things I noticed:
- The `gateway` property is pretty important in vSphere deployments. It represents the default route that VMs deployed by BOSH will have. That IP address is used to route traffic in and out of the subnet where the VMs are deployed -- in our case, we have a literal hardware router. I noticed that it's just at the `X.X.X.1` address of your subnet, so I'm not sure if that's copypasta from instructions or on purpose, but you should make sure that whatever value you put in that spot, it corresponds to something that can manage network traffic.
- The `cloud_properties` properties for the two networks (`VM Network` and `cf2`) must correspond to actual vSphere networks. Make sure that those values are accurate.

**Comment by renatodelgaudio** [comment]
Thank you for your feedback. The gateway is correct as it corresponds to a physical router in my case too.

I tried several things until I gave up and installed with success instead Pivotal Cloud Foundry.
