### ISSUE TITLE
Unable to generate cf_bosh-lite manifest (./scripts/generate-bosh-lite-dev-manifest) [migrated from diego-release]

### ISSUE THREAD

**Issue by ematpl** [cloudfoundry/cf-release#1165]
> Original submitter: @aerondeepak
> Original issue: https://github.com/cloudfoundry/diego-release/issues/284
---
Hi,

I am facing problem while generating manifest in cf-release directory

**~/workspace/cf-release$ ./scripts/generate-bosh-lite-dev-manifest**
`Aborted. Please install spiff by following https://github.com/cloudfoundry-incubator/spiff#installation
`

As such, spiff has been installed successfully

**/go/src/github.com/cloudfoundry-incubator/spiff$ spiff -v**
`spiff version 1.0.8`

**/go/src/github.com/cloudfoundry-incubator/spiff$ go test** 
```
Running Suite: Executable
=========================
Random Seed: 1488935905
Will run 2 of 2 specs

••
Ran 2 of 2 Specs in 0.893 seconds
SUCCESS! -- 2 Passed | 0 Failed | 0 Pending | 0 Skipped PASS
ok  	github.com/cloudfoundry-incubator/spiff	0.898s
```
Anyone please suggest
Thanks,

**Comment by dsabeti** [comment]
@aerondeepack, is spiff in `$GOPATH/bin`? What happens if you run `which spiff`?

**Comment by aerondeepak** [comment]
Issue is resolved. I had to run the following commands after spiff installation:
```
sudo cp spiff /bin/
sudo chmod a+x /bin/spiff
``` 
Thanks for the reply :)

**Comment by dsabeti** [comment]
Great, I'll close the issue.
