### ISSUE TITLE
Possible incorrect documentation around cert creation

### ISSUE THREAD

**Issue by cweibel** [cloudfoundry/cf-release#1171]
Inside of https://github.com/cloudfoundry/cf-release/blob/develop/on-tls-certificates.md under "The interrelated components" there is a duplication row of `cf-diego-certs/cloud_controller.crt` should be mapped `properties.cc.mutual_tls.public_cert`.

I originally figured this was just an accidental copy paste.  While hunting down how to create all the new certificates I could not find documentation on how to create `properties.cc.mutual_tls.private_key` and am thinking that this duplicate row was supposed to contain information for this property value.  Am I correct that this property should be filled by `cf-diego-certs/cloud_controller.key`?  If so I can submit a PR for it.

**Comment by dsabeti** [comment]
@cweibel Great catch! Would you submit a PR?

**Comment by dsabeti** [comment]
I just merged your PR, so I'll close this issue. Thanks @cweibel.
