### ISSUE TITLE
UAA properties documentation

### ISSUE THREAD

**Issue by cweibel** [cloudfoundry/cf-release#1172]
Inside of https://github.com/cloudfoundry/cf-release/blob/develop/on-tls-certificates.md under "UAA" there are references to `properties.uaa.server_cert` and `properties.uaa.server_key` which I cannot find references for in the sample boshlite manifest nor the spec files for uaa.  My best guess is these are supposed to be `properties.uaa.sslCertificate` and `properties.uaa.sslPrivateKey`, if so I can submit a PR.

**Comment by dsabeti** [comment]
@cweibel Another good catch. Indeed, those are supposed to go in `sslCertificate` and `sslPrivateKey`. I'd accept a PR here as well.

**Comment by dsabeti** [comment]
I just merged your PR, so I'll close this issue. Thanks @cweibel.
