### ISSUE TITLE
cf logs --recent returning FAILED: Error dialing trafficcontroller server: net/http: request canceled (Client.Timeout exceeded while awaiting headers)

### ISSUE THREAD

**Issue by jocono** [cloudfoundry/cf-release#1177]
Opening new issue to track...#1094 was previous thread.

**Comment by dsabeti** [comment]
@aerondeepak @enocom @Xenophex

Please follow this thread.

**Comment by enocom** [comment]
@jocono A common problem is misconfigured certs within Loggregator. Let's try to eliminate that as the source of the issue. 

To that end, here are some questions:

1) Are your certificates for Traffic Controller still valid? 
2) Do they have a client extended key usage enabled? 
3) Also, how did you generate the certs for Loggregator?

**Comment by jocono** [comment]
We have a valid cert for traffic controller and we generated them with the generate-loggregator-certs script.   Also I do not believe we have client extended key usage enabled.

**Comment by jocono** [comment]
Also if we had a bad cert wouldn't see a tlsConfig err with the grpc Listener creation? 

Reference 
func NewGRPCListener (lines 26-40) of https://github.com/cloudfoundry/loggregator/blob/749107dcbfa507bd7ddae77000d2f5f94ad144fe/src/doppler/listeners/grpc_listener.go

**Comment by jocono** [comment]
After cracking open the loggregator cert, it appears we do have TLS Web Client Auth:
X509v3 Extended Key Usage:
                TLS Web Server Authentication, TLS Web Client Authentication

**Comment by enocom** [comment]
@jocono Good to know. We'll continue to dig into this on Monday.

**Comment by jocono** [comment]
Additional testing notes:

We are running this on an Openstack (Mitaka) infrastructure environment and the deployment we are experiencing this issue with is located behind a firewalled floating ip network.  While, the floating ip addresses (on haproxy and admin server) are in a firewalled network but all of the runtime and diego instances are on a private, openstack defined network.  

We have also redepoyed the entire existing environment and deployed a similar new environment in a different datacenter with a similar setup (with floating ip behind a firewall)and a similar manifest and release packages.   We are able to consistently reproduce the error with cf logs and stats.

We are unable to reproduce this issue with the same manifest and release packages deployed on an environment where the floating network is not behind a firewall.  

Both security groups and firewall rules are configured to allow TCP 4443 ingress/egress and we seem to be establishing a connection to the traffic controller successfully.

**Comment by jocono** [comment]
After some additional investigation, we have determined this is a configuration issue on our side.  The behavior we were seeing was a result of two of our three DNS resolvers could not be reached from the firewall floating network.  The relevant bit of code that shows why the cf nozzle worked and cf logs did not is as follows:

From trafficcontroller/dopplerproxy/doppler_proxy.go.

Line 115:
func (p *Proxy) serveFirehose(firehoseSubscriptionId string, writer http.ResponseWriter, request *http.Request) {
  authToken := getAuthToken(request)

authorized, err := p.adminAuthorize(authToken)  <- doesn’t need DNS lookup

vs.

Line 142:
func (p *Proxy) serveAppLogs(requestPath, appID string, writer http.ResponseWriter, request *http.Request) {
  authToken := getAuthToken(request)

status, _ := p.logAuthorize(authToken, appID)  <- needs DNS lookup

The difference between the two is that adminAuthorize uses an HTTP request header, and logAuthorize has to connect to api.run.xxxx.xxxx.com:443 (which requires a DNS lookup) to verify access to the appID

Thanks for everyone's willingness to help and I believe we can close this out.

**Comment by enocom** [comment]
@jocono Glad to hear it was just a config problem.

**Comment by aerondeepak** [comment]
Hi @jocono ,
I am having the same problem while retrieving the logs. I am running bosh-lite on virtual box. 
As per above comments, it seems to be some DNS lookup issue, but I didn't understand exactly what configuration changes you have done in the *doppler_proxy.go* to make it resolve.
/workspace/cf-release/src/aggregator/src/traffic controller/doppler proxy/doppler_proxy.go

Could you please explain.
Thanks,

**Comment by jocono** [comment]
Our issue was not with the doppler proxy code but rather our firewall in front of our cf deployment was blocking DNS lookups on two out of three of our DNS servers.  The first two dns servers were not succeeding lookups and by the time the third succeeded the web socket was closed.  Our fix was to allow DNS (port 53) to all of our dns resolvers from our runtime network.  If you are having a similar issue, you should verify that names (specifically your runtime api endpoint) are resolving from your traffic controller and doppler instances.  You can also ssh into the traffic controller and tcpdump port 53 | grep api .  Then issue a cf logs command from your cf cli and you should see the relevant lookup come through.

**Comment by aerondeepak** [comment]
I have been trying to ssh to traffic_controller, but by default is taking the cf-warden-diego as set deployment
```
bosh-lite$ bosh ssh loggregator_trafficcontroller_z1/0
Acting as user 'admin' on deployment 'cf-warden-diego' on 'Bosh Lite Director'
Target deployment is 'cf-warden-diego'

Setting up ssh artifacts

Director task 45
Error 70001: No instances matched {:job=>"loggregator_trafficcontroller_z1", :index=>[0], :deployment_id=>2}

Task 45 error
Failed to set up SSH: see task 45 log for details

```
Even I tried to set the cf-warden deployment, 

```
bosh-lite$ bosh deployment cf-warden
'Missing manifest for 'cf-warden'

```
Please suggest!!

**Comment by dsabeti** [comment]
@aerondeepak You need to target the deployment _manifest_:
```
bosh deployment ../cf-release/bosh-lite/deployments/cf.yml
```
(You'll probably have to modify the path to point to the correct location of the file).

If you can't find the deployment manifest:
```
bosh download manifest cf-warden cf-warden.yml
bosh deployment cf-warden.yml
```
