### ISSUE TITLE
CF 254 is using a "do-not-use" version of uaa-release

### ISSUE THREAD

**Issue by paolostivanin** [cloudfoundry/cf-release#1179]
See https://github.com/cloudfoundry/uaa-release/releases/tag/v28

**Comment by dsabeti** [comment]
Hi @paolostivanin. Thanks for bringing this to my attention. I'm going to follow up with @sreetummidi and @plfx to see if there's any necessary follow up.

**Comment by sreetummidi** [comment]
There is a very specific upgrade incompatibility going from V24.6 to V28 of UAA Release. This doesn't affect any cf-release upgrades as no cf-release release contains V24.6 version of UAA Release.

Stand-alone UAA-Release customers upgrading v24.6 should use [V29](https://github.com/cloudfoundry/uaa-release/releases/tag/v29) Instead.

**Comment by paolostivanin** [comment]
ok, thanks! :)
