### ISSUE TITLE
CF v255 fails to deploy clock_z2 on openstack

### ISSUE THREAD

**Issue by wbean1** [cloudfoundry/cf-release#1180]
going from v254 to v255 on openstack using manifest generation scripts, deployment fails with:
```
  Started creating missing vms
  Started creating missing vms > clock_z1/7ada5c8e-4787-427b-9df2-8d8da6f1ce7a (0)
  Started creating missing vms > clock_z2/f9299312-5c51-4c3c-bb84-f3e449a32c2d (0). Failed: CPI error 'Bosh::Clouds::CloudError' with message 'OpenStack API Conflict (Unable to complete operation for network a6695544-c3f9-4b56-a72a-85cea7f2e2f3. The IP address 10.0.1.4 is in use.). Check task debug log for details.' in 'create_vm' CPI method (00:00:02)
     Done creating missing vms > clock_z1/7ada5c8e-4787-427b-9df2-8d8da6f1ce7a (0) (00:01:19)
   Failed creating missing vms (00:01:19)
```

All other vm types have the `_z2` instance counts overridden to `0` in https://github.com/cloudfoundry/cf-release/blob/master/templates/cf-infrastructure-openstack.yml.  Looks like this was missed in #1157.

**Comment by dsabeti** [comment]
Hey @wbean1

**Comment by dsabeti** [comment]
Sorry @wbean1. I accidentally hit the Close button a minute too early. Now that there's a PR for this, can I close the issue?

**Comment by wbean1** [comment]
yep that's fine, wasn't sure if you'd want both or just the PR.
