### ISSUE TITLE
curl api.YOUR-SYSTEM-DOMAIN/info -  Could not resolve host: 

### ISSUE THREAD

**Issue by Senthilannaswamy** [cloudfoundry/cf-release#1183]
HI Team,

I'm trying to deploy CF on AWS and all VMs are created without any issues.

But could not do curl for api, though configuration in Hosted zone are present, including the CNAME record for "* .offshore.mydomain.com" pointing to "cfrouter11-1606644234.us-east-1.elb.amazonaws.com".

I was able to resolve the 'bosh.offshore.mydomain.com', by "dig"

> curl api.sys.offshore.mydomain.com
> curl: (6) Could not resolve host: api.sys.offshore.mydomain.com; Name or service not known

Please let me know what I'm missing.

> bosh vms 

+---------------------------------------------------------------------------+---------+-----+-----------+-------------+
| VM                                                                        | State   | AZ  | VM Type   | IPs         |
+---------------------------------------------------------------------------+---------+-----+-----------+-------------+
| api_worker_z1/0 (4d080a96-c2fd-4ce9-8cbf-aa303d555f1c)                    | running | n/a | small_z1  | 10.11.17.4  |
| api_worker_z2/0 (2f7871b6-629f-4be9-93f1-3527e08004fa)                    | running | n/a | small_z2  | 10.11.81.2  |
| api_z1/0 (cffcf41f-b673-4d7d-a430-15ae71e6a0ce)                           | running | n/a | large_z1  | 10.11.17.2  |
| api_z2/0 (35742645-5376-41ff-97eb-98d7d8a559a3)                           | running | n/a | large_z2  | 10.11.81.1  |
| clock_global/0 (e93ac8d3-e366-424a-a601-30aec7859848)                     | running | n/a | medium_z1 | 10.11.17.3  |
| consul_z1/0 (da32f439-2a17-4e70-bb82-79862aa6721f)                        | running | n/a | small_z1  | 10.11.16.37 |
| consul_z1/1 (7f819bc4-559b-41a0-8648-9b128d9658be)                        | running | n/a | small_z1  | 10.11.16.38 |
| consul_z2/0 (549c588b-cc38-4785-b2e0-61ae7a058b90)                        | running | n/a | small_z2  | 10.11.80.37 |
| doppler_z1/0 (eb41fe30-e134-4691-aafb-6573fa009bab)                       | running | n/a | medium_z1 | 10.11.17.7  |
| doppler_z2/0 (e19686d8-e6bd-477d-a0af-87cfa03ce44e)                       | running | n/a | medium_z2 | 10.11.81.5  |
| etcd_z1/0 (501fae48-fea8-4acc-ae52-87eb3be1342d)                          | running | n/a | large_z1  | 10.11.16.20 |
| etcd_z1/1 (0f8dae55-28fc-4ca2-ac22-7844464d49bb)                          | running | n/a | large_z1  | 10.11.16.35 |
| etcd_z2/0 (3e6e05bb-b7c7-46cc-9797-53654990c488)                          | running | n/a | large_z2  | 10.11.80.19 |
| hm9000_z1/0 (d8fa6fa5-7ec3-4391-9d42-a2a910e545ff)                        | running | n/a | medium_z1 | 10.11.17.5  |
| hm9000_z2/0 (49fb6f22-6ddb-4809-beba-93a0d0b1d9f0)                        | running | n/a | medium_z2 | 10.11.81.3  |
| loggregator_trafficcontroller_z1/0 (b1cd1615-1738-436b-ab33-7393322cb15a) | running | n/a | small_z1  | 10.11.17.8  |
| loggregator_trafficcontroller_z2/0 (c68f3cc8-5a0e-47a1-90e4-165ddec2e02d) | running | n/a | small_z2  | 10.11.81.6  |
| nats_z1/0 (ffb7272d-cc03-44ac-a3f5-c4f4321a7bec)                          | running | n/a | medium_z1 | 10.11.16.11 |
| nats_z2/0 (7bfdefc8-45df-42bf-a807-ae693add0b71)                          | running | n/a | medium_z2 | 10.11.80.11 |
| router_z1/0 (9684fbf6-3057-4fe3-8398-c6179bcd03a0)                        | running | n/a | router_z1 | 10.11.17.9  |
| router_z2/0 (b5a02967-ca62-49f3-86b1-3697344d1678)                        | running | n/a | router_z2 | 10.11.81.7  |
| runner_z1/0 (ade1acfc-a242-4974-b87d-b172c9fffd72)                        | running | n/a | runner_z1 | 10.11.17.6  |
| runner_z2/0 (a82a047c-8fa0-4cfd-b4f6-1403dc60f4a2)                        | running | n/a | runner_z2 | 10.11.81.4  |
| stats_z1/0 (d4857164-8f9c-45e1-a600-47a5f1b7c9fa)                         | running | n/a | small_z1  | 10.11.17.0  |
| uaa_z1/0 (05f70fa9-cdf2-42ce-a5b8-9d387f9d4fa7)                           | running | n/a | medium_z1 | 10.11.17.1  |
| uaa_z2/0 (6d7614a6-53a3-4e1c-938f-fd3cea3f41ad)                           | running | n/a | medium_z2 | 10.11.81.0  |
+---------------------------------------------------------------------------+---------+-----+-----------+-------------+

**Comment by dsabeti** [comment]
Hey @Senthilannaswamy. It looks like you can resolve `bosh.offshore.mydomain.com`, but can you resolve `sys.offshore.mydomain.com`? If that doesn't resolve, then `api.sys.offshore.mydomain.com` surely won't resolve either. You could also try to deploy without the additional `sys.` -- set your `system_domain` properties in the manifest to `offshore.mydomain.com`, and you'll exclude the `sys.`.

**Comment by Senthilannaswamy** [comment]
HI Dsabeti,

Yes, I'm able to resolve `bosh.offshore.mydomain.com`. 

I've did 
1. `bosh delete deployment`, 
2. updated `cf-stub.xml`, with system_domain without `sys.`. Regenerated the deployment-manifest. 
3. `bosh deploy`

Deployment is successful, but still same issue. 

>[centos@ip-10-11-0-83 deployment]$ nslookup api.offshore.mydomain.com

>Server:         10.11.0.2
Address:        10.11.0.2#53
** server can't find api.offshore.mydomain.com: NXDOMAIN

>[centos@ip-10-11-0-83 deployment]$ nslookup bosh.offshore.mydomain.com

>Server:         10.11.0.2
Address:        10.11.0.2#53
Non-authoritative answer:
Name:   bosh.offshore.mydomain.com
Address: 34.199.50.56

Looks like "nat server configuration" issues, not sure.
Please suggest.
Thanks
Senthil

**Comment by dsabeti** [comment]
Hey @Senthilannaswamy. My question was actually: can you resolve `sys.offshore.mydomain.com`? Either way, your system domain (`sys.offshore.mydomain.com` before you made the change to your cf stub) must resolve to the load balancer for your deployment (ELBs in this case). Also, any subdomains of your system domain (`api.sys.offshore.mydomain.com` for example) should resolve to the load balancer as well.

Your first comment says that you have a CNAME record for `*.offshore.mydomain.com` that maps to your ELB.That's good. Do you also have NS and SOA records for `offshore.mydomain.com`? For `mydomain.com`? I'm pretty sure you'll need all of those DNS entries in order for your CNAME record to take effect.

**Comment by Senthilannaswamy** [comment]
Hi Dsabeti,

I could not resolve the `sys.offshore.mydomain.com`, as you said so is `api.offshore.mydomain.com`.

> [centos@ip-10-11-0-83 cf-release]$ dig sys.offshore.magellancloud.com
; <<>> DiG 9.9.4-RedHat-9.9.4-38.el7_3.2 <<>> sys.offshore.magellancloud.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 51867
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1
;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;sys.offshore.magellancloud.com.        IN      A
;; AUTHORITY SECTION:
magellancloud.com.      60      IN      SOA     ns-1931.awsdns-49.co.uk. awsdns-hostmaster.amazon.com. 1 7200 900 1209600 86400
;; Query time: 36 msec
;; SERVER: 10.11.0.2#53(10.11.0.2)
;; WHEN: Sun Apr 16 16:15:50 UTC 2017
;; MSG SIZE  rcvd: 143

Yes, SOA and NS records are present "public hosted zone" for `mydomain.com`.

Here are my R53 configuration for CF,

> Name|Type|Value
*.offshore.magellancloud.com.|CNAME|cfrouter11-1606644234.us-east-1.elb.amazonaws.com
bat.offshore.magellancloud.com.|A|34.203.114.2
bosh.offshore.magellancloud.com.|A|34.199.50.56
micro.offshore.magellancloud.com.|A|34.198.199.138

 Please let me know what else configuration is missing.

**Comment by Senthilannaswamy** [comment]
Hi Dsabeti,

Looks like issue on our AWS setup, will keep you posted.

Thanks
Senthil

**Comment by Senthilannaswamy** [comment]
Hi  Dsabeti,

The issue was public DNS entry was taking a while to get refresh. Now I'm able to get access.

Thanks
Senthil
