### ISSUE TITLE
Plugin install in CATS run script should be optional

### ISSUE THREAD

**Issue by saliceti** [cloudfoundry/cf-release#1188]
We run CATS from concourse using the same image as [cats-concourse-task](https://github.com/cloudfoundry/cats-concourse-task). This already includes network-policy-plugin.

We start CATS using the cf-release [run script](https://github.com/cloudfoundry/cf-release/blob/master/jobs/acceptance-tests/templates/run.erb).

However, the run script now wants to [install network-policy-plugin](https://github.com/cloudfoundry/cf-release/blob/378994f46128015196f8c0c56f2ddb5979f414f8/jobs/acceptance-tests/templates/run.erb#L22). It fails in our case as we don't keep that package in that path.

Could this be made optional? For example by first testing if it's already installed.

**Comment by dsabeti** [comment]
Hi @saliceti. I want to make sure I understand your use case correctly. Do you run the script from cf-release inside a docker image on Concourse?

**Comment by saliceti** [comment]
Yes, we run [our Concourse task](https://github.com/alphagov/paas-cf/blob/8dc82724ed087738089c844dffe08e3a99e05260/concourse/pipelines/create-cloudfoundry.yml#L1942-L2039) with [this image](https://github.com/alphagov/paas-docker-cloudfoundry-tools/blob/master/cf-acceptance-tests/Dockerfile). It is the same as the [cats-concourse-task](https://github.com/cloudfoundry/cats-concourse-task/blob/master/Dockerfile) image.

The idea was to run CATS as closely as possible as you do, without the burden of using an errand.

**Comment by dsabeti** [comment]
@saliceti, we actually use the [concourse task in that repo](https://github.com/cloudfoundry/cats-concourse-task/blob/master/task) more often than we use the errand. I'd suggest using that task to run CATs instead. Is there a reason for you not to do that?

**Comment by saliceti** [comment]
Thanks @dsabeti I will test it

**Comment by dsabeti** [comment]
Hey @saliceti, any updates on this?

**Comment by saliceti** [comment]
Hi @dsabeti. I've tested with a similar setup as yours and it works fine 👍 
It's much better this way.
