### ISSUE TITLE
 Error 400007: 'consul_z1/0 [...] ' is not running after update. 

### ISSUE THREAD

**Issue by GrahamAka** [cloudfoundry/cf-release#1192]
Trying to deploy v2.57 on bosh-lite hosted through a Vagrant VM on Virtualbox. At the point when actually making the deployment it errors out:

 ```
 Done preparing package compilation > Finding packages to compile (00:00:33)

  Started creating missing vms
  Started creating missing vms > consul_z1/3b9a5b5d-cc1a-4131-a0bc-62976a963f53 (0)
  Started creating missing vms > nats_z1/a7f6ce78-6453-4d95-93f0-4f34fb722676 (0)
  Started creating missing vms > etcd_z1/d84bee20-7bf8-45f7-9c50-304715710051 (0)
  Started creating missing vms > blobstore_z1/9a3c0369-0d62-4fa1-af2e-847b0ae18776 (0)
  Started creating missing vms > postgres_z1/014680dc-a5ba-4d1c-b1e9-2cfcd3190a08 (0)
  Started creating missing vms > uaa_z1/e9d814ba-c108-4623-8a52-0e36169e6eb4 (0)
  Started creating missing vms > api_z1/8631780c-03b9-4886-985b-5624104f17c0 (0)
  Started creating missing vms > hm9000_z1/a78b9036-8235-466d-859c-54777ef729b7 (0)
  Started creating missing vms > runner_z1/e29aa8f6-371e-41ea-bfc1-70b97f0a5cc9 (0)
```
 ```
 Started creating missing vms > doppler_z1/9b11b26f-fb2b-492f-b2cb-c625dacbdf19 (0)
  Started creating missing vms > loggregator_trafficcontroller_z1/c12146ba-56f3-48b2-b170-18edcae86d37 (0)
  Started creating missing vms > router_z1/3e704ce5-49e3-4d8a-8c76-022aace3b04a (0)
  Started creating missing vms > ha_proxy_z1/e8d3f72b-4f16-4006-8809-e3f36f4ed49e (0). Done (00:02:19)
     Done creating missing vms > router_z1/3e704ce5-49e3-4d8a-8c76-022aace3b04a (0) (00:02:20)
     Done creating missing vms > consul_z1/3b9a5b5d-cc1a-4131-a0bc-62976a963f53 (0) (00:02:20)
     Done creating missing vms > etcd_z1/d84bee20-7bf8-45f7-9c50-304715710051 (0) (00:02:20)
     Done creating missing vms > nats_z1/a7f6ce78-6453-4d95-93f0-4f34fb722676 (0) (00:02:20)
     Done creating missing vms > runner_z1/e29aa8f6-371e-41ea-bfc1-70b97f0a5cc9 (0) (00:02:20)
     Done creating missing vms > doppler_z1/9b11b26f-fb2b-492f-b2cb-c625dacbdf19 (0) (00:02:20)
     Done creating missing vms > loggregator_trafficcontroller_z1/c12146ba-56f3-48b2-b170-18edcae86d37 (0) (00:02:20)
     Done creating missing vms > blobstore_z1/9a3c0369-0d62-4fa1-af2e-847b0ae18776 (0) (00:02:20)
     Done creating missing vms > postgres_z1/014680dc-a5ba-4d1c-b1e9-2cfcd3190a08 (0) (00:02:20)
     Done creating missing vms > uaa_z1/e9d814ba-c108-4623-8a52-0e36169e6eb4 (0) (00:02:21)
     Done creating missing vms > hm9000_z1/a78b9036-8235-466d-859c-54777ef729b7 (0) (00:02:21)
     Done creating missing vms > api_z1/8631780c-03b9-4886-985b-5624104f17c0 (0) (00:02:21)
     Done creating missing vms (00:02:21)

  Started updating instance consul_z1 > consul_z1/3b9a5b5d-cc1a-4131-a0bc-62976a963f53 (0) (canary). Failed: 'consul_z1/0 (3b9a5b5d-cc1a-4131-a0bc-62976a963f53)' is not running after update. (00:02:55)

Error 400007: 'consul_z1/0 (3b9a5b5d-cc1a-4131-a0bc-62976a963f53)' is not running after update.
```

Runing the suggested `bosh task 3 --debug` doesn't seem to offer much more detail.

`E, [2017-04-22 23:40:51 #6740] [] ERROR -- DirectorJobRunner: Worker thread rais                                                                                                             ed exception: 'consul_z1/0 (3b9a5b5d-cc1a-4131-a0bc-62976a963f53)' is not runnin                                                                                                             g after update. - /var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-dire                                                                                                             ctor-260.0.0/lib/bosh/director/instance_updater/state_applier.rb:48:in `post_sta                                                                                                             rt'`

**Comment by dsabeti** [comment]
Hey @GrahamAka. Can you provide the logs from the consul job? You can fetch them by running `bosh logs consul_z1 0`.

**Comment by GrahamAka** [comment]
Hi @dsabeti, please find attached. 

[consul_z1.0.2017-04-25-18-03-42.tgz.zip](https://github.com/cloudfoundry/cf-release/files/956087/consul_z1.0.2017-04-25-18-03-42.tgz.zip)

**Comment by dsabeti** [comment]
Hey @GrahamAka. I'm noticing that there aren't and consul logs in there, only metron logs. What's the output of `bosh instances --ps`? Do you see a consul agent actually running on the `consul_z1` job? Could you also provide your manifest **with passwords and private keys redacted?**

**Comment by GrahamAka** [comment]
@dsabeti I think it's failing before it manages to start the consul instance...

vagrant@bosh-lite:~/cf-release$ bosh instances --ps
RSA 1024 bit CA certificates are loaded due to old openssl compatibility
Acting as user 'admin' on deployment 'cf-warden' on 'Bosh Lite Director'

Director task 6

Task 6 done

+----------------------------------------------------------------------------+---------+-----+-----------+--------------+
| Instance                                                                   | State   | AZ  | VM Type   | IPs          |
+----------------------------------------------------------------------------+---------+-----+-----------+--------------+
| api_z1/0 (8631780c-03b9-4886-985b-5624104f17c0)*                           | running | n/a | large_z1  | 10.244.0.138 |
+----------------------------------------------------------------------------+---------+-----+-----------+--------------+
| blobstore_z1/0 (9a3c0369-0d62-4fa1-af2e-847b0ae18776)*                     | running | n/a | medium_z1 | 10.244.0.130 |
+----------------------------------------------------------------------------+---------+-----+-----------+--------------+
| consul_z1/0 (3b9a5b5d-cc1a-4131-a0bc-62976a963f53)*                        | failing | n/a | small_z1  | 10.244.0.54  |
+----------------------------------------------------------------------------+---------+-----+-----------+--------------+
| doppler_z1/0 (9b11b26f-fb2b-492f-b2cb-c625dacbdf19)*                       | running | n/a | medium_z1 | 10.244.0.146 |
+----------------------------------------------------------------------------+---------+-----+-----------+--------------+
| etcd_z1/0 (d84bee20-7bf8-45f7-9c50-304715710051)*                          | running | n/a | large_z1  | 10.244.0.42  |
+----------------------------------------------------------------------------+---------+-----+-----------+--------------+
| ha_proxy_z1/0 (e8d3f72b-4f16-4006-8809-e3f36f4ed49e)*                      | running | n/a | router_z1 | 10.244.0.34  |
+----------------------------------------------------------------------------+---------+-----+-----------+--------------+
| hm9000_z1/0 (a78b9036-8235-466d-859c-54777ef729b7)*                        | running | n/a | medium_z1 | 10.244.0.142 |
+----------------------------------------------------------------------------+---------+-----+-----------+--------------+
| loggregator_trafficcontroller_z1/0 (c12146ba-56f3-48b2-b170-18edcae86d37)* | running | n/a | small_z1  | 10.244.0.150 |
+----------------------------------------------------------------------------+---------+-----+-----------+--------------+
| nats_z1/0 (a7f6ce78-6453-4d95-93f0-4f34fb722676)*                          | running | n/a | medium_z1 | 10.244.0.6   |
+----------------------------------------------------------------------------+---------+-----+-----------+--------------+
| postgres_z1/0 (014680dc-a5ba-4d1c-b1e9-2cfcd3190a08)*                      | running | n/a | medium_z1 | 10.244.0.30  |
+----------------------------------------------------------------------------+---------+-----+-----------+--------------+
| router_z1/0 (3e704ce5-49e3-4d8a-8c76-022aace3b04a)*                        | running | n/a | router_z1 | 10.244.0.22  |
+----------------------------------------------------------------------------+---------+-----+-----------+--------------+
| runner_z1/0 (e29aa8f6-371e-41ea-bfc1-70b97f0a5cc9)*                        | running | n/a | runner_z1 | 10.244.0.26  |
+----------------------------------------------------------------------------+---------+-----+-----------+--------------+
| uaa_z1/0 (e9d814ba-c108-4623-8a52-0e36169e6eb4)*                           | running | n/a | medium_z1 | 10.244.0.134 |
+----------------------------------------------------------------------------+---------+-----+-----------+--------------+

(*) Bootstrap node

Instances total: 13
vagrant@bosh-lite:~/cf-release$

**Comment by GrahamAka** [comment]
@dsabeti , attached is the manifest. This "should" just be a default mainfest from running `scripts/generate-bosh-lite-dev-manifest`

[cf.zip](https://github.com/cloudfoundry/cf-release/files/956308/cf.zip)

**Comment by dsabeti** [comment]
Ok, can you ssh onto the machine (`ssh vcap@ 10.244.0.54` or `bosh ssh consul_z1 0`), and run they following commands:
1. `monit status`
2. `ls -lah /var/vcap/sys/log`. If the consul director is present, let's also look in there: `ls -lah /var/vcap/sys/log/consul_agent`.

Also, did you post the entire output of `bosh task 3 --debug`? If not, could you show the rest of that?

**Comment by GrahamAka** [comment]
If I sudo the bosh ssh command I get a different error:

```
vagrant@bosh-lite:~/cf-release/bosh-lite/deployments$ sudo bosh ssh consul_z1 0
RSA 1024 bit CA certificates are loaded due to old openssl compatibility
Acting as user 'admin' on deployment 'cf-warden' on 'Bosh Lite Director'
Target deployment is 'cf-warden'

Setting up ssh artifacts

Director task 7

Task 7 done
Starting interactive shell on job consul_z1/0
No ECDSA host key is known for 10.244.0.54 and you have requested strict checking.
Host key verification failed.

Cleaning up ssh artifacts

Director task 8

Task 8 queued
vagrant@bosh-lite:~/cf-release/bosh-lite/deployments$

```

**Comment by dsabeti** [comment]
Oh, there's a typo in the command I provided. What you want is `ssh vcap@10.244.0.54`.

The second error has to do with your local ssh config. You need to [disable strict checking](https://askubuntu.com/questions/87449/how-to-disable-strict-host-key-checking-in-ssh).

**Comment by GrahamAka** [comment]
@dsabeti thanks for that, I can get to the login prompt with the ssh vcap@10.244.0.54 command.

But reading https://github.com/cloudfoundry/diego-release/issues/114 suggests that I can't get the password to get past this point.

**Comment by GrahamAka** [comment]
Attached is the debug output for task 3

[task3output.txt](https://github.com/cloudfoundry/cf-release/files/956700/task3output.txt)

**Comment by dsabeti** [comment]
Hey @GrahamAka, I think this is the critical line from the task output:
```
E, [2017-04-22 23:40:51 #6740] [canary_update(consul_z1/3b9a5b5d-cc1a-4131-a0bc-62976a963f53 (0))] ERROR -- DirectorJobRunner: Error updating canary instance: #<Bosh::Director::AgentJobNotRunning: 'consul_z1/0 (3b9a5b5d-cc1a-4131-a0bc-62976a963f53)' is not running after update.>
```

It says that the bosh agent didn't come up successfully. It seems to be an issue with BOSH or bosh-lite. I'd take this error over to the [bosh-lite repo](https://githuib.com/cloudfoundry/bosh-lite) and ask @cppforlife for help.

**Comment by GrahamAka** [comment]
@dsabeti Thanks for your help, I'll do that.

**Comment by dsabeti** [comment]
Hi @GrahamAka. I closed this issue since it looks to be a bosh-lite problem, but feel free to reopen this issue if you need more help.
