### ISSUE TITLE
Typo in the release notes

### ISSUE THREAD

**Issue by Emilius1** [cloudfoundry/cf-release#1193]
CF v257 release says:
Java Buildpack:
java-buildpack v3.15 **(no change**)

Actually in the CF v256 the java-buildpack is v3.14

**Comment by sclevine** [comment]
The Java buildpack version in CF v256 is v3.15.
See: https://github.com/cloudfoundry/cf-release/tree/v256/src 

The release notes for v256 were incorrect, not the release notes for v257. I just fixed this.

**Comment by dsabeti** [comment]
Thanks @Emilius1 for noticing this, and @sclevine for the correction.

**Comment by Emilius1** [comment]
Sorry, the issue was for CF release v270.
"Java Buildpack:
java-buildpack **vRR**"

**Comment by dsabeti** [comment]
Hi @Emilius1, I've updated the release notes to reflect the correct java buildpack version.
