### ISSUE TITLE
See only instances ?/1 after pushing an app

### ISSUE THREAD

**Issue by StBurcher** [cloudfoundry/cf-release#1195]
Hi @ all

I have an interesting error.  After pushing successfully an app, cf apps shows me instances ?/1, but the app is working,

```
C:\cf apps
Getting apps in org admin / space support as admin...
OK

name                      requested state   instances   memory   disk   urls
Brooklyn-Service-Broker   started           ?/1         1G       1G     brooklyn-service-broker.de.cloudlab.com
speller                   started           ?/1         1G       1G     speller.de.cloudlab.com
```

If I calling cf app speller, I can see instances 1/1
```
C:\cf app speller
Showing health and status for app speller in org admin / space support as admin...

name:              speller
requested state:   started
instances:         1/1
usage:             1G x 1 instances
routes:            speller.de.cloudlab.com
last uploaded:     Thu 27 Apr 12:44:28 CEST 2017
stack:             cflinuxfs2
buildpack:         php 4.3.30

     state     since                  cpu    memory        disk           details
#0   running   2017-04-27T10:44:58Z   0.4%   81.9M of 1G   163.9M of 1G
```

I can restart or restage the app, no change.

Any ideas?

It starts after the update form CF 250 to CF258.
Cf is installed on OpenStack.

**Comment by StBurcher** [comment]
Short update. With Diego apps it works fine

**Comment by dsabeti** [comment]
@StBurcher, I was going to come in here and say that the issue probably has to do with the DEAs and/or HM9000 -- both of which are deprecated and will no longer be supported after May 22. I'd suggest shutting off the DEAs and HM9000 in favor of Diego.

**Comment by StBurcher** [comment]
@dsabeti Thank you for the response. How can I deactivate both components?  Only by setting number of instances to 0 or can I remove the template too?

**Comment by dsabeti** [comment]
@StBurcher You can just set the instance count to 0

**Comment by StBurcher** [comment]
@dsabeti 
Thank you. Migration done. 
Additional Question. I have set instance count to 0 in the manifest. But, is there a way to set it in the stub?

**Comment by dsabeti** [comment]
Hey @StBurcher. Absolutely, you can pretty much just put the following in your stub:
```yml
jobs:
- name: runner_z1
  instances: 0
- name: runner_z2
  instances: 0
- name: hm9000_z1
  instances: 0
- name: hm9000_z2
  instances: 0
```
