### ISSUE TITLE
Error 100: Unable to render instance groups for deployment. Errors are

### ISSUE THREAD

**Issue by deepakdefender264** [cloudfoundry/cf-release#1198]
We are deploying cloud foundry on vsphere environment but its getting failed on deploying cloud foundry step $ bosh deploy
Ref link: https://docs.cloudfoundry.org/deploying/vsphere/index.html

Deploying
---------

Director task 17
Deprecation: Ignoring cloud config. Manifest contains 'networks' section.

  Started preparing deployment > Preparing deployment. Done (00:00:00)

Error 100: Unable to render instance groups for deployment. Errors are:
  - Unable to render jobs for instance group 'uaa_z1'. Errors are:
    - Unable to render templates for job 'uaa'. Errors are:
      - Error filling in template 'login.yml.erb' (line 202: Missing properties:\nlogin.saml.serviceProviderCertificate)
  - Unable to render jobs for instance group 'uaa_z2'. Errors are:
    - Unable to render templates for job 'uaa'. Errors are:
      - Error filling in template 'login.yml.erb' (line 202: Missing properties:\nlogin.saml.serviceProviderCertificate)

Task 17 error

**Comment by deepakdefender264** [comment]
Uploading cf-stub.txt and cf-deployment.txt files for review.

[cf-deployment.txt](https://github.com/cloudfoundry/cf-release/files/970698/cf-deployment.txt)
[cf-stub.txt](https://github.com/cloudfoundry/cf-release/files/970699/cf-stub.txt)

**Comment by dsabeti** [comment]
Hi @deepakdefender264. These docs are out of date, so thanks for bringing this to our attention. If you search for `serviceProviderCertificate` in [these docs (for deploying to Azure)](https://docs.cloudfoundry.org/deploying/azure/cf-stub.html), you'll find an explanation for the property that you need to add to your manifest. Don't worry: the value for the property isn't affected by the IaaS you're deploying to, so this section of the docs still apply to vSphere deployments.

**Comment by dsabeti** [comment]
I also opened up a github issue on the docs repo: https://github.com/cloudfoundry/docs-deploying-cf/issues/166

**Comment by deepakdefender264** [comment]
Thanks @dsabeti to highlight it. I have created saml certificate from Azure docs and will wait for updated vSphere docs for cloud foundry

**Comment by dsabeti** [comment]
Great! If everything is working for you, is it ok if I close the issue?

**Comment by deepakdefender264** [comment]
@dsabeti I have tried to deploy CloudFoundry on vSphere but its getting failed with below errors. I tried cf-release and latest ubuntu stem cell. I am not sure what's causing this. Is there any specific release number and stem cell version which works fine on vSphere ?
[cf-stub.txt](https://github.com/cloudfoundry/cf-release/files/981502/cf-stub.txt)
[bosh.txt](https://github.com/cloudfoundry/cf-release/files/981504/bosh.txt)
[cf-deployment.txt](https://github.com/cloudfoundry/cf-release/files/981503/cf-deployment.txt)
![error](https://cloud.githubusercontent.com/assets/22387902/25779864/cd46e142-333d-11e7-9145-b9e3e05fd9a2.jpg)

**Comment by dsabeti** [comment]
We test each stemcell and cf-release version on vSphere, so I doubt that it's a compatibility problem. The error message also suggests that the BOSH Director can't reach your compilation VMs. You should double-check that your firewall rules allow network traffic between your BOSH director and the IP addresses assigned to the compilation VMs. As I skimmed your deployment manifest, I saw that the network assigned to your compilation VMs is `cf1`, which has IP range 192.168.0.1 - 192.168.0.200 -- do your firewall rules allow traffic between the director's IP and the subnet for `cf1`?

**Comment by siddheshwar-more** [comment]
@dsabeti - We have disabled the firewall for esxi host `esxcli network firewall set --enabled false`. But still getting same error.

**Comment by jleavers** [comment]
@siddheshwar-more That would typically relate to the ESXi host's management interface - not traffic going between VMs.

You may have an IP address typo in your bosh manifest:

```
agent: {mbus: "nats://nats:cloud123@192.168.0.24333:4222"}
```

**Comment by dsabeti** [comment]
Great catch, @jleavers! That would definitely cause this error message.

**Comment by deepakdefender264** [comment]
Hi @dsabeti and @jleavers We have redeployed it in new envrionment having no firewall and without network issues. Now its again failing on deploy command but at a later step. It has created around 28 vms but many are unresponsive. Here are the errors:

[2017-05-10 17:48:43 #7699] [] ERROR -- DirectorJobRunner: Worker thread raised exception: Action Failed get_task: Task with id d79bd1a6-2e2d-472d-67df-fa8f67345093 could not be found - /var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-261.4.0/lib/bosh/director/agent_client.rb:271:in `handle_method'

[2017-05-10 17:50:13 #7699] [] ERROR -- DirectorJobRunner: Worker thread raised exception: Timed out sending 'get_task' to f3d84adf-2a8e-4e63-ad6a-6c9e3207b3ec after 45 seconds - /var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-261.4.0/lib/bosh/director/agent_client.rb:262:in `block in handle_method'
/var/vcap/packages/ruby/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'

[2017-05-10 17:50:13 #7699] [task:59] ERROR -- DirectorJobRunner: Action Failed get_task: Task with id d79bd1a6-2e2d-472d-67df-fa8f67345093 could not be found

Now we are using release 258 and bosh v2 cli as well and bosh-director v261.4.0.
bosh -e bosh-1 upload-stemcell bosh-stemcell-3363.20-vsphere-esxi-ubuntu-trusty-go_agent.tgz
bosh create-release --force
bosh -e bosh-1 upload-release releases/cf-258.yml
Edited cf-release number in the cf-deployment.yml
releases:
- name: cf
  version: 258
bosh -e bosh-1 -d cf-vsphere deploy cf-deployment.yml
Logs files -
https://drive.google.com/file/d/0Bzmv935wSr_4dmR0SUtlNDBIRk0/view?usp=sharing
https://drive.google.com/file/d/0Bzmv935wSr_4Qlp6VldJaE91OVU/view?usp=sharing
[cf-deployment.txt](https://github.com/cloudfoundry/cf-release/files/990822/cf-deployment.txt)
[cf-stub.txt](https://github.com/cloudfoundry/cf-release/files/990823/cf-stub.txt)

**Comment by dsabeti** [comment]
@deepakdefender264 Did you see @jleavers's comment? It looks like you have an invalid IP address in your _bosh_ configuration. In general, this looks to be a bosh (rather than CF) issue, so you may want to ask for help by opening an issue in [the bosh repo](https://github.com/cloudfoundry/bosh).

**Comment by deepakdefender264** [comment]
@dsabeti yeah I checked that, that was a typo which was corrected. 
Btw, cf is finally deployed to vsphere. Issues was due to ip conflicts, certs, stemcell issue due to ipv6. Thanks for all your help. :)
