### ISSUE TITLE
Not Access endpoint https://api.local.pfcdev.io   info:Gateway Timeout

### ISSUE THREAD

**Issue by tiagojazz** [cloudfoundry/cf-release#1203]
Você quis dizer: Não consigo logar no PFC Client pois aparece a msg acima
I can not log into PFCClient because the above msg appears! Can someone help me?

**Comment by dsabeti** [comment]
Hi @tiagojazz. This repo is for issues regarding open source Cloud Foundry. For PCF questions, you should reach out to PCF support: support.pivotal.io

**Comment by dsabeti** [comment]
Hi @tiagojazz, I'm going to close this issue due to inactivity, but if you have questions about open source Cloud Foundry, feel free to re-open this issue.
