### ISSUE TITLE
How can i get exception's error code and message? 

### ISSUE THREAD

**Issue by liuxg123** [cloudfoundry/cf-release#1208]
I want to get all of exception's error code,have any document?
Like HTTP Status Code.

**Comment by rboykin** [comment]
Does this help:  https://github.com/cloudfoundry/cloud_controller_ng/blob/master/vendor/errors/v2.yml

**Comment by dsabeti** [comment]
Thanks @rboykin. That's exactly the artifact I was going to point him to.

Does that help @liuxg123?

**Comment by dsabeti** [comment]
I'm going to close this issue due to inactivity, but feel free to re-open it if you need more help.
