### ISSUE TITLE
bosh -d wl-bosh deploy cf-deployment.yml is failing

### ISSUE THREAD

**Issue by dgadiraju** [cloudfoundry/cf-release#1210]
I am able to create and upload release using cf-262.yml
But when I run bosh -d wl-bosh deploy cf-deployment.yml, I am getting following warning and error.

11:55:13 | Deprecation: Ignoring cloud config. Manifest contains 'networks' section.
11:55:13 | Preparing deployment: Preparing deployment (00:00:00)
            L Error: Job 'consul_agent' not found in Template table

11:55:13 | Error: Job 'consul_agent' not found in Template table

Started  Mon Jun 12 11:55:13 UTC 2017
Finished Mon Jun 12 11:55:13 UTC 2017
Duration 00:00:00

Task 68 error

Updating deployment:
  Expected task '68' to succeed but was state is 'error'

Exit code 1

**Comment by dsabeti** [comment]
@dgadiraju It looks like you're using the new (golang) BOSH CLI, or the older (Ruby) one -- is that right? If so, can you try with the old CLI?

**Comment by dsabeti** [comment]
Hi @dgadiraju. I'm going to close the issue due to inactivity, but feel free to open it again if you need more help.
