### ISSUE TITLE
L Error: incompatible character encodings: UTF-8 and US-ASCII

### ISSUE THREAD

**Issue by bxlkm** [cloudfoundry/cf-release#1211]
15:31:01 | Deprecation: Ignoring cloud config. Manifest contains 'networks' section.
15:31:01 | Preparing deployment: Preparing deployment (00:00:01)
15:31:07 | Preparing package compilation: Finding packages to compile (00:00:00)
15:31:07 | Creating missing vms: clock_z2/0f6c6fdb-a8a7-4502-82fa-2d5e5f074fad (0) (00:00:03)
            L Error: incompatible character encodings: UTF-8 and US-ASCII

15:31:10 | Error: incompatible character encodings: UTF-8 and US-ASCII

cf-259  stemcell-3312.28

**Comment by dsabeti** [comment]
Hi @bxlkm. This looks like an issue with the CC Clock, so I'm going to loop in the CAPI team, who maintains the component.

@zrob @Gerg, could someone from CAPI help debug this issue?

**Comment by Gerg** [comment]
@bxlkm @dsabeti It looks like the clock is the first vm being deployed. From the output (and the speed at which it failed), my guess is this is a Bosh error. It appears that `incompatible character encodings` is a Ruby error.

**Comment by dsabeti** [comment]
@cppforlife, any thoughts on this issue?

**Comment by dsabeti** [comment]
@bxlkm, can we get the debug output for the task? You just need to run `bosh task <TASK_ID> --debug`, and upload the logs. The BOSH team will try to help.

**Comment by dpb587-pivotal** [comment]
@bxlkm, specifically we're interested in the stacktrace which should be near the end if you could provide just that section. At this point we probably don't need the entire debug log (it may contain sensitive credentials, which would need to be carefully redacted).

**Comment by cppforlife** [comment]
bosh team only really needs the stacktraces from the debug log so no need to include full log.

**Comment by bxlkm** [comment]
Reference to this link problem has been resolved, ths！
https://github.com/cloudfoundry/cf-release/pull/1181

**Comment by dsabeti** [comment]
Ok, sounds good. I'll close this issue out, then.
