### ISSUE TITLE
Add support for connecting to CC DB over TLS

### ISSUE THREAD

**Issue by jmprice** [cloudfoundry/cf-release#1212]
We have a few environments which have strict security policies in place which only allow secure database connections regardless of the data classification or even if the data itself is encrypted.

A recent commit for the UAA release has enabled TLS connections for the UAA DB.
https://www.pivotaltracker.com/n/projects/997278/stories/145563953

Jon Price
Intel Corp

**Comment by dsabeti** [comment]
Hi @jmprice, this seems like a reasonable feature to me, but that conversation would need to happen with the CAPI team, who maintains the Cloud Controller codebase. Your best bet is to open an issue on [the Cloud Controller](https://github.com/cloudfoundry/cloud_controller_ng), and ask for the feature there.

**Comment by jmprice** [comment]
I have resubmitted this in the CC repo.  Thanks for directing me to the appropriate place. :)
