### ISSUE TITLE
cf-v261 dea push app custom port issue

### ISSUE THREAD

**Issue by bxlkm** [cloudfoundry/cf-release#1216]
E:\IAAS\centos7-openstack-newton\PivotalMySQLWeb>cf map-route pivotal-mysqlweb p
eracloud.com --random-port

fail
The app is running on the DEA backend, which does not support this command.

**Comment by dsabeti** [comment]
Hi @bxlkm. The DEAs have been deprecated for some time, and we officially [ended support for the DEAs back in May](https://github.com/cloudfoundry/cf-release/releases/tag/v262). The first thing you'll need to do is deploy [Diego](https://github.com/cloudfoundry/diego-release) and move your app to the Diego backend. There are instructions in that repo for how to deploy it.

**Comment by dsabeti** [comment]
Hi @bxlkm. I'm going to close this issue due to inactivity. Let's use [your other Github issue](https://github.com/cloudfoundry/cf-release/issues/1220) to discuss deploying Diego.
