### ISSUE TITLE
How cell works?

### ISSUE THREAD

**Issue by rahul221192** [cloudfoundry/cf-release#1218]
Its a question:

If i takes backup (snapshot  in case of aws) of cell there with some app container  and try to reattach or restore that backup(or snapshot) to freshly created cell.
1.What happens to those existing container?
2.Do cloud foundry uses already existing container present in  the  backup(snapshot) or re-push the applications using the data of blobstore?
If cloudfoundry don't use existing conatiner
3.is there is some way to use those container from snapshot. 
 
Thanks  and regards
Rahul Kumar

**Comment by dsabeti** [comment]
Hi @rahul221192. I don't think anyone has ever bothered to take snapshots of the cells, as they're meant to be ephemeral. More specifically, other components in Diego will make sure that apps get restarted on other cells if one of the cell VMs gets deleted.

What problem are you trying to solve with these snapshots?

cc @ematpl @jvshahid

**Comment by rahul221192** [comment]
I encountered  scenario in which if  we have only two cells  and if one cell goes down and other cell is running out of memory,how cf is going to handle that?
For the time till bosh recreates  those cell what will Happens to those apps?
Whether apps or going to crash ?

**Comment by ronakbanka** [comment]
@rahul221192 Yes, in absence of enough runners(Diego cells), Diego won't be able to start those apps.

**Comment by rahul221192** [comment]
@ronakbanka  can we  somehow use  the containers  in snapshots by reattaching (snapshots ) to new cell? 
Or those containers are just garbage?

**Comment by dsabeti** [comment]
@rahul221192, if you're waiting for a new cell to be available, you can just wait for Diego to restart the apps on the new cell. It will do that automatically. @ematpl can correct me if I'm wrong, but app instances (i.e. containers) are definitely meant to be disposable: you can let them expire, and Diego will restart the app instances on cells where there's space.

**Comment by rahul221192** [comment]
@dsabeti @ronakbanka  i think my doubts are clear now .
thank you very much for answers .@dsabeti @ronakbanka 

Greeting 
Rahul 😀

**Comment by dsabeti** [comment]
Happy to help. I'll close the issue, but feel free to re-open it if you have more questions.
