### ISSUE TITLE
Issue with jwt cert creation (doc issue?)

### ISSUE THREAD

**Issue by cwb124** [cloudfoundry/cf-release#1222]
Hey folks,

Taking my first crack at this whole OS CF thing and I'm currently going through editing my manifest for a vsphere deployments.  I am generating and using certs along the way.  I am currently stuck at the jwt cert creation and I think there's an issue with the docs.  Here's the section I'm hung up on:

`Generate a PEM-encoded RSA key pair, and replace JWT_SIGNING_KEY with the private key, and JWT_VERIFICATION_KEY with the corresponding public key. Generate a key pair by running the command openssl rsa -in jwt-key.pem -pubout > key.pub. This command creates jwt-key.pem.pub, which contains your public key, and jwt-key.pem, which contains your private key.
Copy in the full keys, including the BEGIN and END delimiter lines.`

It is saying to use a jwt-key.pem file as an input to the openssl rsa command, but the jwt-key.pem doesn't exist until the command creates the pub file.  So what am I supposed to do here?

**Comment by dsabeti** [comment]
Hey @cwb124. Thanks for raising this issue. Try run the following before the command given in the docs:
```
openssl genrsa -out private.pem 2048
```
If that works, I'll make sure we update the docs to include this information.

**Comment by cwb124** [comment]
That seemed to work.  Wasn't sure if there was a file I was missing or what.  Thanks for the quick response.

**Comment by dsabeti** [comment]
Yeah, it looks like an issue with the docs. Actually, if you check more up-to-date docs, you can see that it has that necessary first step: http://docs.cloudfoundry.org/deploying/azure/cf-stub.html#editing-instructions

I'll submit a fix to the docs team.

**Comment by cwb124** [comment]
Yeah looks like it's correct in the Azure doc but not vsphere section.  I can submit a pull request.  Either way.  Thanks!

**Comment by dsabeti** [comment]
Beat you to it: https://github.com/cloudfoundry/docs-deploying-cf/pull/174

**Comment by dsabeti** [comment]
@cwb124, I'm going to close the issue since the PR has been merged. Let me know if you have any other questions or thoughts on the docs.
