### ISSUE TITLE
Error when deploy cf to bosh-lite

### ISSUE THREAD

**Issue by qibobo** [cloudfoundry/cf-release#1223]
I follow the document http://docs.cloudfoundry.org/deploying/common/deploy.html step by step. In the "bosh deploy" step, always get the following error:
```
Started preparing deployment > Preparing deployment. Done (00:00:01)

  Started preparing package compilation > Finding packages to compile. Done (00:00:00)

  Started updating job uaa_z1 > uaa_z1/0 (41893907-d012-49ae-bb1e-6b2c4971be59) (canary)
  Started updating job blobstore_z1 > blobstore_z1/0 (fc2a659c-fc98-40aa-a342-94f8c89b9647) (canary)
  Started updating job api_z1 > api_z1/0 (57ad3457-143e-450e-9d86-2547a30b516d) (canary)
  Started updating job doppler_z1 > doppler_z1/0 (33ac672d-0689-44da-9191-46b3dd382134) (canary)
   Failed updating job api_z1 > api_z1/0 (57ad3457-143e-450e-9d86-2547a30b516d) (canary): `api_z1/0 (57ad3457-143e-450e-9d86-2547a30b516d)' is not running after update. Review logs for failed jobs: route_registrar (00:03:35)
   Failed updating job uaa_z1 > uaa_z1/0 (41893907-d012-49ae-bb1e-6b2c4971be59) (canary): `uaa_z1/0 (41893907-d012-49ae-bb1e-6b2c4971be59)' is not running after update. Review logs for failed jobs: route_registrar (00:03:40)
   Failed updating job doppler_z1 > doppler_z1/0 (33ac672d-0689-44da-9191-46b3dd382134) (canary): `doppler_z1/0 (33ac672d-0689-44da-9191-46b3dd382134)' is not running after update. Review logs for failed jobs: doppler (00:03:41)
   Failed updating job blobstore_z1 > blobstore_z1/0 (fc2a659c-fc98-40aa-a342-94f8c89b9647) (canary): `blobstore_z1/0 (fc2a659c-fc98-40aa-a342-94f8c89b9647)' is not running after update. Review logs for failed jobs: route_registrar (00:03:42)

Error 400007: `api_z1/0 (57ad3457-143e-450e-9d86-2547a30b516d)' is not running after update. Review logs for failed jobs: route_registrar
```

**Comment by dsabeti** [comment]
Hi @qibobo, it looks like the route_registrar is failing on a bunch of jobs. Your best bet is to download the logs from one of the jobs where it's failing. For exampe:
```
bosh logs api_z1
```
After unzipping the resulting file, you should see a directory called `router_registrar` that has the logs for that job. Take a look in there for more information.

Even without the logs, it's probably likely that the route_registrar is failing to find the NATS cluster. Could you show me the output of `bosh instances --ps`?

**Comment by qibobo** [comment]
I got the api_z1's log and there are 6 files in the route_registrar path and only 2 files are not emtpy:
**route_registrar.err.log**:
[2017-07-21 03:18:38+0000] 2017/07/21 03:18:38 there was 1 error with 'config':
[2017-07-21 03:18:38+0000] * host required
**route_registrar.log**:
[2017-07-21 03:18:38+0000] {"timestamp":"1500607118.531047344","source":"Route Registrar","message":"Route Registrar.Initializing","log_level":1,"data":{}}

And the result of bosh instances --ps Acting as user 'admin' on deployment 'cf-warden' on 'Bosh Lite Director'

Director task 34

Task 34 done

+----------------------------------------------------------------------------+---------+-----+-----------+--------------+
| Instance                                                                   | State   | AZ  | VM Type   | IPs          |
+----------------------------------------------------------------------------+---------+-----+-----------+--------------+
| api_z1/0 (57ad3457-143e-450e-9d86-2547a30b516d)*                           | **failing** | n/a | large_z1  | 10.244.0.138 |
|   consul_agent                                                             | running |     |           |              |
|   cloud_controller_ng                                                      | running |     |           |              |
|   cloud_controller_worker_local_1                                          | running |     |           |              |
|   cloud_controller_worker_local_2                                          | running |     |           |              |
|   nginx_cc                                                                 | running |     |           |              |
|   cloud_controller_clock                                                   | running |     |           |              |
|   cloud_controller_worker_1                                                | running |     |           |              |
|   metron_agent                                                             | running |     |           |              |
|   statsd_injector                                                          | running |     |           |              |
|   route_registrar                                                          | **unknown** |     |           |              |
+----------------------------------------------------------------------------+---------+-----+-----------+--------------+
| blobstore_z1/0 (fc2a659c-fc98-40aa-a342-94f8c89b9647)*                     | **failing** | n/a | medium_z1 | 10.244.0.130 |
|   consul_agent                                                             | running |     |           |              |
|   metron_agent                                                             | running |     |           |              |
|   blobstore_nginx                                                          | running |     |           |              |
|   blobstore_url_signer                                                     | running |     |           |              |
|   route_registrar                                                          | **unknown** |     |           |              |
+----------------------------------------------------------------------------+---------+-----+-----------+--------------+
| consul_z1/0 (6220d464-af51-478a-9df9-d910ddef204d)*                        | running | n/a | small_z1  | 10.244.0.54  |
|   consul_agent                                                             | running |     |           |              |
|   metron_agent                                                             | running |     |           |              |
+----------------------------------------------------------------------------+---------+-----+-----------+--------------+
| doppler_z1/0 (33ac672d-0689-44da-9191-46b3dd382134)*                       | **failing** | n/a | medium_z1 | 10.244.0.142 |
|   consul_agent                                                             | running |     |           |              |
|   doppler                                                                  | **failing** |     |           |              |
|   syslog_drain_binder                                                      | running |     |           |              |
|   metron_agent                                                             | running |     |           |              |
+----------------------------------------------------------------------------+---------+-----+-----------+--------------+
| etcd_z1/0 (cf4eb2ff-f5d6-41df-8580-1b8e87c2a2f8)*                          | running | n/a | large_z1  | 10.244.0.42  |
|   consul_agent                                                             | running |     |           |              |
|   etcd                                                                     | running |     |           |              |
|   etcd_consistency_checker                                                 | running |     |           |              |
|   etcd_metrics_server                                                      | running |     |           |              |
|   metron_agent                                                             | running |     |           |              |
+----------------------------------------------------------------------------+---------+-----+-----------+--------------+
| ha_proxy_z1/0 (b3fd9d33-45fa-4ce1-a164-4f8f053e31e1)*                      | running | n/a | router_z1 | 10.244.0.34  |
+----------------------------------------------------------------------------+---------+-----+-----------+--------------+
| loggregator_trafficcontroller_z1/0 (4428d972-e26e-4969-87ed-99a7c01d63b9)* | running | n/a | small_z1  | 10.244.0.146 |
+----------------------------------------------------------------------------+---------+-----+-----------+--------------+
| nats_z1/0 (d904169a-0dfd-4a07-8cc1-8e9f6cad0b80)*                          | running | n/a | medium_z1 | 10.244.0.6   |
|   consul_agent                                                             | running |     |           |              |
|   nats                                                                     | running |     |           |              |
|   metron_agent                                                             | running |     |           |              |
+----------------------------------------------------------------------------+---------+-----+-----------+--------------+
| postgres_z1/0 (41be1626-3198-47fa-b735-02992686a888)*                      | running | n/a | medium_z1 | 10.244.0.30  |
|   consul_agent                                                             | running |     |           |              |
|   postgres                                                                 | running |     |           |              |
|   metron_agent                                                             | running |     |           |              |
+----------------------------------------------------------------------------+---------+-----+-----------+--------------+
| router_z1/0 (fe5047b4-c946-45fb-9d33-4bf240205bce)*                        | running | n/a | router_z1 | 10.244.0.22  |
+----------------------------------------------------------------------------+---------+-----+-----------+--------------+
| uaa_z1/0 (41893907-d012-49ae-bb1e-6b2c4971be59)*                           | **failing** | n/a | medium_z1 | 10.244.0.134 |
|   consul_agent                                                             | running |     |           |              |
|   uaa                                                                      | running |     |           |              |
|   metron_agent                                                             | running |     |           |              |
|   route_registrar                                                          | **failing** |     |           |              |
|   statsd_injector                                                          | running |     |           |              |
+----------------------------------------------------------------------------+---------+-----+-----------+--------------+

(*) Bootstrap node

Instances total: 11

**Comment by dsabeti** [comment]
So, the nats job looks fine, and the error message suggests a different problem:
> [2017-07-21 03:18:38+0000] 2017/07/21 03:18:38 there was 1 error with 'config':
[2017-07-21 03:18:38+0000] * host required

It implies that there's something wrong with the route_registrar's configuration. Can you ssh on to one of the VMs and look at the rendered templates? Do that, you'll need to run `bosh ssh api_z1/57ad3457-143e-450e-9d86-2547a30b516d` -- don't forget to add the ssh key that you used when you created your bosh director -- and then look at the contents of `/var/vcap/jobs/route_registrar/config/registrar_settings.yml`.  What is the value of the **top level** `host` key?

**Comment by qibobo** [comment]
@dsabeti  back to cf-release v265 and everything is ok now.
