### ISSUE TITLE
jobs/java-offline-buildpack points to non-existing file

### ISSUE THREAD

**Issue by andrew-edgar** [cloudfoundry/cf-release#1224]
I checked out the v268 from cf-release.  Then I ran 

bosh2 create-release

This failed with the following error ...

Building a release from directory '/Users/aedgar/workspace/cf-release':
  - Constructing jobs from manifest:
      - Reading job from '/Users/aedgar/workspace/cf-release/jobs/java-offline-buildpack':
          stat /Users/aedgar/workspace/cf-release/jobs/java-offline-buildpack: no such file or directory

Exit code 1

I looked and the java-offline-buildpack is a symbolic link to ../src/java-offline-buildpack-release/jobs/java-offline-buildpack.

But src/java-offline-buildpack-release does NOT exist in the v268 build.   The symbolic link in jobs needs to be removed and the v268 tag needs fixing.

**Comment by dsabeti** [comment]
Hey @andrew-edgar. Thanks for opening this issue. The java-offline-buildpack was indeed removed from cf-release, but looks like we failed to remove some of the dangling references. We'll take them out.

In the meantime, if you're not making any local modifications to your release, you should be able to upload CF 268 to your bosh director by uploading via the _release manifest_:
```
bosh2 upload-release releases/cf/cf-268.yml
```

**Comment by andrew-edgar** [comment]
@dsabeti   we are making local modifications which is why we need the bosh2 create-release to work.   I updated the bosh2 cli to the latest and got even more errors 

bosh2 create-release
Building a release from directory '/Users/aedgar/workspace/cf-release':
  - Constructing jobs from manifest:
      - Reading job from '/Users/aedgar/workspace/cf-release/jobs/cloud_controller_clock':
          Fingerprinting source files:
            Fingerprinting file '/Users/aedgar/workspace/cf-release/jobs/cloud_controller_clock/templates/newrelic.yml.erb':
              lstat /Users/aedgar/workspace/cf-release/src/capi-release/shared_job_templates: no such file or directory
      - Reading job from '/Users/aedgar/workspace/cf-release/jobs/cloud_controller_ng':
          Fingerprinting source files:
            Fingerprinting file '/Users/aedgar/workspace/cf-release/jobs/cloud_controller_ng/templates/blobstore_waiter.sh.erb':
              lstat /Users/aedgar/workspace/cf-release/src/capi-release/shared_job_templates: no such file or directory
      - Reading job from '/Users/aedgar/workspace/cf-release/jobs/cloud_controller_worker':
          Fingerprinting source files:
            Fingerprinting file '/Users/aedgar/workspace/cf-release/jobs/cloud_controller_worker/templates/blobstore_waiter.sh.erb':
              lstat /Users/aedgar/workspace/cf-release/src/capi-release/shared_job_templates: no such file or directory
      - Reading job from '/Users/aedgar/workspace/cf-release/jobs/java-offline-buildpack':
          stat /Users/aedgar/workspace/cf-release/jobs/java-offline-buildpack: no such file or directory

Exit code 1
aedgar1macbook:~/workspace/cf-release ((v268))$

Looks like the bosh2 cli does not correctly traverse all the symbolic links in cf-release to capi-release.   Can you validate this and see why the bosh2 cli cannot create-release in cf-release.

The errors above about /Users/aedgar/workspace/cf-release/src/capi-release/shared_job_templates is interesting because the newrelic.yml.erb is a symbolic link to "../../../shared_job_tempaltes/newrelic.yml.erb"  but this is not working as 
cf-release/src/capi-release/jobs/cloud_controller_clock" is a symbolic link to "../src/cloud_controller_ng/bosh/jobs/cloud_controller_clock"

So when traversing the second symbolic link it's using the actual path not the path relative to the first symbolic link.   Definitely a bug in bosh2 cli or cf-release or capi-release having all these relative symbolic links.

Thanks!

Andrew

**Comment by dsabeti** [comment]
@andrew-edgar We've seen different versions of this issue before. You're right that the issue are the symlinks in cf-release. It was my understanding that the BOSH team was trying to add symlink support to the CLI. In the meantime, you'll need to use the old ruby CLI if you want to create a local release.

@cppforlife, is there a bug in the BOSH tracker to address this?

**Comment by dsabeti** [comment]
@andrew-edgar. As I noted in the other Github issue, I've added documentation to describe the problem of using the new bosh CLI to `create-release`. Also, we've removed the dangling symlink. Is there anything else to think about, or should we close the issue?

**Comment by andrew-edgar** [comment]
@dsabeti No that should be good.  thanks!

Andrew

**Comment by parthasarathi204** [comment]
does this work ?  getting error while create-release
Building a release from directory '/home/custom/cf-release':
  - Constructing jobs from manifest:
      - Reading job from '/home/custom/cf-release/jobs/cloud_controller_clock':
          stat /home/custom/cf-release/jobs/cloud_controller_clock: no such file or directory

Exit code 1

**Comment by dsabeti** [comment]
@parthasarathi204, I think the BOSH team has decided not to implement the full support of symlinks necessary to work with cf-release. As such, you'll need to use the Ruby CLI to run `bosh create release`, and then you can use the Go CLI for the subsequent operations.

**Comment by parthasarathi204** [comment]
Any way I was doing the same staff  , but did not work .
bosh1 create release --force && bosh1 upload release && bosh1 -n deploy --recreate
Then with out any change i have used 
bosh  create-release  --tarball dev_releases/cf/cf-release.tgz --force
bosh -e vbox upload-release dev_releases/cf/cf-release.tgz

retried the above steps once more. Gives same error
           L Error: Missing template file 'newrelic.yml.erb' for job 'cloud_controller_clock'

15:25:17 | Error: Missing template file 'newrelic.yml.erb' for job 'cloud_controller_clock'

Started  Tue Aug 22 15:25:17 UTC 2017
Finished Tue Aug 22 15:25:17 UTC 2017
Duration 00:00:00

Task 26 error

Uploading release file:
  Expected task '26' to succeed but state is 'error'

Exit code 1

**Comment by dsabeti** [comment]
You have to use the old CLI for "create release", and the _new_ CLI for "upload release":
```
bosh1 create release --force --tarball ...
bosh2 -e vbox upload-release ...
```

**Comment by parthasarathi204** [comment]
Okay but I could not do  that as I am trying to use a new blobstore_client 'foo'. If I provide the credential details in config/private.yml and config/final.yml as per http://bosh.io/docs/reference/blobs.html , bosh1 commands refuse to work . Errors out as 
Cannot initialize blobstore: Unknown client provider 'foo', available providers are: ["dav", "simple", "s3", "local", "s3cli"]
Though I have added the new 'foo' cli  in bosh (https://github.com/cloudfoundry/bosh/blob/master/src/bosh-director/lib/bosh/blobstore_client/client.rb) . 

diff --git a/src/bosh-director/lib/bosh/blobstore_client/client.rb b/src/bosh-director/lib/bosh/blobstore_client/client.rb
index 4b26411..45c18da 100644
--- a/src/bosh-director/lib/bosh/blobstore_client/client.rb
+++ b/src/bosh-director/lib/bosh/blobstore_client/client.rb
@@ -1,13 +1,13 @@
` module Bosh `
 `  module Blobstore`
`     class Client`
`-      PROVIDER_NAMES = %w[local s3cli gcscli davcli]`
`+     PROVIDER_NAMES = %w[local foocli s3cli gcscli davcli] `


Am I missing something ?

**Comment by dsabeti** [comment]
@parthasarathi204, I think you're facing a different issue than the original issue here about compatibility between BOSH CLI's and cf-release. To add a custom blobstore, you'll need to ask help from the BOSH team: https://github.com/cloudfoundry/bosh/issues
