### ISSUE TITLE
bosh2 CLI will not bosh2 create-release in CF-Release update README to indicate the limitation

### ISSUE THREAD

**Issue by andrew-edgar** [cloudfoundry/cf-release#1225]
As discussed in the #rel-int channel.  There are still issues with bosh2 CLI doing bosh2 create-release with cf-release.

https://cloudfoundry.slack.com/archives/C0FAEKGUQ/p1500968386686256

It should be indicated in the README.md that the bosh2 CLI should not be used to build cf-release.

Thanks

**Comment by dsabeti** [comment]
Hi @andrew-edgar, how does [this warning look](https://github.com/cloudfoundry/cf-release/commit/a52ce0adf949763b65d8e292c781c2bed96bcbff)?

**Comment by andrew-edgar** [comment]
@dsabeti looks good thanks!
