### ISSUE TITLE
bosh azure settings

### ISSUE THREAD

**Issue by typik89** [cloudfoundry/cf-release#1226]
Hi! I deployed bosh to azure. I'm trying to push my first application using docs: https://github.com/cloudfoundry-incubator/bosh-azure-cpi-release/blob/master/docs/get-started/push-demo-app.md. 
I can't understand what is ORGANIZATION in string: cf target -o "REPLACE_WITH_CLOUD_FOUNDRY_PUBLIC_IP.xip.io_ORGANIZATION" -s "azure"

**Comment by dsabeti** [comment]
Hey @typik89, I'm not really sure what they mean in that doc, but I can just give you a generic explanation of orgs.

Most resources -- including apps -- are scoped to an org and space. At any point, you can see the list of orgs if you're logged in as an admin by running `cf orgs`. You can create new orgs (also as an admin) by running `cf create-org my-org-name`.

Once you have the org you plan to use, _then_ you run `cf t -o some-org ...`.

**Comment by typik89** [comment]
Hi, dsabeti. Thnk u for ur good reply. I'm new in cloud foundry and I havn't read docs in details. Firsta time I wanted to pass quick start tutorial and I was confused by this doc) Thank you
