### ISSUE TITLE
Permission Denied: When trying to create a deployment manifest.

### ISSUE THREAD

**Issue by shivdeepnv** [cloudfoundry/cf-release#1228]
Hi Team,

I am getting the following error when I running - 

`vagrant@bosh-lite:~/bosh-lite/cf-release$ ./scripts/generate-bosh-lite-dev-manifest`

```
/var/lib/gems/2.0.0/gems/bosh_cli-1.3262.24.0/bin/optionally_run_with_bundler.rb:22:in `write': Permission denied - /var/lib/gems/2.0.0/gems/bosh_cli-1.3262.24.0/bin/run_bosh_with_bundler.Gemfile (Errno::EACCES)
        from /var/lib/gems/2.0.0/gems/bosh_cli-1.3262.24.0/bin/optionally_run_with_bundler.rb:22:in `run'
        from /var/lib/gems/2.0.0/gems/bosh_cli-1.3262.24.0/bin/bosh:3:in `<top (required)>'
        from /usr/local/bin/bosh:23:in `load'
        from /usr/local/bin/bosh:23:in `<main>'
```
Here is some information about my deployment -

```
vagrant@bosh-lite:~/bosh-lite/cf-release$ pwd
/home/vagrant/bosh-lite/cf-release

vagrant@bosh-lite:~/bosh-lite/cf-release$ pwd
/home/vagrant/bosh-lite/cf-release
vagrant@bosh-lite:~/bosh-lite/cf-release$ bosh -v
BOSH 1.3262.24.0

vagrant@bosh-lite:~/bosh-lite/cf-release$ alias bosh
-bash: alias: bosh: not found

vagrant@bosh-lite:~/bosh-lite/cf-release$ git log -n1
commit eea95fc6faa2529748cf69180f80be72fa93187d
Author: CF MEGA BOT <cf-mega@pivotal.io>
Date:   Mon Aug 7 17:47:37 2017 +0000

    Final release 270

vagrant@bosh-lite:~/bosh-lite/cf-release$ ./scripts/generate-bosh-lite-dev-manifest
/var/lib/gems/2.0.0/gems/bosh_cli-1.3262.24.0/bin/optionally_run_with_bundler.rb:22:in `write': Permission denied - /var/lib/gems/2.0.0/gems/bosh_cli-1.3262.24.0/bin/run_bosh_with_bundler.Gemfile (Errno::EACCES)
        from /var/lib/gems/2.0.0/gems/bosh_cli-1.3262.24.0/bin/optionally_run_with_bundler.rb:22:in `run'
        from /var/lib/gems/2.0.0/gems/bosh_cli-1.3262.24.0/bin/bosh:3:in `<top (required)>'
        from /usr/local/bin/bosh:23:in `load'
        from /usr/local/bin/bosh:23:in `<main>'
vagrant@bosh-lite:~/bosh-lite/cf-release$ pwd
/home/vagrant/bosh-lite/cf-release

vagrant@bosh-lite:~/bosh-lite/cf-release$ bosh -v
BOSH 1.3262.24.0

vagrant@bosh-lite:~/bosh-lite/cf-release$ alias bosh
-bash: alias: bosh: not found

vagrant@bosh-lite:~/bosh-lite/cf-release$ git log -n1
commit eea95fc6faa2529748cf69180f80be72fa93187d
Author: CF MEGA BOT <cf-mega@pivotal.io>
Date:   Mon Aug 7 17:47:37 2017 +0000

    Final release 270

vagrant@bosh-lite:~/bosh-lite/cf-release$ ls -alter bosh-lite/
ls: invalid option -- 'e'
Try 'ls --help' for more information.
vagrant@bosh-lite:~/bosh-lite/cf-release$ ls -altr bosh-lite/
ls: cannot access bosh-lite/: No such file or directory
vagrant@bosh-lite:~/bosh-lite/cf-release$ git status
On branch master
Your branch is up-to-date with 'origin/master'.

nothing to commit, working directory clean

```

Please advise?

**Comment by dsabeti** [comment]
Hi @shivdeepnv. This looks to be an issue with the Bosh CLI. I'll rope in someone from the bosh team to help out.

**Comment by cppforlife** [comment]
Does this file exist: `/var/lib/gems/2.0.0/gems/bosh_cli-1.3262.24.0/bin/run_bosh_with_bundler.Gemfile` and what are its perms? I suspect may be at some point you ran something with sudo?

**Comment by shivdeepnv** [comment]
Thanks @dsabeti.

@cppforlife - Yes, the file exists

```
vagrant@bosh-lite:/var/lib/gems/2.0.0/gems/bosh_cli-1.3262.24.0/bin$ ls
bosh  optionally_run_with_bundler.rb
```

Permissions -
```
vagrant@bosh-lite:/var/lib/gems/2.0.0/gems/bosh_cli-1.3262.24.0/bin$ ls -l
total 8
-rwxr-xr-x 1 root root 660 Jan 10  2017 bosh
-rw-r--r-- 1 root root 907 Jan 10  2017 optionally_run_with_bundler.rb
```
Yes, I remember running sudo to install ruby. 

Just to clarify, I am trying to Install CloudFoundry on Bosh-Lite on my Windows Laptop using Vagrant.

I am basically following these instructions - https://medium.com/@ravijagannathan/install-cloud-foundry-on-bosh-lite-6d3b9a1e416a

**Comment by dsabeti** [comment]
@shivdeepnv, I'd actually suggest a different approach to setting up bosh-lite that should avoid this issue.

There's a new way to set up a local bosh-lite. Instead of deploying cf-release, you can use cf-deployment, which is much easier to work with. Most importantly, it uses the v2 bosh CLI, which you can install as a compile binary instead of a Ruby CLI. The workflow should be much nicer.

Here are some links: 
- bosh-lite: http://bosh.io/docs/bosh-lite.html
- cf-deployment: https://github.com/cloudfoundry/cf-deployment
  - The documentation for cf-deployment on bosh-lite: https://github.com/cloudfoundry/cf-deployment/blob/master/bosh-lite.md
- v2 bosh CLI: http://bosh.io/docs/cli-v2.html#install

**Comment by dsabeti** [comment]
Hey there @shivdeepnv, any luck with the new approach to setting up bosh-lite?

**Comment by dsabeti** [comment]
Hi @shivdeepnv, I'm going to close this issue due to inactivity, but definitely reopen it if you need more help.
