### ISSUE TITLE
deploy cf-release to bosh-lite: consul failed

### ISSUE THREAD

**Issue by qibobo** [cloudfoundry/cf-release#1231]
Other vms are running, except consul. The log of consul agent is:

2017/08/10 08:51:41 [ERR] agent.client: Failed to decode response header: EOF
error during start: timeout exceeded: "rpc error: failed to get conn: x509: certificate has expired or is not yet valid"
2017/08/10 08:52:34 [ERR] agent.client: Failed to decode response header: EOF
2017/08/10 08:52:34 [ERR] agent.client: Failed to decode response header: EOF
error during start: timeout exceeded: "rpc error: failed to get conn: x509: certificate has expired or is not yet valid"
2017/08/10 08:53:34 [ERR] agent.client: Failed to decode response header: EOF
2017/08/10 08:53:34 [ERR] agent.client: Failed to decode response header: EOF
error during start: timeout exceeded: "rpc error: failed to get conn: x509: certificate has expired or is not yet valid"
2017/08/10 08:54:45 [ERR] agent.client: Failed to decode response header: EOF
2017/08/10 08:54:45 [ERR] agent.client: Failed to decode response header: EOF
error during start: timeout exceeded: "rpc error: failed to get conn: x509: certificate has expired or is not yet valid"
2017/08/10 08:55:54 [ERR] agent.client: Failed to decode response header: EOF

**Comment by dsabeti** [comment]
Hi @qibobo, we just merged a PR to address this issue. The hard-coded certs in for bosh-lite have expired. We'll try to ship CF 271 soon with the appropriate fix, but you can use the `release-candidate` branch (which has the fix for this) in the meantime.

**Comment by qibobo** [comment]
@dsabeti  it works. thank you.

**Comment by mjsjinsu** [comment]
Hi 
I also use consul certs of bosh-lite.
Is there any way of rolling update consul cert using bosh.

When consul server and client certs updated using bosh, consul clients(cf-core and diego component) aren't able to communicate updated consul cluster set and it can not guarantee non-stop work.

**Comment by dsabeti** [comment]
Hey @mjsjinsu.

Updating consul certificates is a somewhat complicated process. If you want to rotate your certificates, you can follow instructions here:
https://docs.cloudfoundry.org/deploying/common/consul-security.html#rotating-certs

We typically think of bosh-lite as a development or testing environment -- environments that you can easily destroy and recreate -- so we didn't bother rolling out an update plan. **This simplest thing to do is delete your bosh-lite and recreated it.**
