### ISSUE TITLE
Deploying cloudfoundry with multiple app domains

### ISSUE THREAD

**Issue by rahul221192** [cloudfoundry/cf-release#1237]
I want to deploy my cloud foundry with two domains  i.e. is one public and private domains on aws.
Now  the apps running on private domain should not be accessible over internet,it should be accessible only over private VPC.
So what changes i need to do in aws and cloud foundry stub file.

Thanks and Regards 
Rahul Kumar

**Comment by dsabeti** [comment]
Hey @rahul221192. This seems like a tricky setup, but it might be possible. Who are the users of the apps in your private domain? Are they other applications, or humans operating from machines behind a firewall? If the users are other applications, are those applications also on the private domain, or might they be on the public domain as well?

One approach you can take is to push your private apps without a route `cf push --no-route`, and then use [container networking features](https://github.com/cloudfoundry-incubator/cf-networking-release) to allow access between apps, but that doesn't use a "private domain" like you're asking for -- the apps would address each other over IP addresses directly.

Also, the notion of "shared" and "private" domains in CF isn't really a matter of whether the domain is accessible over the public internet or the private VPC, but rather, which organizations are allowed to use that domain for their apps -- shared domains can be used by any tenant of the CF instance, while private domains can only be used by certain organizations.

**Comment by rahul221192** [comment]
Hey @dsabeti just to make it more clear i will tell few scenario. 

First is simple that i am pushing some app xyz and i don't want  this app to be on internet,but it should have some domain. i don't want to push it with
 --no-route.
And 2nd 
Suppose I as company want  logs for my application and platform . i am deploying some app which show me log of my platform and apps .As a company i don't want this app to have some public domain .But this app will talk all other apps which are on public domain.
What would you recommend me for that?

**Comment by rahul221192** [comment]
@dsabeti can you please help me where i can add one more domain in cf deployment manifest file?

**Comment by dsabeti** [comment]
@rahul221192, to add a private domain, you'll want to use the `cf` CLI instead of the manifest (`cf create-domain`). If you want to add a shared domain (accessible by everyone), you can add it to `properties.app_domains`.

**Comment by rahul221192** [comment]
@dsabeti thanks for the help. i deployed a private ELB on aws and added a new router,new domain properties.app_domains and registered that domain to private a as suggested as in isolation segments.SO app with private domain is not accessible over internet.

Thanks for the help again

**Comment by dsabeti** [comment]
Glad it worked out @rahul221192. I'll go ahead and close this issue, but feel free to re-open it if you need more help.
