### ISSUE TITLE
Release notes of v272 are not correct

### ISSUE THREAD

**Issue by tyyko** [cloudfoundry/cf-release#1240]
Release notes of v272 in the 'Job Spec Changes' section:
- The properties `uaa.url` and `login.protocol` have been removed

But looking at both manifest template and uaa spec files the properties are still there, and some other (`uaa.issuer`) depend on them.

Could you please clarify if these properties shall be really removed or not?

Thanks and regards,
Michael

**Comment by aashah** [comment]
Hey @tyyko,

Thanks for catching this! Definitely looks like a mistake in the release notes. As you found out, we most definitely are using these manifest properties...We believe those job spec changes are for a different job, and we missed labeling that job.

We're going to reach out to the right people and get the release notes updated. We'll throw another comment here once we've reached out.

**Comment by dsabeti** [comment]
Hey @tyyko, I've removed that note from the release notes for CF 272. We're still hunting down how it got in there, but we've verified that it's still required for UAA jobs. Thanks!
