### ISSUE TITLE
Need better way to encrypt communication between cloud components

### ISSUE THREAD

**Issue by ron4git** [cloudfoundry/cf-release#1242]
Managing, generating, and updating so many different certificates, keys, and signing CA certs, keys is a big challenge. And may cause significant down time. 
Wondering 1. if a single cert can be used for all communication between components.
2. use ssh tunnel for secure communication.

**Comment by dsabeti** [comment]
Hey @ron4git. I can definitely relate to the difficulty of managing all of these certs and keys. The first thing I'd suggest is to start by looking at [cf-deployment](https://github.com/cloudfoundry/cf-deployment), which will soon replace cf-release (we're planning to cut a 1.0 version in the next week or two). In cf-deployment, you can use the BOSH cli or a BOSH config server to generate and manage all of the certificates and keys.

With regards to your specific questions, using a single certificate has security implications and would be less safe than the current certificate setup. As for ssh tunnels, that would have to be implemented one component at a time, and the authors of each component would have to agree to implement that solution.

Try cf-deployment and see if makes this easier for you.

**Comment by dsabeti** [comment]
Hey @ron4git, did you take a look at cf-deployment? Any other thoughts on this?

**Comment by dsabeti** [comment]
I'm going to close this issue due to inactivity, but feel free to reopen.
