### ISSUE TITLE
Cloud controller database migration fails unless undocumented uaa clients are set

### ISSUE THREAD

**Issue by jmcarp** [cloudfoundry/cf-release#1248]
As of cf-release 274, it appears that cloud controller database migrations fail unless operators configure a `cc_service_broker_client` or `cc-service-dashboards` uaa client. I might have missed it, but I didn't see this requirement in the docs or release notes. IMO, if these clients are supposed to be required, they should be documented; if not, migrations shouldn't fail if they aren't specified.

**Comment by dsabeti** [comment]
Hey @jmcarp. I saw that you had a conversation in the CAPI Slack channel about this, and it sounds like CAPI made these required by mistake. I'll work with CAPI to update the release notes for CF 274 so that this context gets shared.

**Comment by jmcarp** [comment]
Thanks!

**Comment by dsabeti** [comment]
Hey @jmcarp, take a look at the release notes for 274 and 275 now. I think they should include the necessary documentation.

**Comment by dsabeti** [comment]
Hey @jmcarp, I'm going to close this out, since we've got the release notes updated.
