### ISSUE TITLE
mysql nodes are failing in Cloud Foundry upgrade.

### ISSUE THREAD

**Issue by Pratibha-28** [cloudfoundry/cf-release#1253]
We are using cf-mysql service as CF platform db instead of postgresql.
In CF deployment manifest, we have added 3 mysql nodes and 2 proxy vms.

In first time setup all 3 mysql nodes are working fine but when we have tried for CF upgrade then only one mysql node is updating and other 2 mysql nodes are failing.

Attaching mariadb_ctrl.combined.log of failing mysql node.
[mariadb_ctrl.combined-log.txt](https://github.com/cloudfoundry/cf-release/files/1344030/mariadb_ctrl.combined-log.txt)

**Comment by dsabeti** [comment]
Hi @Pratibha-28, I saw that you also opened [a Github issue in the cf-mysql-release repo](https://github.com/cloudfoundry/cf-mysql-release/issues/183). That's the correct place to ask for help with this. I'm going to close this issue so that we don't have duplicate issues.
