### ISSUE TITLE
Error when deploying CF v275 to Bosh Lite: doppler_z1 failed to start

### ISSUE THREAD

**Issue by willsu** [cloudfoundry/cf-release#1254]
Greetings Cloud Foundry Folks!

I'm a Cloud Foundry newb and am having a bit of trouble deploying the latest version (cf-275) to my Bosh Lite installation. 

When I run `bosh deploy`, I receive the following error:

```
   Failed updating instance doppler_z1 > doppler_z1/d08e28c3-cf1c-4a5a-8cd0-6f5c42240617 (0) (canary): 'doppler_z1/d08e28c3-cf1c-4a5a-8cd0-6f5c42240617 (0)' is not running after update. Review logs for failed jobs: syslog_drain_binder (00:03:18)
     Done updating instance uaa_z1 > uaa_z1/47be6d13-7532-406d-85c2-5ca13b029b8f (0) (canary) (00:03:22)

Error 400007: 'doppler_z1/d08e28c3-cf1c-4a5a-8cd0-6f5c42240617 (0)' is not running after update. Review logs for failed jobs: syslog_drain_binder
```

It appears that all services are running except `doppler_z1/0 (d08e28c3-cf1c-4a5a-8cd0-6f5c42240617)`, as shown by the command below.

```
$ bosh instances --ps
```

![screen shot 2017-10-03 at 1 18 45 pm](https://user-images.githubusercontent.com/38972/31147042-6d00c800-a83d-11e7-8001-adf67ceac641.png)
^ Image used to preserve formatting

At this point, I'm even a bit fuzzy on how to access the logs for the `syslog_drain_binder`, as the output suggests. 

Any help or nudge in the right direction for fixing this issue would be greatly appreciated!

Thanks in advance,
Will

**Comment by dsabeti** [comment]
No problem, @willsu. You can pull down the logs from your deployment using either of the `bosh` CLIs. If you're using the old ruby CLI (installed with `gem install bosh_cli`), the command is
```
bosh deployment bosh-lite/deployments/cf.yml
bosh logs doppler_z1 0
```

If you're using the newer golang CLI:
```
bosh -e DIRECTOR_IP logs doppler_z1/0 -d cf-warden
```

That will pull down the logs from the VM in a `.zip` file that you can unpack and dig around in. Let us know what you find in the syslog_drain_binder logs.

(CC'ing @ahevenor and @jasonkeene from the Loggregator team, in case we need their help later.)

**Comment by willsu** [comment]
Hello @dsabeti. Thanks for the info!

Unfortunately the doppler logs did not provide very much information for me:

```
2017/10/03 19:42:40 Startup: Setting up the doppler server
2017/10/03 19:42:40 health bound to: 127.0.0.1:14825
2017/10/03 19:42:40 grpc bound to: 0.0.0.0:8082
2017/10/03 19:42:40 Metrics endpoint is listening on 127.0.0.1:14825
2017/10/03 19:42:40 Starting Health Status Updates to Store: /doppler/meta/z1/doppler_z1/d08e28c3-cf1c-4a5a-8cd0-6f5c42240617
2017/10/03 19:42:40 Startup: doppler server started.
2017/10/03 19:42:40 MessageRouter:Starting
2017/10/03 19:42:40 Starting gRPC server on 0.0.0.0:8082
2017/10/03 19:42:40 pprof bound to: 127.0.0.1:43792
```

It would appear that the service started, according to the logs, which is different than I the `bosh vms` command is reporting.

Can you think of anywhere else that I could look?

**Comment by willsu** [comment]
Ok, so the `syslog_drain_binder.log` contains some repetitive error messages:

```
2017/10/03 19:42:41 x509: certificate signed by unknown authority
panic: x509: certificate signed by unknown authority
```

Do you think I missed a step in my setup of the Bosh Lite Director?

**Comment by dsabeti** [comment]
D'oh. Somehow, I _already_ forgot about a huge fire our team had to fight last week. This should have been the first thing I thought of. The short description of the problem was that the hard-coded certificates for bosh-lite in cf-release are incompatible with the bosh-lite certs in the most recent diego-release. 

Have no fear: CF 276 will include the fixed certs. I'm hoping we'll cut it today to tomorrow. I'd say you have two options:
1. Sit tight until we ship CF 276
2. Checkout the `release-candidate` branch of cf-release and try deploying that. It has the correct certs.

**Comment by willsu** [comment]
@dsabeti Thank you. I'll give the `release-candidate` branch a try.

**Comment by willsu** [comment]
@dsabeti I wanted to confirm that using the `release-candidate` branch fixed my issue. Many thanks for you prompt help with this issue.
