### ISSUE TITLE
Getting "parse : empty url" when using v6.26.0 cf-cli client

### ISSUE THREAD

**Issue by ssshah5** [cloudfoundry/cf-release#1263]
Getting the following error during "cf logs" command:

`parse : empty url`

Would appreciate if you can share details on changes that triggered this error? Is there a workaround besides upgrading the CLI?

**Comment by dsabeti** [comment]
Hey @ssshah5. My first guess is that your CLI is failing to find the loggregator endpoint.

If you run `cf curl /v2/info`, you should get a JSON object back from your CF API that looks something like this:
```
{
   "name": "",
   "build": "",
   "support": "",
   "version": 0,
   "description": "",
   "authorization_endpoint": "https://login.cf-dsabeti.cf-app.com",
   "token_endpoint": "https://uaa.cf-dsabeti.cf-app.com",
   "min_cli_version": null,
   "min_recommended_cli_version": null,
   "api_version": "2.99.0",
   "app_ssh_endpoint": "ssh.cf-dsabeti.cf-app.com:2222",
   "app_ssh_host_key_fingerprint": "b7:12:00:68:87:2d:c9:49:37:68:b4:88:e2:a4:86:56",
   "app_ssh_oauth_client": "ssh-proxy",
   "doppler_logging_endpoint": "wss://doppler.cf-dsabeti.cf-app.com:443",
   "routing_endpoint": "https://api.cf-dsabeti.cf-app.com/routing"
}
```

The important value in there is `doppler_logging_endpoint`, which tells the CLI where to find the logging API.

So, the troubleshooting questions are:
1. What is the output of `cf curl /v2/info`?
2. What version of the CLI are you using?
3. What version of cf-release do you have deployed?

**Comment by ssshah5** [comment]
@dsabeti - Thank you for looking into this. Here is the requested information:

1. Out from `cf curl /v2/info`

```
{
   "name": "Bluemix",
   "build": "270019",
   "support": "http://ibm.com",
   "version": 0,
   "description": "IBM Bluemix",
   "authorization_endpoint": "https://login.stage1.ng.bluemix.net/UAALoginServerWAR",
   "token_endpoint": "https://uaa.stage1.ng.bluemix.net",
   "min_cli_version": null,
   "min_recommended_cli_version": null,
   "api_version": "2.92.0",
   "app_ssh_endpoint": "ssh.stage1.ng.bluemix.net:2222",
   "app_ssh_host_key_fingerprint": "ed:31:a3:12:cf:51:9b:f8:bb:0c:58:06:e3:12:33:f7",
   "app_ssh_oauth_client": "ssh-proxy",
   "doppler_logging_endpoint": "wss://doppler.stage1.ng.bluemix.net:443",
   "user": "00000000-1111-00000-8fb0-eb5a7f588cf3"
}
```

2. The cli version we are using is `v6.26.0`

3. cf-release in Bluemix is v270

**Comment by dsabeti** [comment]
Your CLI is pretty old, so you may want to upgrade. However, the issue I'm thinking of was addressed in CLI 6.22.2, so I don't think that it's the root cause here.

What's the output when you run `cf logs` with `CF_TRACE=TRUE`?

**Comment by ssshah5** [comment]
@dsabeti : Here is the output with CF_TRACE=true
```
REQUEST: [2017-11-16T18:53:36Z]
GET /v2/spaces/0000000000000000000000000000-00000/apps?q=name%3Aenv-toolchain&inline-relations-depth=1 HTTP/1.1
Host: api.stage1.ng.bluemix.net
Accept: application/json
Authorization: [PRIVATE DATA HIDDEN]
Connection: close
Content-Type: application/json
User-Agent: go-cli BUILT_FROM_SOURCE / linux



RESPONSE: [2017-11-16T18:53:37Z]
HTTP/1.1 200 OK
Connection: close
Transfer-Encoding: chunked
Content-Type: application/json;charset=utf-8
Date: Thu, 16 Nov 2017 18:53:37 GMT
Server: nginx
X-Backside-Transport: OK OK
X-Content-Type-Options: nosniff
X-Global-Transaction-Id: 3374562455

1494
{
  "total_results": 1,
  "total_pages": 1,
  "prev_url": null,
  "next_url": null,
  "resources": [
    {
      "metadata": {
        "guid": "0000000000000000000000000000-00000",
        "url": "/v2/apps/0000000000000000000000000000-00000",
        "created_at": "2017-11-16T18:27:21Z",
        "updated_at": "2017-11-16T18:27:29Z"
      },
      "entity": {
        "name": "env-toolchain",
        "production": false,
        "space_guid": "0000000000000000000000000000-00000",
        "stack_guid": "0000000000000000000000000000-00000",
        "buildpack": "sdk-for-nodejs",
        "detected_buildpack": "",
        "detected_buildpack_guid": "0000000000000000000000000000-00000",
        "environment_json": {

        },
        "memory": 128,
        "instances": 1,
        "disk_quota": 1024,
        "state": "STARTED",
        "version": "20000000000000000000000000000-000003",
        "command": null,
        "console": false,
        "debug": null,
        "staging_task_id": "7bd40000000000000000000000000000-000003ad",
        "package_state": "STAGED",
        "health_check_type": "port",
        "health_check_timeout": null,
        "health_check_http_endpoint": null,
        "staging_failed_reason": null,
        "staging_failed_description": null,
        "diego": true,
        "docker_image": null,
        "docker_credentials": {
          "username": null,
          "password": null
        },
        "package_updated_at": "2017-11-16T18:27:23Z",
        "detected_start_command": "./vendor/initial_startup.rb",
        "enable_ssh": true,
        "ports": [
          8080
        ],
        "space_url": "/v2/spaces/0000000000000000000000000000-00000",
        "space": {
          "metadata": {
            "guid": "0000000000000000000000000000-00000",
            "url": "/v2/spaces/4d0000000000000000000000000000-00000",
            "created_at": "2015-08-24T13:43:44Z",
            "updated_at": "2017-11-16T14:24:14Z"
          },
          "entity": {
            "name": "dev",
            "organization_guid": "770000000000000000000000000000-00000c5",
            "space_quota_definition_guid": null,
            "isolation_segment_guid": null,
            "allow_ssh": true,
            "organization_url": "/v2/organizations/70000000000000000000000000000-000005",
            "developers_url": "/v2/spaces/40000000000000000000000000000-00000/developers",
            "managers_url": "/v2/spaces/40000000000000000000000000000-000002/managers",
            "auditors_url": "/v2/spaces/0000000000000000000000000000-000002/auditors",
            "apps_url": "/v2/spaces/0000000000000000000000000000-00000d52/apps",
            "routes_url": "/v2/spaces/40000000000000000000000000000-0000052/routes",
            "domains_url": "/v2/spaces/40000000000000000000000000000-0000052/domains",
            "service_instances_url": "/v2/spaces/000000000000000000000000/service_instances",
            "app_events_url": "/v2/spaces/000000000000000000000000/app_events",
            "events_url": "/v2/spaces/000000000000000000000000/events",
            "security_groups_url": "/v2/spaces/000000000000000000000000/security_groups",
            "staging_security_groups_url": "/v2/spaces/000000000000000000000000/staging_security_groups"
          }
        },
        "stack_url": "/v2/stacks/000000000000000000000000",
        "stack": {
          "metadata": {
            "guid": "000000000000000000000000",
            "url": "/v2/stacks/00000000000000000000000000",
            "created_at": "2015-04-16T22:48:06Z",
            "updated_at": "2015-04-16T22:48:06Z"
          },
          "entity": {
            "name": "cflinuxfs2",
            "description": "Ubuntu 14.04.2 trusty"
          }
        },
        "routes_url": "/v2/apps/000000000000000000000000/routes",
        "routes": [
          {
            "metadata": {
              "guid": "000000000000000000000000",
              "url": "/v2/routes/000000000000000000000000",
              "created_at": "2017-11-14T17:19:51Z",
              "updated_at": "2017-11-14T17:19:51Z"
            },
            "entity": {
              "host": "env-toolchain",
              "path": "",
              "domain_guid": "8000000000000000000000000b",
              "space_guid": "400000000000000000000000052",
              "service_instance_guid": null,
              "port": null,
              "domain_url": "/v2/shared_domains/0000000000000000000000008b",
              "space_url": "/v2/spaces/4d0000000000000000000000002",
              "apps_url": "/v2/routes/0000000000000000000000007e/apps",
              "route_mappings_url": "/v2/routes/4000000000000000000000000/route_mappings"
            }
          }
        ],
        "events_url": "/v2/apps/0000000000000000000000001/events",
        "service_bindings_url": "/v2/apps/0000000000000000000000001/service_bindings",
        "service_bindings": [

        ],
        "route_mappings_url": "/v2/apps/0000000000000000000000001/route_mappings"
      }
    }
  ]
}
0


Connected, dumping recent logs for app env-toolchain in org <org_name> / space dev as <user_name>..
FAILED
parse : empty url
```

**Comment by ssshah5** [comment]
When I upgrade the cli to v6.29.0, I am getting the following error for the same command
```
REQUEST: [2017-11-16T19:03:49Z]
POST /oauth/token HTTP/1.1
Host: uaa.stage1.ng.bluemix.net
Accept: application/json
Authorization: [PRIVATE DATA HIDDEN]
Connection: close
Content-Type: application/x-www-form-urlencoded
User-Agent: cf/6.29.0+ff886fa.2017-11-14 (go1.8.3; amd64 linux)
[PRIVATE DATA HIDDEN]

RESPONSE: [2017-11-16T19:03:50Z]
HTTP/1.1 401 Unauthorized
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Content-Type: application/json;charset=UTF-8
Date: Thu, 16 Nov 2017 19:03:49 GMT
Expires: 0
Pragma: no-cache
Www-Authenticate: Bearer error="invalid_token", error_description="The token expired, was revoked, or the token ID is incorrect: "
X-Backside-Transport: FAIL FAIL
X-Content-Type-Options: nosniff
X-Frame-Options: DENY
X-Global-Transaction-Id: 1642003729
X-Xss-Protection: 1; mode=block
{
  "error": "invalid_token",
  "error_description": "The token expired, was revoked, or the token ID is incorrect: "
}
```
Here is how my /cf/.config.json looks like in both the cases:
```
{
  "ConfigVersion": 3,
  "Target": "https://api.stage1.ng.bluemix.net",
  "APIVersion": "2.92.0",
  "AuthorizationEndpoint": "https://login.stage1.ng.bluemix.net/UAALoginServerWAR",
  "DopplerEndPoint": "",
  "UaaEndpoint": "https://login.stage1.ng.bluemix.net/UAALoginServerWAR",
  "RoutingAPIEndpoint": "",
  "AccessToken": "Bearer 09000000000000000000000m90Y2NsaWVudCJdfQ.YCzLhHjOWgS0Sl809000000000000000000000m90Y2i43yQ09000000000000000000000m90Y2o1MQiM60ao09000000000000000000000m90Y209000000000000000000000m90Y28",
  "SSHOAuthClient": "",
  "UAAOAuthClient": "cf",
  "UAAOAuthClientSecret": "",
  "RefreshToken": "",
  "OrganizationFields": {
    "GUID": "709000000000000000000000m90Y25",
    "Name": "user_email@us.ibm.com",
    "QuotaDefinition": {
      "guid": "",
      "name": "",
      "memory_limit": 0,
      "instance_memory_limit": 0,
      "total_routes": 0,
      "total_services": 0,
      "non_basic_services_allowed": false,
      "app_instance_limit": 0,
      "total_reserved_route_ports": 0
    }
  },
  "SpaceFields": {
    "GUID": "409000000000000000000000m90Y252",
    "Name": "dev",
    "AllowSSH": false
  },
  "SSLDisabled": false,
  "AsyncTimeout": 0,
  "Trace": "",
  "ColorEnabled": "",
  "Locale": "",
  "PluginRepos": null,
  "MinCLIVersion": "",
  "MinRecommendedCLIVersion": ""
}
```

**Comment by dsabeti** [comment]
@ssshah5 For the newer error, you just need to login in again.

**Comment by ssshah5** [comment]
@dsabeti - Thanks. We are running these commands from inside our CI tool and hence we want to use the .cf/config.json file. Till now we used to pre-populate the `AccessToken` field with the bearer token obtained from `cf oauth-token` command and it used to work fine. However, it seems to be not working in v6.29.0. Do you think I am missing something in the config.json file?

**Comment by dsabeti** [comment]
I'm not sure. Let's get some help from the CLI team.

Paging @nickwei84 and @xenophex.

**Comment by ssshah5** [comment]
Thank you! To test that token is actually expired or not, I manually regenerated a new token using `cf oauth-token` and inserted in config.json. Got the same auto error as above with the new token as well.

**Comment by XenoPhex** [comment]
@ssshah5 Can you try upgrading to the lastest version, or at least the latest patch version of 6.29? It appears some changes occurred to the oauth-token command shortly after 6.29.0 came out and 6.29.2 might have already solved your issue. (Also, the CF CLI is fully backwards compatible, so the very latest version of the CLI should work properly with Bluemix.)

If not, I'm curious as to the flow of your CI. Do you have a long term Auth-Token/Refresh-Token that you swap in (to the `config.json`) at the beginning of your CI job run to CF commands? Or is there more orchestration that is done to "log in" to that particular user before you run CF commands?

**Comment by nickwei84** [comment]
@ssshah5 Hi, the error you are seeing related to login is a known issue and was resolved in v 6.29.2 of the CLI and later.

As for the error you're seeing with `cf logs <your_app_name> --recent`, I would recommend upgrading to the latest version of the CLI and trying again. If you encounter this log related error again, please provide us with the trace (ie. run `cf logs <your_app_name> --recent -v) and paste it here.

**Comment by ssshah5** [comment]
@XenoPhex @nickwei84 
I can try upgrading it to a later version. 
In our CI tool, we generate a cf oauth-token at the beginning of the job and save it in the config.json file as a value to the key "AccessToken". I don't think we are using RefreshToken inside our config.json. Should we be setting the "RefreshToken" in the config file as well for login to work correctly?

**Comment by XenoPhex** [comment]
@ssshah5 I'm kind of confused as to how your CI works, do you call `cf auth` or `cf login` before you call `cf oauth-token`?

Before I continue, let's go through some explanations first so that we're all on the same page:
- A fresh access token and refresh token are generated by the UAA once credentials are provided to the CLI via `cf auth` or `cf login`. These tokens are saved to the `config.json` on success.
- The access token is passed in the HTTP header on every request to the CC. If the CC returns back a particular kind of Unauthorized error. The CLI catches it, and uses the refresh token to get a new access/refresh token. These tokens are then saved to the `config.json` for future CC requests.
- The `cf oauth-token` command uses the existing refresh token to forcefully refresh the access token, also saving this tokens on success.

In order to run the `cf oauth-token` command, the only required `config.json` properties are the `Target`, `RefreshToken`, and a valid `AccessToken`. (Note: The `AccessToken` is usually parsed by each command to pull the current user's username to display the flavor text, but the command will not validate if it's expired. So the Access token can be expired as long as the Refresh Token is not.)

**Comment by ssshah5** [comment]
@XenoPhex  Sorry for the confusion and apologize that I didn't clarify it earlier. Here are the details:

-We get the initial bearer token by reaching out directly to the UAA server. This is the same token that you would get by running `cf oauth-token` after a `cf login`. The same response also contains the refresh token but we are not setting this value in the config.json. We are setting only the AccessToken value.
- The users can that run cf commands since the AccesToken is already set in the config.json file.

**Comment by XenoPhex** [comment]
Ah, that makes more sense. In general, I'd recommend placing both the Access Token and the Refresh Token in the config file, as most CF instances have a short TTL for their Access Token (in the order of minutes) while the Refresh Token lasts hours and can fix the issue you are getting from above.

**Comment by XenoPhex** [comment]
@ssshah5 the error was due to a hiccup in the transition between logging back-ends. The CF CLI used to parse the ` loggregator_endpoint` (or something like that, I forget the exact name) from `/v2/info` and modify it to generate what is now the `doppler_logging_endpoint`. At some point, the ` loggregator_endpoint` was removed in favor of the `doppler_logging_endpoint` and the new back-end.

What likely happened is that your previous CF instance had support for both the new and old back ends (the overlap had a year+ of releases) and the upgraded version (v270) finally dropped support for it.

During this period of time, the CF CLI slowly transitioned from constructing the value ourselves to using the value provided by the `/v2/info`. If you're on an old enough version of the CF CLI and you're running against a new CF, the CLI will be looking for a value that no longer exists and passing along an empty value to the logging client (thus causing the error you reported).

**Comment by ssshah5** [comment]
@XenoPhex - Thats a great explanation and appreciate the details. I think I understand the root cause now. Thanks. Closing this issue now.
