### ISSUE TITLE
CF v279/v280 consuming 'Do-Not-Use' uaa-release 

### ISSUE THREAD

**Issue by achawki** [cloudfoundry/cf-release#1264]
Hi,

cf release v279/280 (same applied to `cf-deployment`) uses uaa release [v52.2](https://github.com/cloudfoundry/uaa-release/releases/tag/v52.2), which is marked as Do-Not-Use.

**Comment by dsabeti** [comment]
Hey @achawki. Sorry for the late response on this. I was out on vacation all of last week.

UAA 52.2 is fine to use. There's a known issue with dev/test environments that set `skipSslValidation: true` -- specifically, that version of UAA will continue to validate TLS validation anyway. Production operators set this value to false, so we decided to move forward.

Still, I appreciate that you brought this to our attention. In the meantime, several people have brought this up with us, so we should probably update release notes for cf-release (and cf-deployment) to explain the situation.

**Comment by achawki** [comment]
Ok, thanks.
