### ISSUE TITLE
cf login timeout in bosh-lite

### ISSUE THREAD

**Issue by peluu** [cloudfoundry/cf-release#1266]
i am facing this issue, When attempting to run cf api:
vagrant@bosh-lite:~$ cf login -a https://api.bosh-lite.com --skip-ssl-validation -u admin -p admin API endpoint: https://api.bosh-lite.com FAILED Error performing request: Get https://api.bosh-lite.com/v2/info: dial tcp 10.244.0.34:443: i/o timeout TIP: If you are behind a firewall and require an HTTP proxy, verify the https_proxy environment variable is correctly set. Else, check your network connection.

but i was not able to run ./bin/add_route . it is showing error :
vagrant@bosh-lite:$ ./bin/add-route -bash: ./bin/add-route: No such file or directory vagrant@bosh-lite:$ /bin/add-route -bash: /bin/add-route: /bin/bash^M: bad interpreter: No such file or directory
but it exists in bin
`vagrant@bosh-lite:/$ cd bin

vagrant@bosh-lite:/bin$ ls

add-route `

for reference output of ifconfig:
`vagrant@bosh-lite:~$ ifconfig
eth0 Link encap:Ethernet HWaddr 08:00:27:86:99:68
inet addr:10.0.2.15 Bcast:10.0.2.255 Mask:255.255.255.0
inet6 addr: fe80::a00:27ff:fe86:9968/64 Scope:Link
UP BROADCAST RUNNING MULTICAST MTU:1500 Metric:1
RX packets:1173 errors:0 dropped:0 overruns:0 frame:0
TX packets:772 errors:0 dropped:0 overruns:0 carrier:0
collisions:0 txqueuelen:1000
RX bytes:108082 (108.0 KB) TX bytes:96810 (96.8 KB)

eth1 Link encap:Ethernet HWaddr 08:00:27:94🇩🇪a2
inet addr:192.168.50.4 Bcast:192.168.50.255 Mask:255.255.255.0
inet6 addr: fe80::a00:27ff:fe94:dea2/64 Scope:Link
UP BROADCAST RUNNING MULTICAST MTU:1500 Metric:1
RX packets:0 errors:0 dropped:0 overruns:0 frame:0
TX packets:16 errors:0 dropped:0 overruns:0 carrier:0
collisions:0 txqueuelen:1000
RX bytes:0 (0.0 B) TX bytes:1296 (1.2 KB)

lo Link encap:Local Loopback
inet addr:127.0.0.1 Mask:255.0.0.0
inet6 addr: ::1/128 Scope:Host
UP LOOPBACK RUNNING MTU:65536 Metric:1
RX packets:79999 errors:0 dropped:0 overruns:0 frame:0
TX packets:79999 errors:0 dropped:0 overruns:0 carrier:0
collisions:0 txqueuelen:1
RX bytes:10943669 (10.9 MB) TX bytes:10943669 (10.9 MB)

lo:1 Link encap:Local Loopback
inet addr:10.254.50.4 Mask:255.255.255.0
UP LOOPBACK RUNNING MTU:65536 Metric:1
`

output of route -n:
`vagrant@bosh-lite:~$ route -n

Kernel IP routing table

Destination Gateway Genmask Flags Metric Ref Use Iface
0.0.0.0 10.0.2.2 0.0.0.0 UG 0 0 0 eth0
10.0.2.0 0.0.0.0 255.255.255.0 U 0 0 0 eth0
192.168.50.0 0.0.0.0 255.255.255.0 U 0 0 0 eth1`

Any thoughts for troubleshooting?

**Comment by killer-imaniac** [comment]
I am facing the same issue @peluu . Please help in troubleshooting this. Thanks in advance.

**Comment by dsabeti** [comment]
Hi @peluu and @killer-imaniac. The vagrant workflow for bosh-lite has been deprecated for a while, and cf-release is in the process of being deprecated as well.

May I suggest using the latest tooling for this? You can find docs for bosh-lite here: http://bosh.io/docs/bosh-lite.html

And to deploy cf, I'd recommend using [cf-deployment](https://github.com/cloudfoundry/cf-deployment).

If there's a specific reason you're using vagrant/cf-release, let me know and we'll try to help with that. I just think it will be much easier to use the newer tooling. Also, which docs were you following? We'll soon need to remove it.

**Comment by peluu** [comment]
Hi @dsabeti. Thanks for your suggestions. I will surely try these and there is no specific reason for using vagrant/cf-release. I just want to deploy cloud foundry on local machine. I am using following references:

https://stackoverflow.com/questions/36596743/how-to-install-cloudfoundry-on-local-server

https://www.jbrandsma.com/news/2015/12/19/install-cloudfoundry-on-windows/

http://dimitrijwulf.blogspot.in/2015/03/installing-cloudfoundry-on-windows-and.html

https://medium.com/@ravijagannathan/install-cloud-foundry-on-bosh-lite-6d3b9a1e416a

**Comment by dsabeti** [comment]
Thanks for those links @peluu. I'm going to close this issue, but feel free to open an issue on cf-deployment if you need help with it.
