### ISSUE TITLE
cf start 'app-usage-scheduler exit with error code 1 after  applying changes from Ops Manager

### ISSUE THREAD

**Issue by mymobileapplication** [cloudfoundry/cf-release#1267]
Product : Pivotal Cloud Foundry 
Ops Manager : 1.12.2.0

We have deployed PCF on VMware platform and also have imported Microsoft Azure Service broker v1.5.2 successfully and do all necessaries settings. Error get thrown when changes are applied from Ops Manager at stage "Running errand Usage Service Errand for Pivotal Elastic Runtime", much before it reach  Azure Service Broker. 
{ Error: Command failed: cf start 'app-usage-server' 
Error staging application: Staging error: staging failed 
`cf start 'app-usage-server'` (exited with error code 1) 
at ChildProcess.exithandler (child_process.js:207:12) 
at emitTwo (events.js:106:13) 
at ChildProcess.emit (events.js:191:7) 
at maybeClose (internal/child_process.js:852:16) 
at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5) 
killed: false, 
code: 1, 
signal: null, 

Will appreciate your helps

Regards
Soibam

**Comment by dsabeti** [comment]
Hi @mymobileapplication, this looks to be a PCF-specific issue. The github repos are for OSS-related questions. Your best bet is to contact Pivotal support.
