### ISSUE TITLE
"SSLv3 read server certificate B: certificate verify failed" for "cf push" command

### ISSUE THREAD

**Issue by prashantgnet** [cloudfoundry/cf-release#1269]
Hello,

I am getting following error message for "cf push" command for sample app for CF v286 on Openstack environment. I am using the working copy of stub file from CF v276 environment.

Kindly let us which log files, I should share for debugging this particular issue.

We have working "cf-deployment" based environment but we really require latest version of "cf-release" based environment for migration validation.

```
Getting app info...
Creating app with these attributes...
+ name:        cf-spring
  path:        /home/centos/cf-runtime-286/sample_apps/cf-sample-app-spring
+ instances:   1
+ memory:      1G
  routes:
+   cf-spring-sweet-nyala.runtime1.test.com

Creating app cf-spring...
Mapping routes...
Comparing local files to remote cache...
Packaging files to upload...
Uploading files...
 713.05 KiB / 713.05 KiB [===================================================================================================================] 100.00% 1s

Waiting for API to complete processing files...

Staging app and tracing logs...
Unexpected Response
Response code: 503
CC code:       0
CC error code: 
Request ID:    690087dd-07b1-491c-659f-9ca5f320b1d1::3ceaf1a9-82eb-4eb0-ac17-faba287be372
Description:   {
  "description": "Stager is unavailable: SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed",
  "error_code": "CF-StagerUnavailable",
  "code": 170010
}

FAILED
```

**Comment by dsabeti** [comment]
Hi @prashantgnet. The error message suggests that there's an issue with the mutual TLS certificates. Specifically, it looks like Cloud Controller doesn't trust the certificate provided by something in Diego. I would start by searching the Cloud Controller logs -- you can search with the request (`690087dd-07b1-491c-659f-9ca5f320b1d1`) or app ID to find relevant logs.

**Comment by prashantgnet** [comment]
I really like to create all new certificates for CF and CF Diego and searching for single good documentation. Is following link good to follow? last update date was July 28 - 2017.
https://github.com/cloudfoundry/cf-release/blob/master/on-tls-certificates.md 

Planning to try "bosh2 interpolate" also.

Following error messages under "cloud_controller_clock_ctl.log" file on api instance

```
ERROR -- : Runner is unavailable: getaddrinfo: Name or service not known (bbs.service.cf.internal:8889) (VCAP::CloudController::Diego::ProcessesSync::BBSFetchError)

ERROR -- : Runner is unavailable: SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (VCAP::CloudController::Diego::ProcessesSync::BBSFetchError)
```
and also following error message under "bbs.stderr.log" of database instance of Diego

```
http: TLS handshake error from 192.168.9.34:55426: remote error: tls: unknown certificate authority
```

**Comment by prashantgnet** [comment]
Thanks a lot David for your hint! Issue is sorted out by referring bosh-lite environment based certificates.

**Comment by lordcf** [comment]
@prashantgnet :  Hi,
As you are able to resolve this issue .  Could you help us to solve the issue as we are also facing same error. We tried on normal bosh too, but still facing the same problem.

**Comment by prashantgnet** [comment]
As a workaround, I have taken all the certificates from bosh-lite based environment including property-overrides.yml file etc.

**Comment by lordcf** [comment]
@prashantgnet : Hi,
I have one question.

This is the reference document given in cf-release:283: https://docs.google.com/document/d/1pdxC1DqROqk72BDw--6b5v2r0K7Jpp9l-FbO6tlkQDs/edit.
To eanble mtls between cc and diego.

I am getting similar error what you are getting on BBS after making all the following properties set to "true"

cc.diego.temporary_local_staging
cc.diego.temporary_local_tasks
cc.diego.temporary_local_apps
cc.diego.temporary_local_tps
cc.diego.temporary_local_sync
cc.diego.temporary_cc_uploader_mtls
cc.diego.temporary_droplet_download_mtls

Did you change the above properties true from default values(false)?

**Comment by prashantgnet** [comment]
All values are set to "null" (false), default option.
