### ISSUE TITLE
missing link for generate-loggregator-certs

### ISSUE THREAD

**Issue by jyriok** [cloudfoundry/cf-release#1270]
hello,

i try to upgrade my cf-release to v270 and in this release note, we have link to for generate certificates for loggregator  ( /loggregator/scripts/generate-loggregator-certs => https://github.com/cloudfoundry/loggregator/blob/develop/scripts/generate-loggregator-certs)  but seem to be deleted/moved since 
 (404) 
can you fix that with the good link ?

https://github.com/cloudfoundry/cf-release/releases/tag/v270

thanks 

edit :

same on Loggregator release note link :( :
Loggregator 92 => https://github.com/cloudfoundry/loggregator/releases/tag/v92  (404)

must use : https://bosh.io/releases/github.com/cloudfoundry/loggregator?version=92

**Comment by jyriok** [comment]
the good one ? 
https://github.com/cloudfoundry/cf-release/blob/master/scripts/generate-loggregator-certs

**Comment by dsabeti** [comment]
Hi @jyriok. This repo is being deprecated this week: https://www.pivotaltracker.com/story/show/154853409. If you're trying to set up a new deployment, I'd recommend using [cf-deployment](https://github.com/cloudfoundry/cf-deployment).

**Comment by jyriok** [comment]
ok thanks for this information :) i will try to migrate to cf-deployment
