### ISSUE TITLE
Move all the scripts in root folder in scripts/ or bin/ subfolder

### ISSUE THREAD

**Issue by drnic** [cloudfoundry/cf-release#174]

**Comment by flavorjones** [comment]
Hi there!

We use Pivotal Tracker to provide visibility into what our team is working on. A story for this issue has been automatically created.

The current status is as follows:

* [ ] [#99824358](https://www.pivotaltracker.com/story/show/99824358) Move all the scripts in root folder in scripts/ or bin/ subfolder


This comment, as well as the labels on the issue, will be automatically updated as the status in Tracker changes.

**Comment by Amit-PivotalLabs** [comment]
Wow this is ancient!  We've got a new team, OSS Release Integration, part of our goal is to bring some consistency and best practices to how we maintain and test bosh releases.  This story is in our backlog:

https://www.pivotaltracker.com/story/show/99817668

**Comment by Amit-PivotalLabs** [comment]
This has now been done.  Closing.
