### ISSUE TITLE
Sometimes cf logs --recent and cf push return auth failed

### ISSUE THREAD

**Issue by Vukia** [cloudfoundry/cf-release#440]
Hi all,
My cf v173 sometimes can't push or logs and return:
Log:
---------------
{"access_token":"[PRIVATE DATA HIDDEN]","token_type":"bearer","refresh_token":"[
PRIVATE DATA HIDDEN]","expires_in":599,"scope":"scim.read cloud_controller.admin
 password.write scim.write openid cloud_controller.write cloud_controller.read",
"jti":"39551d80-a55c-43bb-99db-ed1669fbaf95"}
FAILED
Unauthorized error: You are not authorized. message:"Error: Invalid authorizatio
n" message_type:ERR timestamp:1405050051773965166 app_id:"2e091144-afab-4a0f-b82
0-c6c649d9d814" source_name:"LGR"
FAILED
Unauthorized error: You are not authorized. message:"Error: Invalid authorizatio
n" message_type:ERR timestamp:1405050051773965166 app_id:"2e091144-afab-4a0f-b82
0-c6c649d9d814" source_name:"LGR"
------------------
I don't know how this happened, other commands like cf apps and cf login never cause this problem.

**Comment by charyorde** [comment]
I'm seeing the above error in cf-release v211.
```
bash-3.2$ cf push
...

Using route yookore-statics.10.244.0.34.xip.io
Uploading yookore-statics...
Uploading 2.1M, 1042 files
Done uploading
OK

Stopping app yookore-statics in org yookos / space dev as admin...
OK

timeout connecting to log server, no log will be shown
Warning: error tailing logs
Unauthorized error: You are not authorized. Error: Invalid authorization

FAILED
StagingError
```

**Comment by menicosia** [comment]
Humm. I am able to get this to happen too, on a fresh install of cf-release v212 on AWS using MicroBOSH.

Here's the CF_TRACE output: https://gist.github.com/menicosia/924213f4ca11e47c1dc8

Here's the terminal copy:
```
 CF_TRACE=/tmp/trivial-js.push.out cf push
Using manifest file /Volumes/Oriente-HDD/Users/pivotal/workspace/trivial-js/manifest.yml

Creating app trivial-js in org moragasystems / space demo as marco...
OK

Creating route trivial-js.54.152.199.131.xip.io...
OK

Binding trivial-js.54.152.199.131.xip.io to trivial-js...
OK

Uploading trivial-js...
Uploading app files from: /Volumes/Oriente-HDD/Users/pivotal/workspace/trivial-js
Uploading 201.7K, 57 files
Done uploading
OK

Warning: error tailing logs
Unauthorized error: You are not authorized. Error: Invalid authorization
Starting app trivial-js in org moragasystems / space demo as marco...
^C
```

And just quickly covering my bases:
```
$ bosh releases
Acting as user 'admin' on 'my-bosh'

+----------+----------+-------------+
| Name     | Versions | Commit Hash |
+----------+----------+-------------+
| cf       | 212*     | ae2ec7a5+   |
| cf-mysql | 22       | af278086+   |
+----------+----------+-------------+
(*) Currently deployed
(+) Uncommitted changes

Releases total: 2

$ bosh vms
Acting as user 'admin' on 'my-bosh'
Deployment `cf'

Director task 8

Task 8 done

+------------------------------------+---------+---------------+----------------+
| Job/index                          | State   | Resource Pool | IPs            |
+------------------------------------+---------+---------------+----------------+
| api_z1/0                           | running | small_z1      | 10.0.16.4      |
| doppler_z1/0                       | running | small_z1      | 10.0.16.6      |
| etcd_z1/0                          | running | small_z1      | 10.0.16.104    |
| ha_proxy_z1/0                      | running | small_z1      | 10.0.0.11      |
|                                    |         |               | XX.XXX.XXX.XXX |
| hm9000_z1/0                        | running | small_z1      | 10.0.16.5      |
| loggregator_trafficcontroller_z1/0 | running | small_z1      | 10.0.16.7      |
| login_z1/0                         | running | small_z1      | 10.0.16.8      |
| nats_z1/0                          | running | small_z1      | 10.0.16.103    |
| nfs_z1/0                           | running | small_z1      | 10.0.16.105    |
| postgres_z1/0                      | running | small_z1      | 10.0.16.101    |
| router_z1/0                        | running | small_z1      | 10.0.16.102    |
| runner_z1/0                        | running | small_z1      | 10.0.16.9      |
| stats_z1/0                         | running | small_z1      | 10.0.16.10     |
+------------------------------------+---------+---------------+----------------+

VMs total: 13
```

I haven't tried deleting the current release and re-deploying. I'll try that now, using v211 and see if there's a difference.

(Re-opening since two different users are seeing the same odd behavior since it was closed.)

-- Marco N.

**Comment by menicosia** [comment]
I was worried that I had goofed a deploy somehow, so I `bosh delete deployment` and `bosh delete release cf v212` and started over with a fresh checkout of v212 from github.

Same problem. I additionally theorized maybe it's something with my app, but that's not it either - my app deploys fine to PWS.

I'm going to leave the cluster up overnight. Since I happen to be in SF, come see me for the system domain if you'd like to investigate.

-- Marco N.

**Comment by zaksoup** [comment]
Closing as @menicosia's issue was unrelated to the original filer.
