### ISSUE TITLE
Not able to set new "allow_host_access" property in cf-release manifest

### ISSUE THREAD

**Issue by amhuber** [cloudfoundry/cf-release#482]
We'd like to take advantage of the new option added in this commit:

https://github.com/cloudfoundry/warden/commit/64683f4b682dd3a2fcaed37d83d110cef12fc5b3

The new property hasn't been added to the spec or templates in cf-release so right now we'd need to set it manually in warden.yml after deployment.

Opening this in cf-release per the request in https://github.com/cloudfoundry/warden/issues/71, which also discusses why we would like to set this.

**Comment by dieucao** [comment]
Added tracker story for this
https://www.pivotaltracker.com/story/show/85565064

**Comment by flavorjones** [comment]
Hi there!

We use Pivotal Tracker to provide visibility into what our team is working on. A story for this issue has been automatically created.

The current status is as follows:

* [ ] [#99824350](https://www.pivotaltracker.com/story/show/99824350) Not able to set new "allow_host_access" property in cf-release manifest


This comment, as well as the labels on the issue, will be automatically updated as the status in Tracker changes.

**Comment by Amit-PivotalLabs** [comment]
I believe this issue is resolved by [this commit](https://github.com/cloudfoundry/cf-release/commit/238f35f3294f53c0278abe745d6b88e09131ca14).  I realize this is an old issue but feel free to re-open if this doesn't solve your concern.
