### ISSUE TITLE
error when update diffient buildpack twice

### ISSUE THREAD

**Issue by HelloLin** [cloudfoundry/cf-release#510]
hello ,i use the version of cf V172. and get the error as follow:
    first i update a offline version buildpack of nodejs for cf. after update complete, i update a online version buidpack of nodejs immediately. after 15min the buildpack of nodejs in cc blobstore are deleted by itself,both online version and offline version are disappear. how you solve the question in new version?(i test it in new version,it does not show this error)
thank you !

**Comment by fraenkel** [comment]
Please try with a more current release.  There have been a few bugs fixed when updating the same buildpack.

**Comment by dieucao** [comment]
@HelloLin There were many changes between cf v172 and v183/v186 that was available in September and I don't have all the details but it would likely take some digging to identify specific changes.
Do you still require the details for this?

**Comment by HelloLin** [comment]
thank you very much, it was the bug of the version172, and i have update the cf. it work now.
