### ISSUE TITLE
Need ability to filter logs that are being relayed from logs vm into splunk

### ISSUE THREAD

**Issue by paramveer** [cloudfoundry/cf-release#519]
We have set up relay of CF system logs into splunk. However, the volume of logs is turning out to be very large. The logs do not always publish a log level (DEBUG/INFO) and there is currently no way to filter down the logs being sent to splunk. Could we please get the following resolved:

1. All logs should report a log level in the same
2. CF should allow controlling what log level is relayed to external log systems like splunk. Having an entry in the manifest would be best

**Comment by shinji62** [comment]
Are you using splunk Universal forwarder ?  If yes, you can do mostly whatever you want on it.

**Comment by paramveer** [comment]
Please read the issues/problems from the issue description again.

**Comment by flavorjones** [comment]
Hi there!

We use Pivotal Tracker to provide visibility into what our team is working on. A story for this issue has been automatically created.

The current status is as follows:

* [ ] [#99824348](https://www.pivotaltracker.com/story/show/99824348) Need ability to filter logs that are being relayed from logs vm into splunk


This comment, as well as the labels on the issue, will be automatically updated as the status in Tracker changes.

**Comment by amitkgupta** [comment]
Hi @paramveer, sorry there has been no follow-up for so long.  The [tracker story](https://www.pivotaltracker.com/story/show/80329186) has moved to the logging team's backlog.  You may wish to follow up with an issue on [the Loggregator repository](https://github.com/cloudfoundry/loggregator), they can best address your desire to be able to filter by log level.

As for having every component include a log level with every log line, that's a very good idea.  We can try to audit for logging that doesn't include a log level, but this may not be prioritized in the near term.

Closing issue for now.

Thanks,
Amit, CF Release Integration team
