### ISSUE TITLE
uaa varz endpoint reporting wrong type

### ISSUE THREAD

**Issue by jmprice** [cloudfoundry/cf-release#576]
The varz endpoint for uaa is returning "type":"VARZ" rather than "type":"uaa".

This could be fixed by either changing cloudfoundry/cf-release/jobs/uaa/templates/varz.yml.erb to move the "type" parameter to the top level as shown below 
	---
	pid: /var/vcap/sys/run/uaa.pid
	type: uaa
	varz:
		username: _random_username_replaced_by_a_script_
		password: _random_password_replaced_by_a_script_ 
	logging:
		config: /var/vcap/jobs/uaa/config/varz.log4j.properties

Or by changing  cloudfoundry/identity-tools/varz/src/main/webapp/WEB-INF/varz-servlet.xml so that is gets the property from it's current location.

	<bean id="varzEndpoint" class="org.cloudfoundry.identity.varz.VarzEndpoint">
		<property name="server" ref="mbeanServer" />
		<property name="staticValues">
			<map>
				<entry key="type" value="${varz.type:VARZ}" />
			</map>
		</property>
		<property name="environmentProperties" ref="applicationProperties"/>
	</bean>

Jon Price
Intel Corp.

**Comment by flavorjones** [comment]
Hi there!

We use Pivotal Tracker to provide visibility into what our team is working on. A story for this issue has been automatically created.

The current status is as follows:

* [ ] [#99824344](https://www.pivotaltracker.com/story/show/99824344) uaa varz endpoint reporting wrong type


This comment, as well as the labels on the issue, will be automatically updated as the status in Tracker changes.

**Comment by Amit-PivotalLabs** [comment]
@jfmyers9 @mbhave @fhanik what's the status of this issue: "uaa varz endpoint reporting wrong type"?

**Comment by mbhave** [comment]
@Amit-PivotalLabs We are planning on moving from varz to statsd now. @jmprice Bearing that in mind, we would be happy to accept a PR if the fix is simple enough.

Thanks!

**Comment by jmprice** [comment]
Hi everyone - This was fixed quite some time ago.  Thanks for the follow-up. 

Jon Price
@jfmyers9 @mbhave @fhanik @Amit-PivotalLabs
