### ISSUE TITLE
Allow setting the cipher suite for haproxy

### ISSUE THREAD

**Issue by teancom** [cloudfoundry/cf-release#596]
The "out of the box" score for the CF API using Haproxy from https://www.ssllabs.com is a 'B' due to various insecure ciphers that are enabled (based on RC4). Now, I understand that as a big project you need to have things that work for most people, which is fine, but I'd like to be able to tighten down our ciphers to be more secure. I can also see a use case (hopefully purely internal) where people have to use Windows XP/IE6, and would need to expand the cipher list to include really awful things.

So, this issue is basically me asking: is this something that you are interested in, and would accept and pull request for? If so, I'll see what I can do about getting one put together. If not, I'll see what else I can do to mitigate the issue (ELB in AWS, etc.).

Thank you for your time and consideration.

David

**Comment by dieucao** [comment]
@teancom This is something we are interested in and would accept a PR for.
We have an existing story for this [1] but the suggested default cipher in that story is slightly out of date.
[1] https://www.pivotaltracker.com/story/show/77522856
