### ISSUE TITLE
UAA/login server lacking styling

### ISSUE THREAD

**Issue by teancom** [cloudfoundry/cf-release#602]
How can I configure my release to have the "pivotal" styling? Out of the box, going to the login url in a web browser results in something that looks like:

![login screenshot](https://cloud.githubusercontent.com/assets/609527/5839093/e2337a70-a159-11e4-8282-01f93940dbd5.png)

Looking at https://github.com/cloudfoundry/cf-release/blob/master/jobs/login/spec#L28-L29 it seemed like adding
```
properties:
  login:
    asset_base_url: '/resources/pivotal'
```

should have had some sort of effect, but it did not. In the output itself, it says that the UAA does not support a branded UI out of the box, but I was hoping for a nice "unbranded" experience. Is there something that I'm missing?

Thanks!

**Comment by drnic** [comment]
Similarly, how do we enable oss styling? It looks ugly like UAA.

**Comment by flavorjones** [comment]
Hi there!

We use Pivotal Tracker to provide visibility into what our team is working on. A story for this issue has been automatically created.

The current status is as follows:

* [ ] [#99824336](https://www.pivotaltracker.com/story/show/99824336) UAA/login server lacking styling


This comment, as well as the labels on the issue, will be automatically updated as the status in Tracker changes.

**Comment by Amit-PivotalLabs** [comment]
@mbhave @fhanik can people deploying OSS Cloud Foundry get a nice looking UAA?  Why doesn't setting `properties.login.asset_base_url` do anything, as mentioned in the original question?  I notice the UAA source has oss styling resources as well, how do people use those?

**Comment by mbhave** [comment]
@amitkgupta The UAA should have the OSS style enabled by default. Prior to the merge of the login-server and UAA, the UAA pages was unstyled, all styles were applied to the login-server pages.

**Comment by Amit-PivotalLabs** [comment]
Thanks @mbhave.  @teancom closing this, seems like OSS styling should work by default now.
