### ISSUE TITLE
php buildpack still pointing to php-buildpack-legacy

### ISSUE THREAD

**Issue by rvennam** [cloudfoundry/cf-release#631]
https://github.com/cloudfoundry/cf-release/blob/v200/config/blobs.yml#L218 
currently points to:
https://github.com/cloudfoundry/php-buildpack-LEGACY/releases/tag/v1.0.2

Are there plans to update it and point it to the new php buildpack:
https://github.com/cloudfoundry/php-buildpack/releases/tag/v3.0.4

**Comment by dieucao** [comment]
Hi @rvennam cf-release v201 and v202 have the new buildpack included.
https://github.com/cloudfoundry/cf-release/releases
