### ISSUE TITLE
Using awk to prepend logs with timestamp causing buffering problems

### ISSUE THREAD

**Issue by mheath** [cloudfoundry/cf-release#634]
Please see the comment on commit eb779033267ae10824bf513a7e28594dbf581776.

**Comment by zaksoup** [comment]
Hi @mheath, 

We committed f96e2866f11987bef430216092bd201ab080aff3 to address this issue. By adding the `-W interactive` flag to the awk command we should not buffer writing to stdout.  We think this is the best solution as it does not require us to add a new dependency to the stemcell.

Thanks,

@zaksoup + @jfmyers9, CF Runtime Team
