### ISSUE TITLE
Python buildpack: App staging failed in the buildpack compile phase

### ISSUE THREAD

**Issue by jhellan** [cloudfoundry/cf-release#637]
For most Python 3.x runtimes, we are getting 

Server error, status code: 400, error code: 170004, message: App staging failed in the buildpack compile phase

We see this in a virgin Cloud Foundry using python-buildpack 1.1.2. We have tested with CF v203 and CF v200.

Using git master python-buildpack and CF v203, staging succeeds. (This workaround does not work
for v200.)

The application is trivial, it simply writes back some environment variables.

Staging succeeds for Python 2.7.x (tested 2.7.8 and 2.7.9), and for 3.4.0 and 3.4.1.
We see the above mentioned error for all other 3.x.y we have tested: 
3.4.2
3.3.0-3.3.6
3.2.5
3.1.5

Looks like it's time for a new python-buildpack release.

**Comment by jtarchie** [comment]
@jhellan, we are going through a process of documenting (and perhaps culling) versions of the binaries across all buildpacks.

To see the supported version of binaries, you can look at the `manifest.yml` file of the root of the directory.

v1.1.2 [manifest.yml](https://github.com/cloudfoundry/python-buildpack/blob/v1.1.2/manifest.yml) includes Python 2.7.0-2.7.9, 3.2.0-3.2.3 and 3.4.0-3.4.1.

Are there reasons to support the in between versions you've documented as unsupported? 3.3, 3.1, etc.

**Comment by jhellan** [comment]
On 17. mars 2015 21:08, JT Archie wrote:
>
> @jhellan <https://github.com/jhellan>, we are going through a process 
> of documenting (and perhaps culling) versions of the binaries across 
> all buildpacks.
>
> To see the supported version of binaries, you can look at the 
> |manifest.yml| file of the root of the directory.
>
> v1.1.2 manifest.yml 
> <https://github.com/cloudfoundry/python-buildpack/blob/v1.1.2/manifest.yml> 
> includes Python 2.7.0-2.7.9, 3.2.0-3.2.3 and 3.4.0-3.4.1.
>
> Are there reasons to support the in between versions you've documented 
> as unsupported? 3.3, 3.1, etc.
>
We have an application which had been running 3.3.2 for a long time, and 
had a hard time figuring out why we could not deploy a new version.

As for the other versions, we tested some of those we found  in 
builds/runtimes. When 3.4.0 and 3.4.1 worked, and 3.4.2 was present, we 
really thought it was intended to work. Never thought of
checking manifest.yml :-)

Regards

Jon

**Comment by jtarchie** [comment]
@jhellan, did we resolve your issue? We can reopen, again.

We have upcoming [epic](https://www.pivotaltracker.com/epic/show/1747328) to better document the supported versions of our runtimes.

Thanks, JT

**Comment by jhellan** [comment]
On 24/03/15 15:32, JT Archie wrote:
>
> @jhellan <https://github.com/jhellan>, did we resolve your issue? We 
> can reopen, again.
>
> We have upcoming epic 
> <https://www.pivotaltracker.com/epic/show/1747328> to better document 
> the supported versions of our runtimes.
>
> Thanks, JT
>
Up to you. I know where to look next time. But there really should be a 
consistent way to check
for all buildpacks. E.g. there is no manifest.yml for the php buildpack.

Jon

**Comment by jtarchie** [comment]
We are glad to announce as of last week, the PHP buildpack is using the same [manifest.yml](https://github.com/cloudfoundry/php-buildpack/blob/master/manifest.yml) files as the rest of the buildpacks. :)
