### ISSUE TITLE
Size-up compilation VM disk to 8192 (8GB) to address new buildpack sizes

### ISSUE THREAD

**Issue by scotttag** [cloudfoundry/cf-release#648]
Buildpacks fail >v294 on vSphere/vCloud due to lack of filespace on default compliation VM:

`Failed compiling packages > buildpack_php/60fb983e430ab8de7fb647cba59954f8d0c4b9c9: Action Failed get_task: Task 47c66ba0-89a1-4e9a-5431-f01cfedc8dcf result: Compiling package buildpack_php: Compressing compiled package: Shelling out to tar: Running command: 'tar czf /var/vcap/data/tmp/bosh-platform-disk-TarballCompressor-CompressFilesInDir418381800 -C /var/vcap/data/packages/buildpack_php/60fb983e430ab8de7fb647cba59954f8d0c4b9c9.1- .', stdout: '', stderr: '
gzip: stdout: No space left on device
': signal: broken pipe (00:04:08)`

`Failed compiling packages > buildpack_ruby/d98a0ead8dbcc4ed3165ef4b2ef9cd909fd13657: Action Failed get_task: Task 14bb9398-9831-42be-44d5-0530d5ab74b0 result: Compiling package buildpack_ruby: Compressing compiled package: Shelling out to tar: Running command: 'tar czf /var/vcap/data/tmp/bosh-platform-disk-TarballCompressor-CompressFilesInDir146766702 -C /var/vcap/data/packages/buildpack_ruby/d98a0ead8dbcc4ed3165ef4b2ef9cd909fd13657.1- .', stdout: '', stderr: '`

https://github.com/cloudfoundry/cf-release/blob/master/templates/cf-infrastructure-vsphere.yml#L10 should be changed to 8192 or any reasonable value (8192 seems fine)

Confirmed this fixes the issue on 3 separate directors

I would do a pull request for this myself but I haven't signed the CLA and don't have a printer/scanner handy...

**Comment by DanLavine** [comment]
Hi @scotttag,

Sorry for taking so long on this issue, we were hoping to reproduce this on one of our environments, but have not found the time to set up a fresh instance. We are hoping to have smaller buildpacks, but for now we are going to pull in these changes.

Thanks for the PR!

@DanLavine && @utako, CF Runtime Team

**Comment by DanLavine** [comment]
Hi @scotttag,

This was just committed with c915e43. If you have any other concerns please feel free to reopen the issue.

Thanks,
@utako && @DanLavine, CF Runtime Team
