### ISSUE TITLE
HVM by default for aws

### ISSUE THREAD

**Issue by longnguyen11288** [cloudfoundry/cf-release#656]
Hello! I've noticed that recently instances on aws were updated in https://github.com/cloudfoundry/cf-release/commit/65a19358839dd32df9403a92f8b24d55d0cf6ef4 . I'm concerned that templates are HVM and hvm stemcells are only available on us-east-1 as light stemcells

**Comment by dieucao** [comment]
@longnguyen11288 
BOSH has a story currently in progress to publish light hvm stemcells that work in all regions.
https://www.pivotaltracker.com/n/projects/956238/stories/89044786

Does that address your concern?

**Comment by longnguyen11288** [comment]
ah. It's story for ticket I created! Looks like it's there a branch for it now. Awesome!
