### ISSUE TITLE
Permission Issue: Can't Create Service Instances

### ISSUE THREAD

**Issue by mhlandry** [cloudfoundry/cf-release#678]
I'm trying to get the introduction to spring cloud
<https://spring.io/blog/2014/06/03/introducing-spring-cloud> app working
with an instance of Cloud Foundry that I'm running on my machine. I tried
to push the app and I get this message:

        Could not find service postgres-service to bind to hello-spring-cloud

That makes sense to me so I started tracking down the postgres service.
When I run `cf marketplace`, I get:

        service      plans     description
        mongodb      default   MongoDB NoSQL database
        postgresql   default   PostgreSQL database
        rabbitmq     default   RabbitMQ message queue
        redis        default   Redis key-value store

When I try to create a service instance of the postgresql service and I
get:

        $ cf create-service postgresql default postgresql-service
        Creating service instance postgresql-service in org xyz / space development as admin...
        FAILED
        Server error, status code: 500, error code: 10001, message: Service broker error: Not authorized

I have tried running `cf create-service-auth-token postgresql core 123` but that didn't seem to help with the `Not Authorized` message.

Here are the permissions for the space:

        Getting users in org xyz / space development as admin

        SPACE MANAGER
        admin

        SPACE DEVELOPER
        Admin

The cf service-access command doesn't yield anything interesting:

        $ cf service-access
        Getting service access as admin

Then it shows nothing on the terminal. So I tried to enable service access

        $ cf enable-service-access postgresql
        Enabling access to all plans of service postgresql for all orgs as admin...
        All plans of the service are already accessible for all orgs
        OK

For the life of me, I can¹t figure out what's going on.  Can someone help?

**Comment by dsabeti** [comment]
Hi, I've got a few questions to get started.
1. Which broker is offering the service? Is it the v1 broker in https://github.com/cloudfoundry-community/cf-services-contrib-release?
2. Which version of CF are you running?
3. Can you show the output of the same command with `CF_TRACE=true`?

Thanks,
David

**Comment by shalako** [comment]
The issue is you haven't registered a service auth token. You're using v1 services (cf-services-contrib-release) which use a legacy integration. 

See http://docs.cloudfoundry.org/services/api-v1.html#authentication

See `cf help create-service-auth-token`
