### ISSUE TITLE
Cannot connect to local Cloud Foundry deployment when behind proxy

### ISSUE THREAD

**Issue by mhlandry** [cloudfoundry/cf-release#679]
I cannot set my api endpoint when I am behind my corporate proxy. I am following the Cloud Foundry deployment steps in the readme, but whenever I run the command `cf api --skip-ssl-validation https://api.10.244.0.34.xip.io`, I get this error:

     $ cf api --skip-ssl-validation https://api.10.244.0.34.xip.io
     Setting api endpoint to https://api.10.244.0.34.xip.io...
     FAILED
     Error performing request: Get https://api.10.244.0.34.xip.io/v2/info: read tcp <my ip>: connection reset by peer`

My vagrant VM is running, and bosh cck shows no errors and both my http_proxy and https_proxy vars are set. I have tried setting my no_proxy as well, as instructed from the readme:

     $ printenv
     ...
     no_proxy=192.168.50.4,*.xip.io

However, if I disconnect from the company's network and use my own network connection at home, then I do not get the error. Is there something else I need to do to be able to work behind a proxy?

**Comment by DanLavine** [comment]
Hi @mhlandry,
 
Most likely when connected to the company network, whatever client you are using for that has updated your routes to send network traffic over that link first.

If you haven't already done so, run the `bin/add-route` script from the bosh-lite repository.

If that doesn't work, you might need to adjust your routes table in some other way to force the traffic to be routed to the Vagrant VM

The CF Runtime Team,
@jpalermo && @DanLavine

**Comment by mhlandry** [comment]
Hi @DanLavine,

Thanks for the reply.  I did add the route but I still have the same issue.  If I turn on CF_TRACE, I wind up getting:
```
Error performing request: Get https://api.10.244.0.34.xip.io/v2/info: read tcp x.x.x.x:80: connection reset by peer
```
where x.x.x.x:80 is an IP address on my company's internal network.

But if I curl the URL, I get a good response:
```
{"name":"vcap","build":"2222","support":"http://support.cloudfoundry.com","version":2,"description":"Cloud Foundry sponsored by Pivotal","authorization_endpoint":"http://login.10.244.0.34.xip.io","token_endpoint":"https://uaa.10.244.0.34.xip.io","min_cli_version":null,"min_recommended_cli_version":null,"api_version":"2.27.0","logging_endpoint":"wss://loggregator.10.244.0.34.xip.io:443"}%
```

So it seems to me that the cf cli is ignoring my proxy settings somewhere along the line...

**Comment by utako** [comment]
Hi @mhlandry,

The problem with using `xip.io` is that it requires external network activity. You might want to take a look at their [documentation](http://xip.io/). Unless you do something to force traffic to your bosh-lite deployment, unfortunately we don't think there's a workaround for this.  

As an aside, we noticed that you might want to target `api.10.244.xip.io` instead of `https://api.10.244.xip.io` once you've sorted that out (the cli doesn't require you to include the protocol when targeting an api). 

Hope that helps,
@DanLavine && @utako, CF Runtime Team

**Comment by mhlandry** [comment]
Hello @DanLavine and @utako.  I don't think the problem is with my external network activity or xip.io.  From the same terminal that I run the cf api command, I can successfully curl the target.  Doesn't this eliminate network connectivity and xip.io as potential culprits?

**Comment by zaksoup** [comment]
Hi @mhlandry 
It definitely looks like an issue in the way the cli is attempting to communicate with your bosh lite inside the corporate network. That being the case, I'm not sure Runtime can help you much. I'm adding @goehmen (CLI Project Manager) to this conversation to try and sort this out.

Sorry for the continued confusion,
@zaksoup + @wendorf CF Runtime Team

**Comment by Quintaminant** [comment]
Hi @mhlandry,

It looks like you also opened an issue on the (cli)[https://github.com/cloudfoundry/cli/issues/464]. Our investigation so far indicates that the CLI is indeed the more informed team on this matter, so we've decided to close this issue and migrate the conversation to that thread.

@Quintaminant && @DanLavine, CF Runtime Team

**Comment by mhlandry** [comment]
Thanks @Quintaminant and @DanLavine.  I wasn't sure where to create the issue.  Thanks for pointing me in the right direction!

**Comment by sparameswaran** [comment]
Can you try a no_proxy env variable for the xip.io address and test?

 export no_proxy="localhost,127.0.0.1,localaddress,.xip.io"

Then run cf api api.10.244.0.34.xip.io --skip-ssl-validation?

**Comment by mhlandry** [comment]
@sparameswaran Does it matter if no_proxy is capitalized or lowercase?  If it does not matter, then from above my no_proxy is currently `192.168.50.4,*.xip.io`

**Comment by sparameswaran** [comment]
Dont put * in front of the .xip.io (leave it as .xip.io), and no_proxy is
in small case.

-Sabha

**Comment by mhlandry** [comment]
@sparameswaran I have tried without the * as well but I got the same result.

**Comment by sparameswaran** [comment]
Can you have CF_TRACE=true cf api ... and see if its still trying to go
over your proxy or not?

-Sabha
