### ISSUE TITLE
Sensitive Credentials in VCAP_SERVICES

### ISSUE THREAD

**Issue by abhikco** [cloudfoundry/cf-release#686]
Hi,
I was wondering if it would be possible to mark a credential field, provided by a service, as sensitive. For example, to connect with a database instance, the database's service broker must send back the user and password along with the connection details. 

In this scenario, the password is a security-sensitive field- however, there isn't any way of knowing that from the VCAP_SERVICES environment variable. Also, if one is building a Cloud Foundry UI environment (similar to the run.pivotal), it might be a flaw to display all credentials as text.

Is there a way a sensitive field can be identified? Perhaps, via minor modifications to the Service Broker APIs?

**Comment by zaksoup** [comment]
hey @abhikco, We've moved this story over to the services API team's backlog. Their PM/engineers are going to take a look at it and hopefully take it from here! Keep an eye on the tracker story that cf-gitbot linked for changes!

Thanks for bringing this up!
Zak, CF Runtime Team

**Comment by shalako** [comment]
Hello @abhikco, all data in the `credentials` hash in VCAP_SERVICES is considered sensitive. Only users with the SpaceDeveloper role should have access to credentials.

```
 "VCAP_SERVICES": {
  "fake-service": [
   {
    "credentials": {
     "database": "fake-dbname",
     "host": "fake-host",
     "password": "fake-password",
     "port": 3306,
     "uri": "fake-service://fake-user:fake-password@fake-host:3306/fake-dbname",
     "username": "fake-user"
    },
    "label": "fake-service",
    "name": "myfake",
    "plan": "fake-plan",
    "tags": [
     "no-sql",
     "relational"
    ]
   }
  ]
}
```

A user who does not have the SpaceDeveloper role receives responses from CF that redact `credentials` in some cases, or returns a `403 Forbidden` response in others.

As this information is already restricted, could you provide some additional explanation for why the security implications of individual fields within `credentials` must be differentiated? 

Thank you!

**Comment by shalako** [comment]
Hello @abhikco, I'm going to assume we've answered your question and mark this issue closed. If I haven't answered your question, and you can provide more context, feel free to re-open it. 
Thank you!
