### ISSUE TITLE
Manifest templates missing metron agent deployment property

### ISSUE THREAD

**Issue by mjseid** [cloudfoundry/cf-release#690]
Using v210 and the generate manifest script, the created template gives the following error:

 Started preparing configuration > Binding configuration. Failed: Error filling in template `metron_agent.json.erb' for `ha_proxy_z1/0' (line 5: Can't find property `["metron_agent.deployment"]') (00:00:00)

Error 100: Error filling in template `metron_agent.json.erb' for `ha_proxy_z1/0' (line 5: Can't find property `["metron_agent.deployment"]')

See related issue:
https://github.com/cloudfoundry/bosh-lite/issues/265

**Comment by djvdorp** [comment]
We're running into the exact same issue as described by @cdavisafc (via @mjseid, found above).

**Comment by jpalermo** [comment]
We're not seeing this problem.

`metron_agent.deployment` should be getting filled in by `cf-release/templates/cf-lamb.yml`

Could you provide the following to help us troubleshoot?

OS, spiff version, and which infrastructure you are deploying to.

Thanks.

**Comment by mjseid** [comment]
Sure.  I do have the cf-lamb.yml you referenced, and it does contain some metron agent deployment specs as the last 2 lines of the file.
OS: ubuntu
Spiff: 1.0.3
IaaS: Vsphere

**Comment by jpalermo** [comment]
Hmm, and in the deployment manifest that gets generated. Do you have a `properties.metron_agent` section at the top level?

**Comment by mjseid** [comment]
there is a metron_agent section that gets created under top level properties:
  metron_agent:
    deployment: null

But then each job only gets the zone property and not a deployment property Ex:
jobs:
- instances: 0
  name: consul_z1
  networks:
  - name: cf1
    static_ips: []
  persistent_disk: 1024
  properties:
    consul:
      agent:
        mode: server
    metron_agent:
      zone: z1
  resource_pool: medium_z1
  templates:
  - name: consul_agent
    release: cf
  - name: metron_agent
    release: cf
  update:
    max_in_flight: 1
    serial: true

**Comment by jpalermo** [comment]
Yes, each job will not get the property, it is only expected to live at the top level.

BOSH will apply any top level properties to every job, then the job specific properties will overwrite those.

Do you have the `meta.environment` property configured in your stub file?

**Comment by mjseid** [comment]
Nope, I didn't have that setting....guess things have worked fine til now without it. Upon setting it, and re-generating a manifest the resulting yml is identical to before though.  Here's how my stub looks now:
```
---
director_uuid: 5ef4e3d1-dd48-4196-b24c-689b091f75df 
name: cf_mine
meta:
  enviornment: cfmine
  default_env:
    # default vcap/root password on deployed VMs
    bosh:
```
Is that the correct usage?  Is null an acceptable value for the environment parameter?

**Comment by jpalermo** [comment]
You have a typo in environment.

**Comment by mjseid** [comment]
Oops.  Ok, that added it to the properties section.  Thanks

**Comment by djvdorp** [comment]
I'm sorry for commenting on this issue while it's already closed, but I'm currently running into pretty much the same issue here.

Trying to install a cf-aws-large deployment with version 210.
OS: ubuntu
Spiff: 1.0.3
IaaS: AWS

I checked everything that's already mentioned here:

- CF-Lamb seems to be fine (```/home/ubuntu/workspace/deployments/cf-boshworkspace/.releases/cf/templates/cf-lamb.yml```):
```
meta:
  environment: ~

lamb_meta:
  release:
    name: cf

  loggregator_templates:
  - name: doppler
    release: (( lamb_meta.release.name ))
  - name: syslog_drain_binder
    release: (( lamb_meta.release.name ))
  - name: metron_agent
    release: (( lamb_meta.release.name ))

  loggregator_trafficcontroller_templates:
  - name: loggregator_trafficcontroller
    release: (( lamb_meta.release.name ))
  - name: metron_agent
    release: (( lamb_meta.release.name ))

jobs:
- name: loggregator_z1
  properties:
    doppler:
      zone: z1
    metron_agent:
      zone: z1

- name: loggregator_z2
  properties:
    doppler:
      zone: z2
    metron_agent:
      zone: z2

- name: loggregator_trafficcontroller_z1
  properties:
    traffic_controller:
      zone: z1
    metron_agent:
      zone: z1

- name: loggregator_trafficcontroller_z2
  properties:
    traffic_controller:
      zone: z2
    metron_agent:
      zone: z2

properties:
  <<: (( merge ))

  loggregator:
    maxRetainedLogMessages: 100
    debug: (( merge || false ))
    blacklisted_syslog_ranges: ~

  doppler:
    maxRetainedLogMessages: 100
    debug: (( merge || false ))
    blacklisted_syslog_ranges: ~
    unmarshaller_count: (( merge || 5 ))

  metron_agent:
    deployment: (( meta.environment ))
```

- Stub has ```meta.environment``` property configured (```/home/ubuntu/workspace/deployments/cf-boshworkspace/.stubs/cf-aws-large.yml```):
```
---
name: cf-aws-large
director_uuid: ae64e1ad-3ceb-4ff0-9e9b-55012142602c
releases:
- name: cf
  version: 210
meta:
  environment: cf-aws-large
```

However, the ```properties.metron_agent``` section at the top level (```properties:``` without any indentation) is missing, even though I think that CF-Lamb should generate it (```/home/ubuntu/workspace/deployments/cf-boshworkspace/.deployments/cf-aws-large.yml```).

**Comment by djvdorp** [comment]
Update:

In the mean time, I tried to work around the issue by using a higher version of CloudFoundry to install with https://github.com/cloudfoundry-community/terraform-aws-cf-install (cf_release_version = 212 instead of the default 210) but I'm hitting the same issue. 

This might mean that something might be wrong in the deployments/templates provided by that that project? I will try to pinpoint this some more, as far as I'm able to, any input or help would be greatly appreciated!

The spiff command used for merging (with ```cf_size = "large"```):
```
spiff merge /home/ubuntu/workspace/deployments/cf-boshworkspace/templates/cf/cf-deployment.yml /home/ubuntu/workspace/deployments/cf-boshworkspace/templates/cf/cf-jobs.yml /home/ubuntu/workspace/deployments/cf-boshworkspace/templates/cf-uaa-port.yml /home/ubuntu/workspace/deployments/cf-boshworkspace/templates/cf-allow-services-access.yml /home/ubuntu/workspace/deployments/cf-boshworkspace/templates/cf/cf-properties.yml /home/ubuntu/workspace/deployments/cf-boshworkspace/templates/cf/cf-infrastructure-aws.yml /home/ubuntu/workspace/deployments/cf-boshworkspace/templates/cf/cf-minimal-dev.yml /home/ubuntu/workspace/deployments/cf-boshworkspace/templates/cf/cf-lamb.yml /home/ubuntu/workspace/deployments/cf-boshworkspace/templates/cf-runners.yml /home/ubuntu/workspace/deployments/cf-boshworkspace/templates/cf-single-az.yml /home/ubuntu/workspace/deployments/cf-boshworkspace/templates/cf-no-ssl.yml /home/ubuntu/workspace/deployments/cf-boshworkspace/templates/cf-test-errands.yml /home/ubuntu/workspace/deployments/cf-boshworkspace/templates/cf-properties.yml /home/ubuntu/workspace/deployments/cf-boshworkspace/templates/cf-use-haproxy.yml /home/ubuntu/workspace/deployments/cf-boshworkspace/templates/cf-use-postgresql.yml /home/ubuntu/workspace/deployments/cf-boshworkspace/templates/cf-use-nfs.yml /home/ubuntu/workspace/deployments/cf-boshworkspace/templates/cf-secrets.yml /home/ubuntu/workspace/deployments/cf-boshworkspace/templates/cf-networking.yml /home/ubuntu/workspace/deployments/cf-boshworkspace/templates/cf-deployment-size.yml /home/ubuntu/workspace/deployments/cf-boshworkspace/.stubs/cf-aws-large.yml 2>&1
```
