### ISSUE TITLE
[bosh-lite] Please allow security group access to collocated services

### ISSUE THREAD

**Issue by drnic** [cloudfoundry/cf-release#704]
Not sure yet where this patch goes; but could we please allow access to `10.244.2.0-10.255.255.255`?

That is, add this to the default security groups for bosh-lite deployments?

```
        - protocol: all
          destination: 10.244.2.0-10.255.255.255
```

**Comment by dieucao** [comment]
Here's an example of a PR that adds a default security group to bosh-lite's configuration
https://github.com/cloudfoundry/cf-release/pull/681

**Comment by jpalermo** [comment]
@drnic, is there a reason everybody would want this opened up vs. you adding this to a stub that gets merged when you run `generate_deployment_manifest`?

It seems like the range is quite large. All of the cf2 network and all of the services2 network. (cf1 and services1 being excluded from the range)

**Comment by drnic** [comment]
It's bosh-lite - ppl want to deploy services and have apps access them. Currently it's painful/ confusing for new users who all ask "why can't my app access my service?"

**Comment by jpalermo** [comment]
Is the services security group that is open for `10.244.1.0/24` and `10.244.3.0/24` not a large enough range to work in?

**Comment by drnic** [comment]
Typically each new bosh release with its own templates will pick a unique 10.244.X.0/24 range so as to not clash with Pivotal's MySQL service etc; and so they can be easily deployed without changing networking files.

**Comment by jpalermo** [comment]
How do you feel about the range of 10.244.4.0-10.253.255.255?

10.254.x.x is used by running apps in warden, so if we go any higher, those apps can suddenly talk with each other.

**Comment by drnic** [comment]
Sounds great, thanks!

**Comment by jpalermo** [comment]
https://github.com/cloudfoundry/cf-release/commit/25bf0c8032bb186c133a3517d874e6ca39abb462
