### ISSUE TITLE
Deployment name not found in the deployment manifest

### ISSUE THREAD

**Issue by kennetham** [cloudfoundry/cf-release#706]
Hi

I managed to `bosh create release` & `bosh upload release` successfully. However when I executed the command `bosh deploy`, the following error message was returned.

```text
Processing deployment manifest
------------------------------
Deployment name not found in the deployment manifest
```

Any advise to why am I receiving this?

**Comment by Quintaminant** [comment]
Hi @kennetham,

The probable cause is your cf-stub, which might be missing these parameter:

```
name: name_of_deployment_here.

meta:
  environment: name_of_deployment_here
```

Hope this helps,
@Quintaminant && @DanLavine, CF Runtime Team

**Comment by kennetham** [comment]
Hi @Quintaminant,

Please correct me if I am wrong, but this is my cf-stub file
https://gist.github.com/kennetham/499c4cd56a55f4ddde19

**Comment by MarcSchunk** [comment]
Hi kennetham,

we do not see anything obvious wrong in your manifest. However the error message you are getting suggests that the deployment name was not resolved. Doing a 
```
name:
```
will give you the same message. 

Passing in the manifest directly to deploy should be fine. In case there is some preprocessing, it seems thats erasing or not filling in the deployment name. 

@Quintaminant & @MarcSchunk of the runtime team

**Comment by kennetham** [comment]
@MarcSchunk That's weird... Okay so how about, if I have this complete cf-deployment.yml file, I use this file to `bosh create release` & `bosh upload release` once more, and see if it works. Because after the release was uploaded, there were a few changes made to this `cf-deployment.yml` file.

Please advise.

Thanks @Quintaminant @MarcSchunk

**Comment by MarcSchunk** [comment]
Hi kennetham,

sure go ahead and test your manifest. 

If you encounter an issue, you feel is a bug in cloudfoundry, feel free to get in touch with us again.

**Comment by kennetham** [comment]
@MarcSchunk Yup. Could I just confirm, following the docs on cloud foundry, I have to do a Spiff merge of yml configuration file. However, if I were to use my existing `cf-deployment.yml` directly, skipping the spiff merge part, would that be fine? I believe my `cf-stub.yml` has some mistakes which I wouldn't want to spend time debugging on, instead I would prefer to run test on `cf-deployment.xml`

Thanks!

**Comment by MarcSchunk** [comment]
The way this is supposed to work is that you have your config in one file that gets spiff merged with one of the stubs on the cf-release/templates. You can do the spiff merge any time to a temporary file and compare that to your current manifest (bosh download manifest).You can iterate on that until your config will produce your current cf-deployment.yml

You can certainly use your cf-deployment.yml - this way you will have to merge any update to the stubs manually into your deployment. 

@Quintaminant & @MarcSchunk

**Comment by kennetham** [comment]
@MarcSchunk May I ask what are the updates are we looking at? If it's like IP addresses, I don't have much updates, I am using the old IP address. Stemcells, I will have to manually update yes. MicroBOSH size have been resized, I will have to change that too?

Please advise.

**Comment by kennetham** [comment]
@MarcSchunk & @Quintaminant 

I realized it would be best to merge them with Spiff. Here's some questions.

In `cf-stub.yml` there's these 2 configurations. `deployment-name` & `cf_release`

So can I put it that the `deployment-name would be anything I name this particular deployment. And the `cf_release` is the release of the cf version, for example: 208, etc?

```text
<%
director_uuid = '21a5ff84-47c7-420b-966d-d3c4a1a17fb1'
floating_ip = '10.x.x.x'
root_domain = "#{floating_ip}.xip.io"
net_id = 'c8708afa-6d12-4b53-9299-8fa97cc7936c'
deployment_name = 'cfyrl01'
cf_release = '208'
protocol = 'http'
common_password = 'c1oudc0w'
%>
---
name: <%= deployment_name %>
director_uuid: <%= director_uuid %>

meta:
  openstack:
    net_id: <%= net_id %>
    auth_url: http://10.x.x.x:5000/v2.0
    tenant: cf_hook
    username: kenneth
    api_key: 123456
    security_groups: [Bosh]

releases:
 - name: cf
   version: <%= cf_release %>
```

**Comment by MarcSchunk** [comment]
correct

**Comment by kennetham** [comment]
great I will try that out again!

**Comment by zrob** [comment]
closing this issue,  please re-open or create a new issue if this isn't resolved @kennetham
