### ISSUE TITLE
Setting login.saml.signMetadata and login.saml.signRequest at login.yml

### ISSUE THREAD

**Issue by palonsoro** [cloudfoundry/cf-release#707]
Hi.
I have been doing some testing integrations with a SAML identity provider. In order to achieve it, I had to set to false `login.saml.signMetadata` and `login.saml.signRequest` at `login.yml` UAA configuration file (I know that I would not do this in production, but it was just a quick test in a lab environment).
However, there are no properties defined in the UAA job of the cf-release to set these configuration settings in the UAA and I think they may be useful.

**Comment by flavorjones** [comment]
Hi there!

We use Pivotal Tracker to provide visibility into what our team is working on. A story for this issue has been automatically created.

The current status is as follows:

* [ ] [#99824320](https://www.pivotaltracker.com/story/show/99824320) Setting login.saml.signMetadata and login.saml.signRequest at login.yml


This comment, as well as the labels on the issue, will be automatically updated as the status in Tracker changes.

**Comment by palonsoro** [comment]
Pull request #727 already fixed this issue. I thought I had already closed it. Sorry. Closing
