### ISSUE TITLE
Failed updating job api_z1 > api_z1/0 (canary): `api_z1/0' is not running after update (00:12:13)

### ISSUE THREAD

**Issue by Dulanjalie** [cloudfoundry/cf-release#712]
I am bringing up cloud foundry using minimal-aws.yml
 
I am hitting below error
   Failed updating job api_z1 > api_z1/0 (canary): `api_z1/0' is not running after update (00:12:13)
Error 400007: `api_z1/0' is not running after update

I see this error in /cloud_controller_worker_ctl.log
./cloud_controller_worker_ctl.log:{"timestamp":1434996874.6546366,"message":"(0.003843s) UPDATE \"delayed_jobs\" SET \"guid\" = 'a3af8feb-30b7-4b4d-91fd-112045501a0d', \"created_at\" = '2015-06-22 18:14:32.651086+0000', \"updated_at\" = CURRENT_TIMESTAMP, \"priority\" = 0, \"attempts\" = 0, \"handler\" = '--- !ruby/struct:VCAP::CloudController::Jobs::ExceptionCatchingJob\nhandler: !ruby/struct:VCAP::CloudController::Jobs::RequestJob\n  job: !ruby/struct:VCAP::CloudController::Jobs::TimeoutJob\n    job: !ruby/struct:VCAP::CloudController::Jobs::Runtime::BuildpackInstaller\n      name: java_buildpack\n      file: \"/var/vcap/packages/buildpack_java/java-buildpack-v2.5.zip\"\n      opts: {}\n      config: \n  request_id: \n', \"last_error\" = NULL, \"run_at\" = '2015-06-22 18:14:32.660520+0000', \"locked_at\" = '2015-06-22 18:14:34.649651+0000', \"failed_at\" = NULL, \"locked_by\" = 'cc_api_worker.api_z1.0.2', \"queue\" = 'cc-api_z1-0', \"cf_api_error\" = NULL WHERE (\"id\" = 1)","log_level":"debug2","source":"cc.background","data":{},"thread_id":69964119192340,"fiber_id":69964148702360,"process_id":2727,"file":"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.1.0/gems/sequel-4.15.0/lib/sequel/database/logging.rb","lineno":70,"method":"block in log_each"}

I have tried running bosh deploy multiple times and also i tried using m3.large size VM but still the same issue.

**Comment by Quintaminant** [comment]
Hi @Dulanjalie,

We are attempting to recreate your error, but need some information about your workflow. Are you deploying a fresh CF instance, or updating an existing one? In either case, could you provide the release version numbers you are working with?

Thanks!
@Quintaminant & @DanLavine of CF Runtime Team

**Comment by Dulanjalie** [comment]
Hi @Quintaminant & @DanLavine,
I have tried fresh CF instance and updating multiple times.

This are the versions that i have tried today.
git cloned the latest https://github.com/cloudfoundry/cf-release.git
I am using the latest stemcells 2999
+-----------------------------------------+---------+--------------------+
| Name                                    | Version | CID                |
+-----------------------------------------+---------+--------------------+
| bosh-aws-xen-hvm-ubuntu-trusty-go_agent | 2989    | ami-8bc83be0 light |
| bosh-aws-xen-hvm-ubuntu-trusty-go_agent | 2999*   | ami-4dcc3526 light |
+-----------------------------------------+---------+--------------------+
(*) Currently in-use
Finally, i am using 212 release
bosh releases
+------+----------+-------------+
| Name | Versions | Commit Hash |
+------+----------+-------------+
| cf   | 193      | 54613ebb+   |
|      | 212*     | ae2ec7a5+   |
+------+----------+-------------+

**Comment by Dulanjalie** [comment]
i asked the cf-bosh mail group about this and no luck yet. 
email discussion can be found @ http://fpaste.org/236327/14351791/

**Comment by zaksoup** [comment]
Hi @Dulanjalie 

We don't believe that message you're seeing in the cc_ctl.log is an actual error. Can you bosh ssh onto the failing api vm and run a `monit summary` command as the `sudo` user? Once you've found which job on the VM is failing please give us the output of the relevant logs for that job. Alternatively you can run `bosh logs api [index]` to download all of the logs for the failing api vm. In your case `index` will be 0.

Best,
@zaksoup + @myshkin5 CF Runtime + LAMB teams

**Comment by Dulanjalie** [comment]
Hi
I removed NFS server and used S3 bucket. then i was able to deploy successfully. I have no idea why NFS didnt work. I'll paste what i did

cc:
  buildpacks:
    buildpack_directory_key: cfBucket
    cdn: null
    fog_connection:
      provider: 'AWS'
      aws_access_key_id: ACCESS_KEY
      aws_secret_access_key: SECRET
  droplets:
    cdn: null
    droplet_directory_key: cfBucket
    fog_connection:
      provider: 'AWS'
      aws_access_key_id: ACCESS_KEY
      aws_secret_access_key: SECRET
  packages:
    app_package_directory_key: cfBucket
    cdn: null
    fog_connection:
      provider: 'AWS'
      aws_access_key_id: ACCESS_KEY
      aws_secret_access_key: SECRET
  resource_pool:
    cdn: null
    resource_directory_key: cfBucket
    fog_connection:
      provider: 'AWS'
      aws_access_key_id: ACCESS_KEY
      aws_secret_access_key: SECRET

Where

- cfBucket is the name of your bucket
- ACCESS_KEY is the S3 access key id
- SECRET is the secret access key

Please be sure that your credentials have writing permissions. If you have issues deploying this, try deleting the deployment and deploying again. Once everything works fine, you can remove the NFS VM. To do so, replace this

- name: nfs_z1
  instances: 1
  persistent_disk: 102400
  resource_pool: small_z1
  templates:
  - {name: debian_nfs_server, release: cf}
  - {name: metron_agent, release: cf}
  networks:
  - name: cf_private
    static_ips: [10.0.16.105]
    
With this:

- name: nfs_z1
  instances: 0
  persistent_disk: 102400
  resource_pool: small_z1
  templates:
  - {name: debian_nfs_server, release: cf}
  - {name: metron_agent, release: cf}
  networks:
  - name: cf_private
    #static_ips: [10.0.16.105]

To prevent the cloud controller from trying to mount the NFS endpoint.

To do so, look for this:

- name: api_z1
  instances: 1
  resource_pool: small_z1
  templates:
  - {name: cloud_controller_ng, release: cf}
  - {name: cloud_controller_worker, release: cf}
  - {name: cloud_controller_clock, release: cf}
  - {name: metron_agent, release: cf}
  - {name: nfs_mounter, release: cf}
  networks:
  - name: cf_private
  properties:
    nfs_server:
      address: 10.0.16.105
      allow_from_entries: [10.0.16.0/24]

And comment out the properties section, to transform it in this:

- name: api_z1
  instances: 1
  resource_pool: small_z1
  templates:
  - {name: cloud_controller_ng, release: cf}
  - {name: cloud_controller_worker, release: cf}
  - {name: cloud_controller_clock, release: cf}
  - {name: metron_agent, release: cf}
  - {name: nfs_mounter, release: cf}
  networks:
#  - name: cf_private
#  properties:
#    nfs_server:
#      address: 10.0.16.105
#      allow_from_entries: [10.0.16.0/24]

Then go to the main properties: section, look for this snippet (it looks like part of the previous one)

nfs_server:
    address: 10.0.16.105
    allow_from_entries: [10.0.16.0/24]

and comment it out, to transform it in this:

#nfs_server:
#    address: 10.0.16.105
#    allow_from_entries: [10.0.16.0/24]

Then, do a bosh deploy

**Comment by zrob** [comment]
@Dulanjalie 

Glad to see you were able to get things working.  We have recently identified a race condition that would cause the behavior you were seeing.  If you're curious about it you can follow the progress of the bug here:  https://www.pivotaltracker.com/story/show/98158086

I'll leave this issue open until that bug is completed.  Sorry you ran into this annoying issue!

**Comment by Dulanjalie** [comment]
@zrob
Happy to hear that issue with NFS is found and will be fixed. S3 buckets cost me more :)

**Comment by zaksoup** [comment]
The previously mentioned bug was accepted on July 8th and made it into CF v213, however due to issues with a backwards-incompatible migration we have held the release of 213. I will update this story when we have a final release with the fix. In the mean time you can get the fix by pulling the latest version of cf-release/master.

Best,
@zaksoup + @duncwinn CF Release Integration (previously known as runtime) team.

**Comment by Amit-PivotalLabs** [comment]
@Dulanjalie v213 has been un-reverted.  Because of the migration issue @zaksoup mentioned, you may or may not wish to use that version, but it is available with the bug fix.  In general, you can consume cf-release as soon as a bug fix is made available, you may choose whether or not to wait for a final release at your discretion.

**Comment by malu80** [comment]
Hi Team,

Any fix available for this issue now. i used CF-213 but still geting same error as mentioned below.

Started updating job etcd_z1 > etcd_z1/0 (canary). Failed: `etcd_z1/0' is not running after update (00:10:31)

Error 400007: `etcd_z1/0' is not running after update

**Comment by Amit-PivotalLabs** [comment]
Hi @malu80,

Sounds like you're hitting a different issue.  Do you mind opening a separate issue?  Please add any information that you think will help people answer your question, e.g. whether it's a fresh deploy or upgrade from a previous cf-release, which IaaS you're on, any relevant lines from bosh logs, etc.
