### ISSUE TITLE
bosh-lite generated manifest is missing "gateway" property

### ISSUE THREAD

**Issue by apoydence** [cloudfoundry/cf-release#735]
I tried to deploy to my bosh-lite using the generated manifest and I got:

```
Error 40001: Required property `gateway' was not specified in object ({"cloud_properties"=>{"name"=>"random"}, "range"=>"10.244.0.0/30", "reserved"=>["10.244.0.1"], "static"=>["10.244.0.2"]})
```

My bosh version is:

```
bosh -v
BOSH 1.3004.0
```
I fixed it for me by replacing all the:
```
reserved:
 - 10.244.XXX.XXX
```

with:
```
gateway: 10.244.XXX.XXX
```

I'm not sure what stubs need to reflect this change.

**Comment by cppforlife** [comment]
What does 'bosh status' show? Which bosh-lite version are you using?

**Comment by apoydence** [comment]
```
bosh status
Config
             /Users/pivotal/.bosh_config

Director
  Name       Bosh Lite Director
  URL        https://lite-2:25555
  Version    1.3012.0 (00000000)
  User       admin
  UUID       04623b35-e52a-402c-988f-b6771ef67b32
  CPI        cpi
  dns        disabled
  compiled_package_cache disabled
  snapshots  disabled

Deployment
  Manifest   /Users/pivotal/workspace/cf-release/bosh-lite/manifests/cf-manifest.yml
```

**Comment by cppforlife** [comment]
Interesting. I don't think latest bosh-lites provide latest bosh version. 

Did you build bosh-lite vm yourself or consumed one of the prebuilt ones?

**Comment by apoydence** [comment]
According to @ajackson it is a pre-built bosh and a pre-built warden cpi.

**Comment by flavorjones** [comment]
Hi there!

We use Pivotal Tracker to provide visibility into what our team is working on. A story for this issue has been automatically created.

The current status is as follows:

* [ ] [#99824312](https://www.pivotaltracker.com/story/show/99824312) bosh-lite generated manifest is missing "gateway" property


This comment, as well as the labels on the issue, will be automatically updated as the status in Tracker changes.

**Comment by jpalermo** [comment]
According to @cppforlife, this is a custom built environment using the warden cpi and a newer version of BOSH that is not yet supported by cf-release.

Something will likely have to be done with this eventually, but it is not currently high on our priority list. A pull request that works with both the version you're running and the latest version of bosh-lite would be welcome though.

**Comment by bgandon** [comment]
Hi guys,
Just to let you know, I've submitted the PR #757 so that other people can benefit from deploying the cf-release on a recent Bosh version in a bosh-lite box.
Cheers
