### ISSUE TITLE
Error during deployment with current git and v211

### ISSUE THREAD

**Issue by jhiemer** [cloudfoundry/cf-release#745]
Hi,
today I tried to deploy CF with the current manifest. After configuring the manifest 

````
./generate_deployment_manifest vsphere cf-stub.yml > cf-deployment.yml
````

And starting the deploy with `bosh deploy`, I always get:

````
 Started preparing configuration > Binding configuration. Failed: Error filling in template `agent_ctl.sh.erb' for `uaa_z1/0' (line 31: undefined method `tr' for ["uaa", {}]:Array) (00:00:01)

Error 100: Error filling in template `agent_ctl.sh.erb' for `uaa_z1/0' (line 31: undefined method `tr' for ["uaa", {}]:Array)
````

Which seems to be a problem according to the diego part: https://github.com/cloudfoundry-incubator/diego-release/issues/60

Question is, how do I overcome this error?

**Comment by Amit-PivotalLabs** [comment]
Hi @jhiemer:

If you are deploying cf-release v211, you should also check out the v211 tag of the cf-release repo to generate the manifests:

```sh
$ # from cf-release directory
$ git fetch origin
$ git co v211
$ bosh upload release releases/cf-211.yml
$ ./generate_deployment_manifest vsphere cf-stub.yml > cf-deployment.yml
$ bosh -d cf-deployment.yml deploy
```

**Comment by jhiemer** [comment]
Yes, thanks forgot that. My bad. :-(

**Comment by Amit-PivotalLabs** [comment]
Glad to help!
