### ISSUE TITLE
Accessing from host machine(windows) using cf api  https://api.10.244.0.34.xip.io

### ISSUE THREAD

**Issue by naheedmk** [cloudfoundry/cf-release#748]
Hello,
I am attempting to install CF on laptop, completed installation and was able to cf api and login from Ubunt( Vagrant).  However, when trying to access remotely from host (windows) machine, it fails due to connection. 

C:\tools\github_repo\cf-acceptance-tests\bin>cf api --skip-ssl-validation https:
//api.10.244.0.34.xip.io
Setting api endpoint to https://api.10.244.0.34.xip.io...
FAILED
ConnectEx tcp: i/o timeout

Did not find any configuration details for this. Also tried using the IP 192.168.50.4 which was added to windows route table during installation, I can ssh to vagrant using that IP, but not able to reach cloud controller.  Appreciate any pointers on this.

Thanks
Naheed

**Comment by Amit-PivotalLabs** [comment]
Hi @naheedmk,

Sounds like you've deployed Cloud Foundry to a BOSH-Lite Vagrant VM.  You may need to run the  `add-route.bat` script which lives in the BOSH-Lite repo.  See [here](https://github.com/cloudfoundry/bosh-lite/blob/master/bin/add-route.bat).  Just out of curiosity, what documentation are you following to get your BOSH-Lite and Cloud Foundry setup?

Thanks
Amit

**Comment by naheedmk** [comment]
Thanks Amit. Yes, running route script worked, and it is Bosh-LiteI am using following documentationshttps://github.com/cloudfoundry/bosh-lite
https://github.com/cloudfoundry/bosh-lite/blob/master/docs/deploy-cf.md

 


     On Sunday, July 26, 2015 8:53 PM, Amit Gupta <notifications@github.com> wrote:
   

 Hi @naheedmk,Sounds like you've deployed Cloud Foundry to a BOSH-Lite Vagrant VM. You may need to run the add-route.bat script which lives in the BOSH-Lite repo. See here. Just out of curiosity, what documentation are you following to get your BOSH-Lite and Cloud Foundry setup?Thanks
Amit—

**Comment by Amit-PivotalLabs** [comment]
Great @naheedmk, glad to help and know that it's all working.  For reference, the main README on the BOSH-Lite repo explains how to get BOSH-Lite up and running (before you can deploy CF), and [this section](https://github.com/cloudfoundry/bosh-lite#using-the-virtualbox-provider) mentions running the `add-route` script at the end.

I will close out this issue, but if you have any feedback on how we could have documented this better, please comment.

Thanks,
Amit

**Comment by naheedmk** [comment]
Thanks Amit, I did run the script, however somehow after deploy cf-release only 192.168.50.4 was accessible from the host and the other IPs.  After re-running it as you suggested, it worked.  Thanks for your help. 


     On Sunday, July 26, 2015 11:30 PM, Amit Gupta <notifications@github.com> wrote:
   

 Great @naheedmk, glad to help and know that it's all working. For reference, the main README on the BOSH-Lite repo explains how to get BOSH-Lite up and running (before you can deploy CF), and this section mentions running the add-route script at the end.I will close out this issue, but if you have any feedback on how we could have documented this better, please comment.Thanks,
Amit—

**Comment by tatharoy** [comment]
Hi Amit,

I am trying to do the same which Naheed did but even after running the add-route script i am not able to access the cf api from the host machine. 

when i run, ip route i do see 10.244.0.0/19 added

default via 10.0.2.2 dev eth0 
10.0.2.0/24 dev eth0  proto kernel  scope link  src 10.0.2.15 
10.244.0.0/19 via 192.168.50.4 dev eth1  scope link 
10.244.0.4/30 dev w0j3f9r2uccj-0  proto kernel  scope link  src 10.244.0.5 
10.244.0.20/30 dev w0j3f9r2ucci-0  proto kernel  scope link  src 10.244.0.21 
10.244.0.24/30 dev w0j3f9r2uccr-0  proto kernel  scope link  src 10.244.0.25 
10.244.0.28/30 dev w0j3f9r2ucck-0  proto kernel  scope link  src 10.244.0.29 
10.244.0.32/30 dev w0j3f9r2uccp-0  proto kernel  scope link  src 10.244.0.33 
10.244.0.40/30 dev w0j3f9r2uccs-0  proto kernel  scope link  src 10.244.0.41 
10.244.0.128/30 dev w0j3f9r2ucco-0  proto kernel  scope link  src 10.244.0.129 
10.244.0.132/30 dev w0j3f9r2uccl-0  proto kernel  scope link  src 10.244.0.133 
10.244.0.136/30 dev w0j3f9r2uccq-0  proto kernel  scope link  src 10.244.0.137 
10.244.0.140/30 dev w0j3f9r2uccm-0  proto kernel  scope link  src 10.244.0.141 
10.244.0.144/30 dev w0j3f9r2uccn-0  proto kernel  scope link  src 10.244.0.145 
192.168.50.0/24 dev eth1  proto kernel  scope link  src 192.168.50.4 

also if i run bosh vms, the output is 


+------------------------------------+---------+---------------+--------------+
| Job/index                          | State   | Resource Pool | IPs          |
+------------------------------------+---------+---------------+--------------+
| api_z1/0                           | running | large_z1      | 10.244.0.134 |
| doppler_z1/0                       | running | medium_z1     | 10.244.0.142 |
| etcd_z1/0                          | running | medium_z1     | 10.244.0.42  |
| ha_proxy_z1/0                      | running | router_z1     | 10.244.0.34  |
| hm9000_z1/0                        | running | medium_z1     | 10.244.0.138 |
| loggregator_trafficcontroller_z1/0 | running | small_z1      | 10.244.0.146 |
| nats_z1/0                          | running | medium_z1     | 10.244.0.6   |
| postgres_z1/0                      | running | medium_z1     | 10.244.0.30  |
| router_z1/0                        | running | router_z1     | 10.244.0.22  |
| runner_z1/0                        | running | runner_z1     | 10.244.0.26  |
| uaa_z1/0                           | running | medium_z1     | 10.244.0.130 |
+------------------------------------+---------+---------------+--------------+

i wonder why i am not able to access 10.244.0.34 which is the ip for ha_proxy, cf login -a https://api.10.244.0.34.xip.io --skip-ssl-validation. Any inputs?

If needed i can create another ticket

**Comment by Amit-PivotalLabs** [comment]
Hi Tatha,

Do you mind opening a new issue (and referencing the URL for this one) so we can track our responses better?

Thanks,
Amit

**Comment by tatharoy** [comment]
Hi Amit,

I found out where the issue was. Thanks for your response, its working now!!

Thanks,
Tatha
