### ISSUE TITLE
Space environment variables

### ISSUE THREAD

**Issue by bsideup** [cloudfoundry/cf-release#750]
Hi!

We're running some Spring Cloud microservices, and we need to specify Spring Cloud Config URL in environment variables for each service, which is not good.

Would be great if Cloud Foundry will support Space-bounded environment variables instead of "per application only"

**Comment by dieucao** [comment]
We currently support environment variable groups for running and staging that apply deployment wide.
http://docs.cloudfoundry.org/devguide/deploy-apps/environment-variable.html#evgroups

Would that work for you?

**Comment by bsideup** [comment]
@dieucao awesome, thanks! Still not sure about difference between "staging" and "running" tho :)

**Comment by dieucao** [comment]
"staging" refers to the phase where we combine your application bits with the buildpack to produce a runnable "droplet".  You may wish to specify different environment variables to be exposed during this compilation step than the set of environment variables to be exposed to your app when it's running.

**Comment by bsideup** [comment]
@dieucao ok, thanks, I got it :) So groups are exactly what I wanted :)
