### ISSUE TITLE
Service Discovery on CF

### ISSUE THREAD

**Issue by roagarwal** [cloudfoundry/cf-release#755]
On our platform, which will be based on PCF, we will introduce a new component that will work together with our buildpack to expose and secure APIs (you can think of it as a Micro Gateway). In order to configure those gateways a webbased UI will be introduced that should know about all our custom buildpack applications that are pushed to PCF and expose APIs. Ideally speaking every time an app gets pushed to PCF it should also notify the webbased UI that a new API is available (something like service discovery). 

I know PCF has Etcd component which is used for Service Discovery but can we use it to push application cluster details to this custom webbased UI ?

The other part of the question is that the webbased UI will create a new app that will in turn expose an API as well. That new app will be exposed to the outside world and route traffic to the pushed  application (our buildpack apps) offcourse after applying some policies. Would that be possible to do with PCF?

**Comment by zaksoup** [comment]
Hi @roagarwal, if you're a PCF customer please visit http://support.pivotal.io.

Best,
@zaksoup, CF Release Integration

**Comment by loganlee** [comment]
@roagarwal - Are you a PCF customer?  If so, Pivotal's support should be able to answer your questions.
