### ISSUE TITLE
Failed fetching org-users for role ORG MANAGER, status code 500, error code 10001

### ISSUE THREAD

**Issue by liuxiaoxi2237** [cloudfoundry/cf-release#759]
Hi Expert,
cf login success with --skip-ssl-validation. Create user, space, assigning user role works fine.
But when run "cf org-users", get below error.
Failed fetching org-users for role ORG MANAGER.
Server error, status code: 500, error code: 10001, message: An unknown error occurred.

Check controller logs, find that
{"timestamp":1438705617.9227388,"message":"Request failed: 500: {\"code\"=>10001, \"description\"=>\"Invalid SSL Cert for https://uaa.10.62.70.82.xip.io/oauth/token. Use '--skip-ssl-validation' to continue with an insecure target\", \"error_code\"=>\"CF-SSLException\", \"backtrace\"=>[\"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/cache/cf-uaa-lib-b1e11235dc6c/lib/uaa/http.rb:169:

I use self signed certificate.
My questions is:
1, Is there away to skip cert validation when run "cf org-users" ? Or some other solution?
2, in cf-deployment.yml, there are 3 components need to input cert(or key pair) - haproxy, router, uaa token. Should I use same key pair for the 3 components? or I need to generate key pair(cert ) for each components?
any experience and suggestions?
thanks,
David

**Comment by DanLavine** [comment]
You should be able to set skip_cert_verify to true in your deployment manifest to configure this.
```
properties:
  ssl:
    skip_cert_verify: true
```

@jpalermo & @danlavine
OSS Release Integration Team

**Comment by liuxiaoxi2237** [comment]
Thanks you DanLavine, it works.
BTW

**Comment by liuxiaoxi2237** [comment]
skip_cert_verify: true is not secure. Is there some other way to solve this issue?
 If  a company depoy CF with  company CA(root  CA cert is not trusted), how can we make it works with skip_cert_verify: fasle? Import the company root CA cert into stemcell?

**Comment by jpalermo** [comment]
I don't think there are guidelines on how to do it, but yes the root cert would probably have to be built into a custom stemcell.

I don't recall this ever coming up before. @cppforlife, do you know if this has been done?

I would guess that most companies would have a cert that was signed by a trusted root CA.

OSS Release Integration Team

**Comment by liuxiaoxi2237** [comment]
Thank you jpalermo.
The root cert can be import into bosh director by bosh manifest, then bosh director will import root cert to CF VMs.
I have a done a test, it works fine.

**Comment by jpalermo** [comment]
Great to hear.

Here are the docs for anybody else who finds this page:
http://bosh.io/docs/trusted-certs.html
