### ISSUE TITLE
group mapping issue of UAA ldap integration

### ISSUE THREAD

**Issue by liuxiaoxi2237** [cloudfoundry/cf-release#764]
Hi expert,
ldap integration  config in cf-deployment.yml as below
---------------------
My issue:
I can login in with a ldap user successfully. but when run "cf create-user abc 123" or "cf orgs", get error:  Server error, status code: 403, error code: access_denied, message: Invalid token does not contain resource id (scim)
seems  group mapping not work.
-----------------------

      ldap:
          enabled: true
          profile_type: search-and-bind
          url: ldap://x.x.x.x:389/
          mailAttributeName: mail
          userDN: 'cn=xx,cn=xx,dc=xx,dc=xx'
          userPassword: 'xx'
          searchFilter: 'cn={0}'
          searchBase: 'cn=users,dc=xx,dc=xx'
          groups:
            profile_type: groups-map-to-scopes
            autoAdd: true
            searchBase: 'cn=xxx,dc=xx,dc=xx'
            groupRoleAttribute: 'spring.security.ldap.dn'
            groupSearchFilter: 'member={0}'
            searchSubtree: true
            maxSearchDepth: 10
    scim:
          external_groups:
          - scim.write|cn=cfadmin,cn=users,dc=xx,dc=xx
          - scim.read|cn=cfadmin,cn=users,dc=xx,dc=xx
          - cloud_controller.admin|cn=cfadmin,cn=users,dc=xx,dc=xx
          - openid|cn=cfadmin,cn=users,dc=xx,dc=xx
          - doppler.firehose|cn=cfadmin,cn=users,dc=xx,dc=xx
          - clients.admin|cn=cfadmin,cn=users,dc=xx,dc=xx
          - uaa.admin|cn=cfadmin,cn=users,dc=xx,dc=xx
          - zones.write|cn=cfadmin,cn=users,dc=xx,dc=xx
          - password.write|cn=cfadmin,cn=users,dc=xx,dc=xx

Any suggestions,
thanks,
David

**Comment by liuxiaoxi2237** [comment]
ldap is windows 2012 AD ,  cf-release 213

**Comment by fhanik** [comment]
hi David,
The end token scopes are the result of the intersection between client scopes and user scopes. So there are several things that have to happen

  1. Your groups must be successfully mapped, we can verify this in the uaa.log
  2. The client must also have the scopes

You can add uaa.log and the ~/.cf/config.json to the story or here, and we can help you figure it out.

**Comment by youngm** [comment]
One other thought.  I've noticed recently that it appears `external_groups:` config doesn't appear to work.  I haven't had time to get to the root of the problem.

I've had to add my groups via `uaac`.  What does the output of `uaac group mappings` look like?

**Comment by fhanik** [comment]
You are right, I just noticed
https://github.com/cloudfoundry/cf-release/blob/master/jobs/uaa/templates/uaa.yml.erb#L161-L171

Where the external_groups element ends up being bundled under 'zones' rather than 'scim'

**Comment by fhanik** [comment]
Will be fixed via
https://www.pivotaltracker.com/story/show/101042390

**Comment by liuxiaoxi2237** [comment]
The group mapping seems not work.
-------------------------------------------------
$ uaac group mappings
  resources:
  -
    organizations.acme: cn=test_org,ou=people,o=springsource,o=org
  schemas: urn:scim:schemas:core:1.0
  startindex: 1
  itemsperpage: 1
  totalresults: 1
-----------------------------
cofig.json  (there is no scope defined in it)
{
  "ConfigVersion": 3,
  "Target": "https://api.10.62.70.82.xip.io",
  "ApiVersion": "2.33.0",
  "AuthorizationEndpoint": "https://login.10.62.70.82.xip.io",
  "LoggregatorEndPoint": "wss://loggregator.10.62.70.82.xip.io:443",
  "DopplerEndPoint": "wss://doppler.10.62.70.82.xip.io:443",
  "UaaEndpoint": "http://uaa.10.62.70.82.xip.io",
  "AccessToken": "bearer eyJ.....UgwMw",
  "RefreshToken": "ey........oJTng",
  "OrganizationFields": {
    "Guid": "ba4b9849-a17f-491a-a416-cc696cec4ab3",
    "Name": "pivotal",
    "QuotaDefinition": {
      "guid": "17da986c-713e-4e01-942d-bf91fe950ec4",
      "name": "default",
      "memory_limit": 10240,
      "instance_memory_limit": -1,
      "total_routes": 1000,
      "total_services": 100,
      "non_basic_services_allowed": true
    }
  },
  "SpaceFields": {
    "Guid": "e1c818cc-64b3-4f64-997b-fd97abb55073",
    "Name": "space01"
  },
  "SSLDisabled": false,
  "AsyncTimeout": 0,
  "Trace": "",
  "ColorEnabled": "",
  "Locale": "",
  "PluginRepos": [
    {
      "Name": "CF-Community",
      "Url": "http://plugins.cloudfoundry.org"
    }
  ],
  "MinCliVersion": "",
  "MinRecommendedCliVersion": ""
}

**Comment by fhanik** [comment]
> The group mapping seems not work.

Yes. Read through the comment chain, let us know if you have any questions.
Your work around right now is to us `uaac group map` command.

I will close this issue, as we are tracking it in our backlog and will be pushing out the fix soon.
