### ISSUE TITLE
doc for UAA SAML integration with vcenter SSO

### ISSUE THREAD

**Issue by liuxiaoxi2237** [cloudfoundry/cf-release#765]
Hi expert,
Is there some reference site/docs , about UAA SAML integration with vcenter SSO? 
Does community version CF support this feature?
Thanks,
David

**Comment by sreetummidi** [comment]
Hi,
UAA supports all standard SAML 2.0 Identity Provider implementations.This is supported in the community version. This SAML IDP metadata need to be configured under the login->saml->providers-> section of the cf-release manifest.
 login:
       saml:
         providers:
         vmware:
            nameID: urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress
            idpMetadata:  <idp_url> or <XML>
            showSamlLoginLink: true
            linkText: "VMware SSO"
            metadataTrustCheck: false

Thanks,
Sree

**Comment by fhanik** [comment]
vCenter SSO integration is done in the same fashion as other providers
https://github.com/fhanik/cf-release-manifests/blob/master/saml/saml-03-vcenter-sso.yml

depending on how your provider is setup, you may need to change the nameID to persistent

We have an outdated document about setting up vcenter SSO, I believe it is easier these days
https://docs.google.com/document/d/1FEz5VlIuYjkReOYWck9HeIPwebrgrwmovRm20XPckrs/edit?usp=sharing
