### ISSUE TITLE
How to manage Private CA root certificate in CF deployment

### ISSUE THREAD

**Issue by liuxiaoxi2237** [cloudfoundry/cf-release#766]
Hi Expert,
If  using self-signed cert/private CA signed cert for ha_proxy, routers, uaa , seems certificate issue is very common during CF deployment
eg, 
cf-log failed. status 500, error code 10001
cf-org-users failed. status 500, error code 10001
When set "skip_verify_cert = true" , these kind of issue can be solved. But this is not a secure way, since there is no cert validation.
(Actually, I am not sure this kind of issue is by design, or caused by my mis-configuration)

My questions is:
When using private CA signed certificate, how to solve these kind of issue while setting  "skip_verify_cert = false"?

Currently, 
1, my idea is to import private CA root cert into bosh stemcell before deploying.
2, Can it(import root ca cert) be done by  using cf-deployment.yml ? Or need to rebuild stemcells?
3, Some other solutions?

Need your kindly suggestions.
Thanks,
David

**Comment by cppforlife** [comment]
Bosh can configure custom CAs on all machines. See http://bosh.io/docs/trusted-certs.html.

**Comment by liuxiaoxi2237** [comment]
Many thanks. 
I did not notice the chapter.
