### ISSUE TITLE
duplicated cc.info properties

### ISSUE THREAD

**Issue by gberche-orange** [cloudfoundry/cf-release#774]
the new [cc.info.[name,build,version,description]](https://github.com/cloudfoundry/cf-release/blob/9334295133435fa77767651030500d2b0de62611/jobs/cloud_controller_ng/spec#L140-L151) have a good description but lack the default values set in [cloud_controller.yml](https://github.com/cloudfoundry/cloud_controller_ng/blob/0f1b94ee250afdb260c9876adacc960a062c198a/config/cloud_controller.yml#L40-L47)

the apparently old [name, build, version](https://github.com/cloudfoundry/cf-release/blob/9334295133435fa77767651030500d2b0de62611/jobs/cloud_controller_ng/spec#L47-L55) have proper default values, I suspect they're not used anymore (and lack description)

$ cf curl v2/info
{
   "name": "vcap",
   "build": "2222",
   "support": "http://support.cloudfoundry.com",
   "version": 2,
   "description": "Cloud Foundry sponsored by Pivotal",
   "authorization_endpoint": "https://login.run.pivotal.io",
   "token_endpoint": "https://uaa.run.pivotal.io",
   "min_cli_version": null,
   "min_recommended_cli_version": null,
   "api_version": "2.34.0",
   "app_ssh_endpoint": "ssh.run.pivotal.io:2222",
   "app_ssh_host_key_fingerprint": "e7:13:4e:32:ee:39:62:df:54:41:d7:f7:8b:b2:a7:6b",
   "logging_endpoint": "wss://loggregator.run.pivotal.io:4443",
   "doppler_logging_endpoint": "wss://doppler.run.pivotal.io:4443"
}

**Comment by amitkgupta** [comment]
Thanks @gberche-orange 

I created an issue in the CAPI story tracker for a similar issue (https://www.pivotaltracker.com/story/show/101913634, just enumerating some additional properties lacking descriptions), and I've let them know about this issue as well, which highlights the fact that the defaults live in `cloud_controller.yml`.

**Comment by gberche-orange** [comment]
thank @amitkgupta

**Comment by Amit-PivotalLabs** [comment]
This has now been resolved.  Closing.
