### ISSUE TITLE
UAA stacktrace log messages don't contain syslog tag

### ISSUE THREAD

**Issue by youngm** [cloudfoundry/cf-release#778]
UAA uses log4j for logging.  Log4j doesn't properly support syslog tags in any 1.2.x release of log4j.

UAA currently uses a hack to patch in a tag for log messages [0].  One downside of this hack is that it only applies a tag to the first line of a log message not subsequent log lines like exception trace lines.

Looking through the log4j code I don't see any way to hack in support for syslog tag in every log line.

However, if we change uaa to simply print logs to stdout and stderr then these log message would get picked up by the release common exec logging facilities [1] which will send the lines to syslog with a tag for each line.

One possible solution is to simply remove log4j syslog and file appenders from uaa and instead simply let uaa log to stdout/err and allow exec [1] to send logs to `/var/vcap/sys/log/` and syslog.

The impacts of this change will be:
* uaa logs no longer be found in `log/uaa/uaa.log` and will instead be found in `log/uaa_ctl.log` and and `log/uaa_ctl.err.log`
* Local file log messages will now have 2 dates in the file.  One applied in Log4j and one applied by the common script.  Messages send to syslog will not have the additional timestamp in the msg.
* The old uaa tag `vcap.uaa` will be replaced with `vcap.uaa_ctl.stdout` and `vcap.uaa_ctl.stderr`.

Thoughts?  I'd be happy to submit a PR for this.

[0] https://github.com/cloudfoundry/cf-release/blob/master/jobs/uaa/templates/log4j.properties.erb#L22
[1] https://github.com/cloudfoundry/cf-release/blob/master/src/common/utils.sh#L4

**Comment by youngm** [comment]
FWIW support for tag was actually added to the syslog appender.  But, a version of Log4j that included this change was never released: https://bz.apache.org/bugzilla/show_bug.cgi?id=46626

**Comment by Amit-PivotalLabs** [comment]
Thanks @youngm.

I have moved the story to the Identity team's Pivotal Tracker.  The above link from @cf-gitbot will still take you there.  /cc @sreetummidi @mbhave @fhanik.

**Comment by youngm** [comment]
This also causes problems for messages larger than 1K.  They get sent with a blank tag also.

**Comment by sreetummidi** [comment]
HI Mike,
We will review this and get back

-Sree

**Comment by Amit-PivotalLabs** [comment]
@sreetummidi @youngm any update on this issue?

**Comment by fhanik** [comment]
@youngm We're considering simply improving the SyslogAppender to handle the tagging properly. 
Currently we add the tag as part of the formatting, and thus, it's only added to the first line. 

this would still give us the current log file structure, and would allow us give different tags to different loggers (like vcap.uaa.audit for audit messages)

any thoughts?

**Comment by youngm** [comment]
@fhanik Sounds good to me.  It appears the Log4j SyslogAppender in head works correctly so you can base your fixed one on that.

https://bz.apache.org/bugzilla/show_bug.cgi?id=46626

**Comment by amitkgupta** [comment]
I'm going to close this issue out.

@youngm feel free to follow up on [uaa-release](https://github.com/cloudfoundry-incubator/uaa-release/issues) or [uaa](https://github.com/cloudfoundry/uaa/issues) directly.

Best,
Amit

**Comment by youngm** [comment]
Thanks @amitkgupta it looks like progress is being made in the tracker issue.  I'll keep following that.

Mike
