### ISSUE TITLE
cf push hang , after package downloaded. 

### ISSUE THREAD

**Issue by liuxiaoxi2237** [cloudfoundry/cf-release#783]
Hi expert,
my env:
cf 213 
vsphere 5.5

After redeploy CF in a new environment,  testing spring-music as the first app. 
When run cf push, get below issue:
------------------------------------
$ cf push
Using manifest file /home/david/spring-music-master/manifest.yml

Creating app spring-ca in org pivotal / space space01 as admin...
OK

Creating route spring-ca-1234.192.168.2.33.xip.io...
OK

Binding spring-ca-1234.192.168.2.33.xip.io to spring-ca...
OK

Uploading spring-ca...
Uploading app files from: /home/david/spring-music-master/build/libs/spring-music.war
Uploading 576.9K, 90 files
Done uploading
OK

Starting app spring-ca in org pivotal / space space01 as admin...
-----> Downloaded app package (22M)

FAILED
spring-ca failed to stage within 15.000000 minutes
--------------------------------------
$ cf logs app spring-ca --recent 
dose not show valuable info

-------------------------------------
DEA config as below:
dea_next:
    advertise_interval_in_seconds: 5
    allow_host_access: null
    allow_networks: []
    default_health_check_timeout: 60
    deny_networks: []
    directory_server_protocol: https
    disk_mb: 30480
    disk_overcommit_factor: 2
    evacuation_bail_out_time_in_seconds: 600
    heartbeat_interval_in_seconds: 10
    instance_disk_inode_limit: 200000
    kernel_network_tuning_enabled: true
    logging_level: debug
    memory_mb: 10240
    memory_overcommit_factor: 3
    rlimit_core: 0
    staging_disk_inode_limit: 200000
    staging_disk_limit_mb: 10000
    staging_memory_limit_mb: 10240
  description: Cloud Foundry sponsored by Pivotal
  disk_quota_enabled: true
--------------------------------------------------
thanks
David

**Comment by DanLavine** [comment]
Hi @liuxiaoxi2237,

Unfortunately there is not enough information here to help. What we really need are the logs off of the DEA which tried to stage the app and the CC logs that handled the requests. However there are a few configuration options you could check as well.

1) Make sure your blob store is accessible from the dea.
2) CC is sending the correct download urls to the dea.
3) Check that your manifest fog configurations have been setup to point at the correct blobstores.

Feel free to send us the logs if you are still having problems.

Thanks!
@njbennett && @DanLavine, CF OSS Release Integration Team

**Comment by liuxiaoxi2237** [comment]
Thank you.
The issue solved after I add a internet connection to my CF environment. Since CF need to download buildpack.. from github.
My questions is,
Java buildpack 3.1 is already build-in cf , why it will download from internet/github?
Is there some configuration to avoid internet downloading?

------------------------------------------------------
$ cf buildpacks
Getting buildpacks...

buildpack              position   enabled   locked   filename
staticfile_buildpack   1          true      false    staticfile_buildpack-cached-v1.2.0.zip
java_buildpack         2          true      false    java-buildpack-v3.1.zip
ruby_buildpack         3          true      false    ruby_buildpack-cached-v1.5.0.zip
nodejs_buildpack       4          true      false    nodejs_buildpack-cached-v1.4.0.zip
go_buildpack           5          true      false    go_buildpack-cached-v1.4.0.zip
python_buildpack       6          true      false    python_buildpack-cached-v1.4.0.zip
php_buildpack          7          true      false    php_buildpack-cached-v3.3.0.zip
binary_buildpack       8          true      false    binary_buildpack-
------------------------------------------------------
Starting app spring-ca in org pivotal / space space01 as admin...
-----> Downloaded app package (22M)
-----> Java Buildpack Version: v3.1 | https://github.com/cloudfoundry/java-buildpack.git#7a538fb
-----> Downloading Open Jdk JRE 1.8.0_60 from https://download.run.pivotal.io/openjdk/trusty/x86_64/openjdk-1.8.0_60.tar.gz (5m 54s)
       Expanding Open Jdk JRE to .java-buildpack/open_jdk_jre (1.5s)
-----> Downloading Open JDK Like Memory Calculator 1.1.1_RELEASE from https://download.run.pivotal.io/memory-calculator/trusty/x86_64/memory-calculator-

1.1.1_RELEASE (27.7s)
       Memory Settings: -Xmx382293K -Xms382293K -XX:MaxMetaspaceSize=64M -XX:MetaspaceSize=64M -Xss995K
-----> Downloading Spring Auto Reconfiguration 1.10.0_RELEASE from https://download.run.pivotal.io/auto-reconfiguration/auto-reconfiguration-

1.10.0_RELEASE.jar (9.5s)
[DownloadCache]                  WARN  Request failure 1, retrying: Timeout::Error
-----> Downloading Tomcat Instance 8.0.26 from https://download.run.pivotal.io/tomcat/tomcat-8.0.26.tar.gz (2m 50s)
       Expanding Tomcat to .java-buildpack/tomcat (0.1s)
-----> Downloading Tomcat Lifecycle Support 2.4.0_RELEASE from https://download.run.pivotal.io/tomcat-lifecycle-support/tomcat-lifecycle-support-

2.4.0_RELEASE.jar (4.1s)
-----> Downloading Tomcat Logging Support 2.4.0_RELEASE from https://download.run.pivotal.io/tomcat-logging-support/tomcat-logging-support-2.4.0_RELEASE.jar 

(1.8s)
-----> Downloading Tomcat Access Logging Support 2.4.0_RELEASE from https://download.run.pivotal.io/tomcat-access-logging-support/tomcat-access-logging-

support-2.4.0_RELEASE.jar (1.4s)
-----> Uploading droplet (74M)

0 of 1 instances running, 1 starting
1 of 1 instances running

**Comment by zaksoup** [comment]
@liuxiaoxi2237 while the java buildpack is built into CF it does not include the entire JDK. It contains the logic to detect and build java apps, and must download the JDK in order to complete the build process. You can upload an "offline" buildpack by pre-packaging dependancies with the buildpack. Please see our documentation here: https://docs.cloudfoundry.org/buildpacks/depend-pkg-offline.html

For now, I'm going to mark this issue as closed seeing as it seems it has been resolved. Please feel free to reopen it if you have any further questions or issues.

**Comment by Amit-PivotalLabs** [comment]
@liuxiaoxi2237 you can also find official versions of the "offline" java buildpack so you don't have to build it yourself.

* [List of all releases](https://github.com/cloudfoundry/java-buildpack/releases)
* [Latest offline buildpack (zip)](https://github.com/cloudfoundry/java-buildpack/releases/download/v3.2/java-buildpack-offline-v3.2.zip)
