### ISSUE TITLE
templates/cf-infrastructure-vsphere.yml does not properly merge in resource pool cloud_properties

### ISSUE THREAD

**Issue by coryjett** [cloudfoundry/cf-release#794]
The way cf-release/templates/cf-infrastructure-vsphere.yml is written, it does not properly merge in additional cloud_properties (such as datacenter, cluster, and drs_rules) from a stub file.

resource_pools:
  - name: small_z1
    cloud_properties:
      ram: 1024
      disk: 4096
      cpu: 1

Other infrastructure manifests (such as the openstack manifest) follow the below pattern which allows merging in additional cloud_properties but also defaulting where undefined:

resource_pools:
  - name: runner_z1
    cloud_properties: (( merge || meta.resource_pools.runner_z1.cloud_properties ))

I have a working manifest that follows this pattern that I can submit a pull request for that should resolve this.

**Comment by njbennett** [comment]
@coryjett Yeah, a pull request for that would be great. Not sure why that one is different.

@jpalermo & @njbennett
CF Release Integration Team

**Comment by njbennett** [comment]
We see the PR now, closing this issue.

Thanks!
