### ISSUE TITLE
Commit to uaa job to change router.servers.z1/z2 to single router.servers array inconsistent with haproxy job's usage

### ISSUE THREAD

**Issue by rboykin** [cloudfoundry/cf-release#804]
This commit https://github.com/cloudfoundry/cf-release/commit/cb158801cfa78f75dad8e4240cc378826ac7b556 changed reference to router.servers.z1/z2 to single router.servers array within uaa job files.  This is inconsistent with the continued use of router.servers.z1/z2 within the haproxy job files

**Comment by fhanik** [comment]
The haproxy assumes that there are only two zones, and limits it to two zones. We had to remove this limitation in the UAA as it is deployed in environments without haproxy

**Comment by rboykin** [comment]
@fhanik Not questioning the UAA reason.  Just noting a single deployment.yml file cannot now support both existing uaa and haproxy jobs.  For instance, as used within https://github.com/yudai/cf_nise_installer/blob/master/manifests/template.yml

**Comment by fhanik** [comment]
Should support it just fine if you are using spiff to generate your manifests.

the same properties are passed onto the the UAA

https://github.com/cloudfoundry/cf-release/commit/cb158801cfa78f75dad8e4240cc378826ac7b556#diff-cc2001a2d5a35eb4f5c9a724187b6cabR321

**Comment by rboykin** [comment]
@fhanik Just tried a deploy of v219 using cf_nise_Installer and it balked even after changing the template.  I don't believe cf_nise_installer uses spiff, but instead a simple deployment file.  UAA is not going to be the problem.  The problem is haproxy job is going to fail once the cf_nise_installer  template.yml is changed to support UAA job.  As an example haproxy template depends on router.servers.z1:  https://github.com/cloudfoundry/cf-release/blob/master/jobs/haproxy/templates/haproxy.ctmpl.erb#L49

**Comment by fhanik** [comment]
@rboykin I finally understand what you are explaining.

The datatype of `router.servers.z1` and `router.servers.<some-ip>` are different between the two jobs even though they both use the properties. 

This is indeed confusing, and does justify an issue being opened. 

On a side note, it shouldn't break your existing template, if it isn't changed. The key here is that the manifest doesn't change. Because the UAA will function without those value.
Because the UAA will use the values z1 and z2 and those will be treated as strings and ignored in a running UAA.

I will escalate this.

**Comment by fhanik** [comment]
As for a solution, I believe this commit should be amended with another commit, intentionally choosing a different namespace for the property in the UAA.

**Comment by rboykin** [comment]
@fhanik The existing template with router.servers.z1 breaks within https://github.com/cloudfoundry/cf-release/blob/master/jobs/uaa/templates/tomcat.server.xml.erb#L26 due to the fact that it is expecting a string and is instead getting a hash.  The gsub fails.

**Comment by fhanik** [comment]
you are right, I will fix right away...

**Comment by fhanik** [comment]
working on this story : https://www.pivotaltracker.com/story/show/104728458

**Comment by fhanik** [comment]
It has to run through a pipeline, once that has been cleared, I can push into cf-release

**Comment by rboykin** [comment]
@fhanik Any target date for your fix to be included within cf-release?  I notice it did not make it into v220.

**Comment by sreetummidi** [comment]
@rboykin We are checking this on our side now. Will get you an update soon !

**Comment by sreetummidi** [comment]
@rboykin This will be part of release v221

**Comment by rboykin** [comment]
Closing since this is included in v221
