### ISSUE TITLE
Adding Cloud Foundry server through "Cloud Foundry Integration for Eclipse" fails starting from CF-219 release.

### ISSUE THREAD

**Issue by cppforlife** [cloudfoundry/cf-release#805]
@bnanda wrote:

> I have a CF-219 release installed on my local machine (Macbook through VirtualBox). Staring from V219 release, the default domain for BOSH-lite deployments from 10.244.0.34.xip.io to bosh-lite.com. However, the CN in the certificate in the https://api.bosh-lite.com/info still points to *.10.244.0.34.xip.io. So while adding the CF-Server (https://api.bosh-lite.com) from Eclipse using "Cloud Foundry Integration for Eclipse" plugin, the hostname verification fails and the server cannot be added.

original issue: https://github.com/cloudfoundry/bosh-lite/issues/304

**Comment by jpalermo** [comment]
We've committed a fix, which should be included in v221

https://github.com/cloudfoundry/cf-release/commit/86e87490d60d3d4d8d49a992c525de5501c88c34
