### ISSUE TITLE
CF-RELEASE v202 UPLOAD ERROR

### ISSUE THREAD

**Issue by parthitheindian** [cloudfoundry/cf-release#808]
Hi All,
          When am uploading the Cloud Foundry Release v202 to the Director, its throwing the following error.

bosh upload release /root/tmp/cf-release-202.tgz
Acting as user 'admin' on 'microbosh'

Verifying release...
File exists and readable                                     OK
Extract tarball                                              FAILED

Release is invalid, please fix, verify and upload again

My Director VM has more than Enough Free Space in it too.

Could anyone please help me on this issue, since am struck with this more than a week. Thanks

Regards

Parthiban A

**Comment by amitkgupta** [comment]
Looks like you've raised the same issue [on the mailing list](https://lists.cloudfoundry.org/archives/list/cf-dev@lists.cloudfoundry.org/thread/GZWT445VL4Y4WSH6K2Y2I4R5WA5AB665/) and you're getting some help there.  Closing this issue.
