### ISSUE TITLE
[CALL FOR HELP] Failed to org-users and push apps

### ISSUE THREAD

**Issue by yyl8815** [cloudfoundry/cf-release#809]
I have just deployed a CloudFoundry on vSphere. I can create org, space, user. Also can I set the org role for a user. 

However, after I set the org role and try to get the user list, an error appears as below:

    root@boshcli:~/cf-env# cf org-users qaiaas
    Getting users in org qaiaas as admin...

    ORG MANAGER
    FAILED
    Failed fetching org-users for role ORG MANAGER.
    Server error, status code: 500, error code: 10001, message: An unknown error occurred.

And when I try to push apps, below two error:
   - Invalid authorization for fetching logs
   - BuildpackCompileFailed for pushing app

Details as below:
---
root@boshcli:~/cf-env# cf push
Using manifest file /root/cf-env/manifest.yml

Creating app cf-env in org qaiaas / space testing as admin...
OK

Creating route cf-env.10.62.54.34.xip.io...
OK

Binding cf-env.10.62.54.34.xip.io to cf-env...
OK

Uploading cf-env...
Uploading app files from: /root/cf-env
Uploading 885.5K, 17 files
Done uploading
OK

Warning: error tailing logs
Unauthorized error: You are not authorized. Error: Invalid authorization
Starting app cf-env in org qaiaas / space testing as admin...

FAILED
BuildpackCompileFailed

TIP: use 'cf logs cf-env --recent' for more information

**Comment by Amit-PivotalLabs** [comment]
This appears identical to #807, closing.
