### ISSUE TITLE
Intermittent UAA failure after migration from cf 217 to 218

### ISSUE THREAD

**Issue by vvraskin** [cloudfoundry/cf-release#815]
Hello, 

we have migrated from cf 217 to 218 and experience problems while trying to create new users. 
Since the problem is intermittent, I'm not sure if it is a configuration problem or indeed a bug in uaa. 

# Scenario:
1. Run the command `cf create-user` several times in a row.

2. After the first execution it returns HTTP 200. 

3. But the second execution returns HTTP code 401 "Invalid auth token: Invalid token (could not decode): "

This error pattern repeats for every other request. 

# Some more info from our investigation:

In the access log of the uaa component we see that 401 code was returned two times having the same timestamp.

Decoding the jwt that is being marked as invalid did now show any errors.

**Comment by vvraskin** [comment]
Here is the output that I get from from cf cli:

CF_TRACE=true cf create-user test_me2 12345
Creating user test_me2...

REQUEST: [2015-10-16T16:49:24+02:00]
POST /Users HTTP/1.1
Host: uaa.my_domain
Accept: application/json
Authorization: [PRIVATE DATA HIDDEN]
Content-Type: application/json
User-Agent: go-cli 6.12.3-c0c9a03 / darwin

{"userName":"test_me2","emails":[{"value":"test_me2"}],"password":"[PRIVATE DATA HIDDEN]","name":{"givenName":"test_me2","familyName":"test_me2"}}

RESPONSE: [2015-10-16T16:49:24+02:00]
HTTP/1.1 401 Unauthorized
Content-Length: 879
Access-Control-Allow-Origin: *
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Cache-Control: no-store
Content-Type: application/json
Date: Fri, 16 Oct 2015 14:49:23 GMT
Expires: 0
Pragma: no-cache
Pragma: no-cache
Server: Apache-Coyote/1.1
Www-Authenticate: Bearer realm="UAA/oauth", error="invalid_token", error_description="Invalid token (could not decode): MyToken"
X-Cf-Requestid: 237c9c82-11ae-4555-57dd-4ada210504b5
X-Content-Type-Options: nosniff
X-Frame-Options: DENY
X-Xss-Protection: 1; mode=block

{"error":"invalid_token","error_description":"Invalid token (could not decode): MyToken"}

REQUEST: [2015-10-16T16:49:24+02:00]
POST /oauth/token HTTP/1.1
Host: uaa.my_domain
Accept: application/json
Authorization: [PRIVATE DATA HIDDEN]
Content-Type: application/x-www-form-urlencoded
User-Agent: go-cli 6.12.3-c0c9a03 / darwin

grant_type=refresh_token&refresh_token=MyToken&scope=

RESPONSE: [2015-10-16T16:49:24+02:00]
HTTP/1.1 200 OK
Content-Length: 1762
Cache-Control: no-store
Content-Type: application/json;charset=UTF-8
Date: Fri, 16 Oct 2015 14:49:23 GMT
Pragma: no-cache
Server: Apache-Coyote/1.1
X-Cf-Requestid: 2cb4f2de-1719-47a5-52f2-b8f7bb7e8458

{"access_token":"[PRIVATE DATA HIDDEN]","token_type":"bearer","refresh_token":"[PRIVATE DATA HIDDEN]","expires_in":43199,"scope":"scim.read cloud_controller.admin password.write scim.write openid cloud_controller.write cloud_controller.read","jti":"33ddd982-b794-4edf-98e6-6c5056c91bc1"}

REQUEST: [2015-10-16T16:49:24+02:00]
POST /Users HTTP/1.1
Host: uaa.my_domain
Accept: application/json
Authorization: [PRIVATE DATA HIDDEN]
Content-Type: application/json
User-Agent: go-cli 6.12.3-c0c9a03 / darwin

{"userName":"test_me2","emails":[{"value":"test_me2"}],"password":"[PRIVATE DATA HIDDEN]","name":{"givenName":"test_me2","familyName":"test_me2"}}

RESPONSE: [2015-10-16T16:49:24+02:00]
HTTP/1.1 401 Unauthorized
Content-Length: 879
Access-Control-Allow-Origin: *
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Cache-Control: no-store
Content-Type: application/json
Date: Fri, 16 Oct 2015 14:49:23 GMT
Expires: 0
Pragma: no-cache
Pragma: no-cache
Server: Apache-Coyote/1.1
Www-Authenticate: Bearer realm="UAA/oauth", error="invalid_token", error_description="Invalid token (could not decode): MyToken"
X-Cf-Requestid: db7cb073-9564-4009-4fd0-1fce70fd2705
X-Content-Type-Options: nosniff
X-Frame-Options: DENY
X-Xss-Protection: 1; mode=block

{"error":"invalid_token","error_description":"Invalid token (could not decode): MyToken"}
FAILED
Error creating user test_me2.
Invalid auth token: Invalid token (could not decode): MyToken
FAILED
Error creating user test_me2.
Invalid auth token: Invalid token (could not decode): MyToken

**Comment by fhanik** [comment]
Www-Authenticate: Bearer realm="UAA/oauth", error="invalid_token",
error_description="Invalid token (could not decode): MyToken"

looks like the value sent up is 'MyToken'

**Comment by vvraskin** [comment]
Actually I have modified it to be 'MyToken' just here in order not to show the values from the real token. If it would make sense I can also partially post the decoded token here

**Comment by vvraskin** [comment]
Here is the decoded MyToken1:
{
  "jti": "[substituted_value]",
  "sub": "[substituted_value]",
  "scope": [
    "scim.read",
    "cloud_controller.admin",
    "password.write",
    "scim.write",
    "openid",
    "cloud_controller.write",
    "cloud_controller.read"
  ],
  "client_id": "cf",
  "cid": "cf",
  "azp": "cf",
  "grant_type": "password",
  "user_id": "[substituted_value]",
  "user_name": "MyUser",
  "email": "MyUser",
  "iat": 1445005922,
  "exp": 1445049122,
  "iss": "http://uaa.my_domain",
  "aud": [
    "scim",
    "openid",
    "cloud_controller",
    "password",
    "cf"
  ]
}

**Comment by vvraskin** [comment]
Here is the decoded MyToken2. Values that I have hidden are marked with 'substituted_value'

{
  "jti": "[substituted_value]",
  "sub": "[substituted_value]",
  "scope": [
    "scim.read",
    "cloud_controller.admin",
    "password.write",
    "scim.write",
    "openid",
    "cloud_controller.write",
    "cloud_controller.read"
  ],
  "client_id": "cf",
  "cid": "cf",
  "azp": "cf",
  "grant_type": "password",
  "user_id": "[substituted_value]",
  "user_name": "MyUser",
  "email": "MyUser",
  "iat": 1445005922,
  "exp": 1445049122,
  "iss": "http://uaa.my_domain/oauth/token",
  "aud": [
    "scim",
    "openid",
    "cloud_controller",
    "password",
    "cf"
  ]
}

**Comment by fhanik** [comment]
Ok. the UAA (uaa.log) logs should have the error.

**Comment by vvraskin** [comment]
Here is some more information about the requests I have mentioned before:

**Comment by fhanik** [comment]
Did you change the token value in the log? Or is the entry below correct?

    [2015-10-19 09:49:47.549] uaa - 30083 [http-bio-8080-exec-9] .... DEBUG --- OAuth2AuthenticationProcessingFilter: Authentication request failed: error="invalid_token", error_description="Invalid token (could not decode): myToken"

Also, you have not included enough log entries for us to make any sense of it. The *success* vs *failure* are not even the same action. Most likely the success is getting a token, while the failure is trying to create a user.

Two different calls.

**Comment by fhanik** [comment]
Looking at the code, the call that causes that error is 
https://github.com/cloudfoundry/uaa/blob/develop/common/src/main/java/org/cloudfoundry/identity/uaa/oauth/token/UaaTokenServices.java#L929-929

This means one of two things is happening

1. The JWT can not be decoded - this seems unlikely since you can decode it yourself
2. The signature can not be verified. If this is the case, you will want to check the value of `verification-key` in the uaa.yml for all your UAA instances.

**Comment by vvraskin** [comment]
We have deleted `verification-key` and `singing-key` properties of uaa in our deployment manifest. And it worked using the key of the cloud-controller, as defined in the ruby template of uaa https://github.com/cloudfoundry/cf-release/blob/v218/jobs/uaa/templates/uaa.yml.erb#L58-59 

I assume it would be helpful to check the correctness of the following lines in the template:
https://github.com/cloudfoundry/cf-release/blob/v218/jobs/uaa/templates/uaa.yml.erb#L52-55

**Comment by amulyas** [comment]
I faced the same issue, please check if you still have login server running if its running both login server and uaa server publish login... route and that cause almost half of failures .. stop login server and try again

**Comment by amitkgupta** [comment]
Sounds like this issue has been solved.

Thanks @fhanik 

@vvraskin if you still have any follow-up questions, feel free to open a new issue.

Best,
Amit, CF Release Integration PM
