### ISSUE TITLE
bosh-lite's provision_cf fails on spiff error

### ISSUE THREAD

**Issue by cppforlife** [cloudfoundry/cf-release#818]
Using latest cf-release and bosh-lite on master today (17th), failed to launch cf on bosh-lite using provision_cf script:

    2015/010/17 21:22:38 error generating manifest: unresolved nodes:
        dynaml.MergeExpr{[properties <<]}

I have rolled back to cf-release 217 and bosh-lite 9000.55.0 and can proceed.

---

In actual fact I continue to get an error with these versions also:

```
 export CF_RELEASE_DIR=/code/cf-release
+ CF_RELEASE_DIR=/code/cf-release
+ ./bin/make_manifest_spiff
737bd8ee-f4f9-4aec-9b82-80f3d0be26f1
WARNING: The './generate_deployment_manifest' file is deprecated and will be removed. Please use './scripts/generate_deployment_manifest' instead.
2015/10/17 22:28:17 error generating manifest: unresolved nodes:
	dynaml.MergeExpr{[properties <<]}
Incorrect YAML structure in `/code/bosh-lite/manifests/cf-manifest.yml': expected Hash at the root
```

Original issue: cloudfoundry/bosh-lite#307 opened by @johnmcteague

**Comment by zaksoup** [comment]
@johnmcteague Are you certain that you were on the most recent sha of bosh-lite? `./bin/provision_cf` has not used `./bin/make_manifest_spiff` since https://github.com/cloudfoundry/bosh-lite/commit/772dfc55dbea7d18338a61c9a5c6476b6f3b9717

You can see in the diff for that commit where we switched to using `cf-release`'s scripts for manifest generation.

Zak + Mikhail,
CF Release Integration

**Comment by johnmcteague** [comment]
When I rolled back to cf 217, I had to also roll back bosh-lite. It is that attempt that uses make_manifest_spiff.

In either scenario (master for both or rolled back to older commits), I got the spiff error outlined above.

Running all on master today:

```
[johnmcteague] /code/cf-release $ git rev-parse HEAD
e4eb9f4bb337f552fdc20df0220f662bcf5d62d9
[johnmcteague] /code/cf-release $ cd ../bosh-lite/
[johnmcteague] /code/bosh-lite $ git rev-parse HEAD
0d04591d0a6d2e80c56d6e10d9533d449875e232
[johnmcteague] /code/bosh-lite $ bin/provision_cf
+ STEMCELL_SOURCE=http://bosh-jenkins-artifacts.s3.amazonaws.com/bosh-stemcell/warden
+ STEMCELL_FILE=latest-bosh-stemcell-warden.tgz
+++ dirname bin/provision_cf
++ cd bin/../../
++ pwd
+ WORKSPACE_DIR=/code
+ BOSH_LITE_DIR=/code/bosh-lite
+ CF_DIR=/code/cf-release
+ main
...
...
...
+ build_manifest
+ cd /code/cf-release
+ ./scripts/update

===> Uncommitted submodules changes will be clobbered <===


===> Unversioned changes will be clobbered <===

+ has_upstream
+ git rev-parse '@{u}'
+ git pull
Already up-to-date.
+ git submodule sync
Synchronizing submodule url for 'src/cloud_controller_ng'
Synchronizing submodule url for 'src/collector'
...
...
...
Submodule path 'src/smoke-tests': checked out 'c9d7fa48944be825c35043b236e61406fd640414'
Submodule path 'src/statsd-injector': checked out 'e7152f1b153d9f7a0acc0720378b862278af821b'
Submodule path 'src/uaa': checked out 'ff0958c08a93fbbb5f01ec9986cc066dd4497f9c'
Submodule path 'src/warden': checked out '181b550918c8c5354d3989ca557e64bc7a0b30c5'
+ git clean -ffd
Removing bosh-lite/deployments/
+ set +x
CF Release has been updated
+ ./scripts/generate-bosh-lite-dev-manifest
2015/10/22 22:00:35 error generating manifest: unresolved nodes:
	dynaml.MergeExpr{[properties <<]}
Incorrect YAML structure in `/code/cf-release/bosh-lite/deployments/cf.yml': expected Hash at the root
[johnmcteague] /code/bosh-lite $
```

**Comment by johnmcteague** [comment]
Version of spiff caused the error, an older v0.3.0 was on my path. Using the latest solves this issue. APologies.

**Comment by robdimsdale** [comment]
Ok sounds like your issue is resolved. We're going to close this issue - feel free to reopen if you have any additional problems or questions.
