### ISSUE TITLE
Inaccurate disk-usage for bosh-lite through CF Cli

### ISSUE THREAD

**Issue by aminjam** [cloudfoundry/cf-release#819]
We noticed that CF Cli is not emitting the correct disk usage for apps running on bosh-lite. It always reports 0. We are running:
```
cf-release: 221
bosh-lite: 9000.56.0
``` 
We found couple of issues:
* CF Cli always reports 0 disk-usage.
* Apps can use unlimited disk space. CF push with `-k` option is not honored when running the apps in bosh-lite. 

These may be known issues and related to each other. If not, we wanted to capture that and notify the right team for that.

**Comment by ematpl** [comment]
Hi, @aminjam,

The DEAs/Warden don't support disk quotas on BOSH-Lite, and disk usage reporting for Warden containers is based on the disk-quota system. Diego and Garden-Linux do support disk quotas when Garden-Linux makes its own btrfs loopback to store the container layers, but that configuration is currently turned off by default. Once the Diego team merges https://github.com/cloudfoundry-incubator/diego-release/pull/84, they'll be enabled by default, and in the meantime you can apply the change in that PR to your BOSH-Lite `property-overrides.yml` Diego stub now to enable them.

Thanks,
Eric

**Comment by Amit-PivotalLabs** [comment]
Thanks @ematpl!

@aminjam I think that covers it, I'll close this issue for now.

**Comment by jtarchie** [comment]
We've tried these changes on the bosh-lite and now a `cf push` fails. The app is able to stage successfully, but when it starts we are getting the following log message from `cf logs --recent`.

```
2015-10-23T14:52:35.10-0400 [API/0]      OUT App instance exited with guid 4ea531e0-ff24-42fe-a5f2-ce91b1332174 payload: {"instance"=>"404c18c1-4535-462c-6e7c-57339fb88533", "index"=>0, "reason"=>"CRASHED", "exit_description"=>"Copying into the container failed", "crash_count"=>4, "crash_timestamp"=>1445626355093332122, "version"=>"76201d85-9753-4eb7-a805-62cf7b5cb1d4"}
```

This is our `bosh releases` currently:

```
Acting as user 'admin' on 'Bosh Lite Director'

+--------------+-----------+-------------+
| Name         | Versions  | Commit Hash |
+--------------+-----------+-------------+
| cf           | 222*      | 53014242+   |
| diego        | 0.1437.0* | 7a972628    |
| etcd         | 17*       | 89da2bf4    |
| garden-linux | 0.316.0*  | 57446f5b    |
+--------------+-----------+-------------+
(*) Currently deployed
(+) Uncommitted changes

Releases total: 4
```

*NOTE:* None of these are dev releases. We downloaded them all either from `bosh.io` or from there respective release repos.

I don't know if that is a garden error or a diego error. Any insight?

**Comment by ematpl** [comment]
Hi, @aminjam and @jtarchie,

Could you try increasing your app's disk quota? Sounds like this is related to https://github.com/cloudfoundry-incubator/diego-design-notes/blob/master/migrating-to-diego.md#disk-quota-over-enforcement-during-container-setup.

Thanks,
Eric

**Comment by Amit-PivotalLabs** [comment]
You may want to open an issue on cloudfoundry-incubator/diego-release, it'll get quicker attention from the team that knows the components involved.

**Comment by jtarchie** [comment]
@Amit-PivotalLabs Thanks! Worked perfectly!

**Comment by ematpl** [comment]
@jtarchie did you mean me? I don't see a new diego-release issue about this. :) If you do mean me, I'm curious: how much did you have to increase the disk quota from what you may have expected based on DEA disk usage? We're trying to get more precise about what the 'overshoot' is when copying into the container, especially as it may change as part of some work the Garden team is doing to move off of btrfs back onto aufs for the filesystem backing the container layers.

Thanks,
Eric
