### ISSUE TITLE
In our environment,customers always make fixed self private domains,and have self pems,on haproxy,it's not difficult to realize,but when use bosh,how should i do?

### ISSUE THREAD

**Issue by wdxxs2z** [cloudfoundry/cf-release#821]
On haproxy,i can throw the sni to configure the haproxy,and add acls,but on bosh,how should i do?

I modify the haproxy.conf.erb: but it's not work,

        <% if p("ha_proxy.ssl_pem") %>
        frontend https-in
        mode http
        bind :443 ssl crt /var/vcap/jobs/haproxy/config/cert.pem <% if p("ha_proxy.other_domains").size > 0 %> crt /var/vcap/jobs/haproxy/config/self_crt <% end %> no-sslv3 ciphers <%= p("ha_proxy.ssl_ciphers") %>
        option httplog
        option forwardfor
        reqadd X-Forwarded-Proto:\ https
        <% if p("ha_proxy.other_domains").size > 0 %>
	        <% p("ha_proxy.other_domains").each do |other_domain| %>
	        use_backend http-routers if { ssl_fc_sni <%= other_domain %> }
	        <% end %>
        <% end %>
        default_backend http-routers

I add a propertie: other_domains in ha_proxy

        ha_proxy:
          other_domains:
          - a.domain
          - b.domain
          - c.selfdomain

Can cloudfoundry provider a way to configure it?

**Comment by Amit-PivotalLabs** [comment]
@shalako do you mind taking a look?

**Comment by shalako** [comment]
Hello @wdxxs2z, 

It sounds like your customers use private domains in Cloud Foundry, and you're wondering how to terminate SSL for these domains.

You could host certificates for these domains on the HAProxy, but this has two problems. 
1. You'd have to do a BOSH deploy every time a customer adds a private domain.
2. HAProxy is a single point of failure and not recommended for production use.

We currently recommend Cloud Foundry operators refer their customers to third-party, self-service solutions like Cloudflare for SSL termination. Hosting the certs on an external, highly available load balancer like F5 is also an option, but we believe this puts an unnecessary burden on the operator.

**Comment by wdxxs2z** [comment]
Thanks shalako,i close the question.
