### ISSUE TITLE
Weird error when running cf push

### ISSUE THREAD

**Issue by jhiemer** [cloudfoundry/cf-release#823]
Hi,
I have set up v222 and everything worked smoothly. Cloud Controller is behaving fine, create orgs etc.. When I try to deploy an Java application I get following error:

```bash
-----> Downloaded app package (24M)
Cloning into '/tmp/buildpacks/java-buildpack'...
fatal: unable to access 'https://github.com/cloudfoundry/java-buildpack.git/': gnutls_handshake() failed: A TLS packet with unexpected length was received.
Cloning into '/tmp/buildpacks/java-buildpack'...
fatal: unable to access 'https://github.com/cloudfoundry/java-buildpack.git/': gnutls_handshake() failed: A TLS packet with unexpected length was received.
/var/vcap/packages/dea_next/buildpacks/lib/git.rb:23:in `clone': Git clone failed: git clone --recursive https://github.com/cloudfoundry/java-buildpack.git /tmp/buildpacks/java-buildpack (RuntimeError)
	from /var/vcap/packages/dea_next/buildpacks/lib/buildpack.rb:154:in `clone_buildpack'
	from /var/vcap/packages/dea_next/buildpacks/lib/buildpack.rb:120:in `build_pack'
	from /var/vcap/packages/dea_next/buildpacks/lib/buildpack.rb:83:in `block in compile_with_timeout'
	from /usr/lib/ruby/1.9.1/timeout.rb:69:in `timeout'
	from /var/vcap/packages/dea_next/buildpacks/lib/buildpack.rb:82:in `compile_with_timeout'
	from /var/vcap/packages/dea_next/buildpacks/lib/buildpack.rb:58:in `block in stage_application'
	from /var/vcap/packages/dea_next/buildpacks/lib/buildpack.rb:53:in `chdir'
	from /var/vcap/packages/dea_next/buildpacks/lib/buildpack.rb:53:in `stage_application'
	from /var/vcap/packages/dea_next/buildpacks/bin/run:10:in `<main>'
```

I executed the command on the DEA and I am able to pull the repository without any problems. There is also no problem with my resolv.conf, which contains the necessary DNS entries. 

Has anyone an idea, what could cause this problem?

stemcell: 3098
bosh: 1.3104.0
cf-release: 222+dev.1*

**Comment by flavorjones** [comment]
Hi @jhiemer - Thanks for asking this question.

This error message ("Git clone failed") could be happening for a number of reasons. One is if you don't have permission on the repo, which clearly isn't the case with `cloudfoundry/java-buildpack`.

You may want to check if Github was having issues at the time you tried to stage your app. You may also want to verify that your CF instance has access to the public internet.

**Comment by flavorjones** [comment]
Ooh, sorry, I just saw the `gnutls_handshake()` error. That's weird. Let me poke around a bit.

**Comment by flavorjones** [comment]
I'm able to deploy fine on our internal deploys of 222. This is pretty weird. Is it reproducible? If you re-push, do you get the same error?

**Comment by jhiemer** [comment]
Hi,
yes I am able to reproduce the error with all buildpacks. When I log on to the DEA executing the warden container I can clone the repo.

**Comment by flavorjones** [comment]
OK, as a workaround, you should not have this issue if you use the installed admin buildpacks. You can do this by either specifying `-b java_buildpack` or by pushing and not specifying a buildpack.

Can you verify that this works when you use the installed buildpacks (and not a remote git repo)?

**Comment by flavorjones** [comment]
@jhiemer Are you connecting to the outside world through a proxy of some sort?

https://askubuntu.com/questions/186847/error-gnutls-handshake-failed-when-connecting-to-https-servers

**Comment by jhiemer** [comment]
@flavorjones nope there is no proxy involved as far as I know. Just a plain Openstack installation.

**Comment by jhiemer** [comment]
hm, when I deploy with -b java_buildpack, then the deployment keeps hanging at:

```bash
-----> Downloaded app package (24M)
```

**Comment by flavorjones** [comment]
@jhiemer: it looks like you're deploying off the develop branch of cf-release. Any reason you're not using a full release like `v222`? I'd like to try to remove variables from the situation and narrow down possible causes.

The error message you're seeing is consistent with a known issue between GnuTLS and some proxy configurations. I'm not an OpenStack expert, but it might be worth looking into how outbound network connections are handled from your OS compute nodes.

**Comment by jhiemer** [comment]
@flavorjones for my understanding:

/var/vcap/packages/dea_next/buildpacks/lib/git.rb

Is executed locally on the DEA or within the container? When I locally run the following in /tmp you can see that there is no error:

```bash
/var/vcap/data/packages/rootfs_cflinuxfs2/cbcda034c2bc785743c64ad4bbf689e5c96f09ed.1-3ddba574f5c44e217415333e2c040fdb1d03196c/rootfs/usr/lib/git-core/git clone --recursive https://github.com/cloudfoundry/java-buildpack.git
Cloning into 'java-buildpack'...
warning: templates not found /usr/share/git-core/templates
remote: Counting objects: 8817, done.
remote: Total 8817 (delta 0), reused 0 (delta 0), pack-reused 8817
Receiving objects: 100% (8817/8817), 2.64 MiB | 1.93 MiB/s, done.
Resolving deltas: 100% (4891/4891), done.
Checking connectivity... done.
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = (unset),
	LC_ALL = (unset),
	LC_CTYPE = "UTF-8",
	LANG = "en_US.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = (unset),
	LC_ALL = (unset),
	LC_CTYPE = "UTF-8",
	LANG = "en_US.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
```

**Comment by jhiemer** [comment]
Ok, upgraded to Stemcell 3115 with the same result.

**Comment by jhiemer** [comment]
I went into a container and ran the following:

```bash
vcap@192r55pd6vg:~$ git clone http://github.com/cloudfoundry/java-buildpack.git  
Cloning into 'java-buildpack'...
fatal: unable to access 'https://github.com/cloudfoundry/java-buildpack.git/': gnutls_handshake() failed: A TLS packet with unexpected length was received.
vcap@192r55pd6vg:~$ curl https://github.com
curl: (35) Unknown SSL protocol error in connection to github.com:443 
vcap@192r55pd6vg:~$ curl http://github.com
vcap@192r55pd6vg:~$ curl http://google.com
<HTML><HEAD><meta http-equiv="content-type" content="text/html;charset=utf-8">
<TITLE>302 Moved</TITLE></HEAD><BODY>
<H1>302 Moved</H1>
The document has moved
<A HREF="http://www.google.de/?gfe_rd=cr&amp;ei=D5krVs_jFsqH8QeC75bYBA">here</A>.
</BODY></HTML>
vcap@192r55pd6vg:~$ 
```

No I am totally without any clue. :-(

**Comment by jhiemer** [comment]
Ok it seems that we have a misconfiguration in our Openstack envrionment. The MTU is default set to 1450, but the max size I was able so send was 1426.

Reconfiguring MTU in

dea_next:
  mtu: 1426

Fixed it!

**Comment by aerondeepak** [comment]
Hello @jhiemer ,
I am facing the exactly same error, I did the same as you suggested, I changed the MTU size to 1426, but still while deploying application, its giving same error 

"ubuntu@test:~$ sudo ifconfig eth0 mtu 1426
ubuntu@test:~$ ifconfig
eth0      Link encap:Ethernet  HWaddr fa:16:3e:83:b8:0d
          inet addr:10.0.1.147  Bcast:10.0.1.255  Mask:255.255.255.0
          UP BROADCAST RUNNING MULTICAST  MTU:1426  Metric:1
          RX packets:434132 errors:0 dropped:0 overruns:0 frame:0
          TX packets:318172 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:122164665 (122.1 MB)  TX bytes:56859546 (56.8 MB)"

"C:\Users\umroot\workspaceKeplerJee\Web2291>cf push Web2291
Updating app Web2291 in org DevBox / space Applications as admin...
OK
Uploading Web2291...
Uploading app files from: C:\Users\umroot\workspaceKeplerJee\Web2291
Uploading 15.3K, 29 files
Done uploading
OK
Stopping app Web2291 in org DevBox / space Applications as admin...
OK
Starting app Web2291 in org DevBox / space Applications as admin...
-----> Downloaded app package (1.1M)
    Cloning into '/tmp/buildpacks/java-buildpack'...
fatal: unable to access 'https://github.com/cloudfoundry/java-buildpack.git/': gnutls_handshake() failed: A TLS packet with unexpected length was received.
Cloning into '/tmp/buildpacks/java-buildpack'...
fatal: unable to access 'https://github.com/cloudfoundry/java-buildpack.git/': gnutls_handshake() failed: A TLS packet with unexpected length was received.
/var/vcap/packages/dea_next/buildpacks/lib/git.rb:23:in `clone': Git clone failed: git clone --recursive https://github.com/cloudfoundry/java-buildpack.git /tmp/buildpacks/java-buildpack (RuntimeError)
        from /var/vcap/packages/dea_next/buildpacks/lib/buildpack.rb:154:in `clone_buildpack'
        from /var/vcap/packages/dea_next/buildpacks/lib/buildpack.rb:120:in `build_pack'
        from /var/vcap/packages/dea_next/buildpacks/lib/buildpack.rb:83:in `block in compile_with_timeout'
        from /usr/lib/ruby/1.9.1/timeout.rb:69:in `timeout'
        from /var/vcap/packages/dea_next/buildpacks/lib/buildpack.rb:82:in `compile_with_timeout'
        from /var/vcap/packages/dea_next/buildpacks/lib/buildpack.rb:58:in `block in stage_application'
        from /var/vcap/packages/dea_next/buildpacks/lib/buildpack.rb:53:in `chdir'
        from /var/vcap/packages/dea_next/buildpacks/lib/buildpack.rb:53:in `stage_application'
        from /var/vcap/packages/dea_next/buildpacks/bin/run:10:in `<main>'
FAILED
StagingError"

**Comment by jhiemer** [comment]
@aerondeepak I have created a blog article which describes what you can do to determine the correct MTU size: http://www.evoila.de/openstack-opensource/debugging-fatal-unable-to-access-httpsgithub-comcloudfoundryjava-buildpack-git-gnutls_handshake-failed-a-tls-packet-with-unexpected-length-was-received/?lang=en

**Comment by aerondeepak** [comment]
@jhiemer while pinging the instruction is keep haning at:

ubuntu@test:~$ ping github.com -M dont -s 1426
PING github.com (192.30.252.130) 1426(1454) bytes of data.
^C
--- github.com ping statistics ---
437 packets transmitted, 0 received, 100% packet loss, time 437803ms

ubuntu@test:~$ ping github.com -M dont -s 1426
PING github.com (192.30.252.131) 1426(1454) bytes of data.

**Comment by jhiemer** [comment]
@aerondeepak did you try lowering the size towards 1400?

**Comment by aerondeepak** [comment]
@jhiemer yes, finally its working with MTU 1350, 
ubuntu@test:~$ ping github.com -M dont -s 1350
PING github.com (192.30.252.131) 1350(1378) bytes of data.
1358 bytes from 192.30.252.131: icmp_seq=1 ttl=47 time=17.0 ms
1358 bytes from 192.30.252.131: icmp_seq=2 ttl=47 time=16.4 ms
1358 bytes from 192.30.252.131: icmp_seq=3 ttl=47 time=16.3 ms
--- github.com ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 3005ms

ubuntu@test:~$ sudo ifconfig eth0 mtu 1350
ubuntu@test:~$ ifconfig
eth0      Link encap:Ethernet  HWaddr fa:16:3e:83:b8:0d
          inet addr:10.0.1.147  Bcast:10.0.1.255  Mask:255.255.255.0
          UP BROADCAST RUNNING MULTICAST  MTU:1350  Metric:1
          RX packets:590383 errors:0 dropped:0 overruns:0 frame:0
          TX packets:438266 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:149535376 (149.5 MB)  TX bytes:82193376 (82.1 MB)

lo        Link encap:Local Loopback
          inet addr:127.0.0.1  Mask:255.0.0.0
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:60111060 errors:0 dropped:0 overruns:0 frame:0
          TX packets:60111060 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:7286927016 (7.2 GB)  TX bytes:7286927016 (7.2 GB)

rtt min/avg/max/mdev = 16.352/16.608/17.036/0.302 ms




But while deploying an application its giving same Staging error.


C:\Users\umroot\workspaceKeplerJee\Web2291>cf push Web2291 -p C:\Users\umroot\Downloads\war_sample\Web2291.war
Updating app Web2291 in org DevBox / space Applications as admin...
OK

Uploading Web2291...
Uploading app files from: C:\Users\umroot\Downloads\war_sample\Web2291.war
Uploading 20.6K, 12 files
Done uploading
OK

Stopping app Web2291 in org DevBox / space Applications as admin...
OK

Starting app Web2291 in org DevBox / space Applications as admin...
-----> Downloaded app package (1.1M)
    Cloning into '/tmp/buildpacks/java-buildpack'...
fatal: unable to access 'https://github.com/cloudfoundry/java-buildpack.git/': gnutls_handshake() failed: A TLS packet with u
nexpected length was received.
Cloning into '/tmp/buildpacks/java-buildpack'...
fatal: unable to access 'https://github.com/cloudfoundry/java-buildpack.git/': gnutls_handshake() failed: A TLS packet with u
nexpected length was received.
/var/vcap/packages/dea_next/buildpacks/lib/git.rb:23:in `clone': Git clone failed: git clone --recursive https://github.com/c
loudfoundry/java-buildpack.git /tmp/buildpacks/java-buildpack (RuntimeError)
        from /var/vcap/packages/dea_next/buildpacks/lib/buildpack.rb:154:in `clone_buildpack'
        from /var/vcap/packages/dea_next/buildpacks/lib/buildpack.rb:120:in `build_pack'
        from /var/vcap/packages/dea_next/buildpacks/lib/buildpack.rb:83:in `block in compile_with_timeout'
        from /usr/lib/ruby/1.9.1/timeout.rb:69:in `timeout'
        from /var/vcap/packages/dea_next/buildpacks/lib/buildpack.rb:82:in `compile_with_timeout'
        from /var/vcap/packages/dea_next/buildpacks/lib/buildpack.rb:58:in `block in stage_application'
        from /var/vcap/packages/dea_next/buildpacks/lib/buildpack.rb:53:in `chdir'
        from /var/vcap/packages/dea_next/buildpacks/lib/buildpack.rb:53:in `stage_application'
        from /var/vcap/packages/dea_next/buildpacks/bin/run:10:in `<main>'


FAILED
StagingError

TIP: use 'cf logs Web2291 --recent' for more information

C:\Users\umroot\workspaceKeplerJee\Web2291>cf logs Web2291 --recent
Connected, dumping recent logs for app Web2291 in org DevBox / space Applications as admin...

2015-11-27T04:57:08.88-0500 [DEA/0]      OUT Got staging request for app with id c4b8522c-5157-4fa4-bb73-814f63603b23
2015-11-27T04:57:15.04-0500 [STG/0]      OUT -----> Downloaded app package (1.1M)
2015-11-27T04:57:15.90-0500 [STG/0]      ERR     Cloning into '/tmp/buildpacks/java-buildpack'...
2015-11-27T05:00:17.08-0500 [STG/0]      ERR fatal: unable to access 'https://github.com/cloudfoundry/java-buildpack.git/': g
nutls_handshake() failed: A TLS packet with unexpected length was received.
2015-11-27T05:00:17.20-0500 [STG/0]      ERR Cloning into '/tmp/buildpacks/java-buildpack'...
2015-11-27T05:03:17.56-0500 [STG/0]      ERR fatal: unable to access 'https://github.com/cloudfoundry/java-buildpack.git/': g
nutls_handshake() failed: A TLS packet with unexpected length was received.
2015-11-27T05:03:17.57-0500 [STG/0]      ERR /var/vcap/packages/dea_next/buildpacks/lib/git.rb:23:in `clone': Git clone faile
d: git clone --recursive https://github.com/cloudfoundry/java-buildpack.git /tmp/buildpacks/java-buildpack (RuntimeError)
2015-11-27T05:03:17.57-0500 [STG/0]      ERR    from /var/vcap/packages/dea_next/buildpacks/lib/buildpack.rb:154:in `clone_bu
ildpack'
2015-11-27T05:03:17.57-0500 [STG/0]      ERR    from /var/vcap/packages/dea_next/buildpacks/lib/buildpack.rb:120:in `build_pa
ck'
2015-11-27T05:03:17.57-0500 [STG/0]      ERR    from /var/vcap/packages/dea_next/buildpacks/lib/buildpack.rb:83:in `block in
compile_with_timeout'
2015-11-27T05:03:17.58-0500 [STG/0]      ERR    from /usr/lib/ruby/1.9.1/timeout.rb:69:in `timeout'
2015-11-27T05:03:17.58-0500 [STG/0]      ERR    from /var/vcap/packages/dea_next/buildpacks/lib/buildpack.rb:82:in `compile_w
ith_timeout'
2015-11-27T05:03:17.58-0500 [STG/0]      ERR    from /var/vcap/packages/dea_next/buildpacks/lib/buildpack.rb:58:in `block in
stage_application'
2015-11-27T05:03:17.58-0500 [STG/0]      ERR    from /var/vcap/packages/dea_next/buildpacks/lib/buildpack.rb:53:in `chdir'
2015-11-27T05:03:17.58-0500 [STG/0]      ERR    from /var/vcap/packages/dea_next/buildpacks/lib/buildpack.rb:53:in `stage_app
lication'
2015-11-27T05:03:17.58-0500 [STG/0]      ERR    from /var/vcap/packages/dea_next/buildpacks/bin/run:10:in `<main>'
2015-11-27T05:03:17.59-0500 [STG/0]      OUT
2015-11-27T05:04:13.87-0500 [DEA/0]      OUT Got staging request for app with id c4b8522c-5157-4fa4-bb73-814f63603b23
2015-11-27T05:04:15.89-0500 [STG/0]      OUT -----> Downloaded app package (1.1M)
2015-11-27T05:04:16.00-0500 [STG/0]      ERR     Cloning into '/tmp/buildpacks/java-buildpack'...
2015-11-27T05:07:16.41-0500 [STG/0]      ERR fatal: unable to access 'https://github.com/cloudfoundry/java-buildpack.git/': g
nutls_handshake() failed: A TLS packet with unexpected length was received.
2015-11-27T05:07:16.42-0500 [STG/0]      ERR Cloning into '/tmp/buildpacks/java-buildpack'...
2015-11-27T05:10:17.28-0500 [STG/0]      ERR fatal: unable to access 'https://github.com/cloudfoundry/java-buildpack.git/': g
nutls_handshake() failed: A TLS packet with unexpected length was received.
2015-11-27T05:10:17.29-0500 [STG/0]      ERR /var/vcap/packages/dea_next/buildpacks/lib/git.rb:23:in `clone': Git clone faile
d: git clone --recursive https://github.com/cloudfoundry/java-buildpack.git /tmp/buildpacks/java-buildpack (RuntimeError)
2015-11-27T05:10:17.29-0500 [STG/0]      ERR    from /var/vcap/packages/dea_next/buildpacks/lib/buildpack.rb:154:in `clone_bu
ildpack'
2015-11-27T05:10:17.29-0500 [STG/0]      ERR    from /var/vcap/packages/dea_next/buildpacks/lib/buildpack.rb:120:in `build_pa
ck'
2015-11-27T05:10:17.29-0500 [STG/0]      ERR    from /var/vcap/packages/dea_next/buildpacks/lib/buildpack.rb:83:in `block in
compile_with_timeout'
2015-11-27T05:10:17.29-0500 [STG/0]      ERR    from /usr/lib/ruby/1.9.1/timeout.rb:69:in `timeout'
2015-11-27T05:10:17.29-0500 [STG/0]      ERR    from /var/vcap/packages/dea_next/buildpacks/lib/buildpack.rb:82:in `compile_w
ith_timeout'
2015-11-27T05:10:17.29-0500 [STG/0]      ERR    from /var/vcap/packages/dea_next/buildpacks/lib/buildpack.rb:58:in `block in
stage_application'
2015-11-27T05:10:17.30-0500 [STG/0]      ERR    from /var/vcap/packages/dea_next/buildpacks/lib/buildpack.rb:53:in `chdir'
2015-11-27T05:10:17.30-0500 [STG/0]      ERR    from /var/vcap/packages/dea_next/buildpacks/lib/buildpack.rb:53:in `stage_app
lication'
2015-11-27T05:10:17.30-0500 [STG/0]      ERR    from /var/vcap/packages/dea_next/buildpacks/bin/run:10:in `<main>'
2015-11-27T05:10:17.31-0500 [STG/0]      OUT

**Comment by aerondeepak** [comment]
@jhiemer Can you help to resolve this staging problem? 

Thanks,

**Comment by jhiemer** [comment]
@aerondeepak, did you also change the MTU in your deployment manifest?

**Comment by aerondeepak** [comment]
@jhiemer  Yes, I have set the MTU to 1350.

**Comment by jhiemer** [comment]
@aerondeepak and afterwards you did a `bosh deploy`? What happens if you step inside a container and try to run git clone https://buildpack.url?

**Comment by aerondeepak** [comment]
@jhiemer  I have configured cf nise (https://github.com/yudai/cf_nise_installer) on OpenStack. 

I went into the container and ran *git clone*, the command fails. However, I am able to ping or do nslookup github.com from the container . Once the *git clone* command gets terminated the container also gets deleted  from the warden. Below is the log:

root@194p71rsd8m:~# git clone https://github.com/cloudfoundry/java-buildpack.git
Cloning into 'java-buildpack'...
Terminated

root@194p71rsd8m:~# ping github.com
PING github.com (192.30.252.129) 56(84) bytes of data.
64 bytes from github.com (192.30.252.129): icmp_seq=1 ttl=46 time=16.1 ms
64 bytes from github.com (192.30.252.129): icmp_seq=2 ttl=46 time=15.5 ms
64 bytes from github.com (192.30.252.129): icmp_seq=3 ttl=46 time=15.4 ms
^C
--- github.com ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 2002ms
rtt min/avg/max/mdev = 15.484/15.732/16.164/0.323 ms
root@194p71rsd8m:~# nslookup github.com
Server:         132.205.96.93
Address:        132.205.96.93#53

Non-authoritative answer:
Name:   github.com
Address: 192.30.252.129

Now, what else I can do?
Thanks,

**Comment by aerondeepak** [comment]
@jhiemer  Could you please help to resolve this staging issue?

**Comment by jhiemer** [comment]
@aerondeepak without direct access to the infrastructure it is hard to help here. :-(
