### ISSUE TITLE
Setting API endpoint fails in CF CLI on bosh-lite setup

### ISSUE THREAD

**Issue by cppforlife** [cloudfoundry/cf-release#825]
Submitted originally by @raphaelvannson in bosh-lite: https://github.com/cloudfoundry/bosh-lite/issues/309

----

# Message
Hello, can you advise on the following issue occurring when attempting to target the CF API deployed on bosh-lite?<br> I have attempted to resolve this myself via reading of documentation, mailing lists, forums but am out of magic tricks.<br>
Let me know if you need additional information.

Thanks,
Raphael

# System details

Virtual Box 4.3.28

```
$ uname -a
Darwin MUSRV186016-382 14.5.0 Darwin Kernel Version 14.5.0: Wed Jul 29 02:26:53 PDT 2015; root:xnu-2782.40.9~1/RELEASE_X86_64 x86_64

$ vagrant -v
Vagrant 1.7.2

$ bosh -v
BOSH 1.3088.0

$ cf -v
cf version 6.13.0-e68ce0f-2015-10-15T22:53:29+00:00

$ whereis spiff
/usr/bin/spiff
```

The laptop host is not behind a proxy.

# How the error was produced
## Pre-requisites
__Strictly__ followed instructions to:
 
* [Setup bosh-lite](https://github.com/cloudfoundry/bosh-lite) -- (btw: ```./bin/provision_cf``` failed with a ```...bosh/cf-release: No such file or directory``` after uploading the stemcell but that is not the topic of this issue).
* [Deploy cloud foundry release to bosh-lite](http://docs.cloudfoundry.org/deploying/boshlite/) (see status of VMs after ```bosh deploy``` below).
* [Install the CF CLI](https://github.com/cloudfoundry/cli)

```
$ bosh vms
Acting as user 'admin' on 'Bosh Lite Director'
Deployment `cf-warden'

Director task 39

Task 39 done

+------------------------------------+---------+---------------+--------------+
| Job/index                          | State   | Resource Pool | IPs          |
+------------------------------------+---------+---------------+--------------+
| api_z1/0                           | running | large_z1      | 10.244.0.134 |
| consul_z1/0                        | running | small_z1      | 10.244.0.54  |
| doppler_z1/0                       | running | medium_z1     | 10.244.0.142 |
| etcd_z1/0                          | running | medium_z1     | 10.244.0.42  |
| ha_proxy_z1/0                      | running | router_z1     | 10.244.0.34  |
| hm9000_z1/0                        | running | medium_z1     | 10.244.0.138 |
| loggregator_trafficcontroller_z1/0 | running | small_z1      | 10.244.0.146 |
| nats_z1/0                          | running | medium_z1     | 10.244.0.6   |
| postgres_z1/0                      | running | medium_z1     | 10.244.0.30  |
| router_z1/0                        | running | router_z1     | 10.244.0.22  |
| runner_z1/0                        | running | runner_z1     | 10.244.0.26  |
| uaa_z1/0                           | running | medium_z1     | 10.244.0.130 |
+------------------------------------+---------+---------------+--------------+

VMs total: 12
```

## Error: ```api.bosh-lite.com``` is not resolved

```
$ cf api --skip-ssl-validation https://api.bosh-lite.com 
Setting api endpoint to https://api.bosh-lite.com...
FAILED
Error performing request: Get https://api.bosh-lite.com/v2/info: dial tcp: lookup api.bosh-lite.com: no such host
```

### Access to ha_proxy VM > OK
```
$ telnet 10.244.0.34 443
Trying 10.244.0.34...
Connected to 10.244.0.34.
Escape character is '^]'.
Connection closed by foreign host.

$ telnet 10.244.0.34 80
Trying 10.244.0.34...
Connected to 10.244.0.34.
Escape character is '^]'.
Connection closed by foreign host.
```

### Access to api VM >  OK

```
$ telnet 10.244.0.134 443
Trying 10.244.0.134...
telnet: connect to address 10.244.0.134: Connection refused
telnet: Unable to connect to remote host

$ telnet 10.244.0.134 80
Trying 10.244.0.134...
Connected to 10.244.0.134.
Escape character is '^]'.
Connection closed by foreign host.
```

### Trying to point directly to the api VM > KO - Provides empty response

```
$ cf api --skip-ssl-validation http://10.244.0.134
Setting api endpoint to http://10.244.0.134...
FAILED
Error performing request: Get http://10.244.0.134/v2/info: EOF
```

**Comment by cppforlife** [comment]
What does `host api.bosh-lite.com` show?

Expected:

```
$ host api.bosh-lite.com
api.bosh-lite.com has address 10.244.0.34
```

**Comment by raphaelvannson** [comment]
Hello,

This domain name has not IP address assigned to it:

```
$ host api.bosh-lite.com
$ 
```

**Comment by robdimsdale** [comment]
It looks like your DNS isn't resolving properly.  On the public internet, `bosh-lite.com` and all of its subdomains (e.g. `api.bosh-lite.com`) should resolve to `10.244.0.34` via the `pivotal.io` nameservers as you can see by running
```
$ dig bosh-lite.com

; <<>> DiG 9.8.3-P1 <<>> bosh-lite.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 64649
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;bosh-lite.com.			IN	A

;; ANSWER SECTION:
bosh-lite.com.		0	IN	A	10.244.0.34

;; Query time: 23 msec
;; SERVER: 10.80.0.18#53(10.80.0.18)
;; WHEN: Mon Oct 26 13:57:34 2015
;; MSG SIZE  rcvd: 47
```

```
$ dig bosh-lite.com ANY

; <<>> DiG 9.8.3-P1 <<>> bosh-lite.com ANY
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 55463
;; flags: qr rd ra; QUERY: 1, ANSWER: 4, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;bosh-lite.com.			IN	ANY

;; ANSWER SECTION:
bosh-lite.com.		164738	IN	NS	fry.pivotal.io.
bosh-lite.com.		164738	IN	NS	leela.pivotal.io.
bosh-lite.com.		164738	IN	NS	nibbler.pivotal.io.
bosh-lite.com.		164738	IN	NS	zoidberg.pivotal.io.

;; Query time: 1 msec
;; SERVER: 10.80.0.18#53(10.80.0.18)
;; WHEN: Mon Oct 26 13:57:39 2015
;; MSG SIZE  rcvd: 124
```
or by navigating to a public DNS search tool, e.g. [this](http://mxtoolbox.com/SuperTool.aspx?action=a%3abosh-lite.com&run=toolpage).

Perhaps your computer doesn't have access to public DNS records?  Try running these commands:
```bash
dig bosh-lite.com
```
and
```bash
dig bosh-lite.com ANY
```
what do you see?

Regards,
Rob & @rosenhouse

**Comment by raphaelvannson** [comment]
Hello,

Thanks a lot for your debugging suggestions.
Here is the output of dig:

```
$ dig bosh-lite.com

; <<>> DiG 9.8.3-P1 <<>> bosh-lite.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 38212
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;bosh-lite.com.			IN	A

;; Query time: 19 msec
;; SERVER: 192.168.66.1#53(192.168.66.1)
;; WHEN: Tue Oct 27 12:18:40 2015
;; MSG SIZE  rcvd: 31



$ dig bosh-lite.com ANY

; <<>> DiG 9.8.3-P1 <<>> bosh-lite.com ANY
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 13215
;; flags: qr rd ra; QUERY: 1, ANSWER: 6, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;bosh-lite.com.			IN	ANY

;; ANSWER SECTION:
bosh-lite.com.		0	IN	SOA	fry.pivotal.io. root.pivotal.io. 1 10900 60 604800 0
bosh-lite.com.		0	IN	NS	nibbler.pivotal.io.
bosh-lite.com.		0	IN	NS	fry.pivotal.io.
bosh-lite.com.		0	IN	NS	leela.pivotal.io.
bosh-lite.com.		0	IN	NS	zoidberg.pivotal.io.
bosh-lite.com.		0	IN	MX	10 smtp.pivotal.io.

;; Query time: 31 msec
;; SERVER: 192.168.66.1#53(192.168.66.1)
;; WHEN: Tue Oct 27 12:18:42 2015
;; MSG SIZE  rcvd: 186
```

I am attaching a screenshot of the public DNS search tool below:

<img width="999" alt="screen shot 2015-10-27 at 12 28 12 pm" src="https://cloud.githubusercontent.com/assets/12238716/10770003/42eb802e-7ca6-11e5-91d7-ca0f3cf87399.png">


Let me know if there is anything else can do help.

Thanks again!
Raph

**Comment by zaksoup** [comment]
It looks like your computer is configured to use a modem/router as a DNS server which is not resolving the DNS request properly. We're not sure why you are seeing the correct nameservers but not getting a proper resolution. Can you try manually setting your computer's DNS servers to either:

Google DNS
`8.8.8.8`
`8.8.4.4`

Or,

OpenDNS
`208.67.222.222`
`208.67.220.220`

@zaksoup & @robdimsdale

**Comment by raphaelvannson** [comment]
Hello,

Sorry for not getting back to you sooner on this.
I am moved to another piece of work and things have been quite busy but may resume this particular stream of work later.
I will get back to you with the information requested if that is the case. The status of this issue should be changed to "on hold" if that is possible in the meantime.

Thanks,
Raph

**Comment by robdimsdale** [comment]
@raphaelvannson thanks for getting back to us. Github issues don't have that workflow, so we're going to close this issue.

If you still find this is a problem in the future, feel free to open a new issue and link back to this one.

Thanks,
Rob & @njbennett
