### ISSUE TITLE
[dea_ng] Upgrade dea_next to get latest verdored warden that includes wait for iptables lock patch

### ISSUE THREAD

**Issue by keymon** [cloudfoundry/cf-release#832]
In warden, a [new patch was added recently](https://github.com/cloudfoundry/warden/commit/d667339af644776573c1c06b8cd5344e477d6caf) to add the [option -w to iptables to wait for the xtable lock](http://git.netfilter.org/iptables/commit/?id=93587a04d0f2511e108bbc4d87a8b9d28a5c5dd8). 

This patch is actually referred to be included [in the v214 release notes](https://github.com/cloudfoundry/cf-release/releases/tag/v214) as part of the warden upgrade.

This patch solves the issue that when a DEA tries to start several containers at the same time, they fail starting due errors adding the iptables rules.

But dea_next package included in the cf-release is vendoring an older version of warden which does not include this patch in the file `var/vcap/packages/dea_next/vendor/cache/warden-ad18bff7dc56/warden/root/linux/skeleton/net.sh`, so we don't benefit from the patch.

The latest version the [dea_next package installed is 01beca0f1917629512c6ec8af179ed6221123545](https://github.com/cloudfoundry/cf-release/blob/master/releases/cf-222.yml#L97), which correlates, [based on `.final_builds/packages/dea_next/index.yml`](https://github.com/cloudfoundry/cf-release/blob/master/.final_builds/packages/dea_next/index.yml#L334), with this package:

```
$ curl -qs blob.cfblob.com/2301f985-cddd-476a-908d-3273b94a1929 | tar -tvzf -  |grep cache/warden-
drwxr-xr-x  0 root   root        0 14 Oct 18:26 ./dea_next/vendor/cache/warden-d9065ba9df32/
```

That is this commit of warden: https://github.com/cloudfoundry/warden/commit/d9065ba9df32

Can we update the version of the dea package?

More info:
 * [issue initially open in dea_ng](https://github.com/cloudfoundry/dea_ng/issues/176)
 * [related issue in MEGA](https://www.pivotaltracker.com/story/show/106737450)

**Comment by sykesm** [comment]
While there are some vendored dependencies in the DEA for warden (specifically the warden clients), the function you're looking for is actually part of the warden server. That's treated as a separate bosh job with its own package.

v214 and v215 use the following package for warden:

```
curl -qs blob.cfblob.com/4a759bcc-db5d-4c25-84d2-e50fb15ae744 | tar -xvzOf - warden/root/linux/net.sh | grep iptables
x ./warden/root/linux/net.sh
  iptables -w -S INPUT 2> /dev/null |
    xargs --no-run-if-empty --max-lines=1 iptables -w
  iptables -w -S FORWARD 2> /dev/null |
    xargs --no-run-if-empty --max-lines=1 iptables -w
  iptables -w -F warden-dispatch 2> /dev/null || true
  iptables -w -X warden-dispatch 2> /dev/null || true
  iptables -w -S ${filter_forward_chain} 2> /dev/null |
    xargs --no-run-if-empty --max-lines=1 iptables -w
  iptables -w -S 2> /dev/null |
    xargs --no-run-if-empty --max-lines=1 iptables -w
  iptables -w -S 2> /dev/null |
    xargs --no-run-if-empty --max-lines=1 iptables -w
  iptables -w -S FORWARD 2> /dev/null |
    xargs --no-run-if-empty --max-lines=1 iptables -w
  iptables -w -S INPUT |
    xargs --no-run-if-empty --max-lines=1 iptables -w
  iptables -w -S INPUT |
    xargs --no-run-if-empty --max-lines=1 iptables -w
...
```

So, I'm still not sure what the concern is since a properly deployed bosh release at v214 or later will have the changes you're looking for. If you deploy the code, go into warden, and see that the wrong script is there, we need to investigate further. For now, it looks like everything is as it should be.

**Comment by keymon** [comment]
You are right that makes sense that the code used in this case should be the one provided by the warden service installed, and I don't discard that the error that we are experiencing has a different cause.

Actually we are investigating an issue on v215 of instances crashing when scaling to a lot of instances.

The case is: 
 * Running 1 DEA,
 * if you scale one app (static html app, 64M mem, 10M disk) from 1 to 200 instances.
 * several instances will get from starting to crash. 
 * Note: Eventually it starts all the instances

We will research further on the topic, but: are you aware about any limit or restrictions related to multiple concurrent requests to the warden service?

### More details:

While checking, we found that the instances were created, and after just under 28 seconds, the state is changed to 'CRASHED' due to an underlying error bubbling up from Ruby's event machine as it tries to provision egress rules for the warden container (see error example below).

We wondered if perhaps the number of simultaneous interactions with iptables on the parent VM is overloading the kernel's ability to cope, and that drove us to the related patch on warden and trace that was not vendored in `dea_next`

Actually we found that these errors happen in these points (first number of occurrences in the log). In our first tests, `setup_egress_rules` was the most common. Maybe `new_container_with_bind_mounts_and_rootfs` is a similar issue.

```
     19          "/var/vcap/packages/dea_next/lib/container/container.rb:131:in `setup_egress_rules'",
    370          "/var/vcap/packages/dea_next/lib/container/container.rb:153:in `block in new_container_with_bind_mounts_and_rootfs'",
```

### Example errors:

```
{
   "message" : "instance.start.failed with error command exited with failure",
   "file" : "/var/vcap/packages/dea_next/lib/dea/task.rb",
   "data" : {
      "attributes" : {
         "application_version" : "717fc58c-a101-41c4-962c-450591126bee",
         "instance_id" : "ffe370244244442fb7565800093a32d4",
         "vcap_application" : {
            "space_name" : "elk-for-pcf",
            "uris" : [
               "my-site.hector191015.cf2.paas.alphagov.co.uk"
            ],
            "application_id" : "d7fde214-50a2-4f57-8351-2d78b9dc8640",
            "space_id" : "14a14081-31ae-46bd-a62e-68c497a3f72b",
            "application_version" : "717fc58c-a101-41c4-962c-450591126bee",
            "users" : null,
            "application_name" : "my-site",
            "name" : "my-site",
            "limits" : {
               "fds" : 16384,
               "disk" : 10,
               "mem" : 32
            },
            "application_uris" : [
               "my-site.hector191015.cf2.paas.alphagov.co.uk"
            ],
            "version" : "717fc58c-a101-41c4-962c-450591126bee"
         },
         "limits" : {
            "fds" : 16384,
            "disk" : 10,
            "mem" : 32
         },
         "executableFile" : "deprecated",
         "prod" : false,
         "application_name" : "my-site",
         "stack" : "cflinuxfs2",
         "cc_partition" : "default",
         "droplet_sha1" : "8ef24e82476480bb51b0360c8c93d13c09124295",
         "state" : "CRASHED",
         "instance_index" : 51,
         "state_timestamp" : 1446042679.9899,
         "start_command" : null,
         "egress_network_rules" : [
            {
               "protocol" : "tcp",
               "ports" : "9200",
               "destination" : "10.0.0.4"
            },
            {
               "destination" : "0.0.0.0/0",
               "ports" : "53",
               "protocol" : "tcp"
            },
            {
               "ports" : "53",
               "protocol" : "udp",
               "destination" : "0.0.0.0/0"
            },
            {
               "protocol" : "all",
               "destination" : "0.0.0.0-9.255.255.255"
            },
            {
               "destination" : "11.0.0.0-169.253.255.255",
               "protocol" : "all"
            },
            {
               "protocol" : "all",
               "destination" : "169.255.0.0-172.15.255.255"
            },
            {
               "protocol" : "all",
               "destination" : "172.32.0.0-192.167.255.255"
            },
            {
               "protocol" : "all",
               "destination" : "192.169.0.0-255.255.255.255"
            }
         ],
         "private_instance_id" : "8c286642e1c643c0b3813b0b5668273458f1faa45d0e4b41a7cb85b3cf6bc11f",
         "application_id" : "d7fde214-50a2-4f57-8351-2d78b9dc8640",
         "state_crashed_timestamp" : 1446042679.98991,
         "console" : false,
         "health_check_timeout" : null,
         "application_uris" : [
            "my-site.hector191015.cf2.paas.alphagov.co.uk"
         ],
         "state_starting_timestamp" : 1446042618.24595,
         "state_born_timestamp" : 1446042618.24383,
         "debug" : null
      },
      "error" : "command exited with failure",
      "backtrace" : [
         "/var/vcap/packages/dea_next/vendor/cache/warden-ad18bff7dc56/em-warden-client/lib/em/warden/client/connection.rb:27:in `get'",
         "/var/vcap/packages/dea_next/vendor/cache/warden-ad18bff7dc56/em-warden-client/lib/em/warden/client.rb:46:in `call'",
         "/var/vcap/packages/dea_next/lib/container/container.rb:192:in `call'",
         "/var/vcap/packages/dea_next/lib/container/container.rb:132:in `block in setup_egress_rules'",
         "/var/vcap/packages/dea_next/lib/container/container.rb:131:in `each'",
         "/var/vcap/packages/dea_next/lib/container/container.rb:131:in `setup_egress_rules'",
         "/var/vcap/packages/dea_next/lib/container/container.rb:125:in `block in create_container'",
         "/var/vcap/packages/dea_next/lib/container/container.rb:229:in `call'",
         "/var/vcap/packages/dea_next/lib/container/container.rb:229:in `with_em'",
         "/var/vcap/packages/dea_next/lib/container/container.rb:119:in `create_container'",
         "/var/vcap/packages/dea_next/lib/dea/starting/instance.rb:543:in `block in promise_container'",
         "/var/vcap/packages/dea_next/lib/dea/promise.rb:92:in `call'",
         "/var/vcap/packages/dea_next/lib/dea/promise.rb:92:in `block in run'"
      ],
      "duration" : 61.744376958
   },
   "lineno" : 104,
   "log_level" : "warn",
   "fiber_id" : 70238609192460,
   "source" : "Dea::Instance",
   "thread_id" : 70238491087640,
   "method" : "block in resolve_and_log",
   "timestamp" : 1446042680.00229,
   "process_id" : 4212
}
```

**Comment by keymon** [comment]
Potentially related: https://github.com/cloudfoundry/dea_ng/issues/173

**Comment by keymon** [comment]
As the original issue does not seem to be directly related to the fact that dea_next package is not the latest in the release, I close the ticket.

**Comment by keymon** [comment]
Note: I think the root issue is in the number of requests warden can cope with, as described here: https://github.com/cloudfoundry/warden/issues/104
