### ISSUE TITLE
How to use 192.168.1.* in cloudfoundry deploy

### ISSUE THREAD

**Issue by yyl8815** [cloudfoundry/cf-release#839]
Hi there,
    I am trying to deploy cloudfoundry in vsphere environment. My purpose is to use internal IP(192.168.1.*) for most of the VMs created for cloudfoundry. For those VMs which need to interact with external IP, i can give them an additional IP address.

   It might be something like:
    > uaa_z1: 192.168.1.102
    > ha_proxy: 192.168.1.103, 10.62.54.x

   My original bosh director only has an external IP. 

   I want to understand:
   > Do I need to update the bosh director? Is it necessary that I need to give it an Internal IP? How to do that? Can I modify the VM settings(add another network) via vSphere and add another eth? 
   > Maybe i need to re-deploy the bosh director? How to configure the Network for the bosh manifest? I use bosh-init to deploy bosh.

   > For the CF VMs, how should i configure each of the jobs so that I can use 192.168.1.* for internal traffic and 10.62.54.* for external traffic?

Thank you very much for every help!

**Comment by Amit-PivotalLabs** [comment]
Hi @yyl8815 

Since your question doesn't appear to be specific to cf-release, but rather related to deploying and using BOSH on vSphere, I have migrated your issue there: https://github.com/cloudfoundry/bosh/issues/1009

Best,
Amit
