### ISSUE TITLE
How to generate keys and certificates for cloudfoundry(Please help update the doc of deploying CloudFoundry to vshpere)

### ISSUE THREAD

**Issue by yyl8815** [cloudfoundry/cf-release#840]
Hi experts,
     I am trying to understand the ssl related things in CloudFoundry deployment process.

     I am aware of below keys/certs( I don't really know the difference between key pair and certificate in detail) in the manifest: 
      > the jwt key for uaa
      > the secure consul cert
      > the ha_proxy key 
      > the key for router

     Can anybody kindly tell me:
     > are above four keys/certs all that needed for CloudFoundry deployment?
     > are those keys independent with each other? Or must any of them be the same?
     > How to generate those keys?

Thank you very much for any help

**Comment by yyl8815** [comment]
Can anyone kindly help?

**Comment by rosenhouse** [comment]
Hi @yyl8815 

We will attempt to answer your questions in-line:

 > are above four keys/certs all that needed for CloudFoundry deployment?

Depending on how you choose to deploy and configure CloudFoundry, you may not need to provide any certs, or just use built-in ones.  For example, [this deployment manifest for AWS](https://github.com/cloudfoundry/cf-release/blob/master/example_manifests/minimal-aws.yml) works without any user-provided certificates.  If you are deploying to a different type of infrastructure (e.g. vSphere) you may be able to adapt this manifest for your needs.  In other cases, you may need to provide many certificates.

 > are those keys independent with each other? Or must any of them be the same?

You shouldn't need to re-used the same key/cert across components, however you may choose to.


 > How to generate those keys?

You should be able to generate all the same way, for example using the `openssl rsa` and `openssl x509` tools.

You can find some docs about this on docs.cloudfoundry.org.  For example, you can find documentation about [generating these certs for Consul here](https://docs.cloudfoundry.org/deploying/common/consul-security.html).  We're aware that the getting-started experience with CloudFoundry is imperfect and we're actively working to improve the user experience and documentation in this area.

Regards,

@rosenhouse and @zaksoup

**Comment by yyl8815** [comment]
Hi @rosenhouse 

Thanks for your detailing answer. CF is a very good PaaS project. We like it very much. It is just not so easy for us to get started as you mentioned. To be honest, I have spent months getting my CF working while it is still not workable. ( I don't know how. But I want to join you guys in CF to make CF easier for others to use CloudFoundry)

Back to this question:

I am trying to deploy CloudFoundry to vsphere and I am aware of three keys/certs for now as below:
*jwt(I don't know what it stands for): https://github.com/cloudfoundry/uaa/blob/master/docs/Sysadmin-Guide.rst
*consul: http://docs.cloudfoundry.org/deploying/consul-security.html
*ha_proxy ssl_pem: https://github.com/cloudfoundry/cf-release/tree/master/example_manifests

It tooked me days(maybe weeks) to put above three information together. However, I don't even know if they are correct steps for now. I follow exactly the same steps showed in above guides but my CF is still not working :(


I am not familiar with message bus. Nor am I familiar with security things like SSL/KEYs/PEMs/Certificates. So it is extremely painful for me to get things working without a step-by-step guides which I am trying to write one.


My current issue is posted on: https://github.com/cloudfoundry/cf-release/issues/842 

However, I still want to keep this open until I get a detailed guide for generating different certs for deploying CF to vshpere.




Again, thank you, @rosenhouse 

Looking forward to your response

**Comment by Amit-PivotalLabs** [comment]
Hi @yyl8815 

You are right, deploying Cloud Foundry can be very difficult, we apologize for the rough experience.  We have tools like [BOSH-Lite](https://github.com/cloudfoundry/bosh-lite) that make it easy to spin up a local dev environment of CF within a vagrant VM, and we have tools for people who are ready to deploy full blown production deployments on vSphere, AWS, etc. and are already comfortable with generating certs, dealing with the intricacies of their IaaS networking, etc. But we have a lot of work to do to bridge the gap between those two extremes.

One difficult thing about documenting the required credentials is it differs for each deployment, depending on the operator needs so it is hard to explain things in a way that suits all users' needs. Also, we generally have the problem of keeping the documentation up to date.  CF is a big OSS project with many teams and organizations contributing, having a single, versioned, up-to-date source of truth for documenting things like this is challenging, but we are actively working on improving this.

In the mean time, I can give you guidance based on how we actually deploy CF to vSphere for our system acceptance tests.

First off, the primary source of documentation for generating deployment manifests for vSphere is here:

- high level instructions for vSphere: https://docs.cloudfoundry.org/deploying/vsphere/deploy_cf_vsphere.html
- details on generating manifest stub for vSphere: https://docs.cloudfoundry.org/deploying/vsphere/cf-stub-vsphere.html

Also, you can generally find out about what sort of data is expected in a property by looking at the "job specs".  For example, here it is for `router.ssl_key`: https://github.com/cloudfoundry/cf-release/blob/master/jobs/gorouter/spec#L52-L54.  It says in the description: "The private ssl key for ssl termination".  Unfortunately, what this does not capture is that you should only put this here if you are using the gorouter for SSL termination.  If you are not using SSL at all, or are doing SSL termination at an upstream component like HA Proxy or your own Load Balancer (not part of the CF deployment, e.g. you might have your own F5), then you wouldn't populate this value in your stub/manifest.

Finally, before getting into what we do in our actual deployment, I want to point out there's a difference between certs and (RSA) keys, vs other passwords and encryption keys that you might provide in your stub/manifest.  For starters, let's just focus on certs and (RSA) keys.

In our deployment, we have 3 sets:

1. The `uaa.jwt.signing_key` and `uaa.jwt.verification_key`.  The description of these properties in the job specs in cf-release are missing, but we will soon be pulling in this: https://github.com/cloudfoundry-incubator/uaa-release/blob/develop/jobs/uaa/spec#L254-L257.  [This doc](https://docs.cloudfoundry.org/deploying/vsphere/cf-stub-vsphere.html) that I linked to earlier explains that signing key should be an RSA private key, and the verification key should be the corresponding public key.  You can google for instructions on generating RSA key-pairs.
2. The `ha_proxy.ssl_pem` which is a concatenation of an RSA private signing key, and an RSA certificate.  You technically do not need to have this if you don't care about having encrypted https traffic to your CF components and applications.  If you do want encrypted traffic, then you can generate your own certificate (called a self-signed cert) or you can have an official one issued by a certificate authority (CA).  Your organization may also have its own internal CA.  You may wish to study on your own a bit about HTTPS, TLS, and SSL certificates and authorities, as it is very useful knowledge to have even outside the context of CF.  Also, we cannot advise you what is best for you as we cannot be responsible for assessing your security needs.
3. A bunch of certs and keys for `consul`. You technically do not need this either, and is only for *internal* traffic between components that use the internal `consul` component for service discovery.  [This document](https://docs.cloudfoundry.org/deploying/common/consul-security.html) explains in detail how to generate all the required credentials for consul, and also instructs you on how to disable the security features if you don't need them, but you have to assess on your own what your needs are.

Note that we *do not* have an SSL key on the router, as we do all SSL termination at the HA Proxy.

Please let us know if you have any follow-up questions.

**Comment by Amit-PivotalLabs** [comment]
To address your more general point @yyl8815 we're trying more and more to make https://docs.cloudfoundry.org/ the primary source of truth.  This would have led you to https://docs.cloudfoundry.org/deploying/vsphere/, which would have led you to https://docs.cloudfoundry.org/deploying/vsphere/cf-stub-vsphere.html. That doc is presently out of date, but we're working on it.

In the future, put pressure on those documents.  If you go there and it leads to you something that is wrong or doesn't work, open up an issue and we can work on fixing that.  This way we aren't working on keeping N different disparate sources of documentation up to date.

I currently have [this story](https://www.pivotaltracker.com/story/show/105805252) in flight.

**Comment by shalako** [comment]
+1 for docs.cloudfoundry.org. We strive for our docs to provide a successful, self-service experience. If they don't answer your question, kudos for hunting through the READMEs, but you shouldn't have to. Submit a github issue and help us make them better. 

Considering docs updates as an acceptance criteria of all engineering changes may be a way to prevent docs from going stale.

**Comment by yyl8815** [comment]
Thank you, @Amit-PivotalLabs, for such a detail explanation. I am always willing to help to improve CF by all means. Please tell me if you think I can do anything.

Basically I follow these two docs in docs.cloudfoundy.org:
* https://docs.cloudfoundry.org/deploying/vsphere/deploy_cf_vsphere.html
* https://docs.cloudfoundry.org/deploying/vsphere/cf-stub-vsphere.html
My details steps of deloying cloudfoundy to vsphere as below:
* clone cf-release repo
* copy `<./specs/fixtures/vsphere/cf-stub.yml>` to cf-release root folder
* add `<properties.cc.diego.staging>` and `<properties.cc.diego.running>` with value `<disabled>` based on the stub generation guide
* add `<name>`, `<meta.environment>` and `<meta.releae.name>` and `<meta.release.version>`. I do this because spiff will use these to generate `<metron.deployment>` which is a must. _I believe this is a bug for the stub examle and the doc._
* set all the username and password to `<admin>`. I do this because I once read a post saying this can address authentication mismatch issue. _Is this true?_
* create `<jwt key>` by following below step which can be found in [this post](https://github.com/cloudfoundry/uaa/blob/master/docs/Sysadmin-Guide.rst)
    * openssl genrsa -out privkey.pem 2048
    * openssl rsa -pubout -in privkey.pem -out pubkey.pem
* create `<ha_proxy ssl_pem>` by following below step which can be found in [this post](https://github.com/cloudfoundry/cf-release/tree/master/example_manifests)
    * Run "openssl genrsa -out cf.key 1024"
    * Run "openssl req -new -key cf.key -out cf.csr"
        * For the Common Name, you must enter "*." followed by your System Domain
    * Run "openssl x509 -req -in cf.csr -signkey cf.key -out cf.crt"
    * Run "cat cf.crt && cat cf.key" and replace REPLACE_WITH_SSL_CERT_AND_KEY with this value.
* create consul certs by following [this page](http://docs.cloudfoundry.org/deploying/consul-security.html) in docs.cloudfoundry.org
* set `<properties.dea_next.disk_mb/memory_mb>` both to 20480. I do this because I once read a post saying this will address my resouce limitation issue when I push apps. I never have chance to verify this.
* generate manifest by _./scripts/generate_deployment_manifest vsphere cf-stub.yml > cf-deployment.yml _

Above steps can generate a runnig CF. However, that CF is not working. I cann't push APPs, which is described in #842 .

Then I do below 3 more steps. Also it was read from a post. It did address some issue of which I don't remember details. I don't know why. Neither do I know what's the difference below configuration will make.
* add `<properties.ssl.skip_cert_verify>` and set to true
* add `<properties.uaa.no_ssl>` and set to true
* add `jobs.ha_proxy_z1.properties.ha_proxy.disable_http' and set to false

What I want to point out is:
* Am I correct in generating the 3 keys?

**Comment by yyl8815** [comment]
Hi experts,

Any comments. I am sorry that I can't provide the information in time due to the time difference. But I am trying to stay up late so that we can have more interaction

**Comment by yyl8815** [comment]
Hi @Amit-PivotalLabs 

I have set the dns to empty list and re-deployed. Same problem there.

Any ideas?

**Comment by ryanmoran** [comment]
From what I can tell of the conversation happening in #842, it looks like your issue (not being able to push apps) may be caused by a configuration issue with loggregator and not with these keys. Can you try the suggestion offered by @roxtar in that thread and report back your results?

**Comment by yyl8815** [comment]
Hi @Amit-PivotalLabs , @ryanmoran  and all,

Finally I have successfully get my CF working. However, I have do below masks:
- set `properties.uaa.no_ssl` to `true`
- set `properties.ssl.skip_cert_verify` to `true`
- set `jobs.ha_proxy_z1.properties.ha_proxy.disable_http` to false

So I want you to keep this ticket open and I will have a try with those properties set to opposite and get back to you later.

**Comment by Amit-PivotalLabs** [comment]
If you want to turn skip_cert_verify off, you will need to obtain a cert
signed by a trusted CA, you cannot use a self-signed cert.

**Comment by Amit-PivotalLabs** [comment]
@yyl8815 

I will close this ticket.  Your original issue has been solved, and you have a new issue, please open a new ticket for that.  It will not be helpful to the community if solving your new problem is buried under the old issue, no one else will be able to discover it.
