### ISSUE TITLE
Some VMs keep failing to boot up in deployment

### ISSUE THREAD

**Issue by yyl8815** [cloudfoundry/cf-release#841]
![capture](https://cloud.githubusercontent.com/assets/5707308/10971049/2e1e89a2-840d-11e5-98dc-b984a4ace679.png)
Hi there,
    I need a favor to help me out from my situation. I am trying to deploy cf-release 200. I have struggled to the step of "bosh -n deploy". However, the deployment always stoped at "start creating bunding VMS". Some post says retry "bosh -n deploy" can fix this. However, i tried with no luck.

    The retry does fix some VMs. However, there are still some VMs which just keep failing. error code like below:
-------
 Started creating bound missing vms
  Started creating bound missing vms > small_z1/0
  Started creating bound missing vms > small_z1/1
  Started creating bound missing vms > medium_z1/0
  Started creating bound missing vms > medium_z1/1
  Started creating bound missing vms > medium_z1/2
  Started creating bound missing vms > medium_z1/3
  Started creating bound missing vms > router_z1/0
  Started creating bound missing vms > router_z1/1. Failed: Timed out pinging to a8eecfaf-8254-4b04-a2e8-668cd5e0b3fb after 600 seconds (00:11:08)
   Failed creating bound missing vms > small_z1/1: Timed out pinging to e8f56631-9e35-482c-8829-
b6cb14d6724c after 600 seconds (00:11:08)
   Failed creating bound missing vms > medium_z1/3: Timed out pinging to 65d7ef2e-e594-4941-b3e8-fc85ca729d4e after 600 seconds (00:11:09)
------

I use vsphere client to check the VMs before they got deleted and got below screen shots(attached)

**Comment by drnic** [comment]
To debug a failing VM - try SSH into the VM, and look at the bosh agent
logs at /var/vcap/bosh/log/current

**Comment by yyl8815** [comment]
Hi @drnic 

Thanks for your quick response.

It seems that the VM has NOT boot up. So I can't log into the VM to check any log.

**Comment by drnic** [comment]
Perhaps now look in "bosh task <id> --debug" for CPI errors for why it cannot get VMs.




It's odd since I assume you successfully compiled packages already which means you've successfully booted and connected to agents.

**Comment by Amit-PivotalLabs** [comment]
Since this issue is not specfic to cf-release, but rather about using BOSH to deploy VMs to vSphere, I have migrated the issue: https://github.com/cloudfoundry/bosh/issues/1010
