### ISSUE TITLE
Strange error when push app to cloud foundry 220

### ISSUE THREAD

**Issue by yyl8815** [cloudfoundry/cf-release#842]
I am trying to push a simple PHP static file to validate my CF deployment when I found below error.

```
root@boshcli:~/cf-php# cf push app-php
Creating app app-php in org pivotal / space test as admin...
OK

Using route app-php.10.32.102.207.xip.io
Binding app-php.10.32.102.207.xip.io to app-php...
OK

Uploading app-php...
Uploading app files from: /root/cf-php
Uploading 44.2K, 2 files
Done uploading
OK

timeout connecting to log server, no log will be shown
Starting app app-php in org pivotal / space test as admin...
Warning: error tailing logs
Unauthorized error: You are not authorized. Error: Invalid authorization

FAILED
StagingError

TIP: use 'cf logs app-php --recent' for more information
```

I have enable CF Trace and attached log.

Can anyone kindly tell me what the problem is? How to debug? 

This is the log with CF TRACE enabled: https://gist.github.com/yyl8815/9b4684cf0c32b46cb638#file-error-log

**Comment by yyl8815** [comment]
The log: https://gist.github.com/yyl8815/9b4684cf0c32b46cb638#file-error-log

**Comment by allomov** [comment]
Hey, @yyl8815!

One of the problems I see is that you can't fetch app logs [having error](https://gist.github.com/yyl8815/9b4684cf0c32b46cb638#file-error-log-L1024). I believe this will be the reason you'll get empty output after executing `cf logs app-php --recent`. Such issue was described here some time ago https://github.com/cloudfoundry/cf-release/issues/440, but I don't see solution there. 

Also there is a [mailing list thread](https://lists.cloudfoundry.org/archives/list/cf-dev@lists.cloudfoundry.org/thread/PRUTZ43HT7ADQ4P7AMUCDUBK6XVGOUMI/) where they suggested to specify buildpack you need to use.

Could you specify more details on your issue? On what IaaS do you run CF? What is the version of CLI?

**Comment by allomov** [comment]
@yyl8815 could you try to run another app on CF? could you try to specify a buildpack during `cf push`?

**Comment by yyl8815** [comment]
Hi @allomov 

Thank you for your response. 

I am using CF 220. Stemcell 3098 for Trusty. Below is bosh version and cf version:
root@boshcli:~# bosh version
BOSH 1.3112.0
root@boshcli:~# cf -v
cf version 6.12.4-b4b6af1-2015-09-18T17:55:23+00:00
root@boshcli:~#


I saw the same issue when I tried to push other apps.

**Comment by allomov** [comment]
So the problem is in some type of apps? Did you try to run the app with buildpack specified?

**Comment by allomov** [comment]
@yyl8815 did you try to run it with specified buildpack?

At this moment this is hard to say what's wrong with this deployment. please, add more debug info. One way to get it is to subscribe NATS messages and look at messages related to staging. Here is how you can subscribe this messages
```
gem install nats --no-ri --no-rdoc
nats-sub -s '>' nats://<nats-uset>:<nats-password>@<nats-ip>:4222
```

**Comment by allomov** [comment]
You can find some more tips on debugging failed app container in this [blog post](http://blog.altoros.com/creating-a-custom-cloud-foundry-buildpack-from-scratch-whats-under-the-hood.html) in `Debugging` section.

**Comment by allomov** [comment]
@yyl8815 hope it will help.

**Comment by rosenhouse** [comment]
Hi @yyl8815, 

It looks to us like your loggregator is misconfigured and that is causing staging problems.

Do you see your app when you run `cf apps` ?

Also, could we please see the logs for the `loggregator_trafficcontroller` job?

You can use `bosh ssh` to open an ssh session on the VM you have deployed `loggregator_trafficcontroller` to.

Once you have an ssh session on the vm running the trafficcontroller you can find the logs in 
`/var/vcap/sys/log/`

You can also run `bosh download logs loggregator_trafficcontroller` although if you have not deployed the trafficcontroller template as its own job then you specify the job containing that template.

If you're able to share your deployment manifest (with secrets redacted) that would help us debug further.

@rosenhouse and @zaksoup

**Comment by yyl8815** [comment]
Hi all,
Thanks for replying this.

I am trying to provide more debug information as I can. Please tell me if I miss anything.

@rosenhouse 
**Do you see your app when you run cf apps ?**
*Yes, i can see my apps in cf apps*

**could we please see the logs for the loggregator_trafficcontroller job?**
*logs are available at: https://gist.github.com/yyl8815/2784676371af069e844f *

* Also, I have upload the whole output when I enable CF_TRACE to true and the app
    * log: https://gist.github.com/yyl8815/97b1dc07723bd18d57c1 
    * app: https://gist.github.com/yyl8815/cc241d73c978eeb188a8



Again, thank you all for debugging

**Comment by yyl8815** [comment]
Hi Experts,
    Can anyone have a look?

**Comment by rosenhouse** [comment]
Hi @yyl8815 

Thank you for sharing those logs.  I don't see anything amiss there.

The original error message that you showed suggests that you run 
```
cf logs app-php --recent
```
What does that command show?

Also, could you please share your deployment manifest?  It is difficult to determine what is wrong with your configuration without seeing the manifest.  Please redact all secrets and SSL private keys first.

Thank you.

**Comment by wfernandes** [comment]
@yyl8815 Thanks for sharing the information. Also the logs you shared happen to be those from the control scripts. If you could share the logs located in this directory `/var/vcap/sys/log/loggregator_trafficcontroller`. The files should be `loggregator_trafficcontroller.stdout.log` and `loggregator_trafficcontroller.stderr.log`.

And as @rosenhouse mentioned. It would be really helpful to see the manifest to see how loggregator is configured. Thanks.

**Comment by yyl8815** [comment]
Hi all,
Thanks for your response. Below I will add details about my deploying process, my manifest and logs. Again, I am always willing to provide more debug info. I just don't know which is needed. So please tell me if you need more. 

Basically I follow these two docs in docs.cloudfoundy.org:
* https://docs.cloudfoundry.org/deploying/vsphere/deploy_cf_vsphere.html
* https://docs.cloudfoundry.org/deploying/vsphere/cf-stub-vsphere.html
My details steps of deloying cloudfoundy to vsphere as below:
* clone cf-release repo
* copy `<./specs/fixtures/vsphere/cf-stub.yml>` to cf-release root folder
* add `<properties.cc.diego.staging>` and `<properties.cc.diego.running>` with value `<disabled>` based on the stub generation guide
* add `<name>`, `<meta.environment>` and `<meta.releae.name>` and `<meta.release.version>`. I do this because spiff will use these to generate `<metron.deployment>` which is a must. _I believe this is a bug for the stub examle and the doc._
* set all the username and password to `<admin>`. I do this because I once read a post saying this can address authentication mismatch issue. _Is this true?_
* create `<jwt key>` by following below step which can be found in [this post](https://github.com/cloudfoundry/uaa/blob/master/docs/Sysadmin-Guide.rst)
    * openssl genrsa -out privkey.pem 2048
    * openssl rsa -pubout -in privkey.pem -out pubkey.pem
* create `<ha_proxy ssl_pem>` by following below step which can be found in [this post](https://github.com/cloudfoundry/cf-release/tree/master/example_manifests)
    * Run "openssl genrsa -out cf.key 1024"
    * Run "openssl req -new -key cf.key -out cf.csr"
        * For the Common Name, you must enter "*." followed by your System Domain
    * Run "openssl x509 -req -in cf.csr -signkey cf.key -out cf.crt"
    * Run "cat cf.crt && cat cf.key" and replace REPLACE_WITH_SSL_CERT_AND_KEY with this value.
* create consul certs by following [this page](http://docs.cloudfoundry.org/deploying/consul-security.html) in docs.cloudfoundry.org
* set `<properties.dea_next.disk_mb/memory_mb>` both to 20480. I do this because I once read a post saying this will address my resouce limitation issue when I push apps. I never have chance to verify this.

Then I do below 3 more steps. Also it was read from a post. It did address some issue of which I don't remember details. I don't know why. Neither do I know what's the difference below configuration will make.
* add `<properties.ssl.skip_cert_verify>` and set to true
* add `<properties.uaa.no_ssl>` and set to true
* add `jobs.ha_proxy_z1.properties.ha_proxy.disable_http' and set to false


My manifest can be found in below places:
* Bosh manifest: https://gist.github.com/yyl8815/35531e33ada850730d0f. I use bosh-init to deploy bosh
* Stub file: https://gist.github.com/yyl8815/39616135e1bede4b22e5
* Deployment manifest: https://gist.github.com/yyl8815/f9b507efcc6a9d10c203

**Comment by yyl8815** [comment]
For the loggregator_trafficcontroller log:
* the stderror is empty
* the stdout is as below(This is not long, so I just paste it here):

`{"timestamp":1447238932.067175150,"process_id":4073,"source":"loggregator trafficcontroller","log_level":"info","message":"Startup: Setting up the loggregator traffic controller","data":null,"file":"/var/vcap/data/compile/loggregator_trafficcontroller/loggregator/src/trafficcontroller/main.go","line":69,"method":"main.main"}
{"timestamp":1447239438.762517691,"process_id":4073,"source":"loggregator trafficcontroller","log_level":"error","message":"Could not get app information: [Get https://api.192.168.1.103.xip.io/internal/log_access/19e7ea48-2c18-43f5-a29a-3aace719a223: dial tcp: lookup api.192.168.1.103.xip.io: no such host]","data":null,"file":"/var/vcap/data/compile/loggregator_trafficcontroller/loggregator/src/trafficcontroller/authorization/log_access_authorizer.go","line":42,"method":"trafficcontroller/authorization.func·002"}
{"timestamp":1447239438.762780905,"process_id":4073,"source":"loggregator trafficcontroller","log_level":"warn","message":"HttpServer: Auth token [bearer eyJhbGciOiJSUzI1NiJ9.eyJqdGkiOiI1MzhjMzU1YS1jOTVlLTRmNDktYTJiZC03MzUwMzM4MzYyMjEiLCJzdWIiOiJhNGEwNzhkYy02OWIyLTQ4NzEtOThkZi02ZTBmZjdmN2U3NjQiLCJzY29wZSI6WyJjbG91ZF9jb250cm9sbGVyLnJlYWQiLCJwYXNzd29yZC53cml0ZSIsImNsb3VkX2NvbnRyb2xsZXIud3JpdGUiLCJvcGVuaWQiLCJkb3BwbGVyLmZpcmVob3NlIiwic2NpbS53cml0ZSIsInNjaW0ucmVhZCIsImNsb3VkX2NvbnRyb2xsZXIuYWRtaW4iLCJ1YWEudXNlciJdLCJjbGllbnRfaWQiOiJjZiIsImNpZCI6ImNmIiwiYXpwIjoiY2YiLCJncmFudF90eXBlIjoicGFzc3dvcmQiLCJ1c2VyX2lkIjoiYTRhMDc4ZGMtNjliMi00ODcxLTk4ZGYtNmUwZmY3ZjdlNzY0Iiwib3JpZ2luIjoidWFhIiwidXNlcl9uYW1lIjoiYWRtaW4iLCJlbWFpbCI6ImFkbWluIiwicmV2X3NpZyI6ImYxYWMzMWYyIiwiaWF0IjoxNDQ3MjM5NDEwLCJleHAiOjE0NDcyNDAwMTAsImlzcyI6Imh0dHBzOi8vdWFhLjE5Mi4xNjguMS4xMDMueGlwLmlvL29hdXRoL3Rva2VuIiwiemlkIjoidWFhIiwiYXVkIjpbInNjaW0iLCJjbG91ZF9jb250cm9sbGVyIiwicGFzc3dvcmQiLCJjZiIsInVhYSIsIm9wZW5pZCIsImRvcHBsZXIiXX0.h6hZ2vUUxbKxuCZ9JwwsFo6HeOFDPFbuHbNokyrChSiycPHJ88gpgwprHE5CzpPbj4rFTRcfJhzIDlw2PMDdPdm71-0QJS7aSDLOTUFILZQk0AwBkyUve7ZVfMSUjOmmgeHCVl2f-XGC8ogMAGg_QVJLI7lJSk7XBqJodYH6gufOKNFC-fJ6zuOeAx3hR3cytmYULzsMf-pbbG-rIQUi8dsZtXkzLBkAM0hx0z5DR03LpDDvWRzO-6eu7N1UfEQUBW5xtO2JPGJr0O181GkmkkTPiPghwTWi8z1yoNrrjhjTX-WRTMLOc9DySE3h5MH8nytwE1VE84MxyN80j5W52Q] not authorized to access appId [19e7ea48-2c18-43f5-a29a-3aace719a223].","data":null,"file":"/var/vcap/data/compile/loggregator_trafficcontroller/loggregator/src/trafficcontroller/dopplerproxy/doppler_proxy.go","line":178,"method":"trafficcontroller/dopplerproxy.(*Proxy).isAuthorized"}
{"timestamp":1447239459.360309839,"process_id":4073,"source":"loggregator trafficcontroller","log_level":"error","message":"Could not get app information: [Get https://api.192.168.1.103.xip.io/internal/log_access/19e7ea48-2c18-43f5-a29a-3aace719a223: dial tcp: lookup api.192.168.1.103.xip.io: no such host]","data":null,"file":"/var/vcap/data/compile/loggregator_trafficcontroller/loggregator/src/trafficcontroller/authorization/log_access_authorizer.go","line":42,"method":"trafficcontroller/authorization.func·002"}
{"timestamp":1447239459.360438824,"process_id":4073,"source":"loggregator trafficcontroller","log_level":"warn","message":"HttpServer: Auth token [bearer eyJhbGciOiJSUzI1NiJ9.eyJqdGkiOiIxNGNlZGFkMC1iOTZiLTRiZTYtYmQxYi02N2VlNzM2NTM3YWEiLCJzdWIiOiJhNGEwNzhkYy02OWIyLTQ4NzEtOThkZi02ZTBmZjdmN2U3NjQiLCJzY29wZSI6WyJjbG91ZF9jb250cm9sbGVyLnJlYWQiLCJwYXNzd29yZC53cml0ZSIsImNsb3VkX2NvbnRyb2xsZXIud3JpdGUiLCJvcGVuaWQiLCJkb3BwbGVyLmZpcmVob3NlIiwic2NpbS53cml0ZSIsInNjaW0ucmVhZCIsImNsb3VkX2NvbnRyb2xsZXIuYWRtaW4iLCJ1YWEudXNlciJdLCJjbGllbnRfaWQiOiJjZiIsImNpZCI6ImNmIiwiYXpwIjoiY2YiLCJncmFudF90eXBlIjoicGFzc3dvcmQiLCJ1c2VyX2lkIjoiYTRhMDc4ZGMtNjliMi00ODcxLTk4ZGYtNmUwZmY3ZjdlNzY0Iiwib3JpZ2luIjoidWFhIiwidXNlcl9uYW1lIjoiYWRtaW4iLCJlbWFpbCI6ImFkbWluIiwicmV2X3NpZyI6ImYxYWMzMWYyIiwiaWF0IjoxNDQ3MjM5NDM4LCJleHAiOjE0NDcyNDAwMzgsImlzcyI6Imh0dHBzOi8vdWFhLjE5Mi4xNjguMS4xMDMueGlwLmlvL29hdXRoL3Rva2VuIiwiemlkIjoidWFhIiwiYXVkIjpbInNjaW0iLCJjbG91ZF9jb250cm9sbGVyIiwicGFzc3dvcmQiLCJjZiIsInVhYSIsIm9wZW5pZCIsImRvcHBsZXIiXX0.crXnb2otGFSTcbQwZcyHZp4LjAfUwE1yFCEAZcYx4g9dXGw8wQBngflA_lTDLPYIJ7t-n0ZA2wDz1u10qunWOhHuPfeMfvKWw6ywrx18swTyy-JwIZ_uedM3W1OwZYj-vxYPRfjjVKbGJKC_LdRIjS4T0MMarK57zZiNaDW8CrYERKKUzJuLiSiMnH_977OJ_bZhshYag4WtmLLZ4GS95SZmgeSVTULRCkOw5QbgiSWwwSIQF3zvupmLbLjgWFnK8MZZPAfvFkPZ-PYsfMs7SuIFy_mllf2TN4YPRW0rFBakhipHL7xwKdeHGU_oDl40Y4MVQr6j0NEbifgrRsLZyA] not authorized to access appId [19e7ea48-2c18-43f5-a29a-3aace719a223].","data":null,"file":"/var/vcap/data/compile/loggregator_trafficcontroller/loggregator/src/trafficcontroller/dopplerproxy/doppler_proxy.go","line":178,"method":"trafficcontroller/dopplerproxy.(*Proxy).isAuthorized"}`

**Comment by Amit-PivotalLabs** [comment]
Wait, why do you have `0.0.0.0` as one of your DNS entries?

**Comment by yyl8815** [comment]
I copied this somewhere. Should this be the root cause? What would you suggest I put in the DNS? I don't know how to modify that since I am using private IP

**Comment by yyl8815** [comment]
Hi @Amit-PivotalLabs

I have set the dns to empty list and re-deployed. Same problem there.

Any ideas?

**Comment by roxtar** [comment]
@yyl8815 Looking at the traffic controller logs, it looks like the traffic controller isn't able to reach your API endpoint. If that fails you will not be able to get logs. Looking at the logs from your first comment it seems like the API endpoint should be api.10.32.102.207.xip.io but this is set to api.192.168.1.103.xip.io. Maybe that's the problem.

**Comment by roxtar** [comment]
@yyl8815 Loggregator gets the API endpoint from the `srv_api_uri` property present under `cc`

**Comment by yyl8815** [comment]
Hi @roxtar 

Thank you for your response.

I may have confused you. _I have deployed several cloudfoundry instances_. All of them have the same issue. 

The CF in my first comment was not the same one as the one later. I am sorry for that.



I have checked those configuration and they are correct.

**Comment by roxtar** [comment]
@yyl8815 OK. But are you able to access the CC API URL from the traffic controller box? Can you issue a to api.192.168.1.103.xip.io/v2/info  from traffic controller?

**Comment by allomov** [comment]
@roxtar @wfernandes could you tell why you are looking for a reason of `StagingError` in problems with loggregator? It is definitely possible to deploy applications without loggregator. There is a problem with logs here, but still it's not connected with `cf push` fail. I also saw many cases when staging logs didn't give enough data to find the problem.

**Comment by wfernandes** [comment]
@allomov We were hinted from @rosenhouse that it could be related. So we thought we'd look into it a little bit. It does seem from the traffic controller logs that there seems to be a configuration issue of some kind that, yes, to your point may not be related to loggregator at all.

**Comment by yyl8815** [comment]
@roxtar 

What do you mean by traffic controller box? The ha_proxy? I tried in the ha_proxy and get below result:
root@9f518700-22bf-4baa-8131-6d0b23ad0ac2:/var/vcap/bosh_ssh/bosh_ljzv0gufq# curl `api.192.168.1.103.xip.io
curl: (6) Could not resolve host: api.192.168.1.103.xip.io`

How to fix this? Do I need to setup a DNS server to resolve api.192.168.1..103.xip.io? Why is this a must?

**Comment by roxtar** [comment]
@yyl8815 The traffic controller job runs on its own VM. You can get on the box by doing
```
bosh ssh loggregator_trafficcontroller_z1 0 
```

Can you issue the curl from that box? BTW, do these boxes have access to the internet because you will need that to resolve any xip.io address.

**Comment by yyl8815** [comment]
@roxtar  I got the same error in the loggregator box. 

No, none of the boxes can access external network. Why is it a must that each box can access the external internet?

How to fix the "cannot resolve" problem? Can I add a dns server to mapping the domain to the IP of ha_proxy? What address should I mapping?

**Comment by Amit-PivotalLabs** [comment]
You can't set the DNS list to empty.  It appears the trafficcontroller needs to talk to `api.192.168.1.103.xip.io` but can't resolve that hostname.  That hostname is supposed to resolve to `192.168.1.103`. If your components cannot reach the external network, then you will have to configure your deployment with a DNS server that can resolve `*.192.168.1.103.xip.io` to `192.168.1.103`, and then make sure the jobs are configured to use that DNS server for its DNS.  In the `networks` section of your manifest where you were configuring `dns` to `0.0.0.0` (which doesn't make sense) and `8.8.8.8` (which is an external IP that you're saying is unreachable by your VMs), you need to replace it with the IP of a DNS server that your VMs can reach, and that DNS server needs to resolve `*.192.168.1.103.xip.io` to `192.168.1.103`.

**Comment by yyl8815** [comment]
Hi @Amit-PivotalLabs ,

OK. I will set up a DNS server which can resolve *.192.168.1.103.xip.io to 192.168.1.103 to see if that works.

However, I think this should be included into the deployment of CF itself. It doesn't make sense that user needs to setup a DNS server to reserve the address used in CF.

Or at least, this information should be included into the deployment guide if this really maters.


For now, I will have try with your suggestion and will get back to you experts with results.

Thank, experts.

**Comment by Amit-PivotalLabs** [comment]
Hi there,

I see your point, and understand your difficulty.  The hard thing is there
are 100s-1000s of Cloud Foundry deployments, each with their own variations
in network, DNS, NTP, storage, etc. and if we were to have documentation in
the getting started guide for every edge case, it would be impossibly dense
for the new user experience.  Our docs are far from perfect, and we're
constantly working on them, but we strive for them to be very simple and
straightforward and work for the 90%+ use case, and we try to be very
responsive on the mailing lists and GH for the remaining unlikely edge
cases.

The reason you're experiencing the problem is follows:  Components like
Cloud Controller and UAA can be reached via api.SYSTEM_DOMAIN and
uaa.SYSTEM_DOMAIN.  In addition to clients communicating with these
components, they sometimes need to communicate with each other, and instead
of using and internal domain and internal service discovery, they use the
same external endpoints.  While more and more components are starting to
use internal service discovery mechanisms in Cloud Foundry, many of these
external access mechanisms still exist.

We have thought about also providing a DNS server for this purpose you
mentioned, but it did not seem valuable to maintain, because there are many
competing priorities, and especially because most deployments fall into one
of two categories:

1) Use a public domain name (either register a domain with a public domain
name registrar, or use a service like xip.io which is free and easy, but
very flaky and not good for CF deployments that expect to see significant
usage), and allow your VMs to reach the public internet for DNS resolution
2) Run everything behind a strict firewall, where your VMs will not have
external access to DNS servers, but your organization provides an internal
DNS server as well as internally allocates static IPs; in this case the
people in charge of the internal DNS servers and static IP allocation can
configure a DNS record on their servers to resolve to the static IP they've
allocated for you.

Usually people getting started are just kicking the tires, and will try
BOSH Lite or deploying on AWS, which are less secure but easier to get
started, or they are part of an organization with an on-premise vSphere or
Openstack deployment, in which case their organization handles things like
DNS and static IP allocation, or they are power users running their own
personal vSphere or Openstack, and are already very familiar with debugging
problems related to SSL and certs, DNS, networking, etc.

Yours is the first example I've ever seen using xip.io but preventing the
VMs from accessing external DNS servers.

Hope that helps you understand the bigger context a little better, and
hopefully you're able to fix the issue and get to actually pushing some
apps!

Best,
Amit

**Comment by yyl8815** [comment]
Hi @Amit-PivotalLabs and all,

Thanks for your debugging and finally I got my CF running.

It is never of any doubt to me that CloudFoundry is a perfect and top level PaaS in the world. But I believe we can do better in the "get started" part so that we will not push our user away from the just beginning. 

Some feedback from me:
- The stub file example in the docs.cloudfoundry.org is not working. Neither is the one included in the ./spec/fixtures/vsphere in the cf-release repository. The stub file is extremely important for users to deploy cloudfoundry. We need to make sure they are correct.

- The error codes CF cli gives are not so meaningful for debugging. It will be better if the error code to include the error in the execution level, the error in the configuration level and the resolution. I understand that the varieties of error makes it difficult for developer to identify the error in some cases. However, I don't think anyone can think about DNS when he saw error code like "error connect log server" or "staging error".

- About the DNS, I believe it will be better if CF VMs can resolve all the addresses needed for internal traffic, such as between LB and router, between Log server and DEA. Even more, it may be better if we can use two domains, one is for internal traffic and the other for external access

- Again about the DNS, I don't known if it is a must that we need to use domain. It will be much better if we can just use pure IP address as well as domains.


I understand doc is painful for developers. However, it is the first thing when our user decide to try our solution. 


It will be better if someone can put my above comments to CF agile board as enhancements or something.



_Again, Thank you. Everybody, I really appreciate your help._

**Comment by Amit-PivotalLabs** [comment]
* Improving the stubs is already work in progress: https://www.pivotaltracker.com/story/show/105805252
* Please open up issues against the CLI project for errors that are not helpful: https://github.com/cloudfoundry/cli/issues
* Communcation between LB and router does not require DNS.  Communication between Log server and DEA does not require DNS.  Again, most newer components are using Consul and an internal domain for discovering each other, it is unlikely to be a high priority for some of the older components to also switch to this model.  There are costs and benefits with everything.  But I will mention the idea to the relevant PMs
* It would be much worse using a pure IP address instead of domains.
