### ISSUE TITLE
Nobody knows how to set the domain and uris of each api when the ha_proxy is given multiple networks

### ISSUE THREAD

**Issue by yyl8815** [cloudfoundry/cf-release#844]
Hi,
I have talked with guys around about below things but failed to find a correct person to help me out.

I am setting up cloud foundry on vsphere(with exsi 6.0). In the ha_proxy setting, I post two network: One private IP(192.168.1.x) for internal traffic and one public IP(10.32.x.x) for external access. My thought is that user can access cloudfoundry(send cf commands, visit apps on cloudfoundry) via the public IP and apps/modules on cloudfoundry deployment can access external resources(apps access LDAP, download buildpack) via the public IP. 

**However, after I generated the deployment manifest via spiff and the script in cf-release repo,  I never got a workable cloudfoundry with the manifest.**

I find that all the the uris are set to *.<external_ip>.xip.io. For example, the uaa is set to https://uaa.10.32.x.x.xip.io. I don't know if this is correct. Should I change them manually.

It will be very kind of you if you can help me out.

If you need any other information, feel free to tell me. And I will post it here.

Again, Thank you very much.

**Comment by amitkgupta** [comment]
It sounds like you have two separate problems here:

1. You generated the manifest using the spiff script, and you don't end up with a working Cloud Foundry.
2. You want to know how to use the internal IP for internal communication.

I will address your first issue. Let's start and make sure you can get *something* that works, then we can perhaps discuss in a separate issue about managing internal and external traffic.

For the first issue, can you tell me:
* stemcell version
* cf-release version
* exactly what you mean when you say you "never got a workable cloudfoundry". Exactly what errors or problems are you seeing?

**Comment by yyl8815** [comment]
Hi @aaronshurley ,

Thank you very much for answering me. I really appreciate it. 

You are correct. I never success getting a working CF even I have spent weeks on that. 

I am using
  > Stemcell: 3126
  > cf-release: 223

[FAILING DETAILS]
* I can see all VMs in running status. I can log in to the cloudfoundry. I can create space.
* However, I cannot push apps. I tried to push a single PHP file which is uploaded here: https://gist.github.com/yyl8815/cc241d73c978eeb188a8 
* Below are output in console:

root@boshcli:~/cf-php/temp# cf push app
Creating app app in org pivotal / space test as admin...
OK

Creating route app.192.168.1.103.xip.io...
OK

Binding app.192.168.1.103.xip.io to app...
OK

Uploading app...
Uploading app files from: /root/cf-php/temp
Uploading 152, 1 files
Done uploading
OK

timeout connecting to log server, no log will be shown
Starting app app in org pivotal / space test as admin...
Warning: error tailing logs
Unauthorized error: You are not authorized. Error: Invalid authorization


FAILED
StagingError

TIP: use 'cf logs app --recent' for more information
* Also I have enabled CF_TRACE and full logs are available at: https://gist.github.com/yyl8815/97b1dc07723bd18d57c1 . Please be noted that I have two CF in such status. So the IP in the gist is different. However, they are showing exactly the same problem



**Thank you very much for your help**

**Comment by Amit-PivotalLabs** [comment]
You have already opened up a separate issue for that problem, so I will close this one.  Looks like you might be able to push apps fine but have some problem getting logs, maybe some misconfiguration of credentials or something related on the loggregator components.  Your other issue is being addressed already.

**Comment by yyl8815** [comment]
Hi @amitkgupta and all,

The issue above has another issue ticket: https://github.com/cloudfoundry/cf-release/issues/842

What I want to achieve in this thread is the correct approach to use different VLAN in cloudfoundry deployment.

I ever read a doc suggesting that we use 4 VLAN in CF deployment.

*MGMT VLAN for: Hypervisors and NFS (This is not related to CF, ignore)
*CF VLAN for: BOSH VMS, and CF VMS
*Service VLAN for: LB, dual-home routers
*Public VLAN for: LB, incoming requests

What I don't understand is:
    * What's the difference between CF VLAN and Service VLAN. I don't know if the doc I read is too old and at that time ha_proxy is not added to CF. Or I can just treat CF VLAN and Service VLAN as a same one. I created a internal vSwitch in 192.168.1.x for this.
    * About the LB, is it meaning that I set two NIC for the Haproxy VM. For for internal and the other for external communication.


My condition is that:
- I only have one external IP in 10.32..x.x
- My servers are binded in a switch so that can talk with each other in 192.168.x.x
- The apps our developer deployed to CF needs to access LDAP server which locates in external IP range.

My deployment manifest available at:https://gist.github.com/yyl8815/005c524c14ef807d62ef

It will be great if anyone can give a step by step guide.

**Comment by yyl8815** [comment]
Hi @Amit-PivotalLabs

As posted above, can you please help re-open this ticket?

**Comment by Amit-PivotalLabs** [comment]
Let's wait til you at least have a working deployment first.  After that issue has been resolved, if you still have issues, then I would recommend opening up a new issue, with a *single* problem statement, and all relevant information.  Your issue about logs might be related to how you're configuring IPs and domains in your manifest, so both confusions might have the same underlying cause.  Let's focus on one problem at a time.

**Comment by yyl8815** [comment]
OK.

Agree with you.

Thank you, @Amit-PivotalLabs
