### ISSUE TITLE
bosh deploy hangs when deploying cf -170 on Openstack

### ISSUE THREAD

**Issue by DImuthuUpe** [cloudfoundry/cf-release#848]
I'm trying to deploy Cloud Foundry v170 on Openstack and when I run bosh deploy, it seems like it is hanging and debug logs prints same thing again and again. 

output log - https://gist.github.com/DImuthuUpe/39de2c0ff77efd77395b
debug log - https://gist.github.com/DImuthuUpe/249257f3d25f0566ceed

What could be the reason for this issue? I'm using Openstack Juno

**Comment by allomov** [comment]
@DImuthuUpe logs seem to be incomplete, I don't see error messages there.

**Comment by Amit-PivotalLabs** [comment]
@DImuthuUpe any reason you're deploying such an old version? 170 is 2 years old, there have been at least 50 new versions since then.

**Comment by robdimsdale** [comment]
@DImuthuUpe we've not heard back in a week, so we're closing this issue. Feel free to open a new one if you have further issues.
