### ISSUE TITLE
Not able to set API endpoint in CF CLI

### ISSUE THREAD

**Issue by jrsaravanan** [cloudfoundry/cf-release#853]
We are facing the same issue as described in https://github.com/cloudfoundry/cf-release/issues/825

When we try to do cf login or cf set endpoint facing following issue

```
[root@ bosh-lite]# cf api --skip-ssl-validation https://api.bosh-lite.com
Setting api endpoint to https://api.bosh-lite.com...
FAILED
Error performing request: Get https://api.bosh-lite.com/v2/info: unexpected EOF
```

**Environment:**  
```
[root@ bosh-lite]# vagrant --version
Vagrant 1.7.4
[root@ bosh-lite]# VBoxManage --version
5.0.10r104061
[root@ bosh-lite]# cf --version
cf version 6.13.0-e68ce0f-2015-10-15T22:53:58+00:00
[root@ bosh-lite]# bosh --version
BOSH 1.3137.0
```

Trying different URL:

```
[root@ bosh-lite]# cf api --skip-ssl-validation http://10.244.0.134
Setting api endpoint to http://10.244.0.134...
FAILED
Error performing request: Get http://10.244.0.134/v2/info: EOF
```

Checking DNS (this was the root of the problem in cloudfoundry/cf-release#825):
```
[root@ bosh-lite]#  dig bosh-lite.com

; <<>> DiG 9.9.4-RedHat-9.9.4-14.el7 <<>> bosh-lite.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 7562
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;bosh-lite.com.                 IN      A

;; ANSWER SECTION:
bosh-lite.com.          0       IN      A       10.244.0.34

;; Query time: 256 msec
;; SERVER: 10.137.2.5#53(10.137.2.5)
;; WHEN: Mon Nov 16 18:34:09 BDT 2015
;; MSG SIZE  rcvd: 58

[root@ bosh-lite]#  dig bosh-lite.com ANY

; <<>> DiG 9.9.4-RedHat-9.9.4-14.el7 <<>> bosh-lite.com ANY
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 33025
;; flags: qr rd ra; QUERY: 1, ANSWER: 7, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;bosh-lite.com.                 IN      ANY

;; ANSWER SECTION:
bosh-lite.com.          0       IN      SOA     fry.pivotal.io. root.pivotal.io. 1 

10900 60 604800 0
bosh-lite.com.          0       IN      A       10.244.0.34
bosh-lite.com.          0       IN      NS      fry.pivotal.io.
bosh-lite.com.          0       IN      NS      leela.pivotal.io.
bosh-lite.com.          0       IN      NS      nibbler.pivotal.io.
bosh-lite.com.          0       IN      NS      zoidberg.pivotal.io.
bosh-lite.com.          0       IN      MX      10 smtp.pivotal.io.

;; Query time: 257 msec
;; SERVER: 10.137.2.5#53(10.137.2.5)
;; WHEN: Mon Nov 16 18:32:45 BDT 2015
;; MSG SIZE  rcvd: 213
```

**Other info:**

```
[root@ bosh-lite]# bosh vms
Acting as user 'admin' on 'Bosh Lite Director'
Deployment `cf-warden'

Director task 50

Task 50 done

+------------------------------------+---------+---------------+--------------+
| Job/index                          | State   | Resource Pool | IPs          |
+------------------------------------+---------+---------------+--------------+
| api_z1/0                           | running | large_z1      | 10.244.0.134 |
| consul_z1/0                        | running | small_z1      | 10.244.0.54  |
| doppler_z1/0                       | running | medium_z1     | 10.244.0.142 |
| etcd_z1/0                          | running | medium_z1     | 10.244.0.42  |
| ha_proxy_z1/0                      | running | router_z1     | 10.244.0.34  |
| hm9000_z1/0                        | running | medium_z1     | 10.244.0.138 |
| loggregator_trafficcontroller_z1/0 | running | small_z1      | 10.244.0.146 |
| nats_z1/0                          | running | medium_z1     | 10.244.0.6   |
| postgres_z1/0                      | running | medium_z1     | 10.244.0.30  |
| router_z1/0                        | running | router_z1     | 10.244.0.22  |
| runner_z1/0                        | running | runner_z1     | 10.244.0.26  |
| uaa_z1/0                           | running | medium_z1     | 10.244.0.130 |
+------------------------------------+---------+---------------+--------------+

VMs total: 12
```

**Comment by Amit-PivotalLabs** [comment]
Have you done Step 6 in [the BOSH-Lite instructions](https://github.com/cloudfoundry/bosh-lite#using-the-virtualbox-provider)?

> Add a set of route entries to your local route table to enable direct Warden container access every time your networking gets reset (e.g. reboot or connect to a different network). Your sudo password may be required.

> `$ bin/add-route`

**Comment by jrsaravanan** [comment]
Yes. We executed .bin/add-route

Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
default         10.x.x.x     0.0.0.0         UG    1024   0        0 eno1
10.x.x.x     0.0.0.0         255.255.255.255 UH    1024   0        0 eno1
10.244.0.0      192.168.50.4    255.255.0.0     UG    0      0        0 vboxnet0
192.168.50.0    0.0.0.0         255.255.255.0   U     0      0        0 vboxnet0
192.168.56.0    0.0.0.0         255.255.255.0   U     0      0        0 vboxnet0

**Comment by jrsaravanan** [comment]
[root@ bosh-lite]#  host api.bosh-lite.com
api.bosh-lite.com has address 10.244.0.34

**Comment by Amit-PivotalLabs** [comment]
What about `telnet 10.244.0.34 443` and `curl -vvv -k -L https://api.bosh-lite.com/v2/info`?

**Comment by jrsaravanan** [comment]
[root@ bosh-lite]# telnet 10.244.0.34 443
Trying 10.244.0.34...
Connected to 10.244.0.34.
Escape character is '^]'.


[root@ bosh-lite]# curl -vvv -k -L https://api.bosh-lite.com/v2/info
* About to connect() to proxy 10.137.2.14 port 8080 (#0)
*   Trying 10.137.2.14...
* Connected to 10.137.2.14 (10.137.2.14) port 8080 (#0)
* Establish HTTP proxy tunnel to api.bosh-lite.com:443
> CONNECT api.bosh-lite.com:443 HTTP/1.1
> Host: api.bosh-lite.com:443
> User-Agent: curl/7.29.0
> Proxy-Connection: Keep-Alive
>
* Proxy CONNECT aborted
* Connection #0 to host 10.137.2.14 left intact
curl: (56) Proxy CONNECT aborted

**Comment by Amit-PivotalLabs** [comment]
I haven't seen the `Proxy CONNECT aborted` error message before. Can you check if any info [here](https://docs.cloudfoundry.org/devguide/installcf/http-proxy.html) is helpful?

**Comment by jrsaravanan** [comment]
We already set HTTP. HTTPS proxy to our internal proxy servers. do you have to added anything apart from this ?
no_proxy=xip.io,192.168.50.4

**Comment by Amit-PivotalLabs** [comment]
If you SSH into the BOSH-Lite VM (`vagrant ssh` from the `bosh-lite` directory), and run `wget http://10.244.0.134:9022/v2/info -qO-`, what do you get?

```
vagrant@bosh-lite:~$ wget http://10.244.0.134:9022/v2/info -qO-
{"name":"vcap","build":"2222","support":"http://support.cloudfoundry.com","version":2,"description":"Cloud Foundry sponsored by Pivotal","authorization_endpoint":"https://login.bosh-lite.com","token_endpoint":"https://uaa.bosh-lite.com","min_cli_version":null,"min_recommended_cli_version":null,"api_version":"2.43.0","app_ssh_endpoint":"ssh.bosh-lite.com:2222","app_ssh_host_key_fingerprint":"a6:d1:08:0b:b0:cb:9b:5f:c4:ba:44:2a:97:26:19:8a","app_ssh_oauth_client":"ssh-proxy","routing_endpoint":"https://api.bosh-lite.com/routing","logging_endpoint":"wss://loggregator.bosh-lite.com:443","doppler_logging_endpoint":"wss://doppler.bosh-lite.com:4443"}
```

**Comment by jrsaravanan** [comment]
Here is our response : 
[root@bosh-lite]# vagrant ssh
Welcome to Ubuntu 14.04.3 LTS (GNU/Linux 3.19.0-32-generic x86_64)

 * Documentation:  https://help.ubuntu.com/
vagrant@bosh-lite:~$ wget http://10.244.0.134:9022/v2/info -qO-
{"name":"vcap","build":"2222","support":"http://support.cloudfoundry.com","version":2,"description":"Cloud Foundry sponsored by Pivotal","authorization_endpoint":"https://login.bosh-lite.com","token_endpoint":"https://uaa.bosh-lite.com","min_cli_version":null,"min_recommended_cli_version":null,"api_version":"2.43.0","app_ssh_endpoint":"ssh.bosh-lite.com:2222","app_ssh_host_key_fingerprint":null,"app_ssh_oauth_client":"ssh-proxy","routing_endpoint":"https://api.bosh-lite.com/routing","logging_endpoint":"wss://loggregator.bosh-lite.com:443","doppler_logging_endpoint":"wss://doppler.bosh-lite.com:4443"}vagrant@bosh-lite:~$

**Comment by jrsaravanan** [comment]
We have changed our firewall settings  , it resolved the issue.

Thanks for your help and support !!
