### ISSUE TITLE
openstack manifest stub

### ISSUE THREAD

**Issue by pawel2-grape** [cloudfoundry/cf-release#861]
Can I found somewhere working 'stub.yml' file for OpenStack?
After few changes, generated cf manifest was deployed but some jobs are not running. I guess it can be because invalid properties or something in manifest.
Or maybe someone can provide example working cf-openstack-manifest?

**Comment by amitkgupta** [comment]
The one on the docs website hasn't been updated yet, but you can check out the stub on the release-candidate branch:

https://github.com/cloudfoundry/cf-release/blob/eee7972f8874992fde2486d6636d11d03d59c73b/spec/fixtures/openstack/cf-stub.yml

Can you see if that works for you?

**Comment by allomov** [comment]
@pawel2-grape probably, it will interesting for you to take a look at [cf-boshworkspace](https://github.com/cloudfoundry-community/cf-boshworkspace) project, it is build around idea of using templates from cf-release.

**Comment by pawel2-grape** [comment]
Thanks for replies.
@amitkgupta I am checking this and I'll let you know if it's working or not.
@allomov in case of <a href=https://github.com/cloudfoundry-community/cf-boshworkspace>cf-boshworkspace</a>, I'm just curious, can I generate entire manifest without deploying it to bosh? I was using this before with <a href="https://github.com/cloudfoundry-community/terraform-aws-cf-install">terraform<a> on AWS but I'll check it again (if diego will be working with this I will be so happy:))

**Comment by allomov** [comment]
@pawel2-grape at this moment this functionality is not supported by the latest version `bosh-workspace`. Here a PR for this https://github.com/cloudfoundry-incubator/bosh-workspace/pull/35, but it was not accepted. I am going to work on it during this days.

**Comment by pawel2-grape** [comment]
Nice, I will be looking for this functionality, thanks :)

**Comment by pawel2-grape** [comment]
@amitkgupta I have tested stub file that you provided. After some changes in final manifest, CF was deployed (all vms are running). I've changed number of workers to 1 and removed all instances associated with cf2 network.
There are some errors (I cannot push an app) but it's not the subject of this issue:) I will try to make it work and let you know what was wrong.

**Comment by pawel2-grape** [comment]
@allomov I have deploy CF using cf-boshworkspace and manifest looks good. However I cannot push an app. There is an error when starting the app:
```
504 Gateway Time-out
The server didn't respond in time.
```
I was trying to push cf-env app. "cf logs cf-env" is empty...

**Comment by Amit-PivotalLabs** [comment]
@pawel2-grape glad your deploy worked!  If you're having new issues, do you mind opening a separate GH issue for that one.  You can add details there that are specific to that issue (e.g. CF_TRACE output).
