### ISSUE TITLE
cannot get ./scripts/generate-bosh-lite-dev-manifest running [migrated from bosh-lite#322]

### ISSUE THREAD

**Issue by Amit-PivotalLabs** [cloudfoundry/cf-release#864]
> Original issue: https://github.com/cloudfoundry/bosh-lite/issues/322
> Original poster: @NareshKosgi

I'm trying to setup a local CF using bosh-lite.  Getting an issue when I run ./scripts/generate-bosh-lite-dev-manifest.  It states Director UUID is not defined in deployment manifest.  Did I miss a step here?

```
./scripts/generate-bosh-lite-dev-manifest deploy.yml
./scripts/generate-bosh-lite-dev-manifest: line 25: ./scripts/../bosh-lite/deployments/cf.yml: Permission denied
Director UUID is not defined in deployment manifest
```

**Comment by Amit-PivotalLabs** [comment]
Hey @NareshKosgi

Can you show the output of the following commands (here's the example on my machine):

```
$ pwd
/Users/agupta/workspace/cf-release

$ bosh -v
BOSH 1.3144.0

$ alias bosh
bash: alias: bosh: not found

$ git log -n1
commit 0759f6d9fad228e2e84bf9609b592d2576082bad
Author: Yu Zhang <atomhust@gmail.com>
Date:   Mon Dec 7 09:51:22 2015 -0800

    Bump src/cloud_controller_ng

    Bump cloudfoundry/cloud_controller_ng
      Yu Zhang:
         Include warning for route service disabled during broker registration

    Signed-off-by: Jeffrey Pak <jeffrey.pak@emc.com>

$ ls -altr bosh-lite/
total 0
drwxr-xr-x   5 agupta  staff   170 Dec  7 20:12 stubs
drwxr-xr-x  33 agupta  staff  1122 Dec  7 20:12 ..
drwxr-xr-x   3 agupta  staff   102 Dec  7 20:12 .
```

Also, what's in `deploy.yml`, do you have any `director_uuid` set in there?

**Comment by NareshKosgi** [comment]
my output.  This is on a mac running mavericks 10.9.5
```
nareshs-mbp:cf-release nareshkosgi$ pwd
/opt/workspace/cf-release

bosh -v
BOSH 1.3149.0

alias bosh
-bash: alias: bosh: not found

nareshs-mbp:cf-release nareshkosgi$ git log -n1
commit 5de34b6a1327e26dfc427989c4ae2c0c9302b719
Author: CF MEGA BOT <cf-mega@pivotal.io>
Date:   Thu Dec 3 23:36:52 2015 +0000

    Final release 226

ls -altr bosh-lite/
total 0
drwxr-xr-x   5 nareshkosgi  wheel  170 Dec  9 19:30 stubs
drwxr-xr-x  29 nareshkosgi  wheel  986 Dec  9 22:36 ..
drwxr-xr-x   3 root         wheel  102 Dec 10 10:39 deployments
drwxr-xr-x   4 nareshkosgi  wheel  136 Dec 10 10:39 .

```
deploy.yml is a script that is generated using this cmd.  I was just following this tutorial

```
./scripts/generate_deployment_manifest warden templates/cf-infrastructure-warden.yml > deploy.yml
```
the deploy.yml contains just the directory uuid which from the error it states it needs

this directory uuid is in this format:
```
director_uuid: 25b988f9-206d-4e0f-a9e8-851e1ecbbb11
```

**Comment by Amit-PivotalLabs** [comment]
Okay, no need to create the `deploy.yml` with the Director UUID, the `./scripts/generate-bosh-lite-dev-manifest` does it for you as a convenience in the BOSH-Lite case.

Just run `./scripts/generate-bosh-lite-dev-manifest` without any arguments.

Looks like you have a different issue that the `bosh-lite/deployments` director is owned by root and you don't have permissions to it.  If you don't have anything in that directory you care about, delete it.  Are you running the `./scripts/generate-bosh-lite-dev-manifest` script as `root` or `nareshkosgi`?

**Comment by NareshKosgi** [comment]
I deleted the deployments directory.  I ran the script without any arguments and still getting the same error:
```
nareshs-mbp:cf-release nareshkosgi$ ./scripts/generate-bosh-lite-dev-manifest
Director UUID is not defined in deployment manifest
```

I'm running it from the cf-release directory and both cf-release and bosh-lite projects I cloned are inside the workspace directory.  Is there a particular directory structure these two projects need to have in order for this to work?

**Comment by Amit-PivotalLabs** [comment]
Can you share some more output:

```
$ git status
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working directory clean

$ git log -n1
commit 5de34b6a1327e26dfc427989c4ae2c0c9302b719
Author: CF MEGA BOT <cf-mega@pivotal.io>
Date:   Thu Dec 3 23:36:52 2015 +0000

    Final release 226

$ ./scripts/generate-bosh-lite-dev-manifest
Deployment set to `/Users/agupta/workspace/cf-release/bosh-lite/deployments/cf.yml'

$ head bosh-lite/deployments/cf.yml
compilation:
  cloud_properties:
    name: random
  network: cf1
  reuse_compilation_vms: true
  workers: 6
director_uuid: 9bca5701-66c0-43ee-a4d0-64813b4b5ece
jobs:
- instances: 1
  name: consul_z1

$ bosh target
Current target is https://192.168.50.4:25555 (Bosh Lite Director)
```

**Comment by NareshKosgi** [comment]
hi the issue was I edited the cf-deployment template.  I must have done it while trying to debug.  once I rechecked out that file it worked.  I think this can be closed now.  Thank you for the help

**Comment by Amit-PivotalLabs** [comment]
Cool, that's what I guessed (hence the "git status").  Glad you got it working now.

Amit
