### ISSUE TITLE
Bump gnatsd

### ISSUE THREAD

**Issue by fraenkel** [cloudfoundry/cf-release#867]
We have run across an issue when multiple gnatsd servers are restarted around the same time.
A recent fix to gnatsd is potentially the issue we are seeing.  What we do know is that the clients are sending NATS messages but receiving very few to none.

https://github.com/nats-io/gnatsd/commit/b62835363a08d6b14dfee655389261575baca8ee

**Comment by Amit-PivotalLabs** [comment]
Hey @fraenkel 

Sorry for the delayed response, vacation...

Have you tried bumping, does it fix your problem (without causing other problems)?  Sounds like you're saying it's potentially a fix, but not sure.  If you do find a SHA that works, would you be inclined to submit a PR for the bump?

**Comment by Amit-PivotalLabs** [comment]
Hey @fraenkel any thoughts?

**Comment by fraenkel** [comment]
I did try bumping. I don't know if it fixed our problem since any restart as long as it's not within a similar time frame will prevent the issue as well. I did not see any issue with the update.

**Comment by Amit-PivotalLabs** [comment]
Hmmm, doesn't sound too compelling at this time.  Feel free to re-open or submit PR if you're confident it fixes your problem.
