### ISSUE TITLE
bump consul-release, avoid DNS stalling on cloud_controller

### ISSUE THREAD

**Issue by JamesClonk** [cloudfoundry/cf-release#869]
Any plans on bumping the consul-release to v15 or newer?

In v15 the DNS recursor flag was added and gets used automatically, which would help with the 5s/10s DNS resolution stalling issue on the cloud_controller: https://lists.cloudfoundry.org/archives/list/cf-dev@lists.cloudfoundry.org/thread/LLUP4V5DGOU2KMLZWDTUWPTHWOOL4UHH/#Z2HORGFQJBVP5MWGU63LLRM45RKLHB5R

**Comment by robdimsdale** [comment]
@JamesClonk yes we are now continually updating the version of `consul-release` inside of `cf-release` - the next final release will likely have v21 or higher.

Does that answer your question?

Rob & @zaksoup

**Comment by JamesClonk** [comment]
yes, thanks! :smile:
