### ISSUE TITLE
Trusted certificate for HA_Proxy

### ISSUE THREAD

**Issue by yyl8815** [cloudfoundry/cf-release#871]
Hi Team,

I have requested a trusted certificate for my CF. However, after I put the certificate into ha_proxy.ssl_pem., HTTPS still complains for untrusted certificate.

What I put into the ssl_pem is like below:

```
---BEGIN CERTIFICATE---
Here is the content of the certificate I get from security team
---END CERTIFICATE---
---BEGIN PRIVATE KEY---
Here is the content of the key with which I generated the csr file
---END PRIVATE KEY---
```

Can you experts if I am configuring anthing wrongly? How to fix this?

One thing is that, the IT guys not only issue me a Trusted Certificate, they also give me a certificate chain pem file. The pem file includes the root certificate. I haven't used the pem file. I don't know how to use that either.

However, after I installed the root cert on my laptop, I don't get the https warning anymore. However, it doesn't make sense to me that every customer has to install the root certificate manually. I believe CF will have a way to support this.

Can you experts help with this?

**Comment by Amit-PivotalLabs** [comment]
Hi @yyl8815 

When you say "HTTPS still complains", what exactly is complaining?  You mean if you browse to an app in your browser you see it warns about the cert, or do `cf api api.SYSTEM_DOMAIN` you see that it still requires `--skip-ssl-validation`?

**Comment by Amit-PivotalLabs** [comment]
@yyl8815 any update?

**Comment by Amit-PivotalLabs** [comment]
Assuming fixed, closing.
