### ISSUE TITLE
the stack could not be found: The requested app stack cflinuxfs2 is not available on this system.

### ISSUE THREAD

**Issue by linlynn** [cloudfoundry/cf-release#873]
When I push app ,the following error is throwing

FAILED
Server error, status code: 404, error code: 250003, message: The stack could not be found: The requested app stack cflinuxfs2 is not available on this system.

cf vesion is 6.12.4

please let me know if you need more information

**Comment by Amit-PivotalLabs** [comment]
Hi @linlynn 

Can you give some more info about your deployment.  Did you deploy Cloud Foundry yourself or are you using a hosted version, or some installation provided by another party?  If you did it yourself, can you tell me the release version, what infrastructure you're deploying on, and how you generated your deployment manifest?

Also, is this the first app you've pushed, or has the system been working and this just started happening?  If it was working before, did anything change about the system between when it was working and now?  If you deployed CF yourself, can you give the output of `bosh vms`?

Thanks,
Amit

**Comment by Amit-PivotalLabs** [comment]
Hey @linlynn any update on this issue?

**Comment by Amit-PivotalLabs** [comment]
Assuming this issue is resolved due to inactivity, closing.

**Comment by amulyas** [comment]
any update on this issue .. we are also facing same ..

**Comment by amulyas** [comment]
Server error, status code: 404, error code: 250003, message: The stack could not be found: The requested app stack cflinuxfs2 is not available on this system.
02-01-16 15:35:43 Could not stage the application as expected, Please find below the logs
Connected, dumping recent logs for app xxxxxx-11-22 in org qwe-qwe / space qwe-zxc as ********...
