### ISSUE TITLE
Release notes should specify recommended uaa release version

### ISSUE THREAD

**Issue by johnmcteague** [cloudfoundry/cf-release#877]
As of v227, uaa-release is now required. Like the Diego, garden and etcd sections in release notes, we should specify the tested uaa release version.

**Comment by Amit-PivotalLabs** [comment]
It's not required as a separate release, although you could deploy it that way if you wish. Currently the `uaa-release` version is submoduled into `cf-release` and the jobs and packages are symlinked from the submodule, so the fact that it's a separate release is entirely transparent to the consumer of `cf-release`.  The release notes for the **Identity** section haven't been filled out yet, but usually they point to the release notes for the [UAA repo](https://github.com/cloudfoundry/uaa) itself.
