### ISSUE TITLE
cant clean the zombie progress of cloudfoundry

### ISSUE THREAD

**Issue by WenXiuchun** [cloudfoundry/cf-release#882]
![2016-01-15_15-01-04](https://cloud.githubusercontent.com/assets/6194868/12347712/9a039afc-bb9b-11e5-80e6-a33040b84211.jpg)

I cant clean those zombie Tasks. when I cleaned them, another new 8 zombie tasks come out immediately.

**Comment by Amit-PivotalLabs** [comment]
Can you give some more details?

Was this deployed with BOSH?  Which stemcell? Which version of cf-release?  What does `bosh vms` show?

**Comment by WenXiuchun** [comment]
It was deployed by cf_nise_installer. All stemcells are on one VM.

cf-release :
 name: cf
 version: '221'

**Comment by Amit-PivotalLabs** [comment]
Hi @WenXiuchun 

Unfortunately I don't know how `cf_nise_installer` manages process lifecycles.  I'd recommend opening an issue against [that repo](https://github.com/yudai/cf_nise_installer).

**Comment by WenXiuchun** [comment]
@Amit-PivotalLabs thanks anyway
