### ISSUE TITLE
load balancer named cfrouter

### ISSUE THREAD

**Issue by StanleyShen** [cloudfoundry/cf-release#884]
Failed creating bound missing vms > router_z1/0: Unknown CPI error 'Unknown' with message 'There is no ACTIVE Load Balancer named 'cfrouter'' (00:01:11)
   Failed creating bound missing vms > router_z2/0: Unknown CPI error 'Unknown' with message 'There is no ACTIVE Load Balancer named 'cfrouter'' (00:01:09)

I am trying to deploy CF to AWS, and here are my steps:
1. create one manifest stub based on http://docs.cloudfoundry.org/deploying/aws/cf-stub.html
2. generate the deployment manifest 
./scripts/generate_deployment_manifest aws stub.yml > deployment.yml

And I then get above errors, and I didn't find documentation about this cfrouter setting.

Why don't we add some description about it to make the documentation more clear for users new to cloud foundry.

**Comment by Amit-PivotalLabs** [comment]
Hey @StanleyShen 

I see you closed this issue, were you able to find the info you needed?

Cheers,
Amit

**Comment by StanleyShen** [comment]
I create another issue for more help, thanks.
