### ISSUE TITLE
CF222 fresh install: cf apps returns "status code: 500, error code: 10001, message: An unknown error occurred"

### ISSUE THREAD

**Issue by rradecki** [cloudfoundry/cf-release#886]
Hi.

I deployed CF222 on AWS. After the deployment 'cf login' and 'cf apps' succeeded.
After some time (~2h) when I tried to list apps for my org:

```
ubuntu@ip-10-0-0-193:~$ cf apps
Getting apps in org seedorg / space seedspace as admin...
FAILED
Server error, status code: 500, error code: 10001, message: An unknown error occurred.`

I exported CF_TRACE=true and got:

`Getting apps in org seedorg / space seedspace as admin...

REQUEST: [2016-01-20T14:24:46Z]
GET /v2/spaces/034f5b34-ba1b-4f66-a24a-4944bf1e6aa3/summary HTTP/1.1^M
Host: api.test.domain^M
Accept: application/json^M
Authorization: [PRIVATE DATA HIDDEN]
Content-Type: application/json^M
User-Agent: go-cli 6.15.0+fa1bfe2 / linux^M
^M


RESPONSE: [2016-01-20T14:24:46Z]
HTTP/1.1 500 Internal Server Error^M
Content-Length: 99^M
Connection: keep-alive^M
Content-Type: application/json;charset=utf-8^M
Date: Wed, 20 Jan 2016 14:24:30 GMT^M
Server: nginx^M
X-Cf-Requestid: 08cb3e26-43c6-40cf-679b-9ff2acbe9fee^M
X-Content-Type-Options: nosniff^M
X-Vcap-Request-Id: 764ebfdb-adf5-418b-6e45-65df517065fc::10cfce42-78f0-4ff1-bc09-9460ceaf72fb^M
^M
{
  "error_code": "UnknownError",
  "description": "An unknown error occurred.",
  "code": 10001
}

FAILED
Server error, status code: 500, error code: 10001, message: An unknown error occurred.
FAILED
Server error, status code: 500, error code: 10001, message: An unknown error occurred.
```

I checked situation on router_z1/0, router_z2/0 machines and they only show 500 errors in /var/vcap/data/sys/log/gorouter/access.log, 'monit summary' shows that everything is ok.

I checked then the status of api_z1/0 and api_z2/0 machines and verified that 'monit summary' reports no problems but in /var/vcap/data/sys/log/cloud_controller_ng/cloud_controller_ng.log I see info provided in the attached text file. Basically:

```
{"timestamp":1453301514.5059805,"message":"Request failed: 500: {\"code\"=>10001, \"description\"=>\"SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed\", \"error_code\"=>\"CF-SSLError\", \"ba
cktrace\"=>...
```

I noticed now that also 'cf create-org' is failling now:

```
ubuntu@ip-10-0-0-193:~$ cf create-org test
Creating org test as admin...
OK

Assigning role OrgManager to user admin in org test ...
FAILED
Failed assigning org role to user: Server error, status code: 500, error code: 10001, message: An unknown error occurred.
ubuntu@ip-10-0-0-193:~$ cf orgs
Getting orgs as admin...

name
seedorg
test
```

Any clues?

[api_z20.txt](https://github.com/cloudfoundry/cf-release/files/97607/api_z20.txt)

BR,
Rafal.

**Comment by zaksoup** [comment]
Hi Rafal,

This appears to be related to the issue you filed via the mailing list about create-org. I'm going to close out the mailing list issue and attempt to help you here on github.

From the stack trace in the log you provided it looks like there is an SSL error between the CC and the UAA. Can you please post your manifest? It is important that we see what SSL certs are where so if you do not wish to post your manifest with un-redacted certs can you label each unique cert/keypair and redact the actual values?

Thanks,
@zaksoup
CF Release Integration

**Comment by robdimsdale** [comment]
@rradecki 

This issue has been open without reply now for one week, so I'm going to close it.

If you have more to add please feel free to open a new issue.

Thanks,
Rob
