### ISSUE TITLE
StagingError:ERR Error uploading: (Polling failed - status 0 )

### ISSUE THREAD

**Issue by lotus2015** [cloudfoundry/cf-release#887]
When I push a java application, the log shows that it always encounter error as below:
2016-01-21T09:11:58.29+0800 [STG/0]      ERR 
2016-01-21T09:12:07.15+0800 [STG/0]      OUT -----> Uploading droplet (52M)
2016-01-21T09:12:07.97+0800 [API/0]      ERR encountered error: Staging error: failed to
 stage application:
2016-01-21T09:12:07.97+0800 [API/0]      ERR Error uploading: (Polling failed - status 0)

The dea_next.log returns this:
{"timestamp":1453263085.3530385,"message":"staging.task.droplet-upload-failed","log_level":"info","source":"Staging","data":{"app_guid":"2ee08735-1c63-4138-871a-170626187676","task_id":"bb3beab8a039421ea0f29ecbd8e42fb8","duration":null,"destination":"http://STAGING_UPLOAD_USER:STAGING_UPLOAD_PASSWORD@10.2.19.170:9022/staging/droplets/2ee08735-1c63-4138-871a-170626187676/upload","error":"Error uploading: (Polling failed - status 0)","backtrace":null},"thread_id":47405740405560,"fiber_id":47405750514500,"process_id":4244,"file":"/var/vcap/packages/dea_next/lib/dea/staging/staging_task.rb","lineno":346,"method":"block (2 levels) in promise_app_upload"}

**Comment by Amit-PivotalLabs** [comment]
@lotus2015 

Sorry you're running into issues.  Do you see other apps stage successfully?  Do you see any logs from the Cloud Controller at 10.2.19.170 around that timestamp suggesting why the upload failed?

**Comment by lotus2015** [comment]
@Amit-PivotalLabs 

I don't see any apps stage successfully.  And the cloud controller returns this：

{"timestamp":1453426635.00175,"message":"PG::UndefinedTable: ERROR:  relation \"schema_migrations\" does not exist\nLINE 1: SELECT NULL AS \"nil\" FROM \"schema_migrations\" LIMIT 1\n                                  ^: SELECT NULL AS \"nil\" FROM \"schema_migrations\" LIMIT 1","log_level":"error","source":"cc.background","data":{},"thread_id":47266083207560,"fiber_id":47266109446560,"process_id":4515,"file":"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.2.0/gems/sequel-4.21.0/lib/sequel/database/logging.rb","lineno":70,"method":"block in log_each"}

{"timestamp":1453427960.3928854,"message":"Encountered error on stager with id 0-3313ff7d8efe406e9aa9225e76f7123d: VCAP::Errors::ApiError\n/var/vcap/data/packages/cloud_controller_ng/fa50627862bae85bbbb0cb4d0bed7676008abfa1.1-38d02d9fb8b8ee4875aa25f46d3fa950989f087a/cloud_controller_ng/lib/cloud_controller/dea/app_stager_task.rb:112:in `check_staging_error!'\n/var/vcap/data/packages/cloud_controller_ng/fa50627862bae85bbbb0cb4d0bed7676008abfa1.1-38d02d9fb8b8ee4875aa25f46d3fa950989f087a/cloud_controller_ng/lib/cloud_controller/dea/app_stager_task.rb:86:in `handle_second_response'\n/var/vcap/data/packages/cloud_controller_ng/fa50627862bae85bbbb0cb4d0bed7676008abfa1.1-38d02d9fb8b8ee4875aa25f46d3fa950989f087a/cloud_controller_ng/lib/cloud_controller/dea/app_stager_task.rb:57:in `block (2 levels) in stage'\n/var/vcap/data/packages/cloud_controller_ng/fa50627862bae85bbbb0cb4d0bed7676008abfa1.1-38d02d9fb8b8ee4875aa25f46d3fa950989f087a/cloud_controller_ng/lib/cloud_controller/multi_response_message_bus_request.rb:48:in `call'\n/var/vcap/data/packages/cloud_controller_ng/fa50627862bae85bbbb0cb4d0bed7676008abfa1.1-38d02d9fb8b8ee4875aa25f46d3fa950989f087a/cloud_controller_ng/lib/cloud_controller/multi_response_message_bus_request.rb:48:in `trigger_on_response'\n/var/vcap/data/packages/cloud_controller_ng/fa50627862bae85bbbb0cb4d0bed7676008abfa1.1-38d02d9fb8b8ee4875aa25f46d3fa950989f087a/cloud_controller_ng/lib/cloud_controller/multi_response_message_bus_request.rb:43:in `handle_received_response'\n/var/vcap/data/packages/cloud_controller_ng/fa50627862bae85bbbb0cb4d0bed7676008abfa1.1-38d02d9fb8b8ee4875aa25f46d3fa950989f087a/cloud_controller_ng/lib/cloud_controller/multi_response_message_bus_request.rb:22:in `block in request'\n/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.2.0/gems/cf-message-bus-0.3.4/lib/cf_message_bus/message_bus.rb:88:in `yield'\n/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.2.0/gems/cf-message-bus-0.3.4/lib/cf_message_bus/message_bus.rb:88:in `run_handler'\n/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.2.0/gems/cf-message-bus-0.3.4/lib/cf_message_bus/message_bus.rb:41:in `block (2 levels) in request'\n/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.2.0/gems/cf-message-bus-0.3.4/lib/cf_message_bus/message_bus.rb:104:in `yield'\n/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.2.0/gems/cf-message-bus-0.3.4/lib/cf_message_bus/message_bus.rb:104:in `process_message'\n/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.2.0/gems/cf-message-bus-0.3.4/lib/cf_message_bus/message_bus.rb:40:in `block in request'\n/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.2.0/gems/nats-0.5.1/lib/nats/client.rb:415:in `call'\n/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.2.0/gems/nats-0.5.1/lib/nats/client.rb:415:in `block in request'\n/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.2.0/gems/nats-0.5.1/lib/nats/client.rb:515:in `call'\n/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.2.0/gems/nats-0.5.1/lib/nats/client.rb:515:in `on_msg'\n/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.2.0/gems/nats-0.5.1/lib/nats/client.rb:576:in `receive_data'\n/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.2.0/gems/eventmachine-1.0.8/lib/eventmachine.rb:193:in `run_machine'\n/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.2.0/gems/eventmachine-1.0.8/lib/eventmachine.rb:193:in `run'\n/var/vcap/data/packages/cloud_controller_ng/fa50627862bae85bbbb0cb4d0bed7676008abfa1.1-38d02d9fb8b8ee4875aa25f46d3fa950989f087a/cloud_controller_ng/lib/cloud_controller/runner.rb:85:in `run!'\n/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/bin/cloud_controller:8:in `<main>'","log_level":"error","source":"cc.app_stager","data":{},"thread_id":46923772344720,"fiber_id":46923800096140,"process_id":5313,"file":"/var/vcap/data/packages/cloud_controller_ng/fa50627862bae85bbbb0cb4d0bed7676008abfa1.1-38d02d9fb8b8ee4875aa25f46d3fa950989f087a/cloud_controller_ng/lib/cloud_controller/dea/app_stager_task.rb","lineno":90,"method":"rescue in handle_second_response"}

{"timestamp":1453427960.262539,"message":"handle_received_response: sid=10 response='{\"task_id\"=>\"45d6455cfbaf40759f9dd2e360a4a659\", \"detected_buildpack\"=>\"java-buildpack=v3.3.1-https://github.com/cloudfoundry/java-buildpack.git#063836b open-jdk-like-jre=1.8.0_65 open-jdk-like-memory-calculator=2.0.1_RELEASE tomcat-access-logging-support=2.5.0_RELEASE tomcat-instance=8.0.30 tomcat-lifecycle-support=2.5.0_...\", \"buildpack_key\"=>\"b55a6152-6887-416d-9b15-2ca8058ed926_34e071ea58c17e2dec93f14052fd351869e45f7c\", \"droplet_sha1\"=>\"7621c934ebd3a42d03b7771d9dffc2f0ff1d5538\", \"detected_start_command\"=>\"CALCULATED_MEMORY=$($PWD/.java-buildpack/open_jdk_jre/bin/java-buildpack-memory-calculator-2.0.1_RELEASE -memorySizes=metaspace:64m.. -memoryWeights=heap:75,metaspace:10,native:10,stack:5 -memoryInitials=heap:100%,metaspace:100% -totMemory=$MEMORY_LIMIT) &&  JAVA_HOME=$PWD/.java-buildpack/open_jdk_jre JAVA_OPTS=\\\"-Djava.io.tmpdir=$TMPDIR -XX:OnOutOfMemoryError=$PWD/.java-buildpack/open_jdk_jre/bin/killjava.sh $CALCULATED_MEMORY -Daccess.logging.enabled=false -Dhttp.port=$PORT\\\" $PWD/.java-buildpack/tomcat/bin/catalina.sh run\", \"procfile\"=>{\"web\"=>\"CALCULATED_MEMORY=$($PWD/.java-buildpack/open_jdk_jre/bin/java-buildpack-memory-calculator-2.0.1_RELEASE -memorySizes=metaspace:64m.. -memoryWeights=heap:75,metaspace:10,native:10,stack:5 -memoryInitials=heap:100%,metaspace:100% -totMemory=$MEMORY_LIMIT) &&  JAVA_HOME=$PWD/.java-buildpack/open_jdk_jre JAVA_OPTS=\\\"-Djava.io.tmpdir=$TMPDIR -XX:OnOutOfMemoryError=$PWD/.java-buildpack/open_jdk_jre/bin/killjava.sh $CALCULATED_MEMORY -Daccess.logging.enabled=false -Dhttp.port=$PORT\\\" $PWD/.java-buildpack/tomcat/bin/catalina.sh run\"}, \"error\"=>\"Error uploading: (Polling failed - status 0)\"}'","log_level":"debug","source":"MultiResponseMessageBusRequest","data":{},"thread_id":46923772344720,"fiber_id":46923800096140,"process_id":5313,"file":"/var/vcap/data/packages/cloud_controller_ng/fa50627862bae85bbbb0cb4d0bed7676008abfa1.1-38d02d9fb8b8ee4875aa25f46d3fa950989f087a/cloud_controller_ng/lib/cloud_controller/multi_response_message_bus_request.rb","lineno":39,"method":"handle_received_response"}

Thinks,
Amit-PivotalLabs !

**Comment by Amit-PivotalLabs** [comment]
@fraenkel @dieucao any ideas about this error?  Looks like DEA uploading to CC is consistently failing in "Polling".

**Comment by fraenkel** [comment]
@Amit-PivotalLabs This happens when the upload either times out or a connection issue. I will open a bug to add more relevant information when there is a connection error.

**Comment by lotus2015** [comment]
Hi,@fraenkel
Thanks a lot for response.
How can I open a bug for more information?

**Comment by fraenkel** [comment]
I have already created a bug in our tracker for this.
https://www.pivotaltracker.com/story/show/112398859

**Comment by ScarletTanager** [comment]
Hello,

We tried to reproduce the error to see what kind of information gets logged. When we erase the route to the cc on the runner vm and then try to push an app, this is what we see in the dea's logs:

    {"timestamp":1454614275.3288903,"message":"em-upload.error","log_level":"warn",
    "source":"Staging", "data":{"app_guid":"354014eb-d782-40a2-b994-ae86db11c58b",
    "task_id":"78598debedfa4ba98cb7f4ac1d40c8b0",
    "destination":"http://upload-user:upload-password@10.244.0.134:9022/staging/droplets/354014eb-d782-40a2-b994-ae86db11c58b/upload",
    "connection_count":15,"message":"Error uploading: (Polling failed - status 0)",
    "http_error":"Errno::ETIMEDOUT","http_status":0,"http_response":""},
    "thread_id":47275385231760,"fiber_id":47275389076700,"process_id":8457,
    "file":"/var/vcap/packages/dea_next/lib/dea/utils/upload.rb","lineno":53,"method":"handle_error"}

So, we're getting a similar error to yours, but it includes the http error. Have you tried looking at your dea log to see if you might find more helpful info? This was from /var/vcap/sys/log/dea_next/dea_next.log on the runner vm.

Thanks,
@ScarletTanager and @jberkhahn 
CF runtime_og team

**Comment by yatzek** [comment]
Hi,

We had a similar problem, we think it was caused by slow s3 uploads, we fixed it by increasing EM::HttpRequest timeout (default connect and inactivity values are 5s and 10s):

https://github.com/nimbus-cloud/dea_ng/commit/729e3e53180a066b4ad7f6deb9eb02838cb2dc6a

We also made a this fix which may be related to this problem:

https://github.com/nimbus-cloud/cloud_controller_ng/commit/5bfa145c3316e3666053f06fa402c252eae6266e

We use a private s3 provider and they were claiming that 'max_keys' is being ignored by their software and that we should be sending 'max-keys' as per the spec:

http://docs.aws.amazon.com/AmazonS3/latest/API/RESTBucketGET.html

Regards,
Jacek Szlachta

**Comment by lotus2015** [comment]
Hi, @ScarletTanager 
Thanks a lot for response.
My dea log returns this：
{"timestamp":1455596562.290276,"message":"em-upload.error","log_level":"warn","source":"Staging","data":{"app_guid":"10097841-e01c-424f-8bbd-c4132b8c174e","task_id":"a1674890178c4ccda7a5ca4e063976c8","destination":"http://staging_upload_user:staging_upload_password@10.2.19.170:9022/staging/droplets/10097841-e01c-424f-8bbd-c4132b8c174e/upload","connection_count":10,"message":"Error uploading: (Polling failed - status 0)",**"http_error":"connection closed by server"**,"http_status":0,"http_response":""},"thread_id":47012367604120,"fiber_id":47012384126120,"process_id":4268,"file":"/var/vcap/packages/dea_next/lib/dea/utils/upload.rb","lineno":53,"method":"handle_error"}

**Comment by Amit-PivotalLabs** [comment]
Closing this thread due to inactivity.

**Comment by Oskoss** [comment]
We are having the exact same issue. How did you guys get this working?

Our log on CC has this error:
```
{"timestamp":1466086696.1735463,"message":"em-upload.begin","log_level":"info","source":"Staging","data":{"app_guid":"db788ab0-bff0-40d9-9306-c1efd1eeb537","task_id":"95840b8bff4e4fce8a4a64516c391ef9","destination":"http://cloud-controller-ng.service.cf.internal:9022/staging/droplets/db788ab0-bff0-40d9-9306-c1efd1eeb537/upload"},"thread_id":46976250851600,"fiber_id":46976257016500,"process_id":4466,"file":"/var/vcap/packages/dea_next/lib/dea/utils/sync_upload.rb","lineno":22,"method":"upload!"}
{"timestamp":1466086696.3091633,"message":"em-upload.completion.success","log_level":"debug","source":"Staging","data":{"app_guid":"db788ab0-bff0-40d9-9306-c1efd1eeb537","task_id":"95840b8bff4e4fce8a4a64516c391ef9","destination":"http://cloud-controller-ng.service.cf.internal:9022/staging/droplets/db788ab0-bff0-40d9-9306-c1efd1eeb537/upload","response":"{\n  \"metadata\": {\n    \"guid\": \"04a0e8b1-1022-410d-865b-71a289687f3b\",\n    \"created_at\": \"2016-06-16T14:18:16Z\",\n    \"url\": \"https://nats-user:squid@api.vsphere.emc-dojo.com/staging/jobs/04a0e8b1-1022-410d-865b-71a289687f3b\"\n  },\n  \"entity\": {\n    \"guid\": \"04a0e8b1-1022-410d-865b-71a289687f3b\",\n    \"status\": \"queued\"\n  }\n}","class":"String","include":true},"thread_id":46976250851600,"fiber_id":46976257572180,"process_id":4466,"file":"/var/vcap/packages/dea_next/lib/dea/utils/upload.rb","lineno":24,"method":"block in upload!"}
{"timestamp":1466086696.3097246,"message":"em-upload.completion.polling","log_level":"debug","source":"Staging","data":{"app_guid":"db788ab0-bff0-40d9-9306-c1efd1eeb537","task_id":"95840b8bff4e4fce8a4a64516c391ef9","destination":"https://api.vsphere.emc-dojo.com/staging/jobs/04a0e8b1-1022-410d-865b-71a289687f3b"},"thread_id":46976250851600,"fiber_id":46976257572180,"process_id":4466,"file":"/var/vcap/packages/dea_next/lib/dea/utils/upload.rb","lineno":34,"method":"block in upload!"}
{"timestamp":1466086696.309928,"message":"em-upload.polling","log_level":"debug","source":"Staging","data":{"app_guid":"db788ab0-bff0-40d9-9306-c1efd1eeb537","task_id":"95840b8bff4e4fce8a4a64516c391ef9","polling_destination":"https://api.vsphere.emc-dojo.com/staging/jobs/04a0e8b1-1022-410d-865b-71a289687f3b"},"thread_id":46976250851600,"fiber_id":46976257572180,"process_id":4466,"file":"/var/vcap/packages/dea_next/lib/dea/utils/upload.rb","lineno":87,"method":"poll"}
{"timestamp":1466086696.3125775,"message":"em-upload.polling.handle_error","log_level":"warn","source":"Staging","data":{"app_guid":"db788ab0-bff0-40d9-9306-c1efd1eeb537","task_id":"95840b8bff4e4fce8a4a64516c391ef9"},"thread_id":46976250851600,"fiber_id":46976257572180,"process_id":4466,"file":"/var/vcap/packages/dea_next/lib/dea/utils/upload.rb","lineno":90,"method":"block in poll"}
{"timestamp":1466086696.3129203,"message":"em-upload.error","log_level":"warn","source":"Staging","data":{"app_guid":"db788ab0-bff0-40d9-9306-c1efd1eeb537","task_id":"95840b8bff4e4fce8a4a64516c391ef9","destination":"http://cloud-controller-ng.service.cf.internal:9022/staging/droplets/db788ab0-bff0-40d9-9306-c1efd1eeb537/upload","connection_count":10,"message":"Error uploading: (Polling failed - status 0; error: Errno::ECONNREFUSED)","http_error":"Errno::ECONNREFUSED","http_status":0,"http_response":""},"thread_id":46976250851600,"fiber_id":46976257572180,"process_id":4466,"file":"/var/vcap/packages/dea_next/lib/dea/utils/upload.rb","lineno":58,"method":"handle_error"}
{"timestamp":1466086696.3132331,"message":"staging.task.droplet-upload-failed","log_level":"info","source":"Staging","data":{"app_guid":"db788ab0-bff0-40d9-9306-c1efd1eeb537","task_id":"95840b8bff4e4fce8a4a64516c391ef9","duration":null,"destination":"http://cloud-controller-ng.service.cf.internal:9022/staging/droplets/db788ab0-bff0-40d9-9306-c1efd1eeb537/upload","error":"Error uploading: (Polling failed - status 0; error: Errno::ECONNREFUSED)","backtrace":null},"thread_id":46976250851600,"fiber_id":46976257572180,"process_id":4466,"file":"/var/vcap/packages/dea_next/lib/dea/staging/staging_task.rb","lineno":347,"method":"block (2 levels) in promise_app_upload"}
{"timestamp":1466086696.3135197,"message":"staging.task.upload-failed","log_level":"info","source":"Staging","data":{"app_guid":"db788ab0-bff0-40d9-9306-c1efd1eeb537","task_id":"95840b8bff4e4fce8a4a64516c391ef9","error":"Error uploading: (Polling failed - status 0; error: Errno::ECONNREFUSED)","backtrace":["/var/vcap/packages/dea_next/lib/dea/promise.rb:81:in `resolve'","/var/vcap/packages/dea_next/lib/dea/staging/staging_task.rb:606:in `resolve_staging_upload'","/var/vcap/packages/dea_next/lib/dea/staging/staging_task.rb:65:in `block in start'","/var/vcap/packages/dea_next/lib/dea/promise.rb:20:in `block in resolve'"]},"thread_id":46976250851600,"fiber_id":46976262357140,"process_id":4466,"file":"/var/vcap/packages/dea_next/lib/dea/staging/staging_task.rb","lineno":67,"method":"rescue in block in start"}```
