### ISSUE TITLE
Cannot deploy cf to AWS

### ISSUE THREAD

**Issue by StanleyShen** [cloudfoundry/cf-release#888]
Hello, I am trying to deploy cf to aws
And what I am following is page:
And create my stub manifest based on http://docs.cloudfoundry.org/deploying/aws/cf-stub.html
I also tried to use the postgres job provided by cf release but not RDS database.
I also tried to use only one zone to minimum the VMs.

./scripts/generate_deployment_manifest aws my_stub.yml
After the manifest is generated, I also did some manual changes.
And here is my final manifest
https://gist.github.com/StanleyShen/3c3ebb45529fc8310f4b
But when I am deploy it to AWS, the api job keep failing, and here are some logs from "bosh logs api_z1 0"
https://github.com/StanleyShen/learns/blob/master/api_z1.0.2016-01-21-13-30-37.tgz
From the log, I didn't get a clue for the reason.

for the "cfrouter" load balancer in manifest, I tried to create one load balancer based on https://docs.pivotal.io/pivotalcf/customizing/pcf-aws-manual-config.html#pcfaws-om-elbsecgrp
But in latest try, I didn't run to it yet, not sure if I was configuring it right.

| cf   | 226+dev.1* | 5de34b6a    |
| bosh-aws-xen-hvm-ubuntu-trusty-go_agent | ubuntu-trusty | 3177*   | ami-7eafb41f light |

Could someone please help to take a look on it?
1. Is my manifest good enough for a deployment?
2. what's the possible issue for api cannot be running?
3. we should have a way to not use load balancer, or is it must needed, from the minimal-aws.yml, we are creating a NAT machine to do almost the same thing, right?

**Comment by StanleyShen** [comment]
With the stemcell and release, I can deploy them with the minimal-aws.yml
So it may because of some properties, I tried to compare it to bosh-lite manifest, but I didn't figure out yet.

**Comment by mavenraven** [comment]
@StanleyShen There's a number of places in your manifest where you have "bosh-lite.com". This needs to be a domain that you control and can point at your ELB or HAProxy. Cloud Foundry uses that value for routing, and the system won't work without it being right.

**Comment by StanleyShen** [comment]
yes, when I depoly it, I do changed all "bosh-lite.com" to valid domain created by me.
I just change them all to "bosh-lite.com" for security.

This needs to be a domain that you control and can point at your ELB or HAProxy
=> I didn't use HAProxy in this manifest, and I do create a load balancer named "cfrouter".
But when I was creating the balancer, I didn't how to set this domain pointing to the ELB.

for the "cfrouter" load balancer in manifest, I tried to create one load balancer based on https://docs.pivotal.io/pivotalcf/customizing/pcf-aws-manual-config.html#pcfaws-om-elbsecgrp

Is it the right way to create the load balancer based on this doc?

**Comment by dsabeti** [comment]
Hey there @StanleyShen. The logs suggest that the CC is having problems uploading and downloading buildpacks from the blobstore (s3). Take a look at `cloud_controller_ng/cloud_controller_ng.log` and look for a line that begins `{"timestamp":1453354094.4162247,"message":"Request failed: 500: {\"code\"=>10001, \"description\"=>\"connect timeout reached\", \"error_code\"=>\"CF-Timeout\"`. You'll see in the backtrace that the buildpack installer is failing to connect to the buildpacks bucket defined in your manifest:
```
    buildpacks:
      buildpack_directory_key: bosh-lite-com-cc-buildpacks
      cdn: null
      fog_connection:
        aws_access_key_id: [my key]
        aws_secret_access_key: [my key]
        provider: AWS
        region: us-east-1
```
Can you double check that the configuration for this bucket is correct (especially the directory key)? Can you also make sure that any networking configuration is such that the api VM has internet access (or, at least, ensure that it can connect to S3)?

**Comment by robdimsdale** [comment]
@StanleyShen we will close this issue now as it has been one week without response.

Please feel free to open another issue if you have further questions.
