### ISSUE TITLE
openstack template not correct

### ISSUE THREAD

**Issue by ramonskie** [cloudfoundry/cf-release#890]
the openstack template is not correct

when you try to create a simple stub file with no cf2 networks it will fail
even if the instaces are set to 0
this is because the template places [ ]
see https://github.com/cloudfoundry/cf-release/blob/master/templates/cf-infrastructure-openstack.yml#L189

this is not the case for aws template

**Comment by Amit-PivotalLabs** [comment]
@ramonskie 

Can you give an example of a stub that doesn't work, what exact command you're running, and what SHA of this repo you have checked out.  The manifest generation specs for openstack do indeed use a stub that has no cf2 and they don't fail.

https://github.com/cloudfoundry/cf-release/blob/master/spec/manifest_generation_spec.rb#L28-L30
https://github.com/cloudfoundry/cf-release/blob/master/spec/fixtures/openstack/cf-stub.yml#L12-L32

**Comment by ramonskie** [comment]
the issue is that cf2 network needs to defined in the stub file
otherwise bosh will refused the generated deployment manifest because its expects that the jobs that have cf2 network assigned even if it have zero instances

**Comment by Amit-PivotalLabs** [comment]
Ah right, will fix.

**Comment by Amit-PivotalLabs** [comment]
Should be fixed now. Closing.
