### ISSUE TITLE
Not found service "...v2/org/:orgID/quota_usage" in v212

### ISSUE THREAD

**Issue by SolutionBTO** [cloudfoundry/cf-release#899]
Hi

Not exists service "v2/organizations/:orgID/quota_usage" in
http://apidocs.cloudfoundry.org/212/

Only in before version
http://apidocs.cloudfoundry.org/211/organizations/retrieving_quota_usage_for_the_organization.html

Will add or remove definitely?

Roberto Silva
Best Regard's

**Comment by Amit-PivotalLabs** [comment]
Hi @SolutionBTO 

I've migrated this issue to the [cloud_controller_ng repo](https://github.com/cloudfoundry/cloud_controller_ng/issues/532), they will be able to help you with your questions about the API.

Cheers,
Amit
