### ISSUE TITLE
any reason why we use c3.large for all VMs by default in example_manifests

### ISSUE THREAD

**Issue by StanleyShen** [cloudfoundry/cf-release#904]
https://github.com/cloudfoundry/cf-release/blob/master/example_manifests/minimal-aws.yml
Right now the minimal-aws deployment is using c3.large for all VM.
But c3 is optimized for computing.
Just curious why we choose c3.large?
For this minimal env, I think m3.medium is enough for most VMs, right?

Thanks for explanation.

**Comment by drnic** [comment]
Keep one attribute of m3.mediums in mind - they have a tiny ephemeral disk.

**Comment by StanleyShen** [comment]
when deploying on AWS, we can add ephemeral_disk to Resource Pools definition.
So if we customize Resource Pools definition for add more ephemeral_disk then m3.medium is fine for use, right?

except the ephemeral disk, is there any other concerns?
Is there any recommended configuration for each CF components?

**Comment by Amit-PivotalLabs** [comment]
The `c3.large` also has 2 cores, whereas `m3.medium` has 1.  There are no hard and fast rules for what instance type you should have for all jobs.  The example manifest, and manifest generation templates, have some default values that we know to work in our CI environments.  The "right" answers depend on your usage and your budget.

**Comment by Amit-PivotalLabs** [comment]
Hi @StanleyShen I hope that answers your questions.  If you have a specific deployment that you want help right-sizing, feel free to open up a new issue.  I'll close this issue for now.

Best,
Amit
