### ISSUE TITLE
Can't check out candiedyaml during ./scripts/update

### ISSUE THREAD

**Issue by ctooley** [cloudfoundry/cf-release#906]
While running: 
[user@host cf-release]$ ./scripts/update

It runs through Synchronizing submodules until it gets to consul-release and then:
```
Submodule path 'src/consul-release': checked out '0ad37ffa52115a572f91430ee8875c521c4f8575'
Cloning into 'src/acceptance-tests/vendor/github.com/cloudfoundry-incubator/candiedyaml'...
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Clone of 'git://github.com/cloudfoundry-incubator/candiedyaml' into submodule path 'src/acceptance-tests/vendor/github.com/cloudfoundry-incubator/candiedyaml' failed
```

**Comment by ctooley** [comment]
It appears that the upstream package that is at fault has a merged commit from today to resolve this issue. I've tested it by changing directories into the cf-release/src/consul-release directory and manually applying the patch.

I'm still getting an error on bosh upload release because it's failing blobstore sha1 checksums. But, I don't know if that's related:

+ bosh -n -u admin -p ADMIN_PASSWORD upload release --skip-if-exists ~/workspace/cf-release/releases/cf-230.yml
Acting as user 'admin' on 'Bosh Lite Director'
Downloading from blobstore (id=be1390db-220b-4fdd-b832-30b670687a81)...
Downloading from blobstore (id=dd461e59-e9ad-4523-896c-0295df04fc81)...
Downloading from blobstore (id=50f648d7-9f85-4215-b325-ed835d262ddc)...
Downloading from blobstore (id=d6b8074f-314a-4524-b67b-9d74916b4aa4)...
Downloading from blobstore (id=7c8bf65f-0fec-472a-b7a6-410624d243f3)...
Downloading from blobstore (id=5ee5bdce-a042-4aad-a06c-c0b2437162ee)...
Blobstore error: sha1 mismatch expected=f2dca2eae3338c12a5c9082cdd5e1b2eb2499464 actual=178cd84f6bdc3a16158f24092f6ef99c3691cf3c

**Comment by APShirley** [comment]
Hi @ctooley, 
We attempted to reproduce your errors, cf-release 230 worked fine for us. We just wanted to double check you are indeed using 230 (we assume from the cf-230.yml that you are). 

What package are you getting the sha1 checksum mismatch on? This feels unrelated to the changes from the patch you applied to consul-release.

**Comment by APShirley** [comment]
Hi @ctooley,
As there hasn't been response in 7 days, we'll assume you have resolved this and are closing this issue. If you are still having problems please open a new issue.

- Al && @robdimsdale
