### ISSUE TITLE
smoke_tests can't access api.bosh-lite.com

### ISSUE THREAD

**Issue by weberstephanhd** [cloudfoundry/cf-release#908]
I run bosh-lite on esxi like described at https://blog.starkandwayne.com/2014/05/30/running-bosh-lite-on-vsphere-hypervisor-free-edition/. I successfully deployed cf but I have problems with the smoke_tests:

'cf api api.bosh-lite.com --skip-ssl-validation' fails with Error performing request: Get http://api.bosh-lite.com/v2/info: dial tcp: i/o timeout

So I ran the errand with keep-alive and used bosh ssh to login to this failing smoke_tests vm. Now the curious thing:

````
root@c8e205ff-3471-409a-bf01-8700a87df57c:/etc# cf --version
cf version 6.15.0+fa1bfe2-2016-01-13

root@c8e205ff-3471-409a-bf01-8700a87df57c:/etc# ping 8.8.8.8
PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.
64 bytes from 8.8.8.8: icmp_seq=1 ttl=41 time=10.9 ms

root@c8e205ff-3471-409a-bf01-8700a87df57c:/etc# ping 10.244.0.34
PING 10.244.0.34 (10.244.0.34) 56(84) bytes of data.
64 bytes from 10.244.0.34: icmp_seq=1 ttl=63 time=0.105 ms

root@c8e205ff-3471-409a-bf01-8700a87df57c:/etc# curl -k -L https://api.bosh-lite.com/v2/info
{"name":"","build":"","support":"http://support.cloudfoundry.com","version":0,"description":"","authorization_endpoint":"https://login.bosh-lite.com","token_endpoint":"https://uaa.bosh-lite.com","min_cli_version":null,"min_recommended_cli_version":null,"api_version":"2.48.0","app_ssh_endpoint":"ssh.bosh-lite.com:2222","app_ssh_host_key_fingerprint":"a6:d1:08:0b:b0:cb:9b:5f:c4:ba:44:2a:97:26:19:8a","app_ssh_oauth_client":"ssh-proxy","routing_endpoint":"https://api.bosh-lite.com/routing","logging_endpoint":"wss://loggregator.bosh-lite.com:443","doppler_logging_endpoint":"wss://doppler.bosh-lite.com:4443"}

root@c8e205ff-3471-409a-bf01-8700a87df57c:/etc# cf api api.bosh-lite.com --skip-ssl-validation
Setting api endpoint to api.bosh-lite.com...
FAILED
Error performing request: Get http://api.bosh-lite.com/v2/info: dial tcp: i/o timeout
````

At the first glance the network setup seems to be o.k.

Being on the smoke tests vm curl always succeeds to reach https://api.bosh-lite.com/v2/info. It takes about 5secs until the answer comes with curl. The cf api command always fails. Isn't cf patient enough to wait for 5 secs in this case?

Best regards, Stephan

**Comment by krishicks** [comment]
Hi @weberstephanhd,

@dsabeti asked the CLI team to look into this.

The error is coming from the Go standard library, which is just being surfaced by the CLI. There isn't a default dialer timeout in Go (https://golang.org/src/net/dial.go#L18), so it should fall back to the OS timeout (if any).

You might run the command again with CF_TRACE=true so we can get a better idea of the actual request/response cycle time.

**Comment by fraenkel** [comment]
@krishicks Just use DialTimeout instead of Dial.

**Comment by krishicks** [comment]
@fraenkel I'm not sure I follow. @weberstephanhd is having an issue with a timeout being hit. How would adding a DialTimeout help?

**Comment by weberstephanhd** [comment]
My resolv.conf on the smoke_tests VM had three entries:
````
nameserver 8.8.8.8
nameserver 10....
nameserver 10....
````
The 10.something entries are corporate DNSs.

When I remove the 8.8.8.8 entry from resolv.conf the cf command works.
So, it seems that the problem was that using 8.8.8.8 as DNS is somehow blocked by our IT and whilst curl than uses one of the next entries go didn't. More, I had to take care that the bosh-lite instance already has a 'clean' resolv.conf and that bosh-lite's  `/etc/resolvconf/resolv.conf.d/head` has no 8.8.8.8 entry.

Best regards, Stephan

**Comment by krishicks** [comment]
Cool, I'm glad you figured it out.
