### ISSUE TITLE
Builidng libpq via "bosh -n deploy" takes a very long time.

### ISSUE THREAD

**Issue by ericpromislow** [cloudfoundry/cf-release#911]
Trying to deploy cf-release v224:

In cf/bosh-lite:

```
vagrant up
bosh upload stemcell bosh-stemcell-3126-warden-boshlite-ubuntu-trusty-go_agent.tgz
```

In cf/cf-release (clean repo):
```
git checkout v224
scripts/generate-bosh-lite-dev-manifes
bosh create release && bosh upload release
bosh -n deploy
```

`bosh deploy` is stuck with this output:
```
  Started compiling packages > nats/560f582d348325a562493056b973bf49a9a78d33
     Done compiling packages > warden/2f10c7ad4e92f74aa2c82a7c9718b32a51644974 (00:00:35)
     Done compiling packages > route_registrar/5755494567906878c83a04bcdb0b8119a288bf39 (00:00:36)
     Done compiling packages > collector/158398837665181c70bd786b46e6f4d772523017 (00:00:42)
     Done compiling packages > nats/560f582d348325a562493056b973bf49a9a78d33 (00:00:12)
     Done compiling packages > dea_next/b7414ce1be98eb579363c2ad03cd106e90628884 (00:01:46)
```

It turns out it's still compiling `libpq` -- I started this run about 90 minutes ago on a new 4-core machine. Any suggestions?

**Comment by ericpromislow** [comment]
vagrant@bosh-lite:~$ ps auxww | grep pq
root      2360  0.0  0.0  18484  3548 ?        S<   00:08   0:00 /bin/bash ./configure --prefix=/var/vcap/packages/libpq
root      4550  0.0  0.0  18484  1628 ?        S<   00:08   0:00 /bin/bash ./configure --prefix=/var/vcap/packages/libpq
vagrant  21500  0.0  0.0  11752   780 pts/0    S+   01:53   0:00 grep --color=auto pq

Any idea where it's running configure from?

Running 'sudo ./configure --prefix=/tmp/libpq' from `var/vcap/store/warden_cpi/ephemeral_bind_mounts_dir/7cb44f94-1c25-4080-7da0-0a905896d7f3/compile/libpq/postgresql-9.0.3` terminates. `lsof` reports two processes running `configure`, so I'm guessing there's a parent/child fork thing going on, and the parent hasn't reaping the child, so the 'bosh deploy' is still twiddling its thumbs waiting.

**Comment by Amit-PivotalLabs** [comment]
Hey @ericpromislow 

Looks like a bosh-lite issue, I've migrated your issue and follow-up comment to the bosh-lite repo, they should be able to help you better.  Your output doesn't show that it's trying to compile libpq, and normally that would eventually time out, instead it sounds like bosh-lite has lost track of some compilation job.  I'll close out this issue for now, let me know if you discover that it is a cf-release bug after all.

Cheers,
Amit
