### ISSUE TITLE
Performance measurement tests/framework

### ISSUE THREAD

**Issue by milkotodorov** [cloudfoundry/cf-release#912]
Are there any official performance measurement tests/framework for CF available?

**Comment by Amit-PivotalLabs** [comment]
Hi @milkotodorov 

We haven't formalized any test suite as "official", but we make heavy use of the following resources which are *de facto* standards:

* System level performance, stress, and fault tolerance testing with a Diego backend is codified in [a test protocol](https://github.com/cloudfoundry-incubator/diego-dev-notes/blob/master/proposals/measuring_performance.md) and uses [the diego-perf-release](https://github.com/cloudfoundry-incubator/diego-perf-release).
* The [diego-performance-app](https://github.com/cloudfoundry-incubator/diego-performance-app) is another resource, the repo consists of a bunch of apps you can push to your system and configure to consume CPU, disk I/O, network I/O, and logging capacity.

Not sure if you're interested in performance testing of lower level components (as opposed to the whole system/control plane), but there is a benchmark suite for the Diego "BBS" API [here](https://github.com/cloudfoundry-incubator/benchmark-bbs). Other individual components of CF might also have their own performance benchmarking/stress testing tools, e.g. we noticed you asked a similar question on the gorouter repo: https://github.com/cloudfoundry/gorouter/issues/115.  I believe the gorouter team has a test suite that they've used for their own focused performance tests.

Best,
Amit + @ematpl

**Comment by milkotodorov** [comment]
Hi Amit and thanks for your answer.

Regarding my question about the router I've ran local tests using own app and nGrinder as a load generator. I described the issue there on  [cloudfoundry/gorouter#115](https://github.com/cloudfoundry/gorouter/issues/115). It seems like a bug to me in the gorouter. I've posted all the details in the thread.

Regards,
Milko

**Comment by milkotodorov** [comment]
Hi Amit,

one additional question - is there something for the DEA? This that you've sent me is only for Diego...

Regards,
Milko

**Comment by Amit-PivotalLabs** [comment]
@milkotodorov 

I'm not aware of anything for the DEA, but the highest level of perf testing in the diego-perf-release repo should actually work against the DEAs.  The resulting logs and metrics to analyze won't quite be the same though.  You can also open up an issue at https://github.com/cloudfoundry/dea-hm-workspace/ to see if they have any DEA-specific recommendations for performance testing.

I'll close this issue as resolved for now, please re-open if you have further questions.

Cheers,
Amit
