### ISSUE TITLE
it would be nice to override the networks in consul job

### ISSUE THREAD

**Issue by ramonskie** [cloudfoundry/cf-release#913]
i think it would be nice to override the network in consul job so we can add a floating ip to it
see https://github.com/cloudfoundry/cf-release/blob/master/templates/cf-jobs.yml#L202

just likes its done with the ha proxy or the routers
see https://github.com/cloudfoundry/cf-release/blob/master/templates/cf-jobs.yml#L240

**Comment by Amit-PivotalLabs** [comment]
Hey @ramonskie do you want to contribute a PR for this?  I can help you if you get stuck, but it should be mostly similar to what's there for ha_proxy.  Just be sure to run the tests and update the spec fixtures accordingly.  These tests will run automatically if you've installed the git hooks for this repo.  This is all documented in the contributing docs: https://github.com/cloudfoundry/cf-release/blob/master/CONTRIBUTING.md

**Comment by Amit-PivotalLabs** [comment]
Closing this in favour of above PR.
