### ISSUE TITLE
api_z1/0 not running on bosh-lite

### ISSUE THREAD

**Issue by rahulkj** [cloudfoundry/cf-release#919]
Hi,

I'm using the latest v231 release on bosh-lite (virtualbox). On deploying the release I get the following error:

```
 Started updating job consul_z1 > consul_z1/0 (406f6732-1dcb-41b8-915c-f5e34c3e6881). Done (00:00:11)
  Started updating job ha_proxy_z1 > ha_proxy_z1/0 (88cc99e1-9bfb-4bd6-b926-337ff2d50881). Done (00:00:29)
  Started updating job nats_z1 > nats_z1/0 (a344b107-9de6-4b94-a3c1-28c5dcc117db). Done (00:00:12)
  Started updating job etcd_z1 > etcd_z1/0 (857a81ed-f13a-47af-94c2-ed58532e5a28). Done (00:00:29)
  Started updating job blobstore_z1 > blobstore_z1/0 (6afcffe9-632a-41ab-97f7-319071fb7a19). Done (00:00:11)
  Started updating job postgres_z1 > postgres_z1/0 (b5e86b74-415e-4b11-a84a-b91b98f65fb8). Done (00:00:09)
  Started updating job uaa_z1 > uaa_z1/0 (35f70625-9661-4872-85e2-104810138600). Done (00:00:58)
  Started updating job api_z1 > api_z1/0 (557ede7d-c3b4-40e9-8258-c4aaf9547938). Failed: `api_z1/0 (557ede7d-c3b4-40e9-8258-c4aaf9547938)' is not running after update (00:04:24)

Error 400007: `api_z1/0 (557ede7d-c3b4-40e9-8258-c4aaf9547938)' is not running after update

Task 6 error
```
Looking to the `/var/vcap/sys/log/cloud_controller_ng_ctl.log` it states
```
[2016-02-29 17:42:49+0000] ------------ STARTING cloud_controller_ng_ctl at Mon Feb 29 17:42:49 UTC 2016 --------------
[2016-02-29 17:42:49+0000] Checking for blobstore availability
[2016-02-29 17:43:21+0000] Blobstore is not available
[2016-02-29 17:43:36+0000] ------------ STARTING cloud_controller_ng_ctl at Mon Feb 29 17:43:36 UTC 2016 --------------
[2016-02-29 17:43:36+0000] Checking for blobstore availability
[2016-02-29 17:44:08+0000] Blobstore is not available
```

Any thoughts?

**Comment by Amit-PivotalLabs** [comment]
Hi @rahulkj 

I believe the team responsible for Cloud Controller are currently investigating some issues related to the CC Blobstore on BOSH-Lite deployments.  I'll ask them to try and help you out.

/cc @utako @SocalNick

**Comment by fkotsian** [comment]
Hi @rahulkj 

 We have indeed been investigating some issues related to the CC blobstore on bosh-lite. We've recently added the ability to store files using WebDAV, though the default is still NFS. A couple questions to help us debug:

1. Is this a fresh deployment?
1. Are you transitioning from NFS to WebDAV?
1. How are you generating your bosh-lite manifest?

Best,

Frank && Jeff 
CF CAPI Team

**Comment by rahulkj** [comment]
Hi,

Yes this is a fresh deployment on bosh-lite.
I generated the manifests using the `https://github.com/cloudfoundry/cf-release/blob/master/scripts/generate-bosh-lite-dev-manifest` using `spiff`

I haven't done anything special for the WebDAV. What is it that I need to do?

**Comment by fkotsian** [comment]
Hi @rahulkj,

 Interesting. We have not seen this specific issue before, but we'd be happy to help you debug. Would you mind coming to our Slack channel at cloudfoundry.slack.com in the #capi channel so we could help in real time? If not, we are happy to help here.

Best,

Frank && Jeff
CF CAPI Team

**Comment by rahulkj** [comment]
@fkotsian - I'll ping you tomorrow on slack to debug this.

**Comment by rahulkj** [comment]
Closing this issue, as the stemcell I was using was really old... by using the latest 3147, the deployment went fine. Thanks @fkotsian
