### ISSUE TITLE
router.servers.z1/2 is redundant

### ISSUE THREAD

**Issue by johnmcteague** [cloudfoundry/cf-release#920]
The router.servers.z1 and router.servers.z2 config is confusing and irrelevant.

Regardless of what gorouters are referenced in z1 or z2, the resulting config is the same. Using z1/z2 suggests differing behavior between the two and that you should be able to map multiple az's (we accidentally put z3 in and noticed the gorouter in that zone not getting any traffic, obviously).

The config should be changed to simply router.servers with a single list.

https://github.com/cloudfoundry/cf-release/blob/master/jobs/haproxy/templates/haproxy.conf.erb#L55

**Comment by Amit-PivotalLabs** [comment]
I agree.  Something similar was done for UAA: 

* https://github.com/cloudfoundry/uaa-release/blob/develop/jobs/uaa/spec#L65-L67
* https://github.com/cloudfoundry/cf-release/blob/master/templates/cf-jobs.yml#L424-L444

I'll ask the Routing team to consider this change.

/cc @shalako @crhino 

Best,
Amit

**Comment by shalako** [comment]
Sounds reasonable. I'll pull this into the backlog.

"As an operator deploying Cloud Foundry, I should discover that the manifest properties router.servers.z1 and router.servers.z2 have been replaced with a single property router.servers."

**Comment by shalako** [comment]
Hello @johnmcteague we have made this change. It will be included in the next version of cf-release.
