### ISSUE TITLE
error generating manifest: unresolved nodes when deploying on vsphere

### ISSUE THREAD

**Issue by valenbb** [cloudfoundry/cf-release#924]
My test vsphere environment is running ESXi version6. The esx servers are vms running in VMware workstation 12 and both are connected to the NAT network.

The bosh director was deployed successfully in vsphere. When generating the cf-deployment manifest, i am getting the following error:

2016/03/05 18:22:48 error generating manifest: unresolved nodes:
        (( static_ips(1) ))     in /root/my-bosh/cf-release/templates/cf-infrastructure-vsphere.yml     jobs.[1].networks.[0].static_ips        ()
        (( static_ips(5, 6) ))  in /root/my-bosh/cf-release/templates/cf-infrastructure-vsphere.yml     jobs.[6].networks.[0].static_ips        ()
        (( static_ips(13) ))    in /root/my-bosh/cf-release/templates/cf-infrastructure-vsphere.yml     jobs.[15].networks.[0].static_ips       ()
        (( static_ips(17, 18, 19) ))    in /root/my-bosh/cf-release/templates/cf-infrastructure-vsphere.yml     jobs.[17].networks.[0].static_ips       ()

I believe I have enough static ips available and am not sure where else to look.

Networking portion of the stub file:

---
meta:
  environment: vsphere-cf

director_uuid: 82e52733-31fc-48a2-8c62-b5b5b7ec5d70

networks:
  - name: cf1
    subnets:
    - range: 192.168.150.0/24
      gateway: 192.168.150.2
      reserved:
      - 192.168.150.3 - 192.168.150.100
      - 192.168.150.200 - 192.168.150.210
      dns:
      - 192.168.150.14
      static:
      - 192.168.150.230 - 192.168.150.254
      cloud_properties:
        name: 'VM Network'

Any help or suggestions would be appreciated. If more information is needed, I can provide.
Thanks in advance.

**Comment by Amit-PivotalLabs** [comment]
Looks like you only have 1 network.  This is fine, but the provided scripts assume 2, so you need to give it a dummy `cf2` network.  [Example](https://github.com/cloudfoundry/cf-release/blob/3d203ce/spec/fixtures/openstack/cf-stub.yml#L33-L37)

**Comment by valenbb** [comment]
I realized that today and will give it a shot and let you know the results.
