### ISSUE TITLE
Add a parameter `service_id` in Polling Last Operation of service broker APIs

### ISSUE THREAD

**Issue by bingosummer** [cloudfoundry/cf-release#925]
This is a feature request.

```
curl http://username:password@broker-url/v2/service_instances/:instance_id/last_operation?service_id=service-id-here
```

If the broker provides multiple services, with the service id, the broker can determine which service the instance is, and get the state of the last operation. In such a scenario, the broker does not need to store the map between the instance id and the service id.

**Comment by Amit-PivotalLabs** [comment]
@bingosummer thanks for this input.  I'm going to migrate your issue to the Cloud Controller repo so the API team can get eyes on your feature request.
