### ISSUE TITLE
CF v231: HAPROXY always reloads every 10 seconds.

### ISSUE THREAD

**Issue by AbelHu** [cloudfoundry/cf-release#926]
I deployed CF with Diego. Before adding a Windows server to the Diego, I updated my CF manifest. But when updating the CF, the task failed with below error. After checking the logs of haproxy, I found the HAPROXY always reloads every 10 seconds.

Although the task fails, everything still works. I can use cf commands to push new applications and check the status of applications. And the Windows Server also works to deploy .NET applications.

CF Task Logs:
```
$ bosh -n deploy
Acting as user 'admin' on deployment 'multiple-cf-on-azure' on 'bosh'
Getting deployment properties from director...

Detecting deployment changes
----------------------------
Releases
cf
  version type changed: String -> Fixnum
    - 231
    + 231

Compilation
No changes

Update
No changes

Resource pools
resource_z1
  stemcell
    version type changed: String -> Fixnum
      - 3169
      + 3169

Disk pools
No changes

Networks
No changes

Jobs
api_z1
  properties
    nfs_server
      ± allow_from_entries:
        + 10.0.48.0/20

Properties
nfs_server
  ± allow_from_entries:
    + 10.0.48.0/20


Deploying
---------

Director task 11
  Started preparing deployment > Preparing deployment. Done (00:00:00)

  Started preparing package compilation > Finding packages to compile. Done (00:0
0:00)

  Started updating job nfs_z1 > nfs_z1/0 (4231fe91-1c3a-49ff-9231-1e79f7935da4) (
canary)
  Started updating job ha_proxy_z1 > ha_proxy_z1/0 (ad06f763-9eb2-4db3-a318-2367b
7f47bbd) (canary)
     Done updating job nfs_z1 > nfs_z1/0 (4231fe91-1c3a-49ff-9231-1e79f7935da4) (
canary) (00:00:48)
   Failed updating job ha_proxy_z1 > ha_proxy_z1/0 (ad06f763-9eb2-4db3-a318-2367b
7f47bbd) (canary): `ha_proxy_z1/0 (ad06f763-9eb2-4db3-a318-2367b7f47bbd)' is not
running after update. Review logs for failed jobs: haproxy_config, haproxy (00:10
:12)

Error 400007: `ha_proxy_z1/0 (ad06f763-9eb2-4db3-a318-2367b7f47bbd)' is not runni
ng after update. Review logs for failed jobs: haproxy_config, haproxy

Task 11 error

For a more detailed error report, run: bosh task 11 --debug
```
haproxy_ctl.log:
```
[2016-03-10 05:47:17+0000] SUCCESS
[2016-03-10 05:47:17+0000] haproxy.
[2016-03-10 05:47:27+0000] Reloading HAProxy: Thu Mar 10 05:47:27 UTC 2016: reloading HAProxy
[2016-03-10 05:47:27+0000] Thu Mar 10 05:47:27 UTC 2016: Finished reloading HAProxy
[2016-03-10 05:47:27+0000] SUCCESS
[2016-03-10 05:47:27+0000] haproxy.
[2016-03-10 05:47:37+0000] Reloading HAProxy: Thu Mar 10 05:47:37 UTC 2016: reloading HAProxy
[2016-03-10 05:47:37+0000] Thu Mar 10 05:47:37 UTC 2016: Finished reloading HAProxy
[2016-03-10 05:47:37+0000] SUCCESS
[2016-03-10 05:47:37+0000] haproxy.
[2016-03-10 05:47:47+0000] Reloading HAProxy: Thu Mar 10 05:47:47 UTC 2016: reloading HAProxy
[2016-03-10 05:47:47+0000] Thu Mar 10 05:47:47 UTC 2016: Finished reloading HAProxy
[2016-03-10 05:47:47+0000] SUCCESS
[2016-03-10 05:47:47+0000] haproxy.
[2016-03-10 05:47:57+0000] Reloading HAProxy: Thu Mar 10 05:47:57 UTC 2016: reloading HAProxy
[2016-03-10 05:47:57+0000] Thu Mar 10 05:47:57 UTC 2016: Finished reloading HAProxy
[2016-03-10 05:47:57+0000] SUCCESS
[2016-03-10 05:47:57+0000] haproxy.
[2016-03-10 05:48:08+0000] Reloading HAProxy: Thu Mar 10 05:48:08 UTC 2016: reloading HAProxy
[2016-03-10 05:48:08+0000] Thu Mar 10 05:48:08 UTC 2016: Finished reloading HAProxy
[2016-03-10 05:48:08+0000] SUCCESS
[2016-03-10 05:48:08+0000] haproxy.
[2016-03-10 05:48:18+0000] Reloading HAProxy: Thu Mar 10 05:48:18 UTC 2016: reloading HAProxy
[2016-03-10 05:48:18+0000] Thu Mar 10 05:48:18 UTC 2016: Finished reloading HAProxy
[2016-03-10 05:48:18+0000] SUCCESS
[2016-03-10 05:48:18+0000] haproxy.
[2016-03-10 05:48:28+0000] Reloading HAProxy: Thu Mar 10 05:48:28 UTC 2016: reloading HAProxy
[2016-03-10 05:48:28+0000] Thu Mar 10 05:48:28 UTC 2016: Finished reloading HAProxy
[2016-03-10 05:48:28+0000] SUCCESS
[2016-03-10 05:48:28+0000] haproxy.
```
bosh vms:
```
+---------------------------------------------------------------------------+---------+-----+-------------+-------------+
| VM                                                                        | State   | AZ  | VM Type     | IPs         |
+---------------------------------------------------------------------------+---------+-----+-------------+-------------+
| api_z1/0 (7e351456-9507-4b8f-90c9-a9339c3056b6)                           | running | n/a | resource_z1 | 10.0.16.102 |
| consul_z1/0 (3f6c66b2-43e5-4ddb-92e6-49b63e416c8d)                        | running | n/a | resource_z1 | 10.0.16.16  |
| doppler_z1/0 (5eb571ad-3bf7-467f-8757-a74676faea98)                       | running | n/a | resource_z1 | 10.0.16.105 |
| etcd_z1/0 (efc4dd42-5d6b-465c-a08d-eaa62c885624)                          | running | n/a | resource_z1 | 10.0.16.14  |
| ha_proxy_z1/0 (ad06f763-9eb2-4db3-a318-2367b7f47bbd)                      | failing | n/a | resource_z1 | 10.0.16.4   |
```

**Comment by robdimsdale** [comment]
We have not seen this before, and cannot reproduce the behavior you observe. It doesn't look like haproxy produces any more log files, and when we configured haproxy to log debug we found it did not produce any more information.

There may be more information in the monit log: `/var/vcap/monit/monit.log` - could you paste the (sanitized) output here please?

Thanks,
Rob && @nimakaviani

**Comment by AbelHu** [comment]
The manifest is [here](https://github.com/Azure/azure-quickstart-templates/blob/master/bosh-setup/manifests/multiple-vm-cf.yml#L87-L108). Before I changed allow_from_entries in the manifest, it worked well. 

/var/vcap/monit/monit.log:
[UTC Mar 10 05:47:17] error    : 'haproxy' process PID changed from 2735 to 2782
[UTC Mar 10 05:47:17] error    : 'haproxy_config' timestamp was changed for /var/vcap/jobs/haproxy/config/haproxy.conf
[UTC Mar 10 05:47:17] info     : 'haproxy_config' exec: /var/vcap/jobs/haproxy/bin/haproxy_ctl
[UTC Mar 10 05:47:27] error    : 'haproxy' process PID changed from 2782 to 2830
[UTC Mar 10 05:47:27] error    : 'haproxy_config' timestamp was changed for /var/vcap/jobs/haproxy/config/haproxy.conf
[UTC Mar 10 05:47:27] info     : 'haproxy_config' exec: /var/vcap/jobs/haproxy/bin/haproxy_ctl
[UTC Mar 10 05:47:37] error    : 'haproxy' process PID changed from 2830 to 2878
[UTC Mar 10 05:47:37] error    : 'haproxy_config' timestamp was changed for /var/vcap/jobs/haproxy/config/haproxy.conf
[UTC Mar 10 05:47:37] info     : 'haproxy_config' exec: /var/vcap/jobs/haproxy/bin/haproxy_ctl
[UTC Mar 10 05:47:47] error    : 'haproxy' process PID changed from 2878 to 2925
[UTC Mar 10 05:47:47] error    : 'haproxy_config' timestamp was changed for /var/vcap/jobs/haproxy/config/haproxy.conf
[UTC Mar 10 05:47:47] info     : 'haproxy_config' exec: /var/vcap/jobs/haproxy/bin/haproxy_ctl
[UTC Mar 10 05:47:57] error    : 'haproxy' process PID changed from 2925 to 2972
[UTC Mar 10 05:47:57] error    : 'haproxy_config' timestamp was changed for /var/vcap/jobs/haproxy/config/haproxy.conf
[UTC Mar 10 05:47:57] info     : 'haproxy_config' exec: /var/vcap/jobs/haproxy/bin/haproxy_ctl
[UTC Mar 10 05:48:07] error    : 'haproxy' process PID changed from 2972 to 3022
[UTC Mar 10 05:48:07] error    : 'haproxy_config' timestamp was changed for /var/vcap/jobs/haproxy/config/haproxy.conf
[UTC Mar 10 05:48:08] info     : 'haproxy_config' exec: /var/vcap/jobs/haproxy/bin/haproxy_ctl
[UTC Mar 10 05:48:18] error    : 'haproxy' process PID changed from 3022 to 3071
[UTC Mar 10 05:48:18] error    : 'haproxy_config' timestamp was changed for /var/vcap/jobs/haproxy/config/haproxy.conf
[UTC Mar 10 05:48:18] info     : 'haproxy_config' exec: /var/vcap/jobs/haproxy/bin/haproxy_ctl
[UTC Mar 10 05:48:28] error    : 'haproxy' process PID changed from 3071 to 3129
[UTC Mar 10 05:48:28] error    : 'haproxy_config' timestamp was changed for /var/vcap/jobs/haproxy/config/haproxy.conf
[UTC Mar 10 05:48:28] info     : 'haproxy_config' exec: /var/vcap/jobs/haproxy/bin/haproxy_ctl

Check processes with 'ps aux':
ps aux | grep haproxy
root      1287  0.3  0.2  10300  7904 ?        S<l  Mar10  17:45 /var/vcap/packages/consul/bin/consul-template -consul 127.0.0.1:8500 -template /var/vcap/jobs/haproxy/config/haproxy.ctmpl:/var/vcap/jobs/haproxy/config/haproxy.conf
root      1289  0.0  0.0  17980  1556 ?        S<   Mar10   0:00 /bin/bash -e /var/vcap/jobs/haproxy/bin/consul_template_ctl start
root      1290  0.0  0.0  17980  1556 ?        S<   Mar10   0:00 /bin/bash -e /var/vcap/jobs/haproxy/bin/consul_template_ctl start
root      1299  0.0  0.0  17988  1748 ?        S<   Mar10   0:00 /bin/bash -e /var/vcap/jobs/haproxy/bin/consul_template_ctl start
root      1301  0.0  0.0  17988  1748 ?        S<   Mar10   0:00 /bin/bash -e /var/vcap/jobs/haproxy/bin/consul_template_ctl start
vcap      4257  0.0  0.2  36476  8952 ?        S<s  02:19   0:00 /var/vcap/packages/haproxy/bin/haproxy -f /var/vcap/jobs/haproxy/config/haproxy.conf -p /var/vcap/sys/run/haproxy/pid -D -sf 4210
vcap      4355  0.0  0.1  36624  6888 ?        S<s  02:20   0:00 /var/vcap/packages/haproxy/bin/haproxy -f /var/vcap/jobs/haproxy/config/haproxy.conf -p /var/vcap/sys/run/haproxy/pid -D -sf 4307
root      4364  0.0  0.0  10472  2252 pts/0    S+   02:20   0:00 grep --color=auto haproxy

**Comment by dsabeti** [comment]
@AbelHu 

The haproxy reloads when the ssh-proxy registers (or, re-registers) itself with consul. The idea is that the haproxy can dynamically be reconfigured to accommodate the ssh-proxy traffic. It could be there are problems with your ssh-proxy in Diego. Please post the logs from the `access` job on Diego. Also, try querying Consul for its services. You should be able to use [the REST API](https://www.consul.io/docs/agent/http/catalog.html#catalog_services) to find what services are offered and which nodes are offering them. It's possible the the ssh-proxy process is periodically dying, causing the haproxy to reload.

David

**Comment by AbelHu** [comment]
@dsabeti Thanks. It seems like that the diego concul agent causes this issue. But after deploying diego, the haproxy still works. It occurs only when updating cf after deploying diego. You can see my diego manifest [here](https://github.com/cloudfoundry-incubator/bosh-azure-cpi-release/blob/master/docs/advanced/deploy-diego/single-vm-diego.yml). Do you have any idea?

**Comment by APShirley** [comment]
@AbelHu,

Sorry for being repetitive but in order to better help you debug this issue we need to be able to look at the (**sanitized**) logs for the access jobs on the bosh deployment (they should appear as `access_z1/0` etc... in `bosh vms` output). You could also look at the [REST API](https://www.consul.io/docs/agent/http/catalog.html#catalog_services) to see the available services. 

We can take these logs to the diego team and hopefully figure out what is going on. As mentioned, our initial hypothesis is that there could be some flakiness between the ssh-proxy and the consul agent in your deployment. The best way to verify that is by looking at the logs.

Thanks,

Al & @nimakaviani

**Comment by AbelHu** [comment]
@APShirley I cannot find any error in consul_agent.stdout.log and consul_agent.stderr.log. You can see consul_agent log as below.
    2016/03/16 05:47:16 [INFO] agent: Synced check 'service:tps'
    2016/03/16 05:47:16 [INFO] agent: Synced check 'service:bbs'
    2016/03/16 05:47:16 [INFO] agent: Synced check 'service:cc-uploader'
    2016/03/16 05:47:16 [INFO] agent: Synced check 'service:file-server'
    2016/03/16 05:47:16 [INFO] agent: Synced check 'service:file-server'
    2016/03/16 05:47:16 [INFO] agent: Synced check 'service:bbs'
    2016/03/16 05:47:16 [INFO] agent: Synced check 'service:cc-uploader'
    2016/03/16 05:47:16 [INFO] agent: Synced check 'service:stager'
    2016/03/16 05:47:17 [INFO] agent: Synced check 'service:auctioneer'
    2016/03/16 05:47:17 [WARN] agent: Check 'service:nsync' is now critical
    2016/03/16 05:47:17 [WARN] agent: Check 'service:tps' is now critical
    2016/03/16 05:47:17 [INFO] agent: Synced check 'service:nsync'
    2016/03/16 05:47:18 [INFO] agent: Synced check 'service:tps'
    2016/03/16 05:47:18 [WARN] agent: Check 'service:ssh-proxy' is now critical
    2016/03/16 05:47:18 [INFO] agent: Synced check 'service:ssh-proxy'
    2016/03/16 05:47:18 [WARN] agent: Check 'service:auctioneer' is now critical
    2016/03/16 05:47:18 [WARN] agent: Check 'service:stager' is now critical
    2016/03/16 05:47:18 [INFO] agent: Synced check 'service:auctioneer'
    2016/03/16 05:47:18 [INFO] agent: Synced check 'service:ssh-proxy'
    2016/03/16 05:47:18 [INFO] agent: Synced check 'service:stager'
    2016/03/16 05:47:18 [INFO] agent: Synced check 'service:stager'
    2016/03/16 05:47:18 [INFO] agent: Synced check 'service:nsync'
    2016/03/16 05:47:18 [INFO] agent: Synced check 'service:auctioneer'
    2016/03/16 05:47:19 [WARN] agent: Check 'service:bbs' is now critical
    2016/03/16 05:47:19 [INFO] agent: Synced check 'service:bbs'
    2016/03/16 05:47:19 [WARN] agent: Check 'service:cc-uploader' is now critical
    2016/03/16 05:47:19 [WARN] agent: Check 'service:file-server' is now critical
    2016/03/16 05:47:19 [INFO] agent: Synced check 'service:cc-uploader'
    2016/03/16 05:47:19 [INFO] agent: Synced check 'service:tps'
    2016/03/16 05:47:19 [INFO] agent: Synced check 'service:file-server'
    2016/03/16 05:47:19 [INFO] agent: Synced check 'service:file-server'
    2016/03/16 05:47:20 [INFO] agent: Synced check 'service:bbs'
    2016/03/16 05:47:20 [INFO] agent: Synced check 'service:cc-uploader'
    2016/03/16 05:47:20 [WARN] agent: Check 'service:nsync' is now critical
    2016/03/16 05:47:20 [WARN] agent: Check 'service:tps' is now critical
    2016/03/16 05:47:20 [INFO] agent: Synced check 'service:nsync'
    2016/03/16 05:47:21 [INFO] agent: Synced check 'service:tps'
    2016/03/16 05:47:21 [WARN] agent: Check 'service:ssh-proxy' is now critical
    2016/03/16 05:47:21 [INFO] agent: Synced check 'service:ssh-proxy'
    2016/03/16 05:47:21 [INFO] agent: Synced check 'service:tps'
    2016/03/16 05:47:21 [WARN] agent: Check 'service:auctioneer' is now critical
    2016/03/16 05:47:21 [INFO] agent: Synced check 'service:auctioneer'
    2016/03/16 05:47:21 [WARN] agent: Check 'service:stager' is now critical
    2016/03/16 05:47:21 [INFO] agent: Synced check 'service:ssh-proxy'
    2016/03/16 05:47:21 [INFO] agent: Synced check 'service:stager'
    2016/03/16 05:47:21 [INFO] agent: Synced check 'service:stager'
    2016/03/16 05:47:21 [INFO] agent: Synced check 'service:nsync'
    2016/03/16 05:47:22 [INFO] agent: Synced check 'service:auctioneer'
    2016/03/16 05:47:22 [WARN] agent: Check 'service:bbs' is now critical
    2016/03/16 05:47:22 [INFO] agent: Synced check 'service:bbs'
    2016/03/16 05:47:22 [WARN] agent: Check 'service:cc-uploader' is now critical
    2016/03/16 05:47:22 [INFO] agent: Synced check 'service:cc-uploader'
    2016/03/16 05:47:22 [WARN] agent: Check 'service:file-server' is now critical
    2016/03/16 05:47:22 [INFO] agent: Synced check 'service:file-server'
    2016/03/16 05:47:22 [INFO] agent: Synced check 'service:file-server'
    2016/03/16 05:47:23 [INFO] agent: Synced check 'service:bbs'
    2016/03/16 05:47:23 [INFO] agent: Synced check 'service:cc-uploader'
    2016/03/16 05:47:23 [WARN] agent: Check 'service:nsync' is now critical
    2016/03/16 05:47:23 [INFO] agent: Synced check 'service:nsync'
    2016/03/16 05:47:23 [WARN] agent: Check 'service:tps' is now critical
    2016/03/16 05:47:24 [INFO] agent: Synced check 'service:tps'
    2016/03/16 05:47:24 [WARN] agent: Check 'service:ssh-proxy' is now critical
    2016/03/16 05:47:24 [INFO] agent: Synced check 'service:ssh-proxy'
    2016/03/16 05:47:24 [INFO] agent: Synced check 'service:tps'
    2016/03/16 05:47:24 [WARN] agent: Check 'service:auctioneer' is now critical
    2016/03/16 05:47:24 [INFO] agent: Synced check 'service:auctioneer'
    2016/03/16 05:47:24 [WARN] agent: Check 'service:stager' is now critical

**Comment by APShirley** [comment]
Hi @AbelHu,

After further investigation, we don't have a definitive reason why this is happening. Our hypothesis is that this is related to either the consul agent or ssh proxy failing on your diego deployment. 

These repeating sections of your logs leads us to believe it may be related to [this github issue](https://github.com/hashicorp/consul/issues/1057). 
```
2016/03/16 05:47:24 [WARN] agent: Check 'service:ssh-proxy' is now critical
2016/03/16 05:47:24 [INFO] agent: Synced check 'service:ssh-proxy'
```
To further investigate with the diego team can you please run the following commands for each job in all your zones:
```
$ bosh -t [your-bosh-director] -d [your-deployment] ssh diego_z1/0 --gateway_host [your-gateway-host] --gateway_user [your-gateway-user] --gateway_identity_file [your-gateway-identity-file]

$ tail -n 300 /var/vcap/sys/logs/jobs/ssh_proxy/ssh_proxy.stdout.log
```
Copy this output and paste a **sanitized** version here.
```
$ tail -n 300 /var/vcap/sys/logs/jobs/ssh_proxy/ssh_proxy.stderr.log
```
Copy this output and paste a **sanitized** version here.

Also, if possible, could you redeploy after changing the log level for consul agent from the default (`info`) to  `trace`, as this might give us better logs with more information about what is going on.
You will need to edit [this line](https://github.com/cloudfoundry-incubator/bosh-azure-cpi-release/blob/master/docs/advanced/deploy-diego/single-vm-diego.yml#L117) of your manifest to look like this:
```
      log_level: debug
```
**Only do this temporarily as it can result in very large log files.**

Then do the same steps I listed above for the consul agent logs (`/var/vcap/sys/logs/consul_agent...`) as well, and paste the results here please.

Also, I may suggest you take a look at diego team's [manifest generation section under colocated](https://github.com/cloudfoundry-incubator/diego-release/blob/develop/manifest-generation/diego.yml#L772-L804) (since it seems you are running your entire diego-deployment on a single box) it may help you to debug this issue if you compare your manifest with that one.

Thanks,

Al

**Comment by AbelHu** [comment]
Thanks for your help. I have pasted all logs as below.

/var/vcap/sys/log/ssh_proxy/ssh_proxy.stdout.log:
{"timestamp":"1458545650.326978922","source":"ssh-proxy","message":"ssh-proxy.authentication-failed","log_level":2,"data":{"error":"Invalid credentials","user":"ubnt"}}
{"timestamp":"1458545650.615238905","source":"ssh-proxy","message":"ssh-proxy.authentication-failed","log_level":2,"data":{"error":"Invalid credentials","user":"ubnt"}}

/var/vcap/sys/log/ssh_proxy/ssh_proxy.stderr.log: Empty

Releases:
![image](https://cloud.githubusercontent.com/assets/6416187/13980268/966bb1f6-f118-11e5-9e23-3236583bf67a.png)

After setting log_level to debug for consul_agent, /var/vcap/sys/log/consul_agent/consul_agent.stdout.log:
    2016/03/23 09:17:56 [INFO] agent: Synced check 'service:bbs'
    2016/03/23 09:17:56 [DEBUG] agent: Check 'service:file-server' in sync
    2016/03/23 09:17:56 [DEBUG] agent: Check 'service:nsync' in sync
    2016/03/23 09:17:56 [DEBUG] agent: Check 'service:tps' in sync
    2016/03/23 09:17:56 [DEBUG] agent: Check 'service:cc-uploader' in sync
    2016/03/23 09:17:56 [DEBUG] agent: Check 'service:etcd' in sync
    2016/03/23 09:17:56 [DEBUG] agent: Check 'service:ssh-proxy' in sync
    2016/03/23 09:17:56 [DEBUG] agent: Check 'service:stager' in sync
    2016/03/23 09:17:56 [DEBUG] http: Request /v1/agent/check/pass/service:bbs?note= (57.0803ms)
    2016/03/23 09:17:56 [DEBUG] agent: Check 'service:ssh-proxy' status is now passing
    2016/03/23 09:17:56 [DEBUG] agent: Service 'auctioneer' in sync
    2016/03/23 09:17:56 [DEBUG] agent: Service 'ssh-proxy' in sync
    2016/03/23 09:17:56 [DEBUG] agent: Service 'stager' in sync
    2016/03/23 09:17:56 [DEBUG] agent: Service 'tps' in sync
    2016/03/23 09:17:56 [DEBUG] agent: Service 'bbs' in sync
    2016/03/23 09:17:56 [DEBUG] agent: Service 'cc-uploader' in sync
    2016/03/23 09:17:56 [DEBUG] agent: Service 'etcd' in sync
    2016/03/23 09:17:56 [DEBUG] agent: Service 'file-server' in sync
    2016/03/23 09:17:56 [DEBUG] agent: Service 'nsync' in sync
    2016/03/23 09:17:56 [DEBUG] agent: Check 'service:cc-uploader' in sync
    2016/03/23 09:17:56 [DEBUG] agent: Check 'service:etcd' in sync
    2016/03/23 09:17:56 [DEBUG] http: Request /v1/session/renew/4af0a552-3222-75b6-ceb9-a40704f81dd3 (41.9666ms)
    2016/03/23 09:17:56 [DEBUG] agent: check 'service:cc-uploader' script '/var/vcap/jobs/cc_uploader/bin/dns_health_check' output: /bin/sh: 1: /var/vcap/jobs/cc_uploader/bin/dns_health_check: not found
    2016/03/23 09:17:56 [WARN] agent: Check 'service:cc-uploader' is now critical
    2016/03/23 09:17:56 [DEBUG] agent: Check 'service:nsync' status is now passing
    2016/03/23 09:17:57 [DEBUG] http: Request /v1/session/renew/c7d2773b-17e8-6153-acd3-48aae215cd03 (39.3752ms)
    2016/03/23 09:17:57 [DEBUG] http: Request /v1/session/renew/75516829-7d3c-83e9-1755-9ab6f5742b2c (42.0536ms)
    2016/03/23 09:17:57 [INFO] agent: Synced check 'service:ssh-proxy'

**Comment by APShirley** [comment]
@AbelHu,

From these logs it looks like you may have misconfigured credentials in the ssh_proxy section of your manifest:
```
/var/vcap/sys/log/ssh_proxy/ssh_proxy.stdout.log:
{"timestamp":"1458545650.326978922","source":"ssh-proxy","message":"ssh-proxy.authentication-failed","log_level":2,"data":{"error":"Invalid credentials","user":"ubnt"}}
{"timestamp":"1458545650.615238905","source":"ssh-proxy","message":"ssh-proxy.authentication-failed","log_level":2,"data":{"error":"Invalid credentials","user":"ubnt"}}
```
To fix this issue please examine [these lines](https://github.com/cloudfoundry-incubator/bosh-azure-cpi-release/blob/master/docs/advanced/deploy-diego/single-vm-diego.yml#L1074-L1075) and ensure that they match your uaa credentials since you disabled diego auth in place of uaa auth. This should solve your issue, if it does not, then please get back to us.

Cheers,
Al

**Comment by AbelHu** [comment]
@APShirley You can see my setting for uaa [here](https://github.com/Azure/azure-quickstart-templates/blob/master/bosh-setup/manifests/single-vm-cf.yml#L128-L140). It should be same.

**Comment by jfmyers9** [comment]
Hi @AbelHu,

```
/var/vcap/sys/log/ssh_proxy/ssh_proxy.stdout.log:
{"timestamp":"1458545650.326978922","source":"ssh-proxy","message":"ssh-proxy.authentication-failed","log_level":2,"data":{"error":"Invalid credentials","user":"ubnt"}}
{"timestamp":"1458545650.615238905","source":"ssh-proxy","message":"ssh-proxy.authentication-failed","log_level":2,"data":{"error":"Invalid credentials","user":"ubnt"}}
```

The above log lines indicate a user was unable to authenticate while sshing into a container on Diego. This is generally due to improper manifest properties surrounding the UAA and ssh-proxy. Please consult [this documentation on generating the ssh host-key and fingerprint](https://github.com/cloudfoundry-incubator/diego-release/tree/develop/examples/aws#generating-ssh-proxy-host-key-and-fingerprint) and ensure that you have [these properties](https://github.com/cloudfoundry-incubator/diego-release/blob/develop/examples/aws/stubs/cf/diego.yml#L26-L41) set in your cf deployment manifest.

However, those log lines would not explain the constant reloading of HAProxy. In order to better understand why the ssh-proxy service is critical, could you please redeploy your diego release with the `properties.diego.ssh_proxy.log_level` set to `debug`. After redeploying, can you provide us with the **sanitized** logs from the `/var/vcap/sys/log/ssh_proxy/` directory. With these logs we should be able to help you troubleshoot the issue.

Thanks,

@jfmyers9 && @midoblgsm, CF Diego Team

**Comment by AbelHu** [comment]
@jfmyers9 I assure that the [ssh host-key and fingerprint](https://github.com/Azure/azure-quickstart-templates/blob/master/bosh-setup/manifests/single-vm-cf.yml#L185-L187), ssh-proxy properties  in [cf.yml](https://github.com/Azure/azure-quickstart-templates/blob/master/bosh-setup/manifests/single-vm-cf.yml#L589-L595) and in [diego.yml](https://github.com/cloudfoundry-incubator/bosh-azure-cpi-release/blob/master/docs/advanced/deploy-diego/single-vm-diego.yml#L950-L1075) are set to correct values. 
Several weeks ago, [cf.yml](https://github.com/cloudfoundry-incubator/bosh-azure-cpi-release/blob/f8e2976c60f2afa9e62346897d4ed001a0602008/docs/example_manifests/multiple-vm-cf-224-diego.yml) and [diego.yml](https://github.com/cloudfoundry-incubator/bosh-azure-cpi-release/blob/f8e2976c60f2afa9e62346897d4ed001a0602008/docs/example_manifests/diego.yml) work for garden-linux v0.330.0, etcd v20 and diego v0.1444.0.

After I deleted old diego and deployed it again with the properties.diego.ssh_proxy.log_level set to debug, the logs from the /var/vcap/sys/log/ssh_proxy/ directory is as below.
{"timestamp":"1459152169.860211849","source":"ssh-proxy","message":"ssh-proxy.registration-runner.poll-until-signaled.updating-ttl-healthcheck","log_level":0,"data":{"checkID":"service:ssh-proxy","service":"ssh-proxy","session":"2.1","update-interval":"1.5s"}}
{"timestamp":"1459152171.402626038","source":"ssh-proxy","message":"ssh-proxy.registration-runner.poll-until-signaled.updating-ttl-healthcheck","log_level":0,"data":{"checkID":"service:ssh-proxy","service":"ssh-proxy","session":"2.1","update-interval":"1.5s"}}
{"timestamp":"1459152172.931019068","source":"ssh-proxy","message":"ssh-proxy.registration-runner.poll-until-signaled.updating-ttl-healthcheck","log_level":0,"data":{"checkID":"service:ssh-proxy","service":"ssh-proxy","session":"2.1","update-interval":"1.5s"}}
{"timestamp":"1459152174.494250536","source":"ssh-proxy","message":"ssh-proxy.registration-runner.poll-until-signaled.updating-ttl-healthcheck","log_level":0,"data":{"checkID":"service:ssh-proxy","service":"ssh-proxy","session":"2.1","update-interval":"1.5s"}}
{"timestamp":"1459152175.995335102","source":"ssh-proxy","message":"ssh-proxy.registration-runner.poll-until-signaled.updating-ttl-healthcheck","log_level":0,"data":{"checkID":"service:ssh-proxy","service":"ssh-proxy","session":"2.1","update-interval":"1.5s"}}
{"timestamp":"1459152177.565779209","source":"ssh-proxy","message":"ssh-proxy.registration-runner.poll-until-signaled.updating-ttl-healthcheck","log_level":0,"data":{"checkID":"service:ssh-proxy","service":"ssh-proxy","session":"2.1","update-interval":"1.5s"}}
{"timestamp":"1459152179.066852093","source":"ssh-proxy","message":"ssh-proxy.registration-runner.poll-until-signaled.updating-ttl-healthcheck","log_level":0,"data":{"checkID":"service:ssh-proxy","service":"ssh-proxy","session":"2.1","update-interval":"1.5s"}}
{"timestamp":"1459152180.588877916","source":"ssh-proxy","message":"ssh-proxy.registration-runner.poll-until-signaled.updating-ttl-healthcheck","log_level":0,"data":{"checkID":"service:ssh-proxy","service":"ssh-proxy","session":"2.1","update-interval":"1.5s"}}
{"timestamp":"1459152182.090180397","source":"ssh-proxy","message":"ssh-proxy.registration-runner.poll-until-signaled.updating-ttl-healthcheck","log_level":0,"data":{"checkID":"service:ssh-proxy","service":"ssh-proxy","session":"2.1","update-interval":"1.5s"}}
{"timestamp":"1459152184.564747572","source":"ssh-proxy","message":"ssh-proxy.registration-runner.poll-until-signaled.updating-ttl-healthcheck","log_level":0,"data":{"checkID":"service:ssh-proxy","service":"ssh-proxy","session":"2.1","update-interval":"1.5s"}}
{"timestamp":"1459152186.069442749","source":"ssh-proxy","message":"ssh-proxy.registration-runner.poll-until-signaled.updating-ttl-healthcheck","log_level":0,"data":{"checkID":"service:ssh-proxy","service":"ssh-proxy","session":"2.1","update-interval":"1.5s"}}
{"timestamp":"1459152187.790416956","source":"ssh-proxy","message":"ssh-proxy.registration-runner.poll-until-signaled.updating-ttl-healthcheck","log_level":0,"data":{"checkID":"service:ssh-proxy","service":"ssh-proxy","session":"2.1","update-interval":"1.5s"}}
{"timestamp":"1459152189.291793108","source":"ssh-proxy","message":"ssh-proxy.registration-runner.poll-until-signaled.updating-ttl-healthcheck","log_level":0,"data":{"checkID":"service:ssh-proxy","service":"ssh-proxy","session":"2.1","update-interval":"1.5s"}}
{"timestamp":"1459152190.850353956","source":"ssh-proxy","message":"ssh-proxy.registration-runner.poll-until-signaled.updating-ttl-healthcheck","log_level":0,"data":{"checkID":"service:ssh-proxy","service":"ssh-proxy","session":"2.1","update-interval":"1.5s"}}

**Comment by making** [comment]
@AbelHu 
I met same the trouble while deploying CF on Azure.
After restarting consul_agent on diego deployment, it looks fine now.

**Comment by AbelHu** [comment]
@making You are right. I used 'bosh ssh' to login to access_z1/0. Then I executed 'sudo monit restart consul_agent'. The status of haproxy becomes 'running'.

@jfmyers9 @APShirley Does anyone know the reason?

**Comment by Amit-PivotalLabs** [comment]
@AbelHu 

Am I understanding correctly that you're currently on Diego 0.1455.0?  Are you generating your Diego manifest using the scripts in [`diego-release` repo at the `v0.1455.0` tag](https://github.com/cloudfoundry-incubator/diego-release/tree/v0.1455.0)?  One thing that looks fishy are your [consul service configurations](https://github.com/cloudfoundry-incubator/bosh-azure-cpi-release/blob/master/docs/advanced/deploy-diego/single-vm-diego.yml#L107-L115).  In recent versions of Diego, most components do not use the manifest-based configuration mechanism for registering themselves, which would lead to all those critical health check log lines, and may be what's causing your HAProxy config to continually reload.

**Comment by AbelHu** [comment]
@Amit-PivotalLabs Thanks so much. After I remove all services except etcd in my consul service configurations and redeploy Diego, it looks fine now.
