### ISSUE TITLE
Cannot find deployment manifest

### ISSUE THREAD

**Issue by FaKeller** [cloudfoundry/cf-release#929]
**Background:**
I tried to install CloudFoundry on BOSH-Lite and followed the [official documentation](http://docs.cloudfoundry.org/deploying/boshlite/index.html). In Step 2, in the "Deploying Cloud Foundry using BOSH: Deploy!" part, the command `bosh deploy` failed with the following error message:

```sh
Cannot find deployment manifest in `/home/vagrant/cf-release/bosh-lite/deployments/cf.yml'
```

**Bug:**
However, I have followed the docs in Step 2 and created the deployment manifest using the respective script. I noticed in the console history that in the [./scripts/update](https://github.com/cloudfoundry/cf-release/blob/9e31b98e104825c136d96a711bec2135f4a6ed33/scripts/update#L43) script a `git clean -ffd` is executed, which apparently deletes the previously created deployment manifest:

```sh
+ git clean -ffd
Removing bosh-lite/deployments/
```

The `./scripts/update` script is mentioned in the second part of the "Step 2" documentation, and hence after the deployment manifest was created. The question is, whether this is a bug in the documentation or in the script :-)

**Workaround:**
As a workaround, I executed `./scripts/generate-bosh-lite-dev-manifest` again before executing `bosh deploy`. I guess the intermediate steps such as `bosh create release` do not depend on the deployment manifest?

**Comment by ScarletTanager** [comment]
@FaKeller - this looks like a bug in the docs to me.  You run `scripts/update` to refresh your local cf-release repo (and its many submodules), and I would definitely do this before doing the manifest generation.  `bosh create release` does not depend on having a manifest, but `bosh deploy` obviously does.  Your workaround is, I think, what should be the actual documented path.

**Comment by robdimsdale** [comment]
@FaKeller @ScarletTanager yes this was a bug in the docs - we've made a change to [a fork](https://github.com/robdimsdale/docs-deploying-cf) and there will be a PR to the [upstream docs](https://github.com/cloudfoundry/docs-deploying-cf) in due course. Once that PR is merged the docs will be updated.

Thanks,
Rob && @nimakaviani

**Comment by Amit-PivotalLabs** [comment]
PR to fix docs has been submitted, closing.
