### ISSUE TITLE
Router failure during CF Installation

### ISSUE THREAD

**Issue by Xhings** [cloudfoundry/cf-release#930]
Hello guys,

I am trying to get CF up and running on boshlite. Attached is the screen scratch of the installation steps followed, deploy.xml and debug logs for router job.

I tried fixing this with cck but could not get it up and running.Please let me know what am I missing.

[Issue.zip](https://github.com/cloudfoundry/cf-release/files/169921/Issue.zip)
Regards,
Xhings

**Comment by robdimsdale** [comment]
@Xhings your manifest contains:
```
properties:
  router:
    enable_routing_api: true
```

This means you are trying to deploy the routing API. This feature requires diego and the routing release, so if you do not want this feature, remove this line or set `enable_routing_api: false`.

How did you create this bosh-lite manifest? The recommended method is to use `./scripts/generate-bosh-lite-dev-manifest` from the `cf-release` directory which does not result in this property being set.

Thanks,
Rob & @nimakaviani

**Comment by APShirley** [comment]
Closing, no response after 7 days.
