### ISSUE TITLE
push fails after "minimal aws configuration" with "Could not find a default domain"

### ISSUE THREAD

**Issue by scotthasse** [cloudfoundry/cf-release#931]
I recently provisioned an aws micro instance using the "minimal aws configuration" steps found at https://github.com/cloudfoundry/cf-release/tree/master/example_manifests.  The deploy of cf seems to have gone fine, but when trying to push the dora app I get:

FAILED
Could not find a default domain

also "cf domains"fails with a 500 error.   Debugging with CF_TRACE=true shows a 500 response for

GET /v2/shared_domains HTTP/1.1

I was advised at https://cloudfoundry.slack.com/messages/cf-users/ to open an issue here.  Any pointers on how to start diagnosing that issue?

Thanks,

Scott

**Comment by robdimsdale** [comment]
Hi @scotthasse,

First of all, could you please clarify what you mean by the following:

> I recently provisioned an aws micro instance using the "minimal aws configuration"

The minimal bosh deployment results in a handful of VMs; it does not deploy to a single micro instance.

Can you provide the output of `bosh vms`?

Assuming all VMS are healthy, and the deploy succeeded, can you please send us the logs from your `api_z1` job of your bosh deployment (please make sure any secrets are redacted from the logs).

Also if you could tell us what version of `cf release` and the CLI you are using, that will help us determine the issue with your deployment more accurately.

Finally, can you take a look at https://github.com/cloudfoundry/cf-release/issues/900 and see if this issue applies to you?

Thanks,
Rob & @nimakaviani

**Comment by APShirley** [comment]
Closing this issue as it hasn't been active in 7 days. If you need anything else feel free to open a new issue again and reference this one.

Thanks, 
Al
