### ISSUE TITLE
Installing Cloud Foundry in Local Machine

### ISSUE THREAD

**Issue by sujeetyadav** [cloudfoundry/cf-release#934]
Hi,

I am trying to install cloud foundry on local machine.
I am following steps mentioned in http://software.danielwatrous.com/explore-cloudfoundry-using-bosh-lite-on-windows/
I have done following:
1) Installed following softwares on windows 7:
a) VirtualBox-5.0.14-105127-Win
b) vagrant_1.8.1
c) rubyinstaller-2.2.4
d) cf-cli-installer_6.16.1_winx64
e) Git-2.7.0-64-bit
f) Putty

2) Cloned bosh lite into workspace using command:
	git clone https://github.com/cloudfoundry/bosh-lite
3) Modified vagrant file, please find attached Vagrant file.
4) Navigated to bosh-lite folder which contains VagrantFile through command prompt and then fired this command:
	vagrant up --provider=virtualbox
This has configured two virtual machines on Oracle VM VirtualBOx.
5) Now I connected to bosh lite VM using following credentials by putty:
hostname : 127.0.0.1
port number :2200
[VagrantFile.txt](https://github.com/cloudfoundry/cf-release/files/179469/VagrantFile.txt)

Username : vagrant
password: vagrant

6) Ran following commands:
apt-get -y install build-essential linux-headers-`uname -r`
apt-get -y install ruby ruby-dev git zip
gem install bosh_cli --no-ri --no-rdoc
7) Installed spiff
wget https://github.com/cloudfoundry-incubator/spiff/releases/download/v1.0.3/spiff_linux_amd64.zip
unzip spiff_linux_amd64.zip
sudo mv spiff /usr/local/bin/
8) Cloned bosh-lite and cf-release
git clone https://github.com/cloudfoundry/bosh-lite.git
git clone https://github.com/cloudfoundry/cf-release
9) Updated provision file present under bohs-lite/bin direcotry.
get_ip_from_vagrant_ssh_config() {
  echo 192.168.50.4
}
10) bosh target 192.168.50.4 lite
using credentials: admin/admin
11) cd bosh-lite
From bosh-lte directory location fired these two commands:
./bin/add-route
./bin/provision_cf

**This fails and giving me following stacktrace:
root@vagrant-ubuntu-trusty-64:/home/bosh-lite# ./bin/provision_cf
Acquiring bosh-lite IP
Bosh IP is: 192.168.50.4
RSA 1024 bit CA certificates are loaded due to old openssl compatibility
Target set to `Bosh Lite Director'
Uploading stemcell from latest-bosh-lite-stemcell-warden.tgz
RSA 1024 bit CA certificates are loaded due to old openssl compatibility
Acting as user 'admin' on 'Bosh Lite Director'
[VagrantFile.txt](https://github.com/cloudfoundry/cf-release/files/179453/VagrantFile.txt)

Verifying stemcell...
File exists and readable                                     OK
Verifying **tarball...**
Read tarball                                                 OK
Manifest exists                                              OK
Stemcell image file                                          OK
Stemcell properties                                          OK

Stemcell info
-------------
Name:    bosh-warden-boshlite-ubuntu-trusty-go_agent
Version: 3147

Checking if stemcell already exists...
Yes
Stemcell `bosh-warden-boshlite-ubuntu-trusty-go_agent/3147' already exists. Skipping upload.
Updating cf-release sub modules
+ git rev-parse @{u}
+ git pull
+ git submodule sync
+ git submodule foreach --recursive git submodule sync; git clean -d --force --force
+ git submodule update --init --recursive --force
+ git clean -ffd
+ set +x
Generating bosh lite manifest from /home/cf-release/scripts/generate-bosh-lite-dev-manifest
RSA 1024 bit CA certificates are loaded due to old openssl compatibility
RSA 1024 bit CA certificates are loaded due to old openssl compatibility
RSA 1024 bit CA certificates are loaded due to old openssl compatibility
Deployment set to `/home/cf-release/bosh-lite/deployments/cf.yml'
Config
             /root/.bosh_config

Director
RSA 1024 bit CA certificates are loaded due to old openssl compatibility
  Name       Bosh Lite Director
  URL        https://192.168.50.4:25555
  Version    1.3197.1.0 (00000000)
  User       admin
  UUID       44586d7c-bcce-4f5f-ae80-42bb8a1ed08b
  CPI        warden_cpi
  dns        disabled
  compiled_package_cache enabled (provider: local)
  snapshots  disabled

Deployment
  Manifest   /home/cf-release/bosh-lite/deployments/cf.yml
Creating cf-release release
Syncing blobs...

Building DEV release
---------------------------------
Release artifact cache: /root/.bosh/cache

Building license
----------------
Building license...
  Using final version '861d82c0d9745784acfcd026ccf44e942579824a'

Building packages
-----------------
Building loggregator_trafficcontroller...
  Using final version '3e20884b7aafd4cb0ec33c1f7e9101e254e1b0be'

Building go-buildpack...
  Using final version '2ee73bb12cc8aef34b5ce2fd25a893a03fd3a76d'

Building rootfs_cflinuxfs2...
  Using final version 'a9011940f1d1ba1945927d69f963246bc736ff54'

Building php-buildpack...
  Using final version 'a7499b03d9900d107fec28ca209ddd2cb96cc0d9'

Building binary-buildpack...
  Using final version '86f697c3f0ccfae1141c57390988f67f6825dcaf'

Building loggregator_common...
  Using final version 'e401816a4748292163679fafcbd8f818ed8154a5'

Building uaa_utils...
  Using final version 'fc2e416c5af94d6293ac70bb594c984e31097fb7'

Building syslog_drain_binder...
  Using final version '1b77306dcffb38a00a8227d4ab489e81cbf92b5a'

Building dea_next...
  Using final version '4bd2b99df1820b42e050c101371b2d590aa85009'

Building nodejs-buildpack...
  Using final version 'ed8378a05119eefaccc6da601982f12f11db3837'

Building metron_agent...
  Using final version '722a2c3982be416f4ae5e571afdaa1a69c574424'

Building capi_utils...
  Using final version 'e441936c4e6a1b928988515c214f1b0b6f289d0f'

Building acceptance-tests...
  Using final version '107b2fdcb71813f6e61cd1cb7e9ccf3626e14194'

Building statsd-injector...
  Using final version 'e8e54509908a65ede9328b95e9915c1226d412e5'

Building golang1.4...
  Using final version '714698bc352d2a1dbe321376f0676037568147bb'

Building common...
  Using final version 'e401816a4748292163679fafcbd8f818ed8154a5'

Building ruby-buildpack...
  Using final version '668bc5208ab52e4eb7354a941e3bbd69f58e9b51'

Building postgres-9.4.6...
  Using final version '4ca292f2443cfc682e87632ebd15fb3f3fa53123'

Building etcd-common...
  Using final version 'a5492fb0ad41a80d2fa083172c0430073213a296'

Building libpq...
  Using final version '36290c252abdd5750583eca92a8c4fd134594fa8'

Building hm9000...
  Using final version '7cbddcd5cb6dadc80c6c3002c507133c091403c0'
  Downloading from blobstore (id=a6687c42-7fa3-462c-baf8-f077e6648303)...
RSA 1024 bit CA certificates are loaded due to old openssl compatibility

Building smoke-tests...
  Using final version '488b85fd5a9ea933f154f4c6f43d88a5112f3a22'
  Downloading from blobstore (id=695d42de-bfe8-4136-841b-c901a496d04f)...

Building route_registrar...
  Using final version 'a471cd246893763768b0ed9b9088d27572f3916f'
  Downloading from blobstore (id=5d58d740-889a-4b46-9523-9da3adeb6812)...

Building staticfile-buildpack...
  Using final version '19fb854bbce07a9e4913fb63561f4ca161f01af1'
  Downloading from blobstore (id=06e7476f-2183-4d6b-9847-99ac8660166f)...

Building python-buildpack...
  Using final version '56859daf5f573904e1a2b6bb3e3fb15d1dd2b95c'
  Downloading from blobstore (id=9b5ba67e-b490-476c-8130-13d963bfceff)...
Blobstore error: Failed to fetch object, underlying error: #<HTTPClient::ReceiveTimeoutError: execution expired> /usr/lib/ruby/1.9.1/openssl/buffering.rb:121:in `sysread'
/usr/lib/ruby/1.9.1/openssl/buffering.rb:121:in `readpartial'
/var/lib/gems/1.9.1/gems/httpclient-2.7.1/lib/httpclient/ssl_socket.rb:86:in `readpartial'
/var/lib/gems/1.9.1/gems/httpclient-2.7.1/lib/httpclient/session.rb:870:in `block in read_body_length'
/var/lib/gems/1.9.1/gems/httpclient-2.7.1/lib/httpclient/session.rb:868:in `read_body_length'
/var/lib/gems/1.9.1/gems/httpclient-2.7.1/lib/httpclient/session.rb:573:in `get_body'
/var/lib/gems/1.9.1/gems/httpclient-2.7.1/lib/httpclient.rb:1243:in `do_get_block'
/var/lib/gems/1.9.1/gems/httpclient-2.7.1/lib/httpclient.rb:1021:in `block in do_request'
/var/lib/gems/1.9.1/gems/httpclient-2.7.1/lib/httpclient.rb:1129:in `protect_keep_alive_disconnected'
/var/lib/gems/1.9.1/gems/httpclient-2.7.1/lib/httpclient.rb:1016:in `do_request'
/var/lib/gems/1.9.1/gems/httpclient-2.7.1/lib/httpclient.rb:858:in `request'
/var/lib/gems/1.9.1/gems/httpclient-2.7.1/lib/httpclient.rb:739:in `get'
/var/lib/gems/1.9.1/gems/blobstore_client-1.3215.0/lib/blobstore_client/simple_blobstore_client.rb:39:in `get_file'
/var/lib/gems/1.9.1/gems/blobstore_client-1.3215.0/lib/blobstore_client/s3_blobstore_client.rb:79:in `get_file'
/var/lib/gems/1.9.1/gems/blobstore_client-1.3215.0/lib/blobstore_client/base.rb:50:in `get'
/var/lib/gems/1.9.1/gems/blobstore_client-1.3215.0/lib/blobstore_client/sha1_verifiable_blobstore_client.rb:19:in `get'
/var/lib/gems/1.9.1/gems/blobstore_client-1.3215.0/lib/blobstore_client/retryable_blobstore_client.rb:19:in `block in get'
/var/lib/gems/1.9.1/gems/bosh_common-1.3215.0/lib/common/retryable.rb:28:in `call'
/var/lib/gems/1.9.1/gems/bosh_common-1.3215.0/lib/common/retryable.rb:28:in `block in retryer'
/var/lib/gems/1.9.1/gems/bosh_common-1.3215.0/lib/common/retryable.rb:26:in `loop'
/var/lib/gems/1.9.1/gems/bosh_common-1.3215.0/lib/common/retryable.rb:26:in `retryer'
/var/lib/gems/1.9.1/gems/blobstore_client-1.3215.0/lib/blobstore_client/retryable_blobstore_client.rb:18:in `get'
/var/lib/gems/1.9.1/gems/bosh_cli-1.3215.0/lib/cli/versions/version_file_resolver.rb:29:in `block in find_file'
/var/lib/gems/1.9.1/gems/bosh_cli-1.3215.0/lib/cli/versions/version_file_resolver.rb:28:in `open'
/var/lib/gems/1.9.1/gems/bosh_cli-1.3215.0/lib/cli/versions/version_file_resolver.rb:28:in `find_file'
/var/lib/gems/1.9.1/gems/bosh_cli-1.3215.0/lib/cli/archive_repository.rb:31:in `lookup'
/var/lib/gems/1.9.1/gems/bosh_cli-1.3215.0/lib/cli/archive_builder.rb:64:in `locate_artifact'
/var/lib/gems/1.9.1/gems/bosh_cli-1.3215.0/lib/cli/archive_builder.rb:16:in `block in build'
/var/lib/gems/1.9.1/gems/bosh_cli-1.3215.0/lib/cli/core_ext.rb:14:in `with_indent'
/var/lib/gems/1.9.1/gems/bosh_cli-1.3215.0/lib/cli/archive_builder.rb:15:in `build'
/var/lib/gems/1.9.1/gems/bosh_cli-1.3215.0/lib/cli/commands/release/create_release.rb:186:in `block in build_packages'
/var/lib/gems/1.9.1/gems/bosh_cli-1.3215.0/lib/cli/commands/release/create_release.rb:184:in `map'
/var/lib/gems/1.9.1/gems/bosh_cli-1.3215.0/lib/cli/commands/release/create_release.rb:184:in `build_packages'
/var/lib/gems/1.9.1/gems/bosh_cli-1.3215.0/lib/cli/commands/release/create_release.rb:107:in `create_from_spec'
/var/lib/gems/1.9.1/gems/bosh_cli-1.3215.0/lib/cli/commands/release/create_release.rb:51:in `create'
/var/lib/gems/1.9.1/gems/bosh_cli-1.3215.0/lib/cli/command_handler.rb:57:in `run'
/var/lib/gems/1.9.1/gems/bosh_cli-1.3215.0/lib/cli/runner.rb:59:in `run'
/var/lib/gems/1.9.1/gems/bosh_cli-1.3215.0/bin/bosh:19:in `<top (required)>'
/usr/local/bin/bosh:23:in `load'
/usr/local/bin/bosh:23:in `<main>'

**
12) Through putty I connected to cf VM using following credentials:
hostname : 127.0.0.1
port number :2222
Username : vagrant
password: vagrant

Fired following commands:
wget http://go-cli.s3-website-us-east-1.amazonaws.com/releases/v6.6.1/cf-linux-amd64.tgz
tar xzvf cf-linux-amd64.tgz
sudo mv cf /usr/local/bin/

13) In order to set API end point I am using following command:
cf api --skip-ssl-validation https://api.10.244.0.34.xip.io

But it fails and gives following stacktrace:
root@agent-id-bosh-0:/home/vagrant# cf api --skip-ssl-validation https://api.10.244.0.34.xip.io
Setting api endpoint to https://api.10.244.0.34.xip.io...
FAILED
Error performing request: Get https://api.10.244.0.34.xip.io/v2/info: dial tcp 10.244.0.34:443: i/o timeout

Any help will be appreciated.

Thanks & Regards,
Sujeet Yadav

**Comment by Amit-PivotalLabs** [comment]
The `provision_cf` script failed, so you will definitely not be able to set `cf api` successfully.  It timed out downloading an asset from a blobstore, but it was able to download many of the other assets, so it's not a systemic problem.  Something just took too long.  Just try the `provision_cf` script again.

**Comment by Amit-PivotalLabs** [comment]
Hey @sujeetyadav 

Haven't heard back, so I'll assume it was just a timeout and you've progressed.  I'll close the issue for now, please feel free to open a new one if you're still having issues.
