### ISSUE TITLE
Error filling in template 'blobstore.crt.erb' (line 1: Can't find property `["blobstore.tls.cert"]')

### ISSUE THREAD

**Issue by valenbb** [cloudfoundry/cf-release#936]
I am deploying CF v233 in a test vsphere environment.
Bosh CLI installed is v1.3215.0

The following error is reported: 
Error 100: Unable to render instance groups for deployment. Errors are:
   - Unable to render jobs for instance group 'blobstore_z1'. Errors are:
     - Unable to render templates for job 'blobstore'. Errors are:
       - Error filling in template 'blobstore.crt.erb' (line 1: Can't find property `["blobstore.tls.cert"]')
       - Error filling in template 'blobstore.key.erb' (line 1: Can't find property `["blobstore.tls.private_key"]')

Task 36 error

For a more detailed error report, run: bosh task 4 --debug 

Previous deployments did not have this type of error.
Is this now a required parameter? 

I tried putting the missing files in the jobs/blobstore/templates directory and the error still persists.

bosh task 4 --debug log:
https://drive.google.com/file/d/0BxIkSsYm_rxZV2lvajl0Qzhxc1E/view?usp=sharing

I also saw a section for TLS under some of the jobs, but am not sure if this needs to be filled out or a way to eliminate the this error. Please advise.

cf-deployment can be obtained from link below:
https://drive.google.com/file/d/0BxIkSsYm_rxZUGN5UVdRY3FHVlU/view?usp=sharing

**Comment by Amit-PivotalLabs** [comment]
For a test environment, you should be able to generate an RSA private key, then use that to create a self-signed TLS certificate.  You then want to put the (PEM-encoded) contents of those files into your manifest.  I don't see anything in your cf-deployment that has something like:

```
blobstore:
  tls:
    cert: XXXX
    private_key: XXXX
```

/cc @utako @SocalNick

**Comment by valenbb** [comment]
This is the first time seeing anything related to TLS. I wasn't sure if I should have gone ahead and generated key and cert. I will do this and let you know of the results. By chance, will the cloudfoundry docs be updated to reflect that this parameter is now needed?

**Comment by Amit-PivotalLabs** [comment]
They will be soon, yes.

**Comment by SocalNick** [comment]
@valenbb updated release notes (I'm new to this project and put the notes in the wrong section): https://github.com/cloudfoundry/cf-release/releases/tag/v232#job-spec-changes

Here is the direct link to the WebDAV manifest updates: https://docs.google.com/document/d/1PDswakRCBdnQEbJYZa01Fo8vo3DC6h3rtP3sckcp5Eo

**Comment by valenbb** [comment]
@Amit-PivotalLabs - Adding the required key and cert fixed my issue. Thank you very much.

@SocalNick - Thanks for the updated notes. I have put things in the wrong place too (many many times) :-)

I will close this issue. Thanks again for the help!
