### ISSUE TITLE
blobstore(webdav) start issues with larger blobstores

### ISSUE THREAD

**Issue by rwwohl** [cloudfoundry/cf-release#938]
We recently switched from the nfs services for blobstore over to the new webdav service.  We are having issues with monit starting the webdav service on one of our environments that has a very large blobstore.  We have tracked the root cause of the issue to the monit startup script which performs the following procedure before exec'ing nginx:

chown -R vcap:vcap $RUN_DIR $LOG_DIR $DATA

The recursive chown on the entire $DATA can take significant time on larger blobstores (ours is 80k files/dirs).  If it takes too long, monit will try and start it again, so you end up with two nginx daemons.  The first will eventually complete and the second will start erroring because it cannot bind to port 80.  Monit will retry several times but never succeed since the first has port 80 and error out causing the vm to be in failing state due to the blobstore process.

Looks like the debian nfs server behavior was to just chown the toplevel shared directory.  Does webdav need to do this recursive chown?  Can this be done outside the monit startup to prevent this scenario? Someone on the cf-dev forums mentioned a bosh pre-start script could be a possible solution.

**Comment by Amit-PivotalLabs** [comment]
Hi @rwwohl 

Looks like you've raised this issue on the cf-dev mailing list, and the CAPI team (responsible for CC and blobstore) are tracking it and thinking about this.  To consolidate, I'll close out this issue.  For anyone else interested, here is the link to the discussion thread: https://lists.cloudfoundry.org/archives/list/cf-dev@lists.cloudfoundry.org/thread/S7R5KVVL7YBFLH3HXS654I36WYR6MZNC/

/cc @SocalNick @utako 

Cheers,
Amit
