### ISSUE TITLE
Unable to mount nfs store

### ISSUE THREAD

**Issue by omazhary** [cloudfoundry/cf-release#942]
The cloud controller job fails to update from v231 to v233 even after applying the process described in the [document](https://docs.google.com/document/d/1PDswakRCBdnQEbJYZa01Fo8vo3DC6h3rtP3sckcp5Eo/edit?pref=2&pli=1#heading=h.oi6irfqgers2). Following is the output of ```monit summary```:
```
Process 'consul_agent'              running
Process 'cloud_controller_ng'       Execution failed
Process 'cloud_controller_worker_local_1' initializing
Process 'cloud_controller_worker_local_2' initializing
Process 'nginx_cc'                  initializing
Process 'cloud_controller_migration' running
Process 'metron_agent'              running
Process 'statsd-injector'           running
Process 'route_registrar'           running
System 'system_localhost'           running
```
Going through the logs, the following error was found in ```/var/vcap/sys/log/cloud_controller_ng_ctl.log```:
```
------------ STARTING cloud_controller_ng_ctl at Wed Mar 30 13:15:20 UTC 2016 --------------
Checking for nfs to be mounted
Failed to find nfs mount
```
Which led to finding the following error in ```/var/vcap/sys/log/cloud_controller_ng_ctl.err.log```:
```
chown: changing ownership of ‘/var/vcap/nfs/shared’: Operation not permitted
```

On going through the bin scripts, it was determined that the directory is never created, and thus its ownership cannot be changed. This, in turn, leads to the cloud controller not being able to mount the nfs store.

However, on creating the directory manually, changing its ownership, and then mounting the nfs store manually, the data was mounted. I can find no logical reason for this. I'm still going through the scripts in order to find a logical justification.

**Comment by omazhary** [comment]
This [file](https://github.com/cloudfoundry/cloud_controller_ng/blob/33ecd925c6d6a3bcfe6e83e07e02634c10881138/bosh-templates/handle_local_blobstore.sh.erb) might be related. There are checks for all important property sections except buildpacks.

**Comment by omazhary** [comment]
Deploying from scratch did not solve the problem either.

**Comment by omazhary** [comment]
**Root Cause Found:** Removal of the ```nfs_mounter``` template from the ```api_zX``` job. Since the scripts get removed in the update from v231 to v233, the nfs blobstore never gets mounted, and the cloud controller hangs and eventually fails during deployment.

Should the upstream templates be adjusted accordingly?

**Comment by simonleung8** [comment]
@omazhary 
Thank you for bringing this to our attention. We will make the migration document clearer.

Thanks
Simon & @petergtz

**Comment by adowns01** [comment]
We have updated the document to include the `nfs_mounter` entries for the scenario where people would want to continue using NFS blobstore. As you said, `nfs_mounter` template was removed from Cloud Controller because WebDAV is what's supported by default now. The updated document should help those who'd like to continue using NFS.

Link to document for future reference: https://docs.google.com/document/d/1PDswakRCBdnQEbJYZa01Fo8vo3DC6h3rtP3sckcp5Eo/edit?pref=2&pli=1#

Thanks,
Amelia @adowns01 & Riz @rizwanreza, CAPI Team

**Comment by omazhary** [comment]
Thanks everyone. But does this mean you will include the missing template in the manifests, or should users then include it manually?

**Comment by adowns01** [comment]
Hi @omazhary, 

If users want to opt out of WebDav and continue using nfs they will have to manually update their manifests and include the template.

Thanks, 
Amelia @adowns01, CAPI Team Member

**Comment by omazhary** [comment]
Hi @adowns01,

thanks for the response. Will close the issue now.

Regards,
Omar
