### ISSUE TITLE
App stack cflinuxfs2 is not available

### ISSUE THREAD

**Issue by FaKeller** [cloudfoundry/cf-release#946]
I have CF running locally using BOSH Lite. I had the [spring-music](https://github.com/cloudfoundry-samples/spring-music) example deployed on CF and it was running seamlessly until today. Now I cannot run the application anymore. I have tried all combinations of `cf delete`, `cf scale` and `cf push` to deploy the app, but the `cf push` command always fails as follows:

```
{ spring-music } master » cf push
Using manifest file C:\development\cloudfoundry\sampleapps\spring-music\manifest.yml

Creating app spring-music in org myorg / space samples as admin...
OK

Creating route spring-music-unconcatenated-inhabitancy.bosh-lite.com...
OK

Binding spring-music-unconcatenated-inhabitancy.bosh-lite.com to spring-music...
OK

Uploading spring-music...
Uploading app files from: C:\...\unzipped-app038243187
Uploading 457K, 88 files
Done uploading
OK

Starting app spring-music in org myorg / space samples as admin...
FAILED
Server error, status code: 404, error code: 250003, message: The stack could not be found: The requested app stack cflinuxfs2 is not available on this system.
```

So according to the error message, the cflinuxfs2 stack is missing, but `cf stacks` reports its there:

```
{ spring-music } master » cf stacks
Getting stacks in org myorg / space samples as admin...
OK

name         description
cflinuxfs2   Cloud Foundry Linux-based filesystem
```

After a failed push the app status looks as follows:

```
{ spring-music } master » cf app spring-music
Showing health and status for app spring-music in org myorg / space samples as admin...
FAILED
Server error, status code: 400, error code: 170002, message: App has not finished staging
```

I have already tried to reupload the [stemcell according to the docs](http://docs.cloudfoundry.org/deploying/common/deploy.html), but bosh states the stemcell is already there. `bosh create release && bosh upload release && bosh deploy` has also not resolved the issue. 

Any ideas on how I can deploy applications to CF again?

**Comment by ScarletTanager** [comment]
Hi @FaKeller ,

Can you get us some more diagnostic information?  Please try the following:

1 - `CF_TRACE=true cf push _yourapp_`
2 - collect the logs from both the CC and DEA (assuming you're using DEAs), which can be found on the respective VMs (`api_z1/0` and `runner_z1/0`) under `/var/vcap/sys/log` in the appropriate subdirectories.  The logs can be quite large, so please slice out the portions which correspond to when you do the `cf push`.

Thanks,

@ScarletTanager (CF RuntimeOG team)

**Comment by FaKeller** [comment]
Hi, thank you very much for the quick reply! 

1 - I have attached the log output of `cf push` with CF_TRACE enabled: [cf-push-trace.txt](https://github.com/cloudfoundry/cf-release/files/202501/cf-push-trace.txt)
2 - I also went into the two VMs and checked the logs, but due to their size (both in terms of files and lines therein) I am not sure what to look for. I have grepped all log files for `spring-music`, but only found matches in `./nginx_cc/nginx.access.log` on `api_z1/0`, which are probably not as relevant?

What I forgot to mention is that I restarted the whole CF VM due to networking issues today for the first time since I created it (I had since always suspended and resumed it) and [followed the docs](https://github.com/cloudfoundry/bosh-lite/blob/master/docs/bosh-cck.md) to restart the internal VMs - essentially with `bosh cck` and recreating the VMs. I guess that might be related to the issue as well, albeit `bosh cck` does not report any problems now.

**Comment by ScarletTanager** [comment]
@FaKeller - just to get clarification, are you still seeing the issue after your restart?  We are going to look through your logs and see if anything obvious jumps out.

@ScarletTanager & @swetharepakula , RuntimeOG team

**Comment by FaKeller** [comment]
Yes, the issue described above came after the restart. I had networking issues (no ping succeeded to the whole CF VM), which I related to VirtualBox instabilities. After the `vagrant halt`, `vagrant up` of the whole CF VM followed by a `bosh cck` to start everything again, the issue described above occurred. 

I have not "restarted" the CF VM since the above issue occurred. Could a restart potentially resolve the issue? Reading the docs I expected the restart procedure with `bosh cck` to cause more trouble than good :-)

**Comment by ScarletTanager** [comment]
@FaKeller - What is happening is that the CC cannot find a valid stager (DEA) advertising the stack in question.  The most common cause for this is a failure in NATS (message bus) communication, which could itself result from a variety of reasons.  Given what you did to "restart" your CF environment, there is one bug which might be related to this, and it is fixed in [release 233](https://github.com/cloudfoundry/cf-release/releases/tag/v233).

We also suggest you look at your message bus and see if the correct NATS messages are flowing:

To see this you need to:

1. ssh into the nats_z1 vm (`bosh ssh nats_z1`)
2. Get root priviledges (`sudo su`)
3.`cd /var/vcap/packages/nats/nats`
4. Install the gems (`bundle install`)
5. Look at the nats messages: (`bundle exec nats-sub 'dea.advertise' -s nats://nats:nats@10.244.0.6:4222`)
If no messages are showing up, then there is a problem with your DEA. If the messages you see do not have the correct stack in them, your DEA might be misconfigured. If they have the correct stack, there may be an issue with your cloud controller.

Though the way you restarted the CF VM could have rendered your environment non functional. You may need to create it again from scratch. (`vagrant destroy` and `vagrant up`, followed by the steps to deploy a a CF to bosh-lite from scratch).

- @swetharepakula and @ScarletTanager, CF RuntimeOG team

**Comment by FaKeller** [comment]
@ScarletTanager - Thanks for the detailed feedback. Today I examined the environment the way you proposed. I have in fact already a Java-based client listening to all NATS and Firehose messages. I assume that the output using the Java libaries is the same as if I had followed your description.

Here is an excerpt of the NATS messages log:

```
[NATS 2016-04-08 09:04:29] DefaultMessage{subject='dea.advertise', body='{"id":"0-06b948d2da194b82bff37f0f37fbd0a2","stacks":["cflinuxfs2"],"available_memory":8192,"available_disk":98304,"app_id_to_count":{},"placement_properties":{"zone":"z1"}}', queueGroup='null', isRequest=false}
[NATS 2016-04-08 09:04:29] DefaultMessage{subject='staging.advertise', body='{"id":"0-06b948d2da194b82bff37f0f37fbd0a2","stacks":["cflinuxfs2"],"available_memory":8192,"available_disk":98304}', queueGroup='null', isRequest=false}
[NATS 2016-04-08 09:04:34] DefaultMessage{subject='dea.stop', body='{"droplet":"268303e6-ebd0-49f1-9636-8ab1a514205a"}', queueGroup='null', isRequest=false}
```

It seems as if the `dea.advertise` message (which occurs every ~5 seconds) correctly advertises the `cflinuxfs2` stack, so following your explanation there is probably an issue with the cloud controller. Firehose reports the following log messages for the cloud controller (during `cf push`):

```
[09:04:19.555] Updated app with guid 268303e6-ebd0-49f1-9636-8ab1a514205a ({"name"=>"spring-music", "instances"=>1, "memory"=>512, "environment_json"=>"PRIVATE DATA HIDDEN"})
[09:04:20.509] Updated app with guid 268303e6-ebd0-49f1-9636-8ab1a514205a ({"route"=>"87fafc0f-4f50-4c99-a22d-2690337b728c"})
[09:04:34.146] Updated app with guid 268303e6-ebd0-49f1-9636-8ab1a514205a ({"state"=>"STOPPED"})
```

Firehose did not publish any `ERROR` events.



---

As nothing changed, I again tried to `vagrant halt` with graceful shutdown, `vagrant up` and `bosh cck` (with `restart`, not `recreate` chosen as resolution) in hope for a change. `bosh cck` now reports the following:

```
Applying resolutions...

Director task 84
Error 100: Redis lock lock:deployment:cf-warden is acquired by another thread

Task 84 error
```

Detailed debug info for task 84: [bosh-task-84-debug.txt](https://github.com/cloudfoundry/cf-release/files/210279/bosh-task-84-debug.txt)

The procedure has rendered `runner_z1` as `failing` (with `bosh vms`):

```
+---------------------------------------------------------------------------+--------------------+-----+-----------+-------------+
| VM                                                                        | State              | AZ  | VM Type   | IPs         |
+---------------------------------------------------------------------------+--------------------+-----+-----------+-------------+
| api_z1/0 (c8c79822-69f3-4d06-8c76-da5ec9ba4b3f)                           | unresponsive agent | n/a | large_z1  |             |
| blobstore_z1/0 (078d04b6-bb5c-4ca1-b9b7-d7e0ff6d3a50)                     | unresponsive agent | n/a | medium_z1 |             |
| consul_z1/0 (e8c4a8c4-b652-4e7a-96ee-4a551568e4c5)                        | unresponsive agent | n/a | small_z1  |             |
| doppler_z1/0 (2a9168ad-e839-42af-b223-8c7a5cb3d4c1)                       | unresponsive agent | n/a | medium_z1 |             |
| etcd_z1/0 (cc85df9f-d712-4087-bbe9-733feefc6693)                          | unresponsive agent | n/a | medium_z1 |             |
| ha_proxy_z1/0 (a3e5f6d3-3c97-4d17-885e-b362b4afd2d8)                      | unresponsive agent | n/a | router_z1 |             |
| hm9000_z1/0 (d6b71c01-1b22-47e3-8647-4589b6339e6a)                        | unresponsive agent | n/a | medium_z1 |             |
| loggregator_trafficcontroller_z1/0 (18ce4230-981c-4337-84fb-16c08e6b0529) | unresponsive agent | n/a | small_z1  |             |
| nats_z1/0 (21a46934-686c-44ec-bc1a-557cd02ffe20)                          | unresponsive agent | n/a | medium_z1 |             |
| postgres_z1/0 (7716566f-da60-40c6-b474-054bbc668723)                      | unresponsive agent | n/a | medium_z1 |             |
| router_z1/0 (172477ad-55cd-40b0-93ad-15ad0e4a27e9)                        | unresponsive agent | n/a | router_z1 |             |
| runner_z1/0 (f478fecd-d7ba-45f4-9f8a-f7696a15534b)                        | failing            | n/a | runner_z1 | 10.244.0.26 |
| uaa_z1/0 (f1cf60a7-23d5-4072-8fae-4a6e7d2d5013)                           | unresponsive agent | n/a | medium_z1 |             |
+---------------------------------------------------------------------------+--------------------+-----+-----------+-------------+
```

## Resolution

I have tried and errored some more things, but problems got worse and I have now chosen to rebuild the whole CF VM from scratch. My gut feeling says that the issue is related to my specific environment, so I guess this issue can be closed, unless you spot something interesting in the logs I provided ;-)

Thank you again for your quick and supportive help!

**Comment by FaKeller** [comment]
After deciding to `vagrant destroy` and `vagrant up` the CF VM again, the deployment with BOSH Lite did not work anymore as it *always* got stuck deploying the `uaa` component during `bosh deploy`. 

I stumbled upon [bosh-lite#349](https://github.com/cloudfoundry/bosh-lite/issues/349), which is caused by a bug in the linux kernel for certain versions of the CF vagrant boxes. It turned out that I had used one of the affected versions and upgrading the box resolved the installation issue for me. 

Maybe the issue I described here is also related to the linux kernel bug, as it concerns the file system.

**Comment by ScarletTanager** [comment]
Hi @FaKeller , we're glad you were able to resolve your issue.  We just wanted to let you know that the issue with not finding a stack is definitely not related to the linux kernel bug - it actually has nothing at all to do with the filesystem.  Although you've rebuilt your environment, so there is no way to prove it at this point, we would strongly suspect that your CC was failing to subscribe to the dea advertisments and therefore failing to find any valid stagers.

Thanks,

@ScarletTanager && @swetharepakula , RuntimeOG team
