### ISSUE TITLE
Confusion around dropsonde, metron, gorouter, and dea metron ports

### ISSUE THREAD

**Issue by youngm** [cloudfoundry/cf-release#956]
I'm having a little trouble deploying 234.  Digging a little deeper the metron/dropsonde configuration seems to be a little untidy.  Here are some things I noted:

* DEA uses `metron_endpoint.port` for dropsonde messages and defaults it to `3457`: https://github.com/cloudfoundry/dea-hm-workspace/blob/master/jobs/dea_next/spec#L161

* gorouter uses `metron_endpoint.port` "for legacy protocol" and defaults it to `3456`: https://github.com/cloudfoundry/cf-release/blob/master/jobs/gorouter/spec#L128

* gorouter defines a `metron_endpoint.dropsonde_port` that appears to not be used defaulted to `3457`: https://github.com/cloudfoundry/cf-release/blob/master/jobs/gorouter/spec#L125

* gorouter defines a `dropsonde.enabled` that appears to never be used.

* hm9k defines a `metron_agent.dropsonde_incoming_port` defaulted to `3457`: https://github.com/cloudfoundry/dea-hm-workspace/blob/master/jobs/hm9000/spec#L75

A bunch of confusion in here.  I don't know what bosh is doing with all these conflicting properties but leaving `metron_endpoint.port` default resulted in a port of `3456` on my dea which didn't work.

I don't have any strong opinions how the properties should be cleaned up but it would be nice if it was easy to tell what property references metron legacy protocol, what references dropsonde, and it would be nice to know if gorouter uses the dropsonde properties or not.

**Comment by youngm** [comment]
Also, gorouter puts these values into a config called `loggregatorConfig` https://github.com/cloudfoundry/cf-release/blob/master/jobs/gorouter/templates/gorouter.yml.erb#L28 that doesn't appear to even be used by gorouter.  It uses `metron_address` https://github.com/cloudfoundry/gorouter/blob/master/config/config.go#L62 that appears to be defaulting to port 3457 which explains why gorouter is working even though it is using a deprecated (and I thought removed) port.

**Comment by youngm** [comment]
The end result is that if people set `metron_endpoint.port` to `3457` then that is a way to work around gorouter's default of `3456` accidentally being injected into other jobs.  Though I think there is more work to be done here than a simple template change.

**Comment by wfernandes** [comment]
It looks like a property cleanup is needed here. Metron only listens on `localhost:3457`. Dropsonde should be initialized with this by default as can be seen [here](https://github.com/cloudfoundry/gorouter/blob/7cac97c84a0cc667406b1a04b99979e161b2b6fa/main.go#L70).

Even on Loggregator we feel that there are too many 'legacy' properties. We are taking steps to deprecate and remove unnecessary properties to make life simpler.
This is an [FAQ](https://github.com/cloudfoundry/loggregator/wiki/FAQ#q-what-do-the-metron-properties-mean) on **some** of the metron_agent properties. Hopefully, it is able to clear some things up. The list will be updated as often as possible in order to maintain consistency.

The FAQ itself is a work in progress that I'm filling in when I get time.

**Comment by shalako** [comment]
@Jim-Campbell @wfernandes is the takeaway that we can remove `metron_endpoint.port` from the gorouter spec? Anything else?

**Comment by youngm** [comment]
@shalako I also noted that `dropsonde.enabled` and `metron_endpoint.dropsonde_port` both don't appear to do anything under my quick look.

**Comment by youngm** [comment]
I also think a consistent name should be decided on for what port processes use when sending dropsonde messages to their local metron agent.

**Comment by Amit-PivotalLabs** [comment]
Having the default 3457 coordinated in multiple different releases is problematic.  This can be solved more elegantly if the metron_agent job provides the port as a "link", and all these other jobs consume that link.  A shorter-term solution would be to remove the default from all the properties, and force the coordination into the manifest, just as we do with something like `nats.port` (4222).

For now, the routing team is aware of the need to remove the 3456 property and the related unused stuff in the ERB templates, and the logging team is aware of the need to remove many deprecated properties.  The rest will be tidied up with the BOSH links work in cf-release which will be coming up soon, so I'll close this issue for now.

**Comment by youngm** [comment]
Perfect. Thanks @Amit-PivotalLabs

**Comment by Jim-Campbell** [comment]
Loggregator is just finishing up a story
<https://www.pivotaltracker.com/story/show/117777777> to deprecate unused
properties.

On Sun, Apr 24, 2016 at 7:20 PM, Amit Gupta <notifications@github.com>
wrote:

> Having the default 3457 coordinated in multiple different releases is
> problematic. This can be solved more elegantly if the metron_agent job
> provides the port as a "link", and all these other jobs consume that link.
> A shorter-term solution would be to remove the default from all the
> properties, and force the coordination into the manifest, just as we do
> with something like nats.port (4222).
>
> For now, the routing team is aware of the need to remove the 3456 property
> and the related unused stuff in the ERB templates, and the logging team is
> aware of the need to remove many deprecated properties. The rest will be
> tidied up with the BOSH links work in cf-release which will be coming up
> soon, so I'll close this issue for now.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/cloudfoundry/cf-release/issues/956#issuecomment-214083592>
>



-- 
Jim Campbell | Product Manager | Cloud Foundry | Pivotal.io | 303.618.0963

**Comment by shalako** [comment]
@Jim-Campbell 

The three ports @youngm mentioned are not listed in your story. 
- `metron_endpoint.port`
- `dropsonde.enabled`
- `metron_endpoint.dropsonde_port`

Only one of these `metron_endpoint.dropsonde_port` is listed in the FAQ @wfernandes referenced.

This is quite confusing. Could you please point us at docs that indicate what the minimum list of properties we should expose in gorouter are, or send us a PR to clean up these properties?

Which properties should be removed, and which should be kept (and fixed, as @youngm says they aren't working). 

Thank you
