### ISSUE TITLE
Package 'nsync' has a glob that resolves to an empty file list

### ISSUE THREAD

**Issue by djjesseb** [cloudfoundry/cf-release#969]
Doing a local bosh-lite setup and during the "bosh create release --force" command I get the error:

Building nsync...
Package 'nsync' has a glob that resolves to an empty file list: capi-release/src/golang.org/x/crypto/curve25519/*.go

I checked that path on my system and it ends at "x" , after a fresh git pull.

I also downloaded the project as a zip, and it is empty at /x/crypto.

**Comment by robdimsdale** [comment]
@djjesseb before you ran `bosh create release --force`, did you also run `./scripts/submodules`? That script will recursively fetch all the submodules, and will also mean your git status will be clean, hence no need for a `--force` flag in `bosh create release`.

Thanks,
Rob

**Comment by djjesseb** [comment]
@robdimsdale Thanks for replying. I do not have a submodules script in scripts.
I did run ./scripts/update, but it failed on the troublesome module:

```
Cloning into 'src/golang.org/x/crypto'...
remote: Total 2394 (delta 1445), reused 2394 (delta 1445)
error: RPC failed; result=56, HTTP code = 200 | 2.08 MiB/s
Receiving objects: 100% (2394/2394), 1.85 MiB | 2.08 MiB/s, done.
Resolving deltas: 100% (1445/1445), done.
Clone of 'https://go.googlesource.com/crypto' into submodule path 'src/golang.org/x/crypto' failed
```

**Comment by DennisDenuto** [comment]
Hi @djjesseb, We think this might be a network related issue as detailed in [this post] (https://confluence.atlassian.com/stashkb/git-clone-fails-error-rpc-failed-result-56-http-code-200-693897332.html).

You can try setting some git env variables to help debug the problem on your end:
```
export GIT_TRACE_PACKET=1
export GIT_TRACE=1
export GIT_CURL_VERBOSE=1
```

If you believe this issue is not network related, let us know.

Thanks
Al & Dennis

**Comment by JesseTAlford** [comment]
As it's been a week and we haven't heard anything further, we're closing this issue.

Please feel free to open another issue if this is still a problem.
