### ISSUE TITLE
Documentation out of sync

### ISSUE THREAD

**Issue by barkerb1** [cloudfoundry/cf-release#970]
As per issue 955, https://github.com/cloudfoundry/cf-release/issues/955, can you please update the documentation to include said changes - https://docs.cloudfoundry.org/deploying/common/deploy.html.

**Comment by Amit-PivotalLabs** [comment]
Could you provide more detail?

**Comment by barkerb1** [comment]
Hi Amit,

As per issue #955, the default login api for the development environment was https://api.10.244.0.34.xip.io, however since an update it's now https://api.bosh-lite.com.  It would be great if the documentation could outline the default routes.  Additionally when I run a bosh vms command I'm getting a different set of VMs than in the documentation as well.  

Ideally someone might want to go through the documentation by doing an install from a clean slate to make sure all the steps are captured for a new user.    

Thanks,
Brad

**Comment by Amit-PivotalLabs** [comment]
Hi Brad,

The docs assume you're following this workflow:

http://docs.cloudfoundry.org/deploying/boshlite/

Before the doc you linked to, it's assumed you followed
http://docs.cloudfoundry.org/deploying/boshlite/create_a_manifest.html, which
states:

*If you deploy BOSH Lite to an AWS Vagrant VM, you must specify a system
domain in a manifest stub. If you are deploying to a local Vagrant VM this
step is not necessary.*

*By default, BOSH Lite uses the system domain bosh-lite.com
<http://bosh-lite.com>, which resolves to the address 10.244.0.34. Update
the system domain property to one of the following two values:*

   - *The domain that you configured to point to the public IP address of
   the BOSH-Lite box that you previously created.*
   - *The xip.io <http://xip.io> domain the corresponds to the public IP
   address given to your BOSH-Lite vagrant box: YOUR_PUBLIC_IP.xip.io
   <http://YOUR_PUBLIC_IP.xip.io>. For more information about xip.io
   <http://xip.io>, see xip.io <http://xip.io/>.*

Is the confusion you're highlighting that it's not clear in the doc you
linked that the assumption is you've first done the stuff in the previous
doc?

Amit

**Comment by barkerb1** [comment]
Ah ok, it looks like that section precedes this one-
https://docs.cloudfoundry.org/deploying/common/deploy.html

Would it be possible to either reference back to create_a_manifest page or reiterate the routes in step 2 under "Verify the deployment"?

**Comment by Amit-PivotalLabs** [comment]
PR to docs has been merged, closing this issue.
