### ISSUE TITLE
Make it easier to reproduce CATs errand run

### ISSUE THREAD

**Issue by mmb** [cloudfoundry/cf-release#972]
We run CATs using the BOSH errand in our Concourse pipelines. Sometimes there are failures and we want to run individual CATs from our workstation by focusing tests. Two things make this time consuming:

1) Figuring out what commit of CATs to use - could the CATs errand print out the cf-acceptance-tests commit SHA at the beginning of every run?

2) Building the config.json - to replicate the test exactly we want the same config JSON that the errand used and this isn't easy to get. Could the CATs errand write the config JSON to stdout at the beginning of a run (potentially with some redactions)?

**Comment by Amit-PivotalLabs** [comment]
Hi @mmb 

The `acceptance-tests` package in `cf-release` doesn't include any `.git` stuff, and also doesn't contain the `git` binary, so I can't think of a clean way to have the CATS print out its commit SHA.  If the `cf-release` repo is being threaded through your pipeline when you're running CATS, it should be easy to see the SHA of `cf-release`, and then not too hard from there to find the appropriate SHA of `cf-acceptance-tests`.

I've created a [PR to CATS](https://github.com/cloudfoundry/cf-acceptance-tests/issues/120) which should print out a sanitized config whether you run CATS locally using the `bin/test*` scripts, from the errand, or from the Release Integration team's Concourse task.

**Comment by Amit-PivotalLabs** [comment]
@mmb 

I think the above addresses this issue, closing it out for now.  Let me know if you have any follow up questions.
