### ISSUE TITLE
Cannot deploy Kibana as NodeJS application when Shield plugin is enabled

### ISSUE THREAD

**Issue by abtpst** [cloudfoundry/cf-release#974]
I am trying to deploy Kibana on bluemix PaaS. 

https://www.elastic.co/downloads/kibana

Since Kibana is a NodeJs application, it can be deployed as such on bluemix. All i have to do is 

1. Provide a simple `manifest.yml` file that details the app name and a couple of other things

2. Provide a `Procfile` which has just one line as `web: bin/kibana --port=$PORT`

and thus i can run Kibana on bluemix PaaS. Note that this is pushed via cloudfoundry. 

Also, i was able to install the `marvel` and `sense` plugins for Kibana.

Now, i installed the `shield` plugin. This plugin requires and `ssl key` and an `ssl cert` file to run. The path to these files must be provided in the `kibana.yml` file. 

After installation, i tested the shield plugin natively and it worked just fine.

Here is the layout of the directory structure

    bin(d)
    config(d)
    installedPlugins(d)
    node_modules(d)
    sslFiles(d)
    manifest.yml
    Procfile

(d) represents directories. he `sslFiles` folder contains the `ssl key` and `ssl cert` files.

Before i could push to bluemix, i knew that the paths ti the ssl files would have to be relative to the app in bluemix, so in the `kibana.yml` i specified those as

    kibana.ssl.key:app/sslFiles/kibana.key
    kibana.ssl.cert:app/sslFiles/kibana.cert

i did this as in bluemix, i could see the following directory structure

    app(d)
        bin(d)
        config(d)
        installedPlugins(d)
        node_modules(d)
        sslFiles(d)
        manifest.yml
        Procfile

Indentation represents containment. So i pushed it to bluemix PaaS using cloudfoundry, but now i get

`502 Bad Gateway: Registered endpoint failed to handle the request.`

error. I tried changing the paths to `sslFiles/kibana.key` but then i got a staging error 

`cannot find path sslFiles/kibana.key`

What is responsible for my 502 error? Is it the path to the sslFiles? If so, how can i properly provide the paths?

here is my cloudfoundry version

`cf version 6.18.1+a1103f0-2016-05-24`

**Comment by Amit-PivotalLabs** [comment]
@fraenkel @sykesm @DanLavine Here's a question about Bluemix on the cf-release repo which you may wish to take a look at.

**Comment by fraenkel** [comment]
If you have a technical problem or question with Bluemix, please use the supported mechanisms.
See https://developer.ibm.com/bluemix/support/
