### ISSUE TITLE
cf 237 error

### ISSUE THREAD

**Issue by betht1220** [cloudfoundry/cf-release#977]
I've installed cf-237 on mac with Virtualbox/Vagrant.  'bosh vms' returns 13 vms, but I cannot log in

cf login -a https://api.10.244.0.34.xip.io -u admin -p admin --skip-ssl-validation
API endpoint: https://api.10.244.0.34.xip.io
FAILED
Server error, status code: 404, error code: 0, message:

**Comment by Infra-Red** [comment]
Hi @betht1220 !
Could you please share property `system_domain` from `templates/cf-infrastructure-bosh-lite.yml` file in your cf-release folder. Perhaps you use a wrong link for targeting API endpoint from CF CLI.

**Comment by ScarletTanager** [comment]
Have you tried using `api.bosh-lite.com` as your API endpoint yet?  If not, I suggest retrying with that.  This was changed a while back, but I don't remember in which release.

**Comment by betht1220** [comment]
Thanks ScarletTanager - using api.bosh-lite.com works.  Thanks also to Infra-Red for taking the time.
