### ISSUE TITLE
miekg dns git submodule not proxy friendly

### ISSUE THREAD

**Issue by cklause** [cloudfoundry/cf-release#982]
Hi,

all git submodules are referenced via https except 'vendor/github.com/miekg/dns' in 'src/etcd-release/src/etcd-dns-checker/.gitmodules'. Changing this from git:// to https:// would make the 'scripts/update' step more http proxy friendly.

**Comment by Amit-PivotalLabs** [comment]
This should now be fixed on the master branch.
