### ISSUE TITLE
scripts/generate-etcd-certs uses incorrect domain

### ISSUE THREAD

**Issue by swetharepakula** [cloudfoundry/cf-release#984]
The scripts/generate-etcd-certs uses the domain "etcd.service.consul", but it should be "etcd.service.cf.internal".

Thanks,
@swetharepakula & @DanLavine

**Comment by christianang** [comment]
Hi @swetharepakula,

I have updated the script to use cf.internal.

Thanks for the feedback.

-Christian

**Comment by swetharepakula** [comment]
Thanks!
