### ISSUE TITLE
Internal Server error, status code 500 returned when trying to create orgs

### ISSUE THREAD

**Issue by graememross** [cloudfoundry/cf-release#986]
We have been seting up a cloud foundry ecosystem based on internal OpenStack hardware.

We have installed cloud foundry on the openstack system following the instructions at https://docs.cloudfoundry.org/deploying/openstack/index.html and everything seems to be working

We used the latest HEAD on master (as of about a week ago)

I can do a curl on the api info endpoint and it returns information about the system.

I then install the cf cli and logged onto the system (several problems here - but resolved)

```
[mtlgrr@host-192-168-0-86 ~]$ cf login
API endpoint: https://api.cf.memex.sas.com
Email> api.cf.memex.sas.com
Password> [mtlgrr@host-192-168-0-86 ~]$ cf login
API endpoint: https://api.cf.memex.sas.com
Email> admin
Password>
Authenticating...
OK
API endpoint:   https://api.cf.memex.sas.com (API version: 2.56.0)
User:           admin
No org or space targeted, use 'cf target -o ORG -s SPACE'
FAILED
Error finding available orgs
Server error, status code: 500, error code: 0, message:
```
THere are no orgs or spaces defined yet so the error is no great surprise. However when I try and create an org
```
[mtlgrr@host-192-168-0-86 ~]$ cf create-org svi
Creating org svi as admin...
FAILED
Server error, status code: 500, error code: 0, message:
```
I tried again with the -v flag but no real extra information

I tried tracing the request through the log files on the system. I can see it moving from the haproxy to the router and eventually to the nginx server on the api_z1 VM. The nginx server seems to pass it off to the cloud_controller but it is at this point that we are getting the 500 error on the server. 

The cloud_controller doesn't seem to log anything useful!

Can anyone give any hints as to what might be going wrong?

**Comment by srinat999** [comment]
#975. Hey, I am also facing a similar issue. Did you manage to fix it?

You could set CF_TRACE=true and see the HTTP requests that are going through

**Comment by graememross** [comment]
No solution yet. I had set the -v flag but there wasn't enything useful reported

for completness here is the command with CF_TRACE set
```
[mtlgrr@host-192-168-0-86 ~]$ cf logout
Logging out...
OK
[mtlgrr@host-192-168-0-86 ~]$ cf login -u admin --skip-ssl-validation
API endpoint: https://api.cf.memex.sas.com
Password>
Authenticating...
OK
API endpoint:   https://api.cf.memex.sas.com (API version: 2.56.0)
User:           admin
No org or space targeted, use 'cf target -o ORG -s SPACE'
FAILED
Error finding available orgs
Server error, status code: 500, error code: 0, message:
[mtlgrr@host-192-168-0-86 ~]$ export CF_TRACE=true
[mtlgrr@host-192-168-0-86 ~]$ cf create-org svi
Creating org svi as admin...
REQUEST: [2016-06-22T05:35:05-04:00]
POST /v2/organizations HTTP/1.1
Host: api.cf.memex.sas.com
Accept: application/json
Authorization: [PRIVATE DATA HIDDEN]
Content-Type: application/json
User-Agent: go-cli 6.19.0+b29b4e0 / linux
{"name":"svi"}
RESPONSE: [2016-06-22T05:35:05-04:00]
HTTP/1.1 500 Internal Server Error
Content-Length: 21
Content-Type: text/plain
Date: Wed, 22 Jun 2016 09:39:35 GMT
Server: nginx
X-Vcap-Request-Id: 129d304e-cb7f-4aae-4dec-7b90d5df09a3
Internal server error
FAILED
Server error, status code: 500, error code: 0, message:
```

As you can see there is nothing informative here.

**Comment by srinat999** [comment]
Hey, I maanged to fix this issue (only to run into another:()

The fix for me was to use PEM encoded keys for jwt signing and verification. 
```
ssh-keygen -t RSA -f testkeys
ssh-keygen -f testkeys.pub -e -m pem
```
Copy the private key to ```jwt.signing_key`` and the PEM public key to ```jwt.verification_key```

Hope that helps!

**Comment by graememross** [comment]
That fixed it we had a typo in  the PEM keys.

Could I suggest that we have some sort of reasonable error message that would help in this situation.

**Comment by Amit-PivotalLabs** [comment]
Did you folks both happen to have typos in your PEM keys, or did some documentation lead you astray?

**Comment by graememross** [comment]
The wrong key was generated (in our case).

It would be better if there was some sort of logged message rather than an ambiguous "Internal Server Error"

Putting a message in the internal log files saying something like "JWT keys do not match" or "JWT Authorization error" would have saved a lot of time as we would have known to look at the keys.

As it was we weren't sure if we had somehow corrupted the image or the platform we were running on or anything - there were no clues

**Comment by Amit-PivotalLabs** [comment]
@graememross that sounds pretty sensible.  The component that gets the key pair, and could validate that they match, is the UAA.  I would recommend opening an [issue on the uaa-release repo](https://github.com/cloudfoundry/uaa-release/issues) with some details about what input you had, what error you saw, and what error message you'd like to see.

Cheers,
Amit
