### ISSUE TITLE
Error filling in template 'dea.yml.erb' (line 95: bad component(expected user component)

### ISSUE THREAD

**Issue by cpraveen412** [cloudfoundry/cf-release#992]
Could anyone help me on this?

Error 100: Unable to render instance groups for deployment. Errors are:
   - Unable to render jobs for instance group 'runner_z1'. Errors are:
     - Unable to render templates for job 'dea_next'. Errors are:
       - Error filling in template 'dea.yml.erb' (line 95: bad component(expected user component):

**Comment by allomov** [comment]
hey @cpraveen412.

1. it would be nice if you tell what version of cf-release do you use. it would be also helpful if you provide your deployment manifest properties.
1. not long ago cf-release was decoupled in several different releases. `dea.yml.erb` is placed to [cloudfoundry/dea-hm-workspace](https://github.com/cloudfoundry/dea-hm-workspace) release, this project seems a better place to create this issue (imho).
1. could you check if your `cc.internal_api_user` and `cc.internal_api_password` properties are correct?

**Comment by cppforlife** [comment]
@cpraveen412 Looks like your internal_api_password has chars that are not allowed for basic auth:

```
> require 'uri'
> u = URI.parse("http://cloud-controller-ng.service.cf.internal:")
> u.userinfo = "blah:%"
URI::InvalidComponentError: bad component(expected user component): %
```

**Comment by cpraveen412** [comment]
Yes I used "@" in the password. I changed it and started deploying without error.

Thank you
