### ISSUE TITLE
HAProxy logging needs to be improved / exist.

### ISSUE THREAD

**Issue by haydonryan** [cloudfoundry/cf-release#994]
Currently when deploying, haproxy doesn't log any error messages out to /var/vcap/sys/log/haproxy.

For example, on a customer site, we had an issue where they had an invalid private key listed in the PEM.  This was only discovered after manually starting the haproxy job, and observing the output.

**Comment by Amit-PivotalLabs** [comment]
Thanks @haydonryan 

I'll let the routing team know about this issue. /cc @shalako @crhino

**Comment by sreenani** [comment]
Haproxy startup error log is location here /var/vcap/sys/log/monit/haproxy.err.log

**Comment by crhino** [comment]
@haydonryan The HAProxy job has a configuration property `ha_proxy.log_to_file` that should send haproxy logs to `/var/vcap/sys/log/haproxy/haproxy.log`. Does that solve your problem?

**Comment by haydonryan** [comment]
yes it does :) We’ll enable that now.

On Mon, Jul 18, 2016 at 1:33 PM Chris Piraino

<
mailto:Chris Piraino <notifications@github.com>
> wrote:

https://github.com/haydonryan
The HAProxy job has a configuration property

ha_proxy.log_to_file

that should send haproxy logs to

/var/vcap/sys/log/haproxy/haproxy.log

. Does that solve your problem?

—

You are receiving this because you were mentioned.

Reply to this email directly,
https://github.com/cloudfoundry/cf-release/issues/994#issuecomment-233399810
, or

**Comment by Amit-PivotalLabs** [comment]
Looks like this is solved.
