### ISSUE TITLE
Issue with metron_agent/loggregator

### ISSUE THREAD

**Issue by YuPengZTE** [cloudfoundry/cf-release#996]
{"timestamp":1467114903.152345896,"process_id":2874,"source":"metron","log_level":"error","message":"Finder: Watch sent an error","data":{"error":"store request timed out"},"file":"/var/vcap/data/compile/metron_agent/loggregator/src/doppler/dopplerservice/finder.go","line":139,"method":"doppler/dopplerservice.(*Finder).run"}

**Comment by Amit-PivotalLabs** [comment]
Hi @YuPengZTE 

Is there something you would like help with?
