### ISSUE TITLE
Could we have release notes for v238 please

### ISSUE THREAD

**Issue by alext** [cloudfoundry/cf-release#999]
Hi,

There was an [announcement on the mailing list](https://lists.cloudfoundry.org/archives/list/cf-dev@lists.cloudfoundry.org/thread/WMTZBIH5U7DTOOX2SNRVTPQI3U2AINOB/) that we should upgrade to 238 to fix a CVE. This is difficult to do without release notes as it's not clear what the significant changes are. It's also not clear which version of Diego should be used with this release.

thanks,
Alex

**Comment by Amit-PivotalLabs** [comment]
Sorry for the delay.  Notes have been published.  We discussed this delay as a pain point at yesterday's [Runtime PMC](https://github.com/cloudfoundry/pmc-notes/tree/master/Runtime) meeting and [updated our process](https://github.com/cloudfoundry/runtime-ci/commit/2df5706433d9e37036690568473c7e0a57f57b8b) to be more timely about the notes.
